### ISSUE TITLE
java.lang.Throwable: Unexpected file type of: DBAppender.java

### ISSUE THREAD

**Issue by bestv5** [izhangzhihao/intellij-rainbow-brackets#1000]
``` 

java.lang.Throwable: Unexpected file type of: DBAppender.java
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:159)
	at com.intellij.lang.properties.psi.impl.PropertyImpl.getPropertiesFile(PropertyImpl.java:380)
	at com.intellij.lang.properties.references.PropertyReferenceBase.lambda$multiResolve$0(PropertyReferenceBase.java:145)
	at com.intellij.util.containers.ContainerUtil.med3(ContainerUtil.java:2313)
	at com.intellij.util.containers.ContainerUtil.quickSort(ContainerUtil.java:2264)
	at com.intellij.util.containers.ContainerUtil.quickSort(ContainerUtil.java:2243)
	at com.intellij.lang.properties.references.PropertyReferenceBase.multiResolve(PropertyReferenceBase.java:144)
	at com.intellij.lang.properties.references.PropertyReferenceBase.resolve(PropertyReferenceBase.java:47)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitLiteralExpression(HighlightVisitorImpl.java:902)
	at com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl.accept(PsiLiteralExpressionImpl.java:172)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:186)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:336)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:269)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:68)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$analyze$1(HighlightVisitorImpl.java:211)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:370)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:210)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


```

## Your Environment

* Plugin version:6.15
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue might be closed directly.

```
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Licensed to mengyuan hu
Subscription is active until November 12, 2021.
For educational use only.
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1092M
Cores: 4
Registry: ide.intellij.laf.enable.animation=true, light.edit.file.open.enabled=false, compiler.automake.allow.when.app.running=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: AceJump, Gradle View, Statistic, com.chrisrm.idea.MaterialThemeUI, com.hiberbee.intellij.hiberbee-theme, com.intellij.ideolog, com.jetbrains.ChooseRuntime, com.jetbrains.darkPurpleTheme, com.ludditelabs.autodocintellij.plugin, com.mallowigi, com.smilingrob.gitpair, de.netnexus.camelcaseplugin, de.santiv.fastscrolling, io.github.qeesung.component.HighlightBracketPair, net.antelle.intellij-xcode-dark-theme, net.vektah.codeglance, com.failfast, mobi.hsz.idea.gitignore, some.awesome, CheckStyle-IDEA, DBN, EclipseCodeFormatter, zielu.gittoolbox, GrepConsole, LogSupportLite, SequenceDiagram, String Manipulation, zielu.svntoolbox, VisualVMLauncher, com.alibaba.p3c.smartfox, com.dubreuia, com.jetbrains.embeddedProjectJdk, org.sonarlint.idea, MavenRunHelper, com.alibabacloud.intellij.toolkit-intellij, GradleDependenciesHelper, com.github.platan.gradle-dependencies-formatter, tv.twelvetone.gradle.plugin.navigation, com.thoughtworks.gauge, com.codota.csp.intellij, JRebelPlugin, izhangzhihao.rainbow.brackets
```

**Comment by bestv5** [comment]
java.lang.Throwable: Unexpected file type of: DBAppender.java

**Comment by izhangzhihao** [comment]
I have no idea what 'DBAppender.Java' is, and rainbow brackets does nothing about it, this issue must a bug of other plugins or the IDE itself.
