### ISSUE TITLE
[auto-generated:-1446925613] In file: file:///var/fpwork/liyan/gnb/uplane/L2-PS/src/ul/sch/pre/Scheduler.hpp: java.util.zip.ZipException: unknown compression method

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#104]
- Plugin Name: Rainbow Brackets
- Plugin Version: 5.8.2
- OS Name: Linux
- OS Version: 4.4.80-3.nsn.el6.x86_64
- Java Version: 1.8.0_152-release
- App Name: CLion
- App Full Name: CLion
- Is Snapshot: false
- App Build: CL-181.5087.36
- Last Action: Gerrit.Refresh

```
java.lang.RuntimeException: java.util.zip.ZipException: unknown compression method
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:174)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.a(FSRecords.java:517)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.access$000(FSRecords.java:159)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.readContent(FSRecords.java:1195)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.a(PersistentFSImpl.java:241)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.contentsToByteArray(PersistentFSImpl.java:503)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:139)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:130)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:544)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:518)
	at com.jetbrains.cidr.lang.symbols.symtable.SymbolTableProvider.getFileText(SymbolTableProvider.java:111)
	at com.jetbrains.cidr.lang.symbols.symtable.OCSymbolTableProvider.calcTable(OCSymbolTableProvider.java:64)
	at com.jetbrains.cidr.lang.symbols.symtable.OCSymbolTableProvider.calcTable(OCSymbolTableProvider.java:24)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache.forFile(FileSymbolTablesCache.java:505)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.forFile(FileSymbolTable.java:172)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextImpl.preprocessInclude(OCInclusionContextImpl.java:779)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextImpl.preprocessInclude(OCInclusionContextImpl.java:1034)
	at com.jetbrains.cidr.lang.preprocessor.OCPreprocessingLexer.b(OCPreprocessingLexer.java:994)
	at com.jetbrains.cidr.lang.preprocessor.OCPreprocessingLexer.lookAhead(OCPreprocessingLexer.java:279)
	at com.intellij.lexer.LookAheadLexer.doLookAhead(LookAheadLexer.java:73)
	at com.intellij.lexer.LookAheadLexer.advance(LookAheadLexer.java:65)
	at com.intellij.lang.impl.TokenSequence$Builder.performLexing(TokenSequence.java:86)
	at com.intellij.lang.impl.PsiBuilderImpl.a(PsiBuilderImpl.java:190)
	at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:163)
	at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:108)
	at com.intellij.lang.impl.PsiBuilderFactoryImpl.createBuilder(PsiBuilderFactoryImpl.java:78)
	at com.jetbrains.cidr.lang.symbols.symtable.OCSymbolTableProvider.calcTable(OCSymbolTableProvider.java:66)
	at com.jetbrains.cidr.lang.symbols.symtable.OCSymbolTableProvider.calcTable(OCSymbolTableProvider.java:24)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache.forFile(FileSymbolTablesCache.java:505)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.forFile(FileSymbolTable.java:172)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextImpl.preprocessInclude(OCInclusionContextImpl.java:779)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextImpl.preprocessInclude(OCInclusionContextImpl.java:762)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph.getAllRootHeaders(OCImportGraph.java:127)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph.buildSymbolAndRootHeaderCache(OCImportGraph.java:84)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTableUpdater.a(FileSymbolTableUpdater.java:147)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTableUpdater.ensurePendingFilesProcessed(FileSymbolTableUpdater.java:108)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache.ensurePendingFilesProcessed(FileSymbolTablesCache.java:721)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache.ensurePendingFilesProcessed(FileSymbolTablesCache.java:717)
	at com.jetbrains.cidr.lang.symbols.symtable.AbstractGlobalProjectSymbolsCache.processTopLevelAndMemberSymbols(AbstractGlobalProjectSymbolsCache.java:164)
	at com.jetbrains.cidr.lang.symbols.symtable.AbstractGlobalProjectSymbolsCache.processTopLevelAndMemberSymbols(AbstractGlobalProjectSymbolsCache.java:143)
	at com.jetbrains.cidr.lang.symbols.symtable.OCGlobalProjectSymbolsCache.processTopLevelAndMemberSymbols(OCGlobalProjectSymbolsCache.java:220)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedName.processSameSymbols(OCSymbolWithQualifiedName.java:435)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedName.processSameSymbols(OCSymbolWithQualifiedName.java:379)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedName.getDefinitionSymbol(OCSymbolWithQualifiedName.java:348)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedName.processAssociatedSymbols(OCSymbolWithQualifiedName.java:444)
	at com.jetbrains.cidr.lang.symbols.cpp.OCDeclaratorSymbol.processAssociatedSymbols(OCDeclaratorSymbol.java:363)
	at com.jetbrains.cidr.lang.symbols.cpp.OCDeclaratorSymbol.processSameSymbols(OCDeclaratorSymbol.java:385)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedName.processSameSymbols(OCSymbolWithQualifiedName.java:379)
	at com.jetbrains.cidr.lang.daemon.OCDeclaratorChecker.a(OCDeclaratorChecker.java:661)
	at com.jetbrains.cidr.lang.daemon.OCDeclaratorChecker.checkDeclarator(OCDeclaratorChecker.java:536)
	at com.jetbrains.cidr.lang.daemon.OCErrorAnnotator.visitDeclarator(OCErrorAnnotator.java:439)
	at com.jetbrains.cidr.lang.psi.impl.OCDeclaratorImpl.accept(OCDeclaratorImpl.java:452)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:89)
	at com.jetbrains.cidr.lang.daemon.OCAnnotator.annotate(OCAnnotator.java:87)
	at com.jetbrains.cidr.lang.daemon.OCAnnotator.annotate(OCAnnotator.java:71)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:371)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:303)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:333)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:33)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:239)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.zip.ZipException: unknown compression method
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.intellij.openapi.util.io.StreamUtil.copyStreamContent(StreamUtil.java:44)
	at com.intellij.util.io.storage.RefCountingStorage.internalReadStream(RefCountingStorage.java:93)
	at com.intellij.util.io.storage.RefCountingStorage.readStream(RefCountingStorage.java:72)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.a(FSRecords.java:1213)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.readContent(FSRecords.java:1189)
	... 82 more

```

**Comment by izhangzhihao** [comment]
Seems not because of us.
