### ISSUE TITLE
[Auto Generated Report]java.lang.Throwable: Stub index points to a file without PSI: file = jar://G

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#1116]
- Plugin Name: 
- Plugin Version: 6.16
- OS Name: Windows 10
- OS Version: 10.0
- Java Version: 11.0.9.1
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- Is Snapshot: false
- App Build: IC-203.7148.57
- StackTrace:

```
java.lang.Throwable: Stub index points to a file without PSI: file = jar://G:/Program Files (x86)/Java/jdk1.8.0_221/javafx-src.zip!/com/sun/scenario/effect/impl/sw/sse, file type = com.intellij.openapi.fileTypes.UnknownFileType@25e82032, indexed file type = com.intellij.ide.highlighter.JavaClassFileType@3fcbdb39, used scope = com.intellij.psi.impl.search.JavaSourceFilterScope[com.intellij.psi.search.ProjectScopeBuilderImpl$1@a9ed86]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:159)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:52)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$2(StubIndexImpl.java:291)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:327)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:105)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:93)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:30)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:86)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClasses(JavaFileManagerImpl.java:73)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClasses(PsiElementFinderImpl.java:62)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClassesWithoutJvmFacade(JavaPsiFacadeImpl.java:157)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClassesWithJvmFacade(JavaPsiFacadeImpl.java:128)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClasses(JavaPsiFacadeImpl.java:120)
	at com.intellij.psi.impl.file.PsiPackageImpl.findAllClasses(PsiPackageImpl.java:203)
	at com.intellij.psi.impl.file.PsiPackageImpl.getCachedClassesByName(PsiPackageImpl.java:193)
	at com.intellij.psi.impl.file.PsiPackageImpl.findClassByShortName(PsiPackageImpl.java:270)
	at com.intellij.psi.impl.file.PsiPackageImpl.processDeclarations(PsiPackageImpl.java:310)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processPackageDeclarations(PsiJavaFileBaseImpl.java:439)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processOnDemandTarget(PsiJavaFileBaseImpl.java:449)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processImplicitImports(PsiJavaFileBaseImpl.java:416)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processOnDemandPackages(PsiJavaFileBaseImpl.java:369)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:289)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:61)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:40)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:207)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:136)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:489)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:44)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:375)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:368)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:179)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:221)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:198)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:179)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:806)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:798)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:774)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:423)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:417)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:177)
	at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.multiResolveConstructor(PsiResolveHelperImpl.java:52)
	at com.intellij.psi.impl.source.tree.java.PsiNewExpressionImpl$1.resolveInner(PsiNewExpressionImpl.java:151)
	at com.intellij.psi.impl.source.tree.java.PsiNewExpressionImpl$1.resolveInner(PsiNewExpressionImpl.java:141)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiPolyVariantCachingReference$MyResolver.resolve(PsiPolyVariantCachingReference.java:45)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:179)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:221)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:198)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:179)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiPolyVariantCachingReference.multiResolve(PsiPolyVariantCachingReference.java:19)
	at com.intellij.psi.impl.source.tree.java.PsiNewExpressionImpl.resolveMethodGenerics(PsiNewExpressionImpl.java:214)
	at com.intellij.psi.PsiDiamondType.getDiamondsAwareResolveResult(PsiDiamondType.java:200)
	at com.intellij.codeInsight.ExceptionUtil.getUnhandledExceptions(ExceptionUtil.java:450)
	at com.intellij.codeInsight.ExceptionUtil.getUnhandledExceptions(ExceptionUtil.java:439)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitNewExpression(ControlFlowAnalyzer.java:1685)
	at com.intellij.psi.impl.source.tree.java.PsiNewExpressionImpl.accept(PsiNewExpressionImpl.java:382)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitThrowStatement(ControlFlowAnalyzer.java:981)
	at com.intellij.psi.impl.source.tree.java.PsiThrowStatementImpl.accept(PsiThrowStatementImpl.java:85)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitCodeBlock(ControlFlowAnalyzer.java:388)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:212)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitBlockStatement(ControlFlowAnalyzer.java:419)
	at com.intellij.psi.impl.source.tree.java.PsiBlockStatementImpl.accept(PsiBlockStatementImpl.java:66)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.generateConditionalStatementInstructions(ControlFlowAnalyzer.java:812)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitIfStatement(ControlFlowAnalyzer.java:743)
	at com.intellij.psi.impl.source.tree.java.PsiIfStatementImpl.accept(PsiIfStatementImpl.java:194)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitCodeBlock(ControlFlowAnalyzer.java:388)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:212)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitBlockStatement(ControlFlowAnalyzer.java:419)
	at com.intellij.psi.impl.source.tree.java.PsiBlockStatementImpl.accept(PsiBlockStatementImpl.java:66)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitForStatement(ControlFlowAnalyzer.java:685)
	at com.intellij.psi.impl.source.tree.java.PsiForStatementImpl.accept(PsiForStatementImpl.java:158)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitCodeBlock(ControlFlowAnalyzer.java:388)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:212)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitBlockStatement(ControlFlowAnalyzer.java:419)
	at com.intellij.psi.impl.source.tree.java.PsiBlockStatementImpl.accept(PsiBlockStatementImpl.java:66)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.generateConditionalStatementInstructions(ControlFlowAnalyzer.java:806)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitIfStatement(ControlFlowAnalyzer.java:743)
	at com.intellij.psi.impl.source.tree.java.PsiIfStatementImpl.accept(PsiIfStatementImpl.java:194)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitCodeBlock(ControlFlowAnalyzer.java:388)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:212)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitBlockStatement(ControlFlowAnalyzer.java:419)
	at com.intellij.psi.impl.source.tree.java.PsiBlockStatementImpl.accept(PsiBlockStatementImpl.java:66)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.generateConditionalStatementInstructions(ControlFlowAnalyzer.java:806)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitIfStatement(ControlFlowAnalyzer.java:743)
	at com.intellij.psi.impl.source.tree.java.PsiIfStatementImpl.accept(PsiIfStatementImpl.java:194)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitCodeBlock(ControlFlowAnalyzer.java:388)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:212)
	at com.intellij.psi.controlFlow.ControlFlowAnalyzer.buildControlFlow(ControlFlowAnalyzer.java:110)
	at com.intellij.psi.controlFlow.ControlFlowFactory.doGetControlFlow(ControlFlowFactory.java:128)
	at com.intellij.psi.controlFlow.ControlFlowFactory.getControlFlow(ControlFlowFactory.java:113)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightControlFlowUtil.getControlFlow(HighlightControlFlowUtil.java:81)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightControlFlowUtil.checkVariableInitializedBeforeUsage(HighlightControlFlowUtil.java:409)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightControlFlowUtil.checkVariableInitializedBeforeUsage(HighlightControlFlowUtil.java:276)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitReferenceExpression(HighlightVisitorImpl.java:1397)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.accept(PsiReferenceExpressionImpl.java:778)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:186)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:336)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:269)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:68)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:220)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.problems.WolfTheProblemSolverImpl.orderVincentToCleanTheCar(WolfTheProblemSolverImpl.java:275)
	at com.intellij.codeInsight.problems.WolfTheProblemSolverImpl.startCheckingIfVincentSolvedProblemsYet(WolfTheProblemSolverImpl.java:228)
	at com.intellij.codeInsight.daemon.impl.WolfHighlightingPass.collectInformationWithProgress(WolfHighlightingPass.java:40)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: Material Theme UI
- Plugin Version: 6.17
- OS Name: Windows 10
- OS Version: 10.0
- Java Version: 11.0.10
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- Is Snapshot: false
- App Build: IU-203.7717.32
- StackTrace:

```
java.lang.Throwable: Stub index points to a file without PSI: file = jar://G:/Path/mavn/apache-maven-3.5.2/repository/io/springfox/springfox-spring-web/2.6.1/springfox-spring-web-2.6.1-sources.jar!/springfox/documentation/spring/web/readers, file type = com.intellij.openapi.fileTypes.UnknownFileType@41e57130, indexed file type = com.intellij.ide.highlighter.JavaClassFileType@2fa92a1d, used scope = null
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:165)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:52)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$2(StubIndexImpl.java:291)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:327)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:105)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:93)
	at org.jetbrains.kotlin.idea.core.script.KotlinScriptDependenciesClassFinder.findClassInternal(KotlinScriptDependenciesClassFinder.kt:59)
	at org.jetbrains.kotlin.idea.core.script.KotlinScriptDependenciesClassFinder.access$findClassInternal(KotlinScriptDependenciesClassFinder.kt:26)
	at org.jetbrains.kotlin.idea.core.script.KotlinScriptDependenciesClassFinder$everywhereCache$1$1.fun(KotlinScriptDependenciesClassFinder.kt:35)
	at org.jetbrains.kotlin.idea.core.script.KotlinScriptDependenciesClassFinder$everywhereCache$1$1.fun(KotlinScriptDependenciesClassFinder.kt:26)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at org.jetbrains.kotlin.idea.core.script.KotlinScriptDependenciesClassFinder.findClass(KotlinScriptDependenciesClassFinder.kt:42)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:89)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:67)
	at com.intellij.codeInsight.MetaAnnotationUtil.lambda$getAnnotationTypesWithChildren$0(MetaAnnotationUtil.java:66)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.codeInsight.MetaAnnotationUtil.getAnnotationTypesWithChildren(MetaAnnotationUtil.java:78)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.getAnnotationTypes(JamAnnotationTypeUtilImpl.java:139)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.getAnnotationTypesWithChildren(JamAnnotationTypeUtilImpl.java:128)
	at com.intellij.spring.model.jam.SpringSemContributorUtil$2.getAnnotationTypes(SpringSemContributorUtil.java:244)
	at com.intellij.spring.model.jam.SpringSemContributorUtil$2.fun(SpringSemContributorUtil.java:206)
	at com.intellij.spring.model.jam.SpringSemContributorUtil$2.fun(SpringSemContributorUtil.java:200)
	at com.intellij.spring.model.jam.SpringSemContributorUtil.lambda$createFunction$2(SpringSemContributorUtil.java:97)
	at com.intellij.semantic.SemRegistrar.lambda$registerSemElementProvider$0(SemRegistrar.java:27)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:133)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:103)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:88)
	at com.intellij.jam.JamService.getMetas(JamService.java:112)
	at com.intellij.jam.JamSemContributor.lambda$registerSemProviders$3(JamSemContributor.java:72)
	at com.intellij.semantic.SemRegistrar.lambda$registerSemElementProvider$0(SemRegistrar.java:27)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:133)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:103)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:88)
	at com.intellij.jam.JamService.getMetas(JamService.java:112)
	at com.intellij.jam.JamSemContributor.lambda$registerSemProviders$2(JamSemContributor.java:53)
	at com.intellij.semantic.SemRegistrar.lambda$registerSemElementProvider$0(SemRegistrar.java:27)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:133)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:103)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:88)
	at com.intellij.jam.JamReferenceContributor.getReferences(JamReferenceContributor.kt:37)
	at com.intellij.jam.JamReferenceContributor.access$getReferences(JamReferenceContributor.kt:17)
	at com.intellij.jam.JamReferenceContributor$registerReferenceProviders$1.invoke(JamReferenceContributor.kt:23)
	at com.intellij.jam.JamReferenceContributor$registerReferenceProviders$1.invoke(JamReferenceContributor.kt:17)
	at com.intellij.psi.UastReferenceRegistrar$uastReferenceProviderByUsage$1.getReferencesByElement(UastReferenceRegistrar.kt:103)
	at com.intellij.psi.UastReferenceProviderAdapter.getReferencesByElement(UastReferenceProviderAdapter.kt:12)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:204)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:167)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:146)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:39)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:153)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:78)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:120)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
	at com.intellij.psi.PsiReferenceServiceImpl.doGetReferences(PsiReferenceServiceImpl.java:35)
	at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:27)
	at com.intellij.psi.PsiReferenceService.getContributedReferences(PsiReferenceService.java:34)
	at com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl.getReferences(PsiLiteralExpressionImpl.java:193)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:45)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:336)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:269)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$analyze$1(HighlightVisitorImpl.java:211)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:370)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:210)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
