### ISSUE TITLE
[Auto Generated Report]java.lang.StringIndexOutOfBoundsException: String index out of range

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#1133]
- Plugin Name: 
- Plugin Version: 6.17
- OS Name: Mac OS X
- OS Version: 10.16
- Java Version: 11.0.9.1
- App Name: WebStorm
- App Full Name: WebStorm
- Is Snapshot: false
- App Build: WS-203.7148.54
- StackTrace:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at com.intellij.lang.javascript.frameworks.modules.JSMappingReferenceSet.getAliasedReferences(JSMappingReferenceSet.kt:114)
	at com.intellij.lang.javascript.frameworks.modules.JSMappingReferenceSet.getAliasedAndExactReferences(JSMappingReferenceSet.kt:97)
	at com.intellij.lang.typescript.modules.PathMappingReferenceContributorBase.getReferencesForConfig(PathMappingReferenceContributorBase.java:57)
	at com.intellij.lang.typescript.modules.TypeScriptPathMappingReferenceContributor.getReferences(TypeScriptPathMappingReferenceContributor.java:40)
	at com.intellij.lang.javascript.frameworks.modules.JSBaseModuleReferenceContributor.getAllReferences(JSBaseModuleReferenceContributor.java:31)
	at com.intellij.lang.javascript.psi.resolve.JSModuleReferenceContributor.resolveReferences(JSModuleReferenceContributor.java:84)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferencesUtil.getMostPriorityModules(JSFileReferencesUtil.java:157)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferencesUtil.calculateMainModules(JSFileReferencesUtil.java:111)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.resolveDirectModulesNoCache(JSFileReferenceCache.java:209)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.getCachedModules(JSFileReferenceCache.java:130)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.resolveDirectModules(JSFileReferenceCache.java:116)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.resolveModuleReference(JSFileReferenceCache.java:78)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.resolveModuleReferences(JSFileReferenceCache.java:67)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferencesUtil.resolveModuleReferences(JSFileReferencesUtil.java:64)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferencesUtil.resolveModuleReferences(JSFileReferencesUtil.java:59)
	at com.intellij.lang.ecmascript6.psi.impl.ES6FromClauseImpl.resolveReferencedElements(ES6FromClauseImpl.java:75)
	at com.intellij.lang.ecmascript6.resolve.ES6PsiUtil.getFromClauseResolvedReferences(ES6PsiUtil.java:195)
	at com.intellij.lang.ecmascript6.resolve.ES6PsiUtil.resolveSymbolForSpecifier(ES6PsiUtil.java:325)
	at com.intellij.lang.ecmascript6.resolve.ES6PsiUtil.resolveSymbolForSpecifier(ES6PsiUtil.java:308)
	at com.intellij.lang.ecmascript6.psi.impl.ES6ImportSpecifierImpl.resolveImportSpecifier(ES6ImportSpecifierImpl.java:103)
	at com.intellij.lang.ecmascript6.psi.impl.ES6ImportSpecifierImpl.lambda$multiResolve$0(ES6ImportSpecifierImpl.java:76)
	at com.intellij.psi.impl.source.resolve.ResolveCache$PolyVariantResolver.resolve(ResolveCache.java:64)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:149)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:221)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:198)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:149)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:164)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:157)
	at com.intellij.lang.ecmascript6.psi.impl.ES6ImportSpecifierImpl.multiResolve(ES6ImportSpecifierImpl.java:76)
	at com.intellij.lang.javascript.highlighting.JSSemanticHighlightingUtil.highlight(JSSemanticHighlightingUtil.java:197)
	at com.intellij.lang.javascript.validation.JSAnnotatingVisitor.visitImportSpecifier(JSAnnotatingVisitor.java:1296)
	at com.intellij.lang.ecmascript6.psi.impl.ES6ImportSpecifierImpl.accept(ES6ImportSpecifierImpl.java:47)
	at com.intellij.lang.javascript.validation.JSAnnotator.annotate(JSAnnotator.java:17)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:336)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:269)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: 
- Plugin Version: 6.17
- OS Name: Mac OS X
- OS Version: 11.3.1
- Java Version: 11.0.10
- App Name: GoLand
- App Full Name: GoLand
- Is Snapshot: false
- App Build: GO-211.7142.13
- StackTrace:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 22
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at com.goide.highlighting.errors.GoStringLiteralSpecChecker.visitStringLiteral(GoStringLiteralSpecChecker.java:36)
	at com.goide.psi.impl.GoStringLiteralImpl.accept(GoStringLiteralImpl.java:21)
	at com.goide.psi.impl.GoStringLiteralImpl.accept(GoStringLiteralImpl.java:26)
	at com.goide.highlighting.GoAnnotator.annotate(GoAnnotator.java:93)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: 
- Plugin Version: 6.17
- OS Name: Mac OS X
- OS Version: 11.3.1
- Java Version: 11.0.10
- App Name: GoLand
- App Full Name: GoLand
- Is Snapshot: false
- App Build: GO-211.7142.13
- StackTrace:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 28
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at com.goide.highlighting.errors.GoStringLiteralSpecChecker.visitStringLiteral(GoStringLiteralSpecChecker.java:36)
	at com.goide.psi.impl.GoStringLiteralImpl.accept(GoStringLiteralImpl.java:21)
	at com.goide.psi.impl.GoStringLiteralImpl.accept(GoStringLiteralImpl.java:26)
	at com.goide.highlighting.GoAnnotator.annotate(GoAnnotator.java:93)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: 
- Plugin Version: 6.17
- OS Name: Mac OS X
- OS Version: 11.4
- Java Version: 11.0.10
- App Name: PhpStorm
- App Full Name: PhpStorm
- Is Snapshot: false
- App Build: PS-211.7142.44
- StackTrace:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at com.intellij.lang.javascript.frameworks.modules.JSMappingReferenceSet.getAliasedReferences(JSMappingReferenceSet.kt:114)
	at com.intellij.lang.javascript.frameworks.modules.JSMappingReferenceSet.getAliasedAndExactReferences(JSMappingReferenceSet.kt:97)
	at com.intellij.lang.typescript.modules.PathMappingReferenceContributorBase.getReferencesForConfig(PathMappingReferenceContributorBase.java:57)
	at com.intellij.lang.typescript.modules.TypeScriptPathMappingReferenceContributor.getReferences(TypeScriptPathMappingReferenceContributor.java:45)
	at com.intellij.lang.javascript.frameworks.modules.JSBaseModuleReferenceContributor.getAllReferences(JSBaseModuleReferenceContributor.java:31)
	at com.intellij.lang.javascript.psi.resolve.JSModuleReferenceContributor.resolveReferences(JSModuleReferenceContributor.java:84)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferencesUtil.getMostPriorityModules(JSFileReferencesUtil.java:154)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferencesUtil.calculateMainModules(JSFileReferencesUtil.java:108)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.resolveDirectModulesNoCache(JSFileReferenceCache.java:205)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.getCachedModules(JSFileReferenceCache.java:126)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.resolveDirectModules(JSFileReferenceCache.java:112)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.resolveModuleReference(JSFileReferenceCache.java:74)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.resolveModuleReferences(JSFileReferenceCache.java:63)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferencesUtil.resolveModuleReferences(JSFileReferencesUtil.java:61)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferencesUtil.resolveModuleReferences(JSFileReferencesUtil.java:56)
	at com.intellij.lang.ecmascript6.psi.impl.ES6FromClauseImpl.resolveReferencedElements(ES6FromClauseImpl.java:75)
	at com.intellij.lang.ecmascript6.resolve.ES6PsiUtil.resolveDefaultExport(ES6PsiUtil.java:222)
	at com.intellij.lang.ecmascript6.psi.impl.ES6ImportedExportedDefaultBindingImpl.findReferencedElementsImpl(ES6ImportedExportedDefaultBindingImpl.java:108)
	at com.intellij.lang.ecmascript6.psi.impl.ES6ImportedExportedDefaultBindingImpl.lambda$findReferencedElements$0(ES6ImportedExportedDefaultBindingImpl.java:97)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.lang.ecmascript6.psi.impl.ES6ImportedExportedDefaultBindingImpl.findReferencedElements(ES6ImportedExportedDefaultBindingImpl.java:94)
	at com.intellij.lang.ecmascript6.psi.impl.ES6ImportedBindingImpl.findReferencedElements(ES6ImportedBindingImpl.java:70)
	at com.intellij.lang.javascript.validation.JSAnnotatingVisitor.visitES6ImportedBinding(JSAnnotatingVisitor.java:1306)
	at com.intellij.lang.ecmascript6.psi.impl.ES6ImportedBindingImpl.accept(ES6ImportedBindingImpl.java:52)
	at com.intellij.lang.javascript.validation.JSAnnotator.annotate(JSAnnotator.java:17)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:603)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
