### ISSUE TITLE
[Auto Generated Report]org.jetbrains.mvstore.MVStoreException

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#1824]
- Plugin Name: 
- Plugin Version: 6.17
- OS Name: Mac OS X
- OS Version: 10.15.7
- Java Version: 11.0.10
- App Name: PhpStorm
- App Full Name: PhpStorm
- Is Snapshot: false
- App Build: PS-211.7142.44
- StackTrace:

```
org.jetbrains.mvstore.MVStoreException: Reading from file sun.nio.ch.FileChannelImpl@766eca4a failed at 3712347 (length -1), read 0, remaining 32768
	at org.jetbrains.mvstore.DataUtil.readFully(DataUtil.java:119)
	at org.jetbrains.mvstore.FileStore.readFully(FileStore.java:124)
	at org.jetbrains.mvstore.Chunk.readBufferForPage(Chunk.java:431)
	at org.jetbrains.mvstore.MVStore.doReadPage(MVStore.java:2627)
	at org.jetbrains.mvstore.MVStore.lambda$readPage$10(MVStore.java:2613)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2346)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2344)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2327)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at org.jetbrains.mvstore.MVStore.readPage(MVStore.java:2613)
	at org.jetbrains.mvstore.NonLeafPage.getChildPage(NonLeafPage.java:62)
	at org.jetbrains.mvstore.Page.get(Page.java:205)
	at org.jetbrains.mvstore.MVMap.get(MVMap.java:372)
	at com.intellij.ui.svg.SvgPrebuiltCacheManager.loadFromCache(SvgPrebuiltCacheManager.java:48)
	at com.intellij.util.SVGLoader.loadFromClassResource(SVGLoader.java:147)
	at com.intellij.ui.RasterizedImageDataLoader.loadRasterized(RasterizedImageDataLoader.java:139)
	at com.intellij.ui.RasterizedImageDataLoader.loadImage(RasterizedImageDataLoader.java:56)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.loadImage(IconLoader.java:936)
	at com.intellij.openapi.util.IconLoader$ScaledIconCache.getOrScaleIcon(IconLoader.java:1005)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getRealIcon(IconLoader.java:824)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getIconWidth(IconLoader.java:752)
	at com.intellij.ui.BalloonLayoutConfiguration.<init>(BalloonLayoutConfiguration.java:162)
	at com.intellij.ui.BalloonLayoutConfiguration.<init>(BalloonLayoutConfiguration.java:126)
	at com.intellij.ui.BalloonLayoutConfiguration.treeLines(BalloonLayoutConfiguration.java:117)
	at com.intellij.ui.BalloonLayoutConfiguration.create(BalloonLayoutConfiguration.java:96)
	at com.intellij.notification.impl.NotificationsManagerImpl.createBalloon(NotificationsManagerImpl.java:478)
	at com.intellij.notification.impl.NotificationsManagerImpl.createBalloon(NotificationsManagerImpl.java:370)
	at com.github.izhangzhihao.rainbow.brackets.NotifyKt.showFullNotification(Notify.kt:42)
	at com.github.izhangzhihao.rainbow.brackets.RainbowUpdateNotifyActivity$Companion.showUpdate(RainbowUpdateNotifyActivity.kt:95)
	at com.github.izhangzhihao.rainbow.brackets.RainbowUpdateNotifyActivity$Companion.access$showUpdate(RainbowUpdateNotifyActivity.kt:41)
	at com.github.izhangzhihao.rainbow.brackets.RainbowUpdateNotifyActivity.runActivity(RainbowUpdateNotifyActivity.kt:24)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.java:335)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:309)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivities$3(StartupManagerImpl.java:245)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:403)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:395)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.EOFException
	at org.jetbrains.mvstore.DataUtil.readFully(DataUtil.java:105)
	... 67 more
```

**Comment by izhangzhihao** [comment]
Not a bug of this plugin, please follow: https://youtrack.jetbrains.com/issue/WI-60492
