### ISSUE TITLE
[Auto Generated Report]java.nio.file.NoSuchFileException: D

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#1869]
- Plugin Name: 
- Plugin Version: 6.17
- OS Name: Windows 10
- OS Version: 10.0
- Java Version: 11.0.10
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- Is Snapshot: false
- App Build: IU-211.7142.45
- StackTrace:

```
java.nio.file.NoSuchFileException: D:\develop\JetBrains\.IntelliJIdea\system\Maven\Indices\Index12\data0\artifactIds-map.dat.len
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
	at com.intellij.util.io.ResizeableMappedFile.readLength(ResizeableMappedFile.java:178)
	at com.intellij.util.io.ResizeableMappedFile.<init>(ResizeableMappedFile.java:66)
	at com.intellij.util.io.PersistentBTreeEnumerator.<init>(PersistentBTreeEnumerator.java:73)
	at com.intellij.util.io.PersistentEnumerator.createDefaultEnumerator(PersistentEnumerator.java:65)
	at com.intellij.util.io.PersistentMapImpl.<init>(PersistentMapImpl.java:131)
	at com.intellij.util.io.PersistentMapBuilder.buildImplementation(PersistentMapBuilder.java:64)
	at com.intellij.util.io.PersistentMapBuilder.build(PersistentMapBuilder.java:41)
	at com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:39)
	at com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:60)
	at org.jetbrains.idea.maven.indices.MavenIndex$IndexData.createPersistentMap(MavenIndex.java:686)
	at org.jetbrains.idea.maven.indices.MavenIndex$IndexData.<init>(MavenIndex.java:673)
	at org.jetbrains.idea.maven.indices.MavenIndex.doOpen(MavenIndex.java:210)
	at org.jetbrains.idea.maven.indices.MavenIndex.open(MavenIndex.java:184)
	at org.jetbrains.idea.maven.indices.MavenIndex.doIndexTask(MavenIndex.java:637)
	at org.jetbrains.idea.maven.indices.MavenIndex.lambda$hasVersion$8(MavenIndex.java:587)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1003)
	at org.jetbrains.idea.maven.indices.MavenIndex.hasVersion(MavenIndex.java:587)
	at org.jetbrains.idea.maven.indices.MavenProjectIndicesManager.lambda$hasVersion$7(MavenProjectIndicesManager.java:284)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at org.jetbrains.idea.maven.indices.MavenProjectIndicesManager.hasVersion(MavenProjectIndicesManager.java:284)
	at org.jetbrains.idea.maven.dom.converters.MavenArtifactCoordinatesVersionConverter.doIsValid(MavenArtifactCoordinatesVersionConverter.kt:63)
	at org.jetbrains.idea.maven.dom.converters.MavenArtifactCoordinatesConverter$ConverterStrategy.isValid(MavenArtifactCoordinatesConverter.java:216)
	at org.jetbrains.idea.maven.dom.converters.MavenArtifactCoordinatesConverter.fromString(MavenArtifactCoordinatesConverter.java:69)
	at org.jetbrains.idea.maven.dom.converters.MavenArtifactCoordinatesVersionConverter.fromString(MavenArtifactCoordinatesVersionConverter.kt:33)
	at org.jetbrains.idea.maven.dom.converters.MavenArtifactCoordinatesVersionConverter.fromString(MavenArtifactCoordinatesVersionConverter.kt:30)
	at com.intellij.util.xml.impl.GetInvocation.a(GetInvocation.java:99)
	at com.intellij.util.xml.impl.GetInvocation.a(GetInvocation.java:74)
	at com.intellij.util.xml.impl.GetInvocation.invoke(GetInvocation.java:62)
	at com.intellij.util.xml.impl.DomInvocationHandler.invoke(DomInvocationHandler.java:658)
	at com.intellij.util.xml.GenericDomValue$$EnhancerByJetBrainsMainCglib$$2e754a1e.getValue(<generated>)
	at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils.findParent(MavenDomProjectProcessorUtils.java:94)
	at org.jetbrains.idea.maven.dom.annotator.MavenDomGutterAnnotator.annotateMavenDomParent(MavenDomGutterAnnotator.java:162)
	at org.jetbrains.idea.maven.dom.annotator.MavenDomGutterAnnotator.annotate(MavenDomGutterAnnotator.java:104)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:603)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: 
- Plugin Version: 6.17
- OS Name: Windows 10
- OS Version: 10.0
- Java Version: 11.0.11
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- Is Snapshot: false
- App Build: IU-211.7442.40
- StackTrace:

```
java.nio.file.NoSuchFileException: D:\IntelliJ IDEA\.IntelliJIdea12\system\Maven\Indices\Index3\data2\artifactIds-map.dat.len
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
	at com.intellij.util.io.ResizeableMappedFile.readLength(ResizeableMappedFile.java:178)
	at com.intellij.util.io.ResizeableMappedFile.<init>(ResizeableMappedFile.java:66)
	at com.intellij.util.io.PersistentBTreeEnumerator.<init>(PersistentBTreeEnumerator.java:73)
	at com.intellij.util.io.PersistentEnumerator.createDefaultEnumerator(PersistentEnumerator.java:65)
	at com.intellij.util.io.PersistentMapImpl.<init>(PersistentMapImpl.java:131)
	at com.intellij.util.io.PersistentMapBuilder.buildImplementation(PersistentMapBuilder.java:64)
	at com.intellij.util.io.PersistentMapBuilder.build(PersistentMapBuilder.java:41)
	at com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:39)
	at com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:60)
	at org.jetbrains.idea.maven.indices.MavenIndex$IndexData.createPersistentMap(MavenIndex.java:684)
	at org.jetbrains.idea.maven.indices.MavenIndex$IndexData.<init>(MavenIndex.java:671)
	at org.jetbrains.idea.maven.indices.MavenIndex.doOpen(MavenIndex.java:208)
	at org.jetbrains.idea.maven.indices.MavenIndex.open(MavenIndex.java:182)
	at org.jetbrains.idea.maven.indices.MavenIndex.doIndexTask(MavenIndex.java:635)
	at org.jetbrains.idea.maven.indices.MavenIndex.lambda$hasValue$10(MavenIndex.java:591)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at org.jetbrains.idea.maven.indices.MavenIndex.hasValue(MavenIndex.java:591)
	at org.jetbrains.idea.maven.indices.MavenIndex.hasGroupId(MavenIndex.java:571)
	at org.jetbrains.idea.maven.indices.MavenProjectIndicesManager.lambda$hasGroupId$5(MavenProjectIndicesManager.java:261)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at org.jetbrains.idea.maven.indices.MavenProjectIndicesManager.hasGroupId(MavenProjectIndicesManager.java:261)
	at org.jetbrains.idea.maven.dom.converters.MavenArtifactCoordinatesGroupIdConverter.doIsValid(MavenArtifactCoordinatesGroupIdConverter.java:23)
	at org.jetbrains.idea.maven.dom.converters.MavenArtifactCoordinatesConverter$ConverterStrategy.isValid(MavenArtifactCoordinatesConverter.java:216)
	at org.jetbrains.idea.maven.dom.converters.MavenArtifactCoordinatesConverter.fromString(MavenArtifactCoordinatesConverter.java:69)
	at org.jetbrains.idea.maven.dom.converters.MavenArtifactCoordinatesConverter.fromString(MavenArtifactCoordinatesConverter.java:59)
	at com.intellij.util.xml.impl.GetInvocation.a(GetInvocation.java:99)
	at com.intellij.util.xml.impl.GetInvocation.a(GetInvocation.java:74)
	at com.intellij.util.xml.impl.GetInvocation.invoke(GetInvocation.java:62)
	at com.intellij.util.xml.impl.DomInvocationHandler.invoke(DomInvocationHandler.java:658)
	at com.intellij.util.xml.GenericDomValue$$EnhancerByJetBrainsMainCglib$$2e754a1e.getValue(<generated>)
	at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils.findParent(MavenDomProjectProcessorUtils.java:93)
	at org.jetbrains.idea.maven.dom.annotator.MavenDomGutterAnnotator.annotateMavenDomParent(MavenDomGutterAnnotator.java:162)
	at org.jetbrains.idea.maven.dom.annotator.MavenDomGutterAnnotator.annotate(MavenDomGutterAnnotator.java:104)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:603)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
