### ISSUE TITLE
AppCode prompt error

### ISSUE THREAD

**Issue by karise-guo** [izhangzhihao/intellij-rainbow-brackets#189]
## Programming language

Swift

## Environment

* Plugin version: 5.1.0
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
AppCode 2018.2.4
Build #OC-182.4892.21, built on October 16, 2018
Licensed to Jonzzs Guo
Subscription is active until May 29, 2019
For educational use only.
JRE: 1.8.0_152-release-1248-b19 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1
```

## Error Info

![](https://ws2.sinaimg.cn/large/006tNbRwgy1fx0xu9h3lhj31ay0titg5.jpg)

**Comment by izhangzhihao** [comment]
Thanks for your report, could you provide the full `stacktrace.txt`? thanks

**Comment by Gixx** [comment]
Hi, this (or kind of similar) just happened me also. Here is the stacktrace:

```
In file: file:///Users/g.ivan/Projects/*******************/Campaign.Form.js

java.lang.IllegalStateException: color must not be null
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.setHighlightInfo(RainbowHighlightVisitor.kt:65)
	at com.github.izhangzhihao.rainbow.brackets.visitor.DefaultRainbowVisitor.visit(DefaultRainbowVisitor.kt:37)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:366)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:33)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.problems.WolfTheProblemSolverImpl.a(WolfTheProblemSolverImpl.java:245)
	at com.intellij.codeInsight.problems.WolfTheProblemSolverImpl.startCheckingIfVincentSolvedProblemsYet(WolfTheProblemSolverImpl.java:198)
	at com.intellij.codeInsight.daemon.impl.WolfHighlightingPass.collectInformationWithProgress(WolfHighlightingPass.java:43)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.e(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by izhangzhihao** [comment]
@Gixx Which version are you using?

**Comment by Gixx** [comment]
PHPStorm 2018.2.5
Rainbow Brackets 5.11 now (was 5.10 when I got the popup)

**Comment by izhangzhihao** [comment]
Thanks, this should be fixed in the next release.

**Comment by karise-guo** [comment]
Hi, it's no reappeared before, but today it happened me again. Here is the stack trace:

```
java.lang.Throwable: Calendar Equatable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftSubstitutionCache.a(SwiftSubstitutionCache.java:262)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftSubstitutionCache.b(SwiftSubstitutionCache.java:127)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftSubstitutionCache.get(SwiftSubstitutionCache.java:117)
	at com.jetbrains.swift.search.SwiftSearchUtil.c(SwiftSearchUtil.java:319)
	at com.jetbrains.swift.search.SwiftSearchUtil.checkInheriting(SwiftSearchUtil.java:149)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftCallableFilteringStrategy.b(SwiftCallableFilteringStrategy.java:428)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftCallableFilteringStrategy.a(SwiftCallableFilteringStrategy.java:178)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftCallableFilteringStrategy.compareAccessibleResults(SwiftCallableFilteringStrategy.java:55)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftAccessControlFilteringStrategy.compare(SwiftAccessControlFilteringStrategy.kt:19)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftComparingFilteringStrategy.a(SwiftComparingFilteringStrategy.java:83)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftComparingFilteringStrategy.a(SwiftComparingFilteringStrategy.java:60)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftComparingFilteringStrategy.filterResults(SwiftComparingFilteringStrategy.java:37)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftRecursiveResolverProcessor.getResults(SwiftRecursiveResolverProcessor.java:166)
	at com.jetbrains.swift.psi.impl.expression.SwiftOperatorFunctionReference.multiResolve(SwiftOperatorFunctionReference.java:181)
	at com.jetbrains.swift.psi.impl.expression.SwiftOperatorFunctionReference.multiResolve(SwiftOperatorFunctionReference.java:152)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.b(SwiftSymbolsManagerImpl.java:224)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.a(SwiftSymbolsManagerImpl.java:218)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:96)
	at com.jetbrains.swift.codeinsight.resolve.recursive.DependencyManager.run(DependencyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:90)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.b(RecursiveResolveContext.java:66)
	at com.jetbrains.swift.codeinsight.resolve.recursive.KeyManager.doWithKey(KeyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.cacheOrGet(RecursiveResolveContext.java:65)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.multiResolve(SwiftSymbolsManagerImpl.java:218)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceBase.multiResolve(SwiftReferenceBase.java:252)
	at com.jetbrains.swift.psi.impl.SwiftReferenceElementBase.doMultiResolve(SwiftReferenceElementBase.java:124)
	at com.jetbrains.swift.psi.impl.SwiftReferenceElementBase.advancedResolve(SwiftReferenceElementBase.java:102)
	at com.jetbrains.swift.codeinsight.highlighting.SwiftColorAnnotator.annotate(SwiftColorAnnotator.java:113)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:366)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.e(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
