### ISSUE TITLE
AppCode prompt error

### ISSUE THREAD

**Issue by karise-guo** [izhangzhihao/intellij-rainbow-brackets#190]
## Programming language

Swift

## Environment

* Plugin version: 5.1.0
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
AppCode 2018.2.4
Build #OC-182.4892.21, built on October 16, 2018
Licensed to Jonzzs Guo
Subscription is active until May 29, 2019
For educational use only.
JRE: 1.8.0_152-release-1248-b19 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1
```

## Error Info

![](https://ws2.sinaimg.cn/large/006tNbRwgy1fx0xu9h3lhj31ay0titg5.jpg)

```
java.lang.Throwable: Invalid file: file:///Users/Jonzzs/Library/Developer/Xcode/DerivedData/client_ios_fm_b-bnyofnagwblkvtbqmqhylknbilgw/Build/Products/Debug-iphoneos/Material/Material.framework/Headers/Material-umbrella.h
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:364)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:183)
	at com.jetbrains.cidr.modulemap.resolve.ModuleMapResolveService.getModuleDependencies(ModuleMapResolveService.kt:192)
	at com.jetbrains.cidr.modulemap.resolve.ModuleMapResolveService$ModuleMapProcessingContext.doProcess(ModuleMapResolveService.kt:269)
	at com.jetbrains.cidr.modulemap.resolve.ModuleMapResolveService.a(ModuleMapResolveService.kt:240)
	at com.jetbrains.cidr.modulemap.resolve.ModuleMapResolveService.processModules(ModuleMapResolveService.kt:230)
	at com.jetbrains.cidr.modulemap.resolve.ModuleMapResolveService.processModules$default(ModuleMapResolveService.kt:227)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftModuleDependenciesImportUtils.a(SwiftModuleDependenciesImportUtils.kt:48)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftModuleDependenciesImportUtils.b(SwiftModuleDependenciesImportUtils.kt:30)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftModuleDependenciesImportUtils.processModuleAndDependencies(SwiftModuleDependenciesImportUtils.kt:20)
	at com.jetbrains.swift.codeinsight.resolve.SwiftGlobalSymbolsImpl$CacheBuilder.a(SwiftGlobalSymbolsImpl.java:233)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:789)
	at com.jetbrains.swift.codeinsight.resolve.SwiftResolveService.processFileImports(SwiftResolveService.java:292)
	at com.jetbrains.swift.codeinsight.resolve.SwiftGlobalSymbolsImpl$CacheBuilder.processImportedModules(SwiftGlobalSymbolsImpl.java:232)
	at com.jetbrains.swift.codeinsight.resolve.SwiftGlobalSymbolsImpl$CacheBuilder.build(SwiftGlobalSymbolsImpl.java:202)
	at com.jetbrains.swift.codeinsight.resolve.SwiftGlobalSymbolsImpl.buildFileCache(SwiftGlobalSymbolsImpl.java:158)
	at com.jetbrains.swift.codeinsight.resolve.SwiftFileSymbolCache$FileCache.createValue(SwiftFileSymbolCache.java:60)
	at com.jetbrains.swift.codeinsight.resolve.SwiftFileSymbolCache$FileCache.createValue(SwiftFileSymbolCache.java:53)
	at com.jetbrains.cidr.lang.psi.impl.symbols.SLRUSynchronizedCache$1$1.compute(SLRUSynchronizedCache.java:21)
	at com.intellij.openapi.util.AtomicNotNullLazyValue.getValue(AtomicNotNullLazyValue.java:40)
	at com.jetbrains.cidr.lang.psi.impl.symbols.SLRUSynchronizedCache.get(SLRUSynchronizedCache.java:37)
	at com.jetbrains.swift.codeinsight.resolve.SwiftFileSymbolCache.getCache(SwiftFileSymbolCache.java:40)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceBase.processGlobal(SwiftReferenceBase.java:69)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceBase.processGlobal(SwiftReferenceBase.java:56)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftTypeReferenceImpl.a(SwiftTypeReferenceImpl.java:136)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftTypeReferenceImpl.multiResolve(SwiftTypeReferenceImpl.java:78)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.b(SwiftSymbolsManagerImpl.java:224)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.a(SwiftSymbolsManagerImpl.java:239)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.multiResolve(SwiftSymbolsManagerImpl.java:214)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceBase.multiResolve(SwiftReferenceBase.java:252)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReference.advancedResolve(SwiftReference.java:41)
	at com.jetbrains.swift.psi.impl.types.SwiftClassTypeImpl.doResolve(SwiftClassTypeImpl.java:29)
	at com.jetbrains.swift.psi.impl.types.SwiftAbstractReferenceClassTypeImpl.advancedResolve(SwiftAbstractReferenceClassTypeImpl.java:33)
	at com.jetbrains.swift.psi.impl.types.SwiftTypeUtil.resolveClassType(SwiftTypeUtil.java:182)
	at com.jetbrains.swift.psi.impl.types.SwiftReferenceClassTypeImpl.resolveType(SwiftReferenceClassTypeImpl.java:27)
	at com.jetbrains.swift.codeinsight.resolve.SwiftResolveUtil.getExtensionBaseClassSymbol(SwiftResolveUtil.java:423)
	at com.jetbrains.swift.symbols.impl.typeDeclarations.SwiftExtensionSymbolImpl.getBaseTypeSymbol(SwiftExtensionSymbolImpl.java:55)
	at com.jetbrains.swift.codeinsight.resolve.SwiftExtensionsImpl.a(SwiftExtensionsImpl.java:73)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:99)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:54)
	at com.jetbrains.swift.codeinsight.resolve.SwiftExtensionsImpl.a(SwiftExtensionsImpl.java:73)
	at com.jetbrains.swift.codeinsight.resolve.SwiftExtensionsImpl.processExtensions(SwiftExtensionsImpl.java:45)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalker.processExtensions(SwiftSuperTypesWalker.java:236)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalker.processExtensionsAndSuperTypes(SwiftSuperTypesWalker.java:218)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalker.processClassSymbol(SwiftSuperTypesWalker.java:202)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalker.a(SwiftSuperTypesWalker.java:148)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalker.process(SwiftSuperTypesWalker.java:115)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftTypeReferenceImpl.a(SwiftTypeReferenceImpl.java:279)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftTypeReferenceImpl.a(SwiftTypeReferenceImpl.java:220)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:99)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:54)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftTypeReferenceImpl.a(SwiftTypeReferenceImpl.java:217)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftTypeReferenceImpl.a(SwiftTypeReferenceImpl.java:149)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftTypeReferenceImpl.a(SwiftTypeReferenceImpl.java:131)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftTypeReferenceImpl.multiResolve(SwiftTypeReferenceImpl.java:78)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftLocalTypeReferenceImpl.multiResolve(SwiftLocalTypeReferenceImpl.java:51)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.b(SwiftSymbolsManagerImpl.java:224)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.a(SwiftSymbolsManagerImpl.java:218)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:96)
	at com.jetbrains.swift.codeinsight.resolve.recursive.DependencyManager.run(DependencyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.b(RecursiveResolveContext.java:90)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:66)
	at com.jetbrains.swift.codeinsight.resolve.recursive.KeyManager.doWithKey(KeyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.cacheOrGet(RecursiveResolveContext.java:65)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.multiResolve(SwiftSymbolsManagerImpl.java:218)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceBase.multiResolve(SwiftReferenceBase.java:252)
	at com.jetbrains.swift.psi.impl.SwiftReferenceElementBase.doMultiResolve(SwiftReferenceElementBase.java:118)
	at com.jetbrains.swift.psi.impl.SwiftReferenceElementBase.advancedResolve(SwiftReferenceElementBase.java:102)
	at com.jetbrains.swift.codeinsight.highlighting.SwiftColorAnnotator.annotate(SwiftColorAnnotator.java:113)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:366)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.e(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by izhangzhihao** [comment]
`Invalid file`? I think we should ignore this error cause there is nothing to do with this plugin.
