### ISSUE TITLE
It seems that I can't press CTRL in CLion.

### ISSUE THREAD

**Issue by gaoxiangliu** [izhangzhihao/intellij-rainbow-brackets#193]
Hello,
This plug-in works properly in IDEA and Android Studio and so forth. However, it seems that something wrong when working in CLion. When I press down the CTRL button, the code block isn't highlighted. What is more, I got an exception about the plug-in. It writes:
```org/jetbrains/kotlin/psi/psiUtil/PsiUtilsKt
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/psi/psiUtil/PsiUtilsKt
	at com.github.izhangzhihao.rainbow.brackets.RainbowInfo.containsOffset(RainbowInfo.kt:38)
	at com.github.izhangzhihao.rainbow.brackets.CtrlHandler$Companion.getRainbowInfo(CtrlHandler.kt:118)
	at com.github.izhangzhihao.rainbow.brackets.CtrlHandler$Companion.findRainbowInfoAt(CtrlHandler.kt:110)
	at com.github.izhangzhihao.rainbow.brackets.CtrlHandler$Companion.access$findRainbowInfoAt(CtrlHandler.kt:97)
	at com.github.izhangzhihao.rainbow.brackets.CtrlHandler.addHighlightAt(CtrlHandler.kt:65)
	at com.github.izhangzhihao.rainbow.brackets.CtrlHandler.onKeyPressed(CtrlHandler.kt:50)
	at com.github.izhangzhihao.rainbow.brackets.EditorEventActionManager$EventListener.keyPressed(EditorEventActionManager.kt:70)
	at java.awt.AWTEventMulticaster.keyPressed(AWTEventMulticaster.java:250)
	at java.awt.Component.processKeyEvent(Component.java:6506)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2833)
	at java.awt.Component.processEvent(Component.java:6325)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:27)
	at java.awt.Component.dispatchEventImpl(Component.java:4774)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:705)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)```

So, how can I use it in CLion, or making it to support the CLion?

**Comment by izhangzhihao** [comment]
Please common as below: 

## Your Environment

* Plugin version:
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.519, built on March 22, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3
```

## Plugins
Which version of Kotlin plugin are you using? Is it enabled?
