### ISSUE TITLE
java.lang.RuntimeException: java.lang.NoSuchMethodException: net.ishchenko.idea.nginx.annotator.NginxAnnotatingVisitor.<init>()

### ISSUE THREAD

**Issue by BorzdeG** [izhangzhihao/intellij-rainbow-brackets#212]
```
In file: file:///PROJECT_DIR/!configs/nginx.conf

java.lang.RuntimeException: java.lang.NoSuchMethodException: net.ishchenko.idea.nginx.annotator.NginxAnnotatingVisitor.<init>()
	at com.intellij.util.ExceptionUtilRt.rethrow(ExceptionUtilRt.java:31)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:411)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:379)
	at com.intellij.codeInsight.daemon.impl.ThreadLocalAnnotatorMap.cloneTemplates(ThreadLocalAnnotatorMap.java:46)
	at com.intellij.codeInsight.daemon.impl.ThreadLocalAnnotatorMap.get(ThreadLocalAnnotatorMap.java:66)
	at com.intellij.codeInsight.daemon.impl.CachedAnnotators.get(CachedAnnotators.java:31)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:107)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:284)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:71)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:281)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NoSuchMethodException: net.ishchenko.idea.nginx.annotator.NginxAnnotatingVisitor.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:385)
	... 35 more
```

**Comment by izhangzhihao** [comment]
This issue should go to [idea-nginx](https://github.com/ishchenko/idea-nginx).

**Comment by BorzdeG** [comment]
![](https://habrastorage.org/webt/pu/gp/0i/pugp0ixurkl6dguu95aisqwz3no.png)

**Comment by izhangzhihao** [comment]
Yes, but this pop up is because of `NoSuchMethodException:net.ishchenko.idea.nginx.annotator.NginxAnnotatingVisitor`.

**Comment by WuglyakBolgoink** [comment]
@izhangzhihao 

same in 

```
WebStorm 2019.2.2
Build #WS-192.6603.19, built on September 3, 2019
Runtime version: 11.0.3+12-b304.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry: ide.mac.allowDarkWindowDecorations=true
Non-Bundled Plugins: Dummy Text Generator, String Manipulation, com.github.leomillon.uuidgenerator, com.github.novotnyr.gitlab-quickmr-idea-plugin, com.intellij.jira, com.jooas.themes, com.meizu.flyme.mall.XmlToJson, com.potterhsu.jsonviewer, com.ppolivka.gitlabprojects, ideanginx9, in.thekalinga.snippet.intellij, mobi.hsz.idea.gitignore, com.wix.sasslint, izhangzhihao.rainbow.brackets, com.vladsch.idea.multimarkdown, com.khahn.angular-extract-component, lermitage.intellij.extra.icons
```
