### ISSUE TITLE
报错哈

### ISSUE THREAD

**Issue by adoin** [izhangzhihao/intellij-rainbow-brackets#2295]
出错了啊老铁
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  206 != 197
  which is length of [el-upload={}, upload={}, el-image-viewer={}, el-radio-group={}, component={}, el-timeline={}, el-select={}, el-input={}, el-tree-node={}, el-aside={}, time-spinner={}, locale={}, el-tree={}, el-divider={}, badge_src_main={}, cascader={}, el-cascader={}, el-table-footer={}, el-tabs={}, src_form={}, el-carousel={}, src_select={}, link_src_main={}, el-page-header={}, label-wrap={}, el-col={}, col={}, el-collapse={}, radio_button={}, el-footer={}, autocomplete={}, el-popconfirm={}, breadcrumb={}, checkbox_group={}, input_number={}, el-spinner={}, el-color-picker={}, dropdown={}, input={}, src_component={}, el-switch={}, el-menu-item-group={}, menu_item_group={}, el-slider={}, el-button-group={}, el-main={}, aside_src_main={}, time={}, el-menu={}, upload_src={}, src_button={}, submenu={}, el-drawer={}, tabs={}, transfer_src_main={}, el-table={}, src_radio={}, src_item={}, collapse_item={}, tree={}, element-ui.common={}, src_checkbox={}, page_header_src_main={}, el-transfer={}, drawer_src_main={}, el-header={}, el-scrollbar={}, el-backtop={}, el-table-column={}, el-color-alpha-slider={}, el-cascader-panel={}, table_column={}, el-tooltip={}, el-radio-button={}, el-time-select={}, el-date-picker={}, el-progress={}, menu_item={}, el-dropdown={}, el-time-picker={}, el-checkbox-button={}, divider_src_main={}, timeline_src_item={}, menu={}, main={}, vue-popper={}, el-radio={}, steps={}, el-steps={}, emitter={}, year-table={}, el-dropdown-item={}, el-step={}, el-table-filter-panel={}, carousel_src_main={}, el-marker={}, el-breadcrumb={}, el-popover={}, alert_src_main={}, el-carousel-item={}, progress={}, el-input-number={}, time-select={}, el-color-hue-slider={}, el-select-dropdown={}, month-range={}, el-checkbox={}, backtop_src_main={}, step={}, el-pager={}, avatar_src_main={}, el-tag={}, main_src_main={}, el-container={}, autocomplete-suggestions={}, el-button={}, el-form-item={}, el-autocomplete={}, src_input={}, calendar_src_main={}, dropdown_item={}, menu-mixin={}, scrollbar_src_main={}, el-upload-drag={}, el-icon={}, tab_pane={}, src_main={}, el-color-picker-dropdown={}, el-timeline-item={}, checkbox_button={}, el-table-body={}, el-tab-pane={}, predefine={}, container_src_main={}, el-menu-item={}, el-card={}, tab-nav={}, cascader_panel={}, el-cascader-menu={}, src_menu={}, dropdown_menu={}, el-row={}, el-breadcrumb-item={}, el-collapse-transition={}, collapse={}, rate_src_main={}, src_tree={}, date-table={}, switch_src_component={}, card_src_main={}, el-upload-list={}, form_item={}, spinner={}, el-collapse-item={}, el-pagination={}, pagination={}, timeline_src_main={}, src_table={}, item={}, el-option-group={}, slider_src_main={}, el-rate={}, month-table={}, el-form={}, src_option={}, bar={}, el-checkbox-group={}, icon={}, el-sl-panel={}, time-range={}, el-image={}, el-link={}, date_picker={}, el-alert={}, date-range={}, image_src_main={}, el-table-header={}, index={}, table={}, el-submenu={}, el-avatar={}, picker={}, el-badge={}, src={}, el-option={}, footer_src_main={}, cascader-node={}, el-dialog={}, breadcrumb_item={}, el-calendar={}, tab-bar={}, migrating={}, radio_group={}, header_src_main={}, popconfirm_src_main={}, el-transfer-panel={}, option_group={}, src_row={}, button_group={}, time_picker={}, date={}, el-dropdown-menu={}, color_picker_src_main={}, tag={}, picker_time_select={}, el-slider-button={}] and [el-upload={}, upload={}, el-image-viewer={}, el-radio-group={}, component={}, el-timeline={}, el-select={}, el-input={}, el-tree-node={}, el-aside={}, time-spinner={}, locale={}, el-tree={}, el-divider={}, badge_src_main={}, cascader={}, el-cascader={}, el-table-footer={}, el-tabs={}, src_form={}, el-carousel={}, src_select={}, link_src_main={}, el-page-header={}, label-wrap={}, el-col={}, el-collapse={}, radio_button={}, el-footer={}, autocomplete={}, el-popconfirm={}, breadcrumb={}, checkbox_group={}, input_number={}, el-spinner={}, el-color-picker={}, dropdown={}, input={}, src_component={}, el-switch={}, el-menu-item-group={}, menu_item_group={}, el-slider={}, el-button-group={}, el-main={}, aside_src_main={}, time={}, el-menu={}, upload_src={}, src_button={}, submenu={}, el-drawer={}, tabs={}, transfer_src_main={}, el-table={}, src_radio={}, src_item={}, collapse_item={}, tree={}, element-ui.common={}, src_checkbox={}, page_header_src_main={}, el-transfer={}, drawer_src_main={}, el-header={}, el-scrollbar={}, el-backtop={}, el-table-column={}, el-color-alpha-slider={}, el-cascader-panel={}, el-tooltip={}, el-radio-button={}, el-time-select={}, el-date-picker={}, el-progress={}, menu_item={}, el-dropdown={}, el-time-picker={}, el-checkbox-button={}, divider_src_main={}, timeline_src_item={}, menu={}, main={}, vue-popper={}, el-radio={}, steps={}, el-steps={}, emitter={}, year-table={}, el-dropdown-item={}, el-step={}, el-table-filter-panel={}, carousel_src_main={}, el-marker={}, el-breadcrumb={}, el-popover={}, alert_src_main={}, el-carousel-item={}, progress={}, el-input-number={}, time-select={}, el-color-hue-slider={}, el-select-dropdown={}, month-range={}, el-checkbox={}, backtop_src_main={}, step={}, el-pager={}, avatar_src_main={}, el-tag={}, main_src_main={}, el-container={}, autocomplete-suggestions={}, el-button={}, el-form-item={}, el-autocomplete={}, src_input={}, calendar_src_main={}, dropdown_item={}, menu-mixin={}, el-upload-drag={}, el-icon={}, tab_pane={}, el-color-picker-dropdown={}, el-timeline-item={}, checkbox_button={}, el-table-body={}, el-tab-pane={}, predefine={}, container_src_main={}, el-menu-item={}, el-card={}, tab-nav={}, cascader_panel={}, el-cascader-menu={}, src_menu={}, dropdown_menu={}, el-row={}, el-breadcrumb-item={}, el-collapse-transition={}, collapse={}, rate_src_main={}, src_tree={}, date-table={}, switch_src_component={}, card_src_main={}, el-upload-list={}, form_item={}, spinner={}, el-collapse-item={}, el-pagination={}, timeline_src_main={}, src_table={}, item={}, el-option-group={}, slider_src_main={}, el-rate={}, month-table={}, el-form={}, src_option={}, bar={}, el-checkbox-group={}, icon={}, el-sl-panel={}, time-range={}, el-image={}, el-link={}, el-alert={}, date-range={}, image_src_main={}, el-table-header={}, index={}, table={}, el-submenu={}, el-avatar={}, picker={}, el-badge={}, src={}, el-option={}, footer_src_main={}, cascader-node={}, el-dialog={}, breadcrumb_item={}, el-calendar={}, tab-bar={}, migrating={}, radio_group={}, header_src_main={}, popconfirm_src_main={}, el-transfer-panel={}, option_group={}, button_group={}, date={}, el-dropdown-menu={}, color_picker_src_main={}, tag={}, el-slider-button={}]

Recomputation gives com.intellij.util.CachedValueBase$Data@734e8e9f which is equivalent to 'existing'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:90)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:77)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at org.jetbrains.vuejs.model.source.VueSourcePlugin.getComponents(VueSourcePlugin.kt:34)
	at org.jetbrains.vuejs.model.VueDelegatedEntitiesContainer.getComponents(VueDelegatedEntitiesContainer.kt:10)
	at org.jetbrains.vuejs.model.VueGlobalImpl.buildElementToParentMap(VueGlobalImpl.kt:140)
	at org.jetbrains.vuejs.model.VueGlobalImpl.access$buildElementToParentMap(VueGlobalImpl.kt:29)
	at org.jetbrains.vuejs.model.VueGlobalImpl$getElementToParentMap$1.compute(VueGlobalImpl.kt:53)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at org.jetbrains.vuejs.model.VueGlobalImpl.getElementToParentMap(VueGlobalImpl.kt:52)
	at org.jetbrains.vuejs.model.VueGlobalImpl.access$getElementToParentMap(VueGlobalImpl.kt:29)
	at org.jetbrains.vuejs.model.VueGlobalImpl$Companion.getParents(VueGlobalImpl.kt:172)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.getParents(VueSourceContainer.kt:18)
	at org.jetbrains.vuejs.model.VueScopeElement$DefaultImpls.acceptEntities(VueScopeElement.kt:34)
	at org.jetbrains.vuejs.model.VueEntitiesContainer$DefaultImpls.acceptEntities(VueEntitiesContainer.kt)
	at org.jetbrains.vuejs.model.VueContainer$DefaultImpls.acceptEntities(VueContainer.kt)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.acceptEntities(VueSourceContainer.kt:13)
	at org.jetbrains.vuejs.model.VueScopeElement$DefaultImpls.acceptPropertiesAndMethods(VueScopeElement.kt:94)
	at org.jetbrains.vuejs.model.VueEntitiesContainer$DefaultImpls.acceptPropertiesAndMethods(VueEntitiesContainer.kt)
	at org.jetbrains.vuejs.model.VueContainer$DefaultImpls.acceptPropertiesAndMethods(VueContainer.kt)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.acceptPropertiesAndMethods(VueSourceContainer.kt:13)
	at org.jetbrains.vuejs.model.VueInstanceOwnerKt.contributeComponentProperties(VueInstanceOwner.kt:101)
	at org.jetbrains.vuejs.model.VueInstanceOwnerKt.buildInstanceType(VueInstanceOwner.kt:57)
	at org.jetbrains.vuejs.model.VueInstanceOwnerKt.access$buildInstanceType(VueInstanceOwner.kt:1)
	at org.jetbrains.vuejs.model.VueInstanceOwner$thisType$1.compute(VueInstanceOwner.kt:33)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at org.jetbrains.vuejs.model.VueInstanceOwner$DefaultImpls.getThisType(VueInstanceOwner.kt:32)
	at org.jetbrains.vuejs.model.VueEntitiesContainer$DefaultImpls.getThisType(VueEntitiesContainer.kt)
	at org.jetbrains.vuejs.model.VueContainer$DefaultImpls.getThisType(VueContainer.kt)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.getThisType(VueSourceContainer.kt:13)
	at org.jetbrains.vuejs.codeInsight.refs.VueJSReferenceContributor$VueComponentLocalReference.resolveInner(VueJSReferenceContributor.kt:111)
	at com.intellij.lang.javascript.psi.resolve.CachingPolyReferenceBase$MyResolver.resolve(CachingPolyReferenceBase.java:67)
	at com.intellij.lang.javascript.psi.resolve.CachingPolyReferenceBase$MyResolver.resolve(CachingPolyReferenceBase.java:62)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at com.intellij.lang.javascript.psi.resolve.CachingPolyReferenceBase.multiResolve(CachingPolyReferenceBase.java:22)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolveFromProviders(JSReferenceExpressionResolver.java:231)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:78)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:37)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$5.get(JSResolveUtil.java:1616)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$5.get(JSResolveUtil.java:1613)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:72)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.lambda$getCachedValue$0(JSComplexityAwareRecursionGuard.java:71)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$4.lambda$calculateWithCaching$0(JSResolveUtil.java:1629)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:289)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$4.calculateWithCaching(JSResolveUtil.java:1627)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.getCachedValue(JSComplexityAwareRecursionGuard.java:74)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.resolve(JSResolveUtil.java:1611)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.multiResolve(JSReferenceExpressionImpl.java:524)
	at com.intellij.lang.javascript.highlighting.JSSemanticHighlightingUtil.highlight(JSSemanticHighlightingUtil.java:198)
	at com.intellij.lang.javascript.validation.JSAnnotatingVisitor.visitJSReferenceExpression(JSAnnotatingVisitor.java:502)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.accept(JSReferenceExpressionImpl.java:512)
	at com.intellij.lang.javascript.validation.JSAnnotator.annotate(JSAnnotator.java:17)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:603)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by izhangzhihao** [comment]
Not a bug of this plugin, the IDE should be blamed.
