### ISSUE TITLE
Exception thrown while editing

### ISSUE THREAD

**Issue by vlaplante-cgi** [izhangzhihao/intellij-rainbow-brackets#2301]
An exception is thrown by Rainbow Brackets while editing code in PyCharm 2021.1.3. The exception is:

```
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.jetbrains.python.psi.impl.PyClassImpl #Python  because: parent is null
invalidated at: see attachment; class com.jetbrains.python.psi.impl.PyClassImpl: PySubscriptionExpression
	at com.jetbrains.python.psi.types.PyClassTypeImpl.assertValid(PyClassTypeImpl.java:702)
	at com.jetbrains.python.psi.types.TypeEvalContext.assertValid(TypeEvalContext.java:215)
	at com.jetbrains.python.psi.types.TypeEvalContext.lambda$getType$0(TypeEvalContext.java:176)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
        etc...
```

When the exception is thrown, if messes up the syntax checker.

```
PyCharm 2021.1.3 (Professional Edition)
Build #PY-211.7628.24, built on June 30, 2021
Runtime version: 11.0.11+9-b1341.60 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1963M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM (0.68), String Manipulation (8.15.203.000.3), com.mallowigi (36.0), com.chrisrm.idea.MaterialThemeUI (6.7.2), izhangzhihao.rainbow.brackets (6.19), ru.adelf.idea.dotenv (2021.2)
```

**Comment by izhangzhihao** [comment]
Can you provide full error log？

**Comment by izhangzhihao** [comment]
Closed for no response, if you have any other issues, please re-open this issue or create a new one.
