### ISSUE TITLE
[🐛bug]IDE异常

### ISSUE THREAD

**Issue by web-zhangbo** [izhangzhihao/intellij-rainbow-brackets#2319]
### 系统信息：

> 设备名称	DESKTOP-*******
> 处理器	AMD Ryzen 5 3400G with Radeon Vega Graphics       3.70 GHz
> 机带 RAM	16.0 GB (13.9 GB 可用)
> 设备 ID	2AEAD07F-5D38-439E-B1BF-**********
> 产品 ID	00328-10000-00001-*******
> 系统类型	64 位操作系统, 基于 x64 的处理器
> 笔和触控	没有可用于此显示器的笔或触控输入

### IDE版本：

> ![image](https://user-images.githubusercontent.com/53821155/127248306-64d35ea2-52f0-4290-af74-7021137bd45b.png)

### 插件版本：

> 6.19

### webstorm异常：
````
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  class org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty != class org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod
  which is class of org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@1b00ead5 and org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@365ee102
  which is 11th element of [org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@48f40c06, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@1d2db5dd, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@167a2ef, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@40f00530, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@280cb514, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@58ff7e95, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@64b3cfbf, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@242a8f9c, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@69432a18, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@4a6bfa73, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@30df0ab6, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@1b00ead5, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@4079355e, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@301ad4a3, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@25b718b1, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@6df53c0b, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@642f272e, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@2f658c4, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@1f99babb, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@5b48c827, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@46439237, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@76c3c243, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@245de242, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@39c90f1e, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@63c1f03a, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@b78e7db, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@407c4b04, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@31bc1dea, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@5d106bc7, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@111a1981, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@331c54cd, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@621e4c09, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@3c8e5dde, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@7d998ddf, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@2cf2049d, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@3c1c6b0e, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@72b2a1fe, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@43f43d02, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@7f1e0f0d, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@20855ffb, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@475fa744, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@25a18e80, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@2a488b5e, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@20b8636b, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@1ae785bf, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@331bdded, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@5de7b2ab, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@3ea73147, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@184b8151, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@7552c300, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@15c045eb, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@12ea631d, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@56ef2918, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@35c6aa06, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@223e5e48, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@638d2399, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@4c056119, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@4c936405, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@1c8fbfc1, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@1614d622] and [org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@717e6050, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@261a8136, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@478a4383, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@771f3896, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@7561bac5, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@780866e, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@12834b46, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@1c560a08, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@64193cd5, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@67a975ce, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@6ff8db06, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@365ee102, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@43d28abb, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@6e80f980, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@42abf69b, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@6ba23523, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@3c72edbe, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@55575f49, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@48556456, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@32244b52, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@19904fb5, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@76d2e6d9, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@15464b81, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@528fca0, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@1edee657, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@7fdb3f7b, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@58666942, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@1a694312, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@73ecf256, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@556a3bb7, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@3ead7421, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@6e8cd135, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@7ae6e0f0, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@7ed5db98, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@2b8cb41f, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@2381dd22, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@6e2d48c2, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@3e744784, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@70963019, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@5d539be4, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@59bcb3d4, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@45e89700, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@43f715c, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@45f25684, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@796c7ffd, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedDataProperty@783db747, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@7f79c8d, org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueComposedMethod@50e6ac81, org.jetbrai ...


Recomputation gives com.intellij.util.CachedValueBase$Data@4eabde50 which is equivalent to 'existing'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:90)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:77)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueCompositionInfo.getRawBindings(VueCompositionInfoProvider.kt:46)
	at org.jetbrains.vuejs.model.source.VueCompositionInfoProvider$VueCompositionInfo.getData(VueCompositionInfoProvider.kt:39)
	at org.jetbrains.vuejs.model.source.VueSourceContainer$Companion$DATA$1.get(VueSourceContainer.kt:56)
	at kotlin.jvm.internal.PropertyReference1.invoke(PropertyReference1.java:35)
	at org.jetbrains.vuejs.model.source.VueSourceContainer$MemberAccessor$get$1.invoke(VueSourceContainer.kt:76)
	at org.jetbrains.vuejs.model.source.VueSourceContainer$MemberAccessor$get$1.invoke(VueSourceContainer.kt:70)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at org.jetbrains.vuejs.model.source.VueSourceContainer$MemberAccessor.get(VueSourceContainer.kt:167)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.get(VueSourceContainer.kt:44)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.getData(VueSourceContainer.kt:25)
	at org.jetbrains.vuejs.model.VueScopeElement$acceptPropertiesAndMethods$1.visitContainer(VueScopeElement.kt:110)
	at org.jetbrains.vuejs.model.VueScopeElement$acceptPropertiesAndMethods$1.visitSelfComponent(VueScopeElement.kt:96)
	at org.jetbrains.vuejs.model.VueScopeElement$DefaultImpls.acceptEntities(VueScopeElement.kt:58)
	at org.jetbrains.vuejs.model.VueEntitiesContainer$DefaultImpls.acceptEntities(VueEntitiesContainer.kt)
	at org.jetbrains.vuejs.model.VueContainer$DefaultImpls.acceptEntities(VueContainer.kt)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.acceptEntities(VueSourceContainer.kt:13)
	at org.jetbrains.vuejs.model.VueScopeElement$DefaultImpls.acceptPropertiesAndMethods(VueScopeElement.kt:94)
	at org.jetbrains.vuejs.model.VueEntitiesContainer$DefaultImpls.acceptPropertiesAndMethods(VueEntitiesContainer.kt)
	at org.jetbrains.vuejs.model.VueContainer$DefaultImpls.acceptPropertiesAndMethods(VueContainer.kt)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.acceptPropertiesAndMethods(VueSourceContainer.kt:13)
	at org.jetbrains.vuejs.model.VueInstanceOwnerKt.contributeComponentProperties(VueInstanceOwner.kt:101)
	at org.jetbrains.vuejs.model.VueInstanceOwnerKt.buildInstanceType(VueInstanceOwner.kt:57)
	at org.jetbrains.vuejs.model.VueInstanceOwnerKt.access$buildInstanceType(VueInstanceOwner.kt:1)
	at org.jetbrains.vuejs.model.VueInstanceOwner$thisType$1.compute(VueInstanceOwner.kt:33)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at org.jetbrains.vuejs.model.VueInstanceOwner$DefaultImpls.getThisType(VueInstanceOwner.kt:32)
	at org.jetbrains.vuejs.model.VueEntitiesContainer$DefaultImpls.getThisType(VueEntitiesContainer.kt)
	at org.jetbrains.vuejs.model.VueContainer$DefaultImpls.getThisType(VueContainer.kt)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.getThisType(VueSourceContainer.kt:13)
	at org.jetbrains.vuejs.codeInsight.template.VueContainerScopeProvider$VueContainerScope.resolve(VueContainerScopeProvider.kt:23)
	at org.jetbrains.vuejs.codeInsight.template.VueTemplateScope.process(VueTemplateScope.kt:44)
	at org.jetbrains.vuejs.codeInsight.template.VueTemplateScope.processAllScopesInHierarchy(VueTemplateScope.kt:32)
	at org.jetbrains.vuejs.codeInsight.template.VueTemplateScopesResolver$resolve$2.test(VueTemplateScopesResolver.kt:36)
	at org.jetbrains.vuejs.codeInsight.template.VueTemplateScopesResolver$resolve$2.test(VueTemplateScopesResolver.kt:13)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:278)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at one.util.streamex.AbstractStreamEx.findFirst(AbstractStreamEx.java:561)
	at one.util.streamex.AbstractStreamEx.findFirst(AbstractStreamEx.java:834)
	at org.jetbrains.vuejs.codeInsight.template.VueTemplateScopesResolver.resolve(VueTemplateScopesResolver.kt:36)
	at org.jetbrains.vuejs.codeInsight.refs.VueJSReferenceExpressionResolver.resolveTemplateVariable(VueJSReferenceExpressionResolver.kt:85)
	at org.jetbrains.vuejs.codeInsight.refs.VueJSReferenceExpressionResolver.resolve(VueJSReferenceExpressionResolver.kt:54)
	at org.jetbrains.vuejs.codeInsight.refs.VueJSReferenceExpressionResolver.resolve(VueJSReferenceExpressionResolver.kt:28)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$5.get(JSResolveUtil.java:1616)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$5.get(JSResolveUtil.java:1613)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:72)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.lambda$getCachedValue$0(JSComplexityAwareRecursionGuard.java:71)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$4.lambda$calculateWithCaching$0(JSResolveUtil.java:1629)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:289)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$4.calculateWithCaching(JSResolveUtil.java:1627)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.getCachedValue(JSComplexityAwareRecursionGuard.java:74)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.resolve(JSResolveUtil.java:1611)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.multiResolve(JSReferenceExpressionImpl.java:524)
	at com.intellij.lang.javascript.highlighting.JSSemanticHighlightingUtil.highlight(JSSemanticHighlightingUtil.java:198)
	at com.intellij.lang.javascript.validation.JSAnnotatingVisitor.visitJSReferenceExpression(JSAnnotatingVisitor.java:502)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.accept(JSReferenceExpressionImpl.java:512)
	at com.intellij.lang.javascript.validation.JSAnnotator.annotate(JSAnnotator.java:17)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:603)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
````

### 描述：

> 没感觉有什么明显的异常，但是IDE报错了

**Comment by izhangzhihao** [comment]
It's a bug of the IDE itself, not this plugin, thanks for your report anyway~
