### ISSUE TITLE
Is it able to support SQL begin end colorization

### ISSUE THREAD

**Issue by daleqq** [izhangzhihao/intellij-rainbow-brackets#235]
I know the **Database Tools and SQL** need a licence to use it. Is it able this plugin to use the functionality provided by the **Database Tools and SQL** to colorize the `begin` / `end`, because `begin` /  `end` act same as the curly brace.

Thanks.

**Comment by izhangzhihao** [comment]
According to [the recent change log](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/api_changes/api_changes_list_2019.html#changes-in-datagrip-and-database-tools-plugin-20191), there are some break changes between 2019.1 and previews versions. And I have tried, it turns out that's true;

in version 2017.2.7, begin and end rainbowfiy will works as expected:
![image](https://user-images.githubusercontent.com/12044174/60411960-d8572180-9c01-11e9-9402-0d55b51869ef.png)

But in version 2019.1.3, it an exception is thrown:

```
java.lang.NoSuchFieldError: SQL_BEGIN
	at com.github.izhangzhihao.rainbow.brackets.provider.SqlProvider.<clinit>(SqlProvider.kt:12)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:41)
	at com.intellij.util.ExtensionInstantiator.instantiateWithPicoContainerOnlyIfNeeded(ExtensionInstantiator.java:34)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:21)
	at com.intellij.lang.LanguageExtensionPoint.lambda$new$0(LanguageExtensionPoint.java:22)
	at com.intellij.openapi.util.NotNullLazyValue$2.compute(NotNullLazyValue.java:68)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
	at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:27)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensionsFromExtensionPoint(KeyedExtensionCollector.java:171)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:155)
	at com.intellij.lang.LanguageExtension.buildExtensions(LanguageExtension.java:98)
	at com.intellij.lang.LanguageExtension.buildExtensions(LanguageExtension.java:23)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:134)
	at com.intellij.lang.LanguageExtension.findForLanguage(LanguageExtension.java:60)
	at com.intellij.lang.LanguageExtension.forLanguage(LanguageExtension.java:52)
	at com.github.izhangzhihao.rainbow.brackets.BracePairs.<clinit>(BracePairs.kt:30)
	at com.github.izhangzhihao.rainbow.brackets.visitor.DefaultRainbowVisitor$Companion.filterPairs(DefaultRainbowVisitor.kt:151)
	at com.github.izhangzhihao.rainbow.brackets.visitor.DefaultRainbowVisitor$Companion.access$filterPairs(DefaultRainbowVisitor.kt:52)
	at com.github.izhangzhihao.rainbow.brackets.visitor.DefaultRainbowVisitor.visit(DefaultRainbowVisitor.kt:25)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:284)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:71)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:281)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by izhangzhihao** [comment]
So let's revisit this feature request later.

**Comment by izhangzhihao** [comment]
This feature will happen in version 6.0. By the way, please considers donating to this project on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) if you love this plugin.
