### ISSUE TITLE
Plugin triggers errors in IntelliJ stating there is problem saving settings

### ISSUE THREAD

**Issue by bukajsytlos** [izhangzhihao/intellij-rainbow-brackets#236]
## Current Behavior
After upgrade to version , intelliJ starts to report errors in event log stating
`Unable to save settings: Failed to save settings. Please restart`

See log for detail

## Possible Solution
Disabling plugin resolved issue

## Your Environment

* Plugin version: 5.20

```
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-25-generic
```
```
2019-07-04 10:39:18,782 [1318979]   WARN - l.compiled.ClassFileDecompiler - decompiler: class org.jetbrains.java.decompiler.IdeaDecompiler 
com.intellij.psi.compiled.ClassFileDecompilers$Light$CannotDecompileException: java.lang.IllegalStateException: @NotNull method com/intellij/psi/impl/source/codeStyle/CodeStyleSchemeImpl.getCodeStyleSettings must not return null
	at org.jetbrains.java.decompiler.IdeaDecompiler.decompile(IdeaDecompiler.kt:176)
	at org.jetbrains.java.decompiler.IdeaDecompiler.getText(IdeaDecompiler.kt:126)
	at com.intellij.psi.impl.compiled.ClassFileDecompiler.decompile(ClassFileDecompiler.java:43)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:490)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.getDocument(FileDocumentManagerImpl.java:181)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:342)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getMirror(ClsElementImpl.java:159)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getTextRange(ClsElementImpl.java:166)
	at com.intellij.psi.PsiAnchor.doCreateAnchor(PsiAnchor.java:97)
	at com.intellij.psi.PsiAnchor.create(PsiAnchor.java:64)
	at com.intellij.jam.JamClassGeneratorImpl$JamReferenceHolderImpl.<init>(JamClassGeneratorImpl.java:301)
	at com.intellij.jam.JamClassGeneratorImpl$JamReferenceHolderImpl.<init>(JamClassGeneratorImpl.java:295)
	at com.intellij.jam.JamClassGeneratorImpl.a(JamClassGeneratorImpl.java:261)
	at com.intellij.jam.JamClassGeneratorImpl.a(JamClassGeneratorImpl.java:245)
	at com.intellij.jam.reflect.JamInstantiator$1.instantiate(JamInstantiator.java:39)
	at com.intellij.jam.reflect.JamAnnotationAttributeMeta$JamCreator.fun(JamAnnotationAttributeMeta.java:169)
	at com.intellij.jam.reflect.JamAnnotationAttributeMeta$JamCreator.fun(JamAnnotationAttributeMeta.java:156)
	at com.intellij.semantic.SemServiceImpl$1.lambda$registerSemElementProvider$0(SemServiceImpl.java:80)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:187)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:158)
	at com.intellij.semantic.SemService.getSemElement(SemService.java:22)
	at com.intellij.jam.JamService.getJamElement(JamService.java:106)
	at com.intellij.jam.reflect.JamAnnotationAttributeMeta$Collection.getJam(JamAnnotationAttributeMeta.java:138)
	at com.intellij.jam.reflect.JamAnnotationAttributeMeta$Collection.lambda$getJam$0(JamAnnotationAttributeMeta.java:132)
	at com.intellij.util.containers.ContainerUtilRt.mapNotNull(ContainerUtilRt.java:378)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1988)
	at com.intellij.jam.reflect.JamAttributeMeta.getCollectionJam(JamAttributeMeta.java:64)
	at com.intellij.jam.reflect.JamAnnotationAttributeMeta$Collection.getJam(JamAnnotationAttributeMeta.java:132)
	at com.intellij.jam.reflect.JamAnnotationAttributeMeta$Collection.getJam(JamAnnotationAttributeMeta.java:123)
	at com.intellij.spring.model.jam.stereotype.SpringJamComponentScanArchetype.getIncludeContextFilters(SpringJamComponentScanArchetype.java:147)
	at com.intellij.spring.model.jam.stereotype.SpringComponentScan.getScannedBeans(SpringComponentScan.java:79)
	at com.intellij.spring.model.jam.stereotype.SpringComponentScan.lambda$null$0(SpringComponentScan.java:52)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:181)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:45)
	at com.intellij.spring.model.jam.stereotype.SpringComponentScan.getScannedElements(SpringComponentScan.java:62)
	at com.intellij.spring.contexts.model.SpringComponentScanModel.calculateScannedBeans(SpringComponentScanModel.java:76)
	at com.intellij.spring.contexts.model.ComponentScanPackagesModel.calculateLocalBeans(ComponentScanPackagesModel.java:57)
	at com.intellij.spring.contexts.model.SpringComponentScanModel.lambda$getLocalBeans$1(SpringComponentScanModel.java:54)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$0(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:116)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.spring.contexts.model.SpringComponentScanModel.getLocalBeans(SpringComponentScanModel.java:61)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.processLocalBeans(AbstractSimpleSpringModel.java:122)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.access$100(AbstractSimpleSpringModel.java:38)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel$1.doProcessBeans(AbstractSimpleSpringModel.java:45)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel$1.doProcessBeans(AbstractSimpleSpringModel.java:41)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel$LocalBeansCachingProcessor.findPointers(AbstractSimpleSpringModel.java:73)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$1.createValue(SpringCachingProcessor.java:46)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$1.createValue(SpringCachingProcessor.java:42)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$SpringSLRUCache.get(SpringCachingProcessor.java:107)
	at com.intellij.spring.contexts.model.SpringCachingProcessor.process(SpringCachingProcessor.java:73)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.processLocalBeansByClass(AbstractSimpleSpringModel.java:151)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.processByClass(AbstractSimpleSpringModel.java:106)
	at com.intellij.spring.contexts.model.AbstractProcessableModel.lambda$processByClass$0(AbstractProcessableModel.java:26)
	at com.intellij.spring.contexts.model.visitors.CommonSpringModelVisitorContext.visit(CommonSpringModelVisitorContext.java:30)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:49)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:58)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:50)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:58)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:50)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:58)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:50)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:58)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:50)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:58)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:50)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:58)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:50)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelatedModels(SpringModelVisitors.java:30)
	at com.intellij.spring.contexts.model.AbstractProcessableModel.processByClass(AbstractProcessableModel.java:26)
	at com.intellij.spring.model.utils.SpringModelSearchers.findBeans(SpringModelSearchers.java:47)
	at com.intellij.spring.persistence.integration.jpa.SpringJpaPersistencePackageProvider.lambda$getCachedPackages$1(SpringJpaPersistencePackageProvider.java:67)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$0(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:116)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.spring.persistence.integration.jpa.SpringJpaPersistencePackageProvider.getCachedPackages(SpringJpaPersistencePackageProvider.java:56)
	at com.intellij.spring.persistence.integration.jpa.SpringJpaPersistencePackageProvider.lambda$getPersistencePackages$0(SpringJpaPersistencePackageProvider.java:49)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:116)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.spring.persistence.integration.jpa.SpringJpaPersistencePackageProvider.getPersistencePackages(SpringJpaPersistencePackageProvider.java:49)
	at com.intellij.jpa.facet.JpaFacetImpl.lambda$getExtensionPersistenceUnits$1(JpaFacetImpl.java:186)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1534)
	at com.intellij.jpa.facet.JpaFacetImpl.getExtensionPersistenceUnits(JpaFacetImpl.java:186)
	at com.intellij.jpa.facet.JpaFacetImpl.getPersistenceUnits(JpaFacetImpl.java:163)
	at com.intellij.persistence.roles.PersistenceRoleHolderImpl.lambda$getFacetXmlInfo$2(PersistenceRoleHolderImpl.java:101)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$0(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:116)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:119)
	at com.intellij.persistence.roles.PersistenceRoleHolderImpl.getFacetXmlInfo(PersistenceRoleHolderImpl.java:89)
	at com.intellij.persistence.roles.PersistenceRoleHolderImpl.lambda$static$1(PersistenceRoleHolderImpl.java:38)
	at com.intellij.persistence.roles.PersistenceRoleHolderImpl.processRoles(PersistenceRoleHolderImpl.java:58)
	at com.intellij.persistence.roles.PersistenceRoleHolderImpl.processXmlRoles(PersistenceRoleHolderImpl.java:52)
	at com.intellij.jpa.model.annotations.mapping.JpaJamContributor$5.accepts(JpaJamContributor.java:218)
	at com.intellij.jpa.model.annotations.mapping.JpaJamContributor$5.accepts(JpaJamContributor.java:206)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:61)
	at com.intellij.patterns.StandardPatterns$3.accepts(StandardPatterns.java:118)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:56)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:50)
	at com.intellij.semantic.SemServiceImpl$1.lambda$registerSemElementProvider$0(SemServiceImpl.java:79)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:187)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:158)
	at com.intellij.jam.JamService.getMetas(JamService.java:115)
	at com.intellij.jam.JamSemContributor.a(JamSemContributor.java:72)
	at com.intellij.semantic.SemServiceImpl$1.lambda$registerSemElementProvider$0(SemServiceImpl.java:80)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:187)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:158)
	at com.intellij.jam.JamService.getMetas(JamService.java:115)
	at com.intellij.jam.JamSemContributor.c(JamSemContributor.java:53)
	at com.intellij.semantic.SemServiceImpl$1.lambda$registerSemElementProvider$0(SemServiceImpl.java:80)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:187)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:158)
	at com.intellij.semantic.SemService.getSemElement(SemService.java:22)
	at com.intellij.jam.JamService.getMeta(JamService.java:125)
	at com.intellij.jam.JamSemContributor.b(JamSemContributor.java:105)
	at com.intellij.jam.JamSemContributor.c(JamSemContributor.java:61)
	at com.intellij.semantic.SemServiceImpl$1.lambda$registerSemElementProvider$0(SemServiceImpl.java:80)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:187)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:158)
	at com.intellij.jam.JamReferenceContributor$registerReferenceProviders$2.invoke(JamReferenceContributor.kt:39)
	at com.intellij.jam.JamReferenceContributor$registerReferenceProviders$2.invoke(JamReferenceContributor.kt:28)
	at com.intellij.psi.UastReferenceRegistrar$uastInjectionHostReferenceProvider$1.getReferencesForInjectionHost(UastReferenceRegistrar.kt:77)
	at com.intellij.psi.UastInjectionHostReferenceProvider.getReferencesByElement(UastInjectionHostReferenceProvider.kt:14)
	at com.intellij.psi.UastReferenceProviderAdapter.getReferencesByElement(UastReferenceRegistrar.kt:134)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:156)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:126)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:105)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:56)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$0(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:116)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:55)
	at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:32)
	at com.intellij.psi.PsiReferenceService.getContributedReferences(PsiReferenceService.java:52)
	at com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl.getReferences(PsiLiteralExpressionImpl.java:215)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:28)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:120)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:284)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$analyze$2(HighlightVisitorImpl.java:161)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:370)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:160)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:71)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:281)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.IllegalStateException: @NotNull method com/intellij/psi/impl/source/codeStyle/CodeStyleSchemeImpl.getCodeStyleSettings must not return null
	at com.intellij.psi.impl.source.codeStyle.CodeStyleSchemeImpl.$$$reportNull$$$0(CodeStyleSchemeImpl.java)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleSchemeImpl.getCodeStyleSettings(CodeStyleSchemeImpl.java:78)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getCurrentSettings(CodeStyleSettingsManager.java:98)
	at com.intellij.application.options.CodeStyle.getDefaultSettings(CodeStyle.java:36)
	at org.jetbrains.java.decompiler.IdeaDecompiler$Companion.getOptions(IdeaDecompiler.kt:51)
	at org.jetbrains.java.decompiler.IdeaDecompiler$Companion.access$getOptions(IdeaDecompiler.kt:42)
	at org.jetbrains.java.decompiler.IdeaDecompiler$myOptions$1.invoke(IdeaDecompiler.kt:70)
	at org.jetbrains.java.decompiler.IdeaDecompiler$myOptions$1.invoke(IdeaDecompiler.kt:41)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.java.decompiler.IdeaDecompiler.decompile(IdeaDecompiler.kt:143)
	... 188 more
```

**Comment by izhangzhihao** [comment]
I didn't find anything related to this plugin. So did version 5.19 works well?

**Comment by izhangzhihao** [comment]
And how to reproduce the problem?

**Comment by bukajsytlos** [comment]
Yeah it worked on previous version. I just reenabled the plugin and everything looks fine. So maybe this was just IntelliJ hicup that was resolved by restart demanded by disabling plugin. I disabled plugin because of suggestions on internet and this was plugin I have updated most recently.
Thanks and keep up good work ;)

**Comment by izhangzhihao** [comment]
Great then.
