### ISSUE TITLE
java.lang.Throwable: Cannot read scheme from /colors/GitHub (Material).xml

### ISSUE THREAD

**Issue by FurryWolfX** [izhangzhihao/intellij-rainbow-brackets#237]
## Your programming language(s)

JavaScript，Vue

## Error Log
```
java.lang.Throwable: Cannot read scheme from /colors/GitHub (Material).xml
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.loadBundledScheme(SchemeManagerImpl.kt:123)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.loadSchemesFromThemes(EditorColorsManagerImpl.java:217)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.<init>(EditorColorsManagerImpl.java:151)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:88)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.createAndInitialize(ServiceManagerImpl.java:243)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.lambda$getComponentInstance$0(ServiceManagerImpl.java:232)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:197)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:231)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:75)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:44)
	at com.intellij.openapi.editor.colors.EditorColorsManager.getInstance(EditorColorsManager.java:36)
	at com.github.izhangzhihao.rainbow.brackets.RainbowHighlighter.fixHighlighting$default(RainbowHighlighter.kt:155)
	at com.github.izhangzhihao.rainbow.brackets.component.RainbowComponent.initComponent(RainbowComponent.kt:30)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$7(ApplicationImpl.java:414)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:414)
	at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:150)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:433)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

## Your Environment

* Plugin version: 5.20
* macOS and Windows 10 both have the problem

```
WebStorm 2019.2
Build #WS-192.5728.87, built on July 22, 2019
You have a perpetual fallback license for this version
Subscription is active until July 22, 2020
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1970M
Cores: 16
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.alayouni.ansiHighlight, com.intellij.ideolog, com.intellij.properties, com.mallowigi, com.mallowigi.idea, BashSupport, com.deadlock.scsyntax, com.ytw88.weappsupport, izhangzhihao.rainbow.brackets, tv.twelvetone.intellij.plugins.intellivue
```

**Comment by izhangzhihao** [comment]
What is `GitHub (Material)`? Does the file exist?

**Comment by izhangzhihao** [comment]
Did you edit the file (/colors/GitHub (Material).xml) by hand? it seems that the file does not correct.

**Comment by izhangzhihao** [comment]
ping

**Comment by andrej-urvantsev** [comment]
I had the same problem after updating Intellij Idea to 2019.2
I also had plugin "Material Theme UI Lite" installed. I think mentioned file is from there. So "Material Theme UI Lite" somehow caused failure of rainbow-brackets.

After uninstalling "Material Theme UI Lite" rainbow-brackets works without issue.

But I still think that this is an issue of rainbow-brackets: something needs to be worked around at RainbowHighlighter.fixHighlighting$default(RainbowHighlighter.kt:155)

**Comment by izhangzhihao** [comment]
There is nothing to do with this plugin.

**Comment by izhangzhihao** [comment]
Please ask [Material Theme UI Lite](https://github.com/chrisrm/material-theme-jetbrains/issues) for a fix.
