### ISSUE TITLE
Intellij IDEA error report: PSI and index do not match

### ISSUE THREAD

**Issue by sebastian-brandt** [izhangzhihao/intellij-rainbow-brackets#2379]
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file=PsiFile:ParallelListResourceBundle.class, file.class=class com.intellij.psi.impl.compiled.ClsFileImpl, file.lang=Language: JAVA, modStamp=0
 stub debugInfo=created from file content; with backReference
latestIndexedStub=null
 viewProvider=com.intellij.psi.ClassFileViewProvider{vFile=jrt:///home/sebastian/.jdks/corretto-11.0.12!/java.base/sun/util/resources/ParallelListResourceBundle.class, vFileId=934112, content=VirtualFileContent{size=4115}, eventSystemEnabled=true}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1630022816158; file length: 4115
indexing info: null
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$3(CoreProgressManager.java:242)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:240)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:61)
	at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:151)
	at com.intellij.psi.stubs.StubProcessingHelperBase.checkType(StubProcessingHelperBase.java:93)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:72)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$2(StubIndexImpl.java:287)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:333)
	at com.intellij.psi.impl.PsiShortNamesCacheImpl.processFieldsWithName(PsiShortNamesCacheImpl.java:184)
	at com.intellij.psi.impl.CompositeShortNamesCache.processFieldsWithName(CompositeShortNamesCache.java:228)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportConstantFix.getMembersToImport(StaticImportConstantFix.java:73)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportMemberFix.<init>(StaticImportMemberFix.java:52)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportConstantFix.<init>(StaticImportConstantFix.java:35)
	at com.intellij.codeInsight.daemon.impl.quickfix.DefaultQuickFixProvider.registerFixes(DefaultQuickFixProvider.java:42)
	at com.intellij.codeInsight.daemon.impl.quickfix.DefaultQuickFixProvider.registerFixes(DefaultQuickFixProvider.java:24)
	at com.intellij.codeInsight.quickfix.UnresolvedReferenceQuickFixProvider.registerReferenceFixes(UnresolvedReferenceQuickFixProvider.java:27)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightUtil.checkReference(HighlightUtil.java:3014)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.doVisitReferenceElement(HighlightVisitorImpl.java:1223)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitReferenceExpression(HighlightVisitorImpl.java:1400)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.accept(PsiReferenceExpressionImpl.java:777)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:189)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:94)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

ParallelListResourceBundle.class_file.txt
compiled

subTree.txt
PsiJavaFileStub [sun.util.resources]
  PsiClassStub[name=ParallelListResourceBundle fqn=sun.util.resources.ParallelListResourceBundle]
    PsiModifierListStub[mask=1025]
    PsiTypeParameterListStub
    PsiRefListStub[EXTENDS_LIST:java.util.ResourceBundle]
    PsiRefListStub[IMPLEMENTS_LIST:]
    PsiClassStub[name=KeySet fqn=sun.util.resources.ParallelListResourceBundle.KeySet]
      PsiModifierListStub[mask=10]
      PsiTypeParameterListStub
      PsiRefListStub[EXTENDS_LIST:java.util.AbstractSet<java.lang.String>]
      PsiRefListStub[IMPLEMENTS_LIST:]
    PsiFieldStub[lookup:java.util.concurrent.ConcurrentMap<java.lang.String,java.lang.Object>]
      PsiModifierListStub[mask=66]
    PsiFieldStub[keyset:java.util.Set<java.lang.String>]
      PsiModifierListStub[mask=66]
    PsiFieldStub[parallelContents:java.util.concurrent.atomic.AtomicMarkableReference<java.lang.Object[][]>]
      PsiModifierListStub[mask=18]
    PsiMethodStub[cons ParallelListResourceBundle:void]
      PsiModifierListStub[mask=4]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[getContents:java.lang.Object[][]]
      PsiModifierListStub[mask=1028]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[getParent:java.util.ResourceBundle]
      PsiModifierListStub[mask=4096]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[setParallelContents:void]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[rb:sun.util.resources.OpenListResourceBundle]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[areParallelContentsComplete:boolean]
      PsiModifierListStub[mask=4096]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[handleGetObject:java.lang.Object]
      PsiModifierListStub[mask=4]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[key:java.lang.String]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[getKeys:java.util.Enumeration<java.lang.String>]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[containsKey:boolean]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[key:java.lang.String]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[handleKeySet:java.util.Set<java.lang.String>]
      PsiModifierListStub[mask=4]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[keySet:java.util.Set<java.lang.String>]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[resetKeySet:void]
      PsiModifierListStub[mask=4128]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[loadLookupTablesIfNecessary:void]
      PsiModifierListStub[mask=4096]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:]

## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [X] This issue/feature request is not reported before.

## Your programming languages
Java (11)

## Expected Behavior
Didn't notice anything special, though Intellij IDEA reported this error and I though you might want to know about it.

## Current Behavior
-

## Possible Solution
-

## Code snippet for reproduce (for bugs)
-

## Your Environment

* Plugin version: 6.21
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.14.12-201.current
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: debugger.watches.in.variables=false, documentation.show.toolbar=true, debugger.valueTooltipAutoShowOnSelection=true
Non-Bundled Plugins: net.seesharpsoft.intellij.plugins.csv (2.17.1), org.jetbrains.plugins.rest (212.4746.57), AWSCloudFormation (212.4746.57), com.intellij.ideolog (203.0.27.0), org.jetbrains.plugins.localization (212.4746.57), com.github.chencn.yamlandprops (1.0.5), com.jetbrains.jbre.bintray.downloader (2.2), PMDPlugin (1.8.21), com.jetbrains.ChooseRuntime (1.2), de.docksnet.puml.syntaxchecker (0.2.0), TunnelliJ (1.0), PlantUML integration (5.6.1), org.asciidoctor.intellij.asciidoc (0.35.4), QAPlug (1.3.27), VisualVMLauncher (1.20.203.4204.0), QAPlug - PMD (1.4.7), String Manipulation (8.17.203.000.0), org.apache.camel (0.7.9), mobi.hsz.idea.gitignore (4.2.0), Karma (212.4746.57), Pythonid (212.5284.44), com.intellij.selenium (212.5284.19), aws.toolkit (1.32-212), com.madrapps.dagger-plugin (0.3.2021.2.1), izhangzhihao.rainbow.brackets (6.21), com.bruce.intellijplugin.generatesetter (2.8)
Kotlin: 212-1.5.10-release-IJ5457.46
Current Desktop: Budgie:GNOME

**Comment by sebastian-brandt** [comment]
ok, whatever.
