### ISSUE TITLE
Getting exception on psi.ResolveResult

### ISSUE THREAD

**Issue by Soromeister** [izhangzhihao/intellij-rainbow-brackets#2403]
Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/README.md) before creating one.

## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [X] This issue/feature request is not reported before.

## Expected Behavior
Exception should not occur

## Current Behavior
Got exception:

```
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  LightVariableBuilder:entityName != LightVariableBuilder:entityName
  which is element of PsiElementResolveResult with class com.intellij.psi.impl.light.LightVariableBuilder: entityName and PsiElementResolveResult with class com.intellij.psi.impl.light.LightVariableBuilder: entityName
  which is 0th element of [PsiElementResolveResult with class com.intellij.psi.impl.light.LightVariableBuilder: entityName] and [PsiElementResolveResult with class com.intellij.psi.impl.light.LightVariableBuilder: entityName]

Recomputation gives [Lcom.intellij.psi.ResolveResult;@3c716aa8 (class [Lcom.intellij.psi.ResolveResult;) which is different from both values
Recomputation log:
  Resolving entityName of class com.intellij.jsp.el.impl.ELReference
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:89)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:76)
	at com.intellij.psi.impl.source.resolve.ResolveCache.cache(ResolveCache.java:322)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:249)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at com.intellij.jsp.el.impl.ELReference.multiResolve(ELReference.java:561)
	at com.intellij.jsp.el.impl.ELReference.resolve(ELReference.java:137)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl$1.visitElement(HighlightVisitorImpl.java:82)
	at com.intellij.psi.jsp.el.impl.ELExpressionBase.accept(ELExpressionBase.java:37)
	at com.intellij.psi.jsp.el.impl.ELVariableImpl.accept(ELVariableImpl.java:25)
	at com.intellij.spring.el.psi.impl.SpringELVariableImpl.accept(SpringELVariableImpl.java:23)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:67)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:24)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:62)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:49)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:76)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl$1.visitElement(HighlightVisitorImpl.java:80)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:70)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$registerReferencesFromInjectedFragments$0(HighlightVisitorImpl.java:195)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.probeElementsUp(InjectedLanguageUtilBase.java:262)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.enumerate(InjectedLanguageUtilBase.java:178)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.enumerateEx(InjectedLanguageManagerImpl.java:331)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.registerReferencesFromInjectedFragments(HighlightVisitorImpl.java:195)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitLiteralExpression(HighlightVisitorImpl.java:923)
	at com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl.accept(PsiLiteralExpressionImpl.java:172)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:189)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.mallowigi.visitors.ColorVisitor.analyze(ColorVisitor.kt:58)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.mallowigi.visitors.ColorVisitor.analyze(ColorVisitor.kt:58)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:94)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change.
Or what have you tried to resolve this issue.

## Code snippet for reproduce (for bugs)
Create a repository interface in Spring Boot and extend JpaRepository interface. Then add some methods. Try to navigate away and to that repository file.

## Your Environment

* Plugin version: 6.21
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue might be closed directly.

```
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: de.netnexus.camelcaseplugin (3.0.8), ski.chrzanow.foldableprojectview (1.1.1), com.rangaofei.UrlTool (0.0.7), cn.haojiyou.CodeGlance3 (2.1.1-2021.1.3), mobi.hsz.idea.gitignore (4.3.0), com.mallowigi (50.2.0), color.scheme.Molokai (1.5), com.intellij.javafx (1.0.3), com.intellij.ideolog (203.0.27.0), String Manipulation (8.22.203.000.1), com.github.MappingGeneratorIntellijPlugin (1.5), GrepConsole (12.1.211.6086.0), MavenRunHelper (4.18.212.000.3), com.github.copilot (1.1.1), com.github.lppedd.idea-return-highlighter (0.8.1), lermitage.intellij.extra.icons (1.66.0.203), org.jetbrains.plugins.vue (212.5457.27), com.intellij.plugins.html.instantEditing (212.4746.57), org.jetbrains.kotlin (212-1.6.0-release-799-IJ5457.46), org.mapstruct.intellij (1.3.0), org.intellij.scala (2021.2.24), com.mallowigi.colorHighlighter (9.2.0), zielu.gittoolbox (212.8.1), com.chrisrm.idea.MaterialThemeUI (6.9.1), com.haulmont.jpab (5.8-212), izhangzhihao.rainbow.brackets (6.21)
Kotlin: 212-1.6.0-release-799-IJ5457.46
```

**Comment by izhangzhihao** [comment]
Thanks for your report! But actually, it's not a bug of this plugin, you can report it to [JetBrains](https://youtrack.jetbrains.com). Thanks again for your support~
