### ISSUE TITLE
java.lang.ClassCastException in .http file

### ISSUE THREAD

**Issue by petr-nehez** [izhangzhihao/intellij-rainbow-brackets#2406]
The error occurred in the background (notification) after restarting of IDEA.

* Plugin version: 6.21

* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
```
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
Runtime version: 11.0.12+7-b1504.27 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.18.0-348.2.1.el8_5.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 7500M
Cores: 12
Registry: documentation.show.toolbar=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: org.turbanov.run.configuration.as.action (1.4.5), com.intellij.nativeDebug (212.5284.19), com.intellij.javafx (1.0.3), com.intellij.ideolog (203.0.27.0), net.seesharpsoft.intellij.plugins.file-preview (1.6.4), hunspell (212.4746.57), com.intellij.plugins.watcher (212.5080.8), de.ehmkah.projects.imgdiff (1.11.0), com.jetbrains.ChooseRuntime (1.2), com.tabnine.TabNine (0.5.3), Batch Scripts Support (1.0.12), net.seesharpsoft.intellij.plugins.csv (2.18.1), ch.raffael.idea.plugins.runpopup (1.3.0), org.dandoh.favacts (0.0.3), Key Promoter X (2021.3), org.toml.lang (0.2.155.4114-212), lermitage.intellij.extra.icons (1.66.0.203), com.github.beansoftapp.visualgc.plugin (2021.3.0), org.intellij.qodana (212.5284.31), com.majera.intellij.codereview.bitbucket (2021.2.14), mobi.hsz.idea.gitignore (4.3.0), name.kropp.intellij.makefile (212.5457.62), com.layoutmanager (1.4.0), lermitage.intellij.iconviewer (1.11.0.193), ski.chrzanow.foldableprojectview (1.1.1), com.jetbrains.CyanTheme (1.2), com.wix.sasslint (1.1.2), org.sonarlint.idea (6.3.0.39716), CheckStyle-IDEA (5.58.0), com.github.setial (4.0.2), GrepConsole (12.1.211.6086.0), JFormDesigner-Marketplace-Edition (7.0.4), zielu.gittoolbox (212.8.1), org.rust.lang (0.4.160.4261-212), VisualVMLauncher (1.20.203.4204.0), EclipseCodeFormatter (22.0.203.000.0-Eclipse_2021-09), com.github.beansoft.devkit.helper (2.2), org.jetbrains.kotlin (212-1.6.0-release-799-IJ5457.46), com.intellij.bigdatatools (212.4037.95), izhangzhihao.rainbow.brackets (6.21), pro.bashsupport (2.0.6.212), String Manipulation (8.22.203.000.1), com.khmelyuk.multirun (1.13), com.intellij.plugins.html.instantEditing (212.4746.57), com.haulmont.jpab (5.9-212)
Kotlin: 212-1.6.0-release-799-IJ5457.46
Current Desktop: GNOME
```

```
In file: file:///home/petr/work/src/tipsport/tipsys2/http-calls/CZ_localhost_ZEK.http

java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class com.intellij.psi.impl.source.resolve.reference.ProviderBinding$ProviderInfo ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; com.intellij.psi.impl.source.resolve.reference.ProviderBinding$ProviderInfo is in unnamed module of loader com.intellij.util.lang.PathClassLoader @6be46e8f)
	at com.intellij.psi.impl.source.resolve.reference.NamedObjectProviderBinding.addMatchingProviders(NamedObjectProviderBinding.java:83)
	at com.intellij.psi.impl.source.resolve.reference.SimpleProviderBinding.addAcceptableReferenceProviders(SimpleProviderBinding.java:26)
	at com.intellij.psi.impl.source.resolve.reference.PsiReferenceRegistrarImpl.getPairsByElement(PsiReferenceRegistrarImpl.java:180)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:139)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:39)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:31)
	at com.intellij.httpClient.http.request.psi.impl.HttpRequestTargetBaseImpl.getReferences(HttpRequestTargetBaseImpl.java:35)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:45)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:134)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:114)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:94)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by petr-nehez** [comment]
It's happenning now quite often :(

**Comment by izhangzhihao** [comment]
Thanks for your report! But actually, it's not a bug of this plugin, you can report it to [JetBrains](https://youtrack.jetbrains.com). Thanks again for your support~

**Comment by petr-nehez** [comment]
Thanks, will see what they will do about it ;)
https://youtrack.jetbrains.com/issue/IDEA-283963
