### ISSUE TITLE
IDE Fatal error

### ISSUE THREAD

**Issue by oldigor** [izhangzhihao/intellij-rainbow-brackets#241]
I really don't know what happened.
It did not affected me (At least not that I saw), but I thought maybe the error stacktrace would be important for you guys.

```
In file: file:///home/ilv/Desktop/git_remote/general/extracao_features/cria_atributos_diferencas_percentuais.rb

java.util.NoSuchElementException
	at com.intellij.util.containers.EmptyIterator.next(EmptyIterator.java:32)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.controlFlow.impl.RControlFlowBuilder.a(RControlFlowBuilder.java:1044)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.controlFlow.impl.RControlFlowBuilder.visitRNextStatement(RControlFlowBuilder.java:1020)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.controlStructures.RNextStatementImpl.accept(RNextStatementImpl.java:27)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.controlFlow.impl.RControlFlowBuilder.a(RControlFlowBuilder.java:765)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.controlFlow.impl.RControlFlowBuilder.visitRIfModStatement(RControlFlowBuilder.java:722)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.controlStructures.modifierStatements.RIfModStatementImpl.accept(RIfModStatementImpl.java:28)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.controlFlow.impl.RControlFlowBuilder.a(RControlFlowBuilder.java:180)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.controlFlow.impl.RControlFlowBuilder.visitRCompoundStatement(RControlFlowBuilder.java:174)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.controlStructures.blocks.RCompoundStatementImpl.accept(RCompoundStatementImpl.java:49)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.controlFlow.impl.RControlFlowBuilder.visitRBodyStatement(RControlFlowBuilder.java:1061)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.controlStructures.blocks.RBodyStatementImpl.accept(RBodyStatementImpl.java:57)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.codeInsight.controlflow.ControlFlowBuilder.visitFor(ControlFlowBuilder.java:284)
	at com.intellij.codeInsight.controlflow.ControlFlowBuilder.build(ControlFlowBuilder.java:277)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.controlFlow.impl.RControlFlowBuilder.buildControlFlow(RControlFlowBuilder.java:90)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.iterators.RCodeBlockBase.b(RCodeBlockBase.java:48)
	at com.intellij.openapi.util.AtomicClearableLazyValue$1.compute(AtomicClearableLazyValue.java:29)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:48)
	at com.intellij.openapi.util.AtomicClearableLazyValue.getValue(AtomicClearableLazyValue.java:37)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.iterators.RCodeBlockBase.getControlFlow(RCodeBlockBase.java:113)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.resolve.scope.impl.ScopeImpl.<init>(ScopeImpl.java:48)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.iterators.RCodeBlockBase.a(RCodeBlockBase.java:51)
	at com.intellij.openapi.util.AtomicClearableLazyValue$1.compute(AtomicClearableLazyValue.java:29)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:48)
	at com.intellij.openapi.util.AtomicClearableLazyValue.getValue(AtomicClearableLazyValue.java:37)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.iterators.RCodeBlockBase.getScope(RCodeBlockBase.java:119)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.resolve.scope.impl.ScopeImpl.a(ScopeImpl.java:213)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.resolve.scope.impl.ScopeImpl.a(ScopeImpl.java:214)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.resolve.scope.impl.ScopeImpl.b(ScopeImpl.java:168)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.resolve.scope.impl.ScopeImpl.computeScopeVariables(ScopeImpl.java:123)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.resolve.scope.impl.ScopeImpl.getDeclaredVariable(ScopeImpl.java:76)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.variables.RIdentifierImpl.getScopeVariable(RIdentifierImpl.java:139)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.variables.RIdentifierImpl.isParameter(RIdentifierImpl.java:207)
	at org.jetbrains.plugins.ruby.ruby.lang.annotator.RubyAnnotatorVisitor.visitRIdentifier(RubyAnnotatorVisitor.java:150)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.variables.RIdentifierImpl.accept(RIdentifierImpl.java:82)
	at org.jetbrains.plugins.ruby.ruby.lang.annotator.RubyAnnotator.annotate(RubyAnnotator.java:16)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:120)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:284)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:32)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:71)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:281)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
Rubymine showed a popup notification with the text "IDE Fatal Error". I clicked in the notification and this stacktrace appeared.
![image](https://user-images.githubusercontent.com/20232290/63216111-e2c47080-c106-11e9-85b1-8e699e32833c.png)
## Your programming language(s)
Ruby

## Expected Behavior
-

## Current Behavior
-

## Possible Solution
-

## Code snippet for reproduce (for bugs)
-

## Your Environment

* Plugin version: 5.21
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
RubyMine 2019.1.2
Build #RM-191.7141.58, built on May 14, 2019
JRE: 1.8.0_202-release-1483-b49 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-23-generic

**Comment by izhangzhihao** [comment]
It's a bug of IntelliJ, please report it to Jetbrains.
