### ISSUE TITLE
com.intellij.openapi.progress.ProcessCanceledException in .http file

### ISSUE THREAD

**Issue by petr-nehez** [izhangzhihao/intellij-rainbow-brackets#2426]
When a project was opened

```
decoding of (47,133) failed for REQUEST_TARGET inSegment = [22, 59]

com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:156)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:147)
	at com.intellij.codeInsight.daemon.impl.DaemonProgressIndicator.checkCanceled(DaemonProgressIndicator.java:97)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:143)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:210)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
	at com.intellij.psi.impl.source.tree.AstBufferUtil$BufferVisitor.visitLeaf(AstBufferUtil.java:72)
	at com.intellij.psi.impl.source.tree.LeafElement.acceptTree(LeafElement.java:184)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:67)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:59)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:62)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:49)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitNode(RecursiveTreeElementWalkingVisitor.java:86)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:81)
	at com.intellij.psi.impl.source.tree.AstBufferUtil$BufferVisitor.visitComposite(AstBufferUtil.java:96)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:117)
	at com.intellij.psi.impl.source.tree.AstBufferUtil.toBuffer(AstBufferUtil.java:22)
	at com.intellij.psi.impl.source.tree.AstBufferUtil.toBuffer(AstBufferUtil.java:17)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:230)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:212)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getText(ASTDelegatePsiElement.java:145)
	at com.intellij.psi.LiteralTextEscaper$1.decode(LiteralTextEscaper.java:79)
	at com.intellij.psi.util.PartiallyKnownString$mapRangeToHostRange$1.invoke(PartiallyKnownString.kt:193)
	at com.intellij.psi.util.PartiallyKnownString.mapRangeToHostRange(PartiallyKnownString.kt:232)
	at com.intellij.psi.util.PartiallyKnownString.rangeForSubElement(PartiallyKnownString.kt:85)
	at com.intellij.psi.util.PartiallyKnownString.access$rangeForSubElement(PartiallyKnownString.kt:24)
	at com.intellij.psi.util.PartiallyKnownString$split$2.invoke(PartiallyKnownString.kt:153)
	at com.intellij.psi.util.PartiallyKnownString.split(PartiallyKnownString.kt:167)
	at com.intellij.psi.util.PartiallyKnownString.split$default(PartiallyKnownString.kt:124)
	at com.intellij.microservices.url.references.UrlPksParser.d(UrlPksParser.kt:116)
	at com.intellij.microservices.url.references.UrlPksParser.parseFullUrl(UrlPksParser.kt:85)
	at com.intellij.microservices.url.references.UrlPathReferenceInjector.buildFullUrlReference(UrlPathReferenceInjector.kt:67)
	at com.intellij.httpClient.http.request.microservices.HttpRequestSegmentsReferenceContributor$2.getReferencesByElement(HttpRequestSegmentsReferenceContributor.java:68)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:199)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:162)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:141)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:39)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:31)
	at com.intellij.httpClient.http.request.psi.impl.HttpRequestTargetBaseImpl.getReferences(HttpRequestTargetBaseImpl.java:35)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:42)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:344)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:283)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:303)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:306)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:219)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

## Environment

* Plugin version: 6.21

```
IntelliJ IDEA 2021.3 (Ultimate Edition)
Build #IU-213.5744.223, built on November 27, 2021
Licensed to Petr Nehéz
Subscription is active until November 28, 2022.
Runtime version: 11.0.13+7-b1751.19 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 4.18.0-348.7.1.el8_5.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 7500M
Cores: 12
Registry:
    documentation.show.toolbar=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.1)
    org.turbanov.run.configuration.as.action (1.4.5)
    org.toml.lang (213.5744.224)
    org.dandoh.favacts (0.0.3)
    nix-idea (0.4.0.2)
    net.seesharpsoft.intellij.plugins.file-preview (1.6.4)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    name.kropp.intellij.makefile (213.5744.224)
    lermitage.intellij.iconviewer (1.13.0.193)
    lermitage.intellij.extra.icons (1.68.0.203)
    idea.plugin.protoeditor (213.5744.224)
    hunspell (213.5744.122)
    de.ehmkah.projects.imgdiff (1.11.0)
    com.wakatime.intellij.plugin (13.1.8)
    com.tabnine.TabNine (0.5.9)
    com.layoutmanager (1.4.0)
    com.khmelyuk.multirun (1.13)
    com.jetbrains.CyanTheme (1.2)
    com.jetbrains.ChooseRuntime (1.2)
    com.intellij.plugins.watcher (213.5744.122)
    com.intellij.nativeDebug (213.5744.186)
    com.intellij.javafx (1.0.3)
    com.intellij.ideolog (203.0.27.0)
    org.sonarlint.idea (6.3.1.40498)
    com.wix.sasslint (1.1.2)
    com.github.setial (4.0.2)
    com.github.beansoftapp.visualgc.plugin (2021.3.1)
    ch.raffael.idea.plugins.runpopup (1.3.0)
    com.intellij.selenium (213.5744.172)
    VisualVMLauncher (1.20.203.4204.0)
    String Manipulation (8.24.203.5981.1)
    PsiViewer (213-SNAPSHOT)
    Key Promoter X (2021.3)
    JFormDesigner-Marketplace-Edition (7.0.5.2)
    GrepConsole (12.1.211.6086.0)
    zielu.gittoolbox (212.8.4)
    mobi.hsz.idea.gitignore (4.3.0)
    org.rust.lang (0.4.162.4321-213)
    com.majera.intellij.codereview.bitbucket (2021.3.15)
    EclipseCodeFormatter (22.0.203.000.0-Eclipse_2021-09)
    com.intellij.plugins.html.instantEditing (213.5744.122)
    CheckStyle-IDEA (5.59.1)
    Batch Scripts Support (1.0.13)
    com.intellij.bigdatatools (213.5449.230)
    com.haulmont.jpab (2021.6.1-213)
    izhangzhihao.rainbow.brackets (6.21)
    pro.bashsupport (2.1.1.213)
    com.github.beansoft.devkit.helper (2.2)

Kotlin: 213-1.5.10-release-949-IJ5744.223
Current Desktop: GNOME
```

**Comment by izhangzhihao** [comment]
Thanks for your report! But actually, it's not a bug of this plugin, you can report it to [JetBrains](https://youtrack.jetbrains.com). Thanks again for your support~
