### ISSUE TITLE
v6.21 .vue file bug

### ISSUE THREAD

**Issue by xu455255849** [izhangzhihao/intellij-rainbow-brackets#2427]
![image](https://user-images.githubusercontent.com/15166243/148515849-2b209538-e7ed-4fb4-b7fc-dd227b14ab4f.png)

In file: file:///Users/xushaoping/Documents/work/cloud-ice/packages/upload/src/main.vue

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/psi/impl/PsiManagerImpl.findFile must not be null
	at com.intellij.psi.impl.PsiManagerImpl.$$$reportNull$$$0(PsiManagerImpl.java)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java)
	at org.jetbrains.vuejs.model.typed.VueTypedEntitiesProvider.calculateDtsComponents(VueTypedEntitiesProvider.kt:61)
	at org.jetbrains.vuejs.model.source.VueSourcePlugin$componentsWithProximity$1.compute(VueSourcePlugin.kt:64)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at org.jetbrains.vuejs.model.source.VueSourcePlugin.getComponentsWithProximity(VueSourcePlugin.kt:44)
	at org.jetbrains.vuejs.model.source.VueSourcePlugin.getDefaultProximity(VueSourcePlugin.kt:38)
	at org.jetbrains.vuejs.model.VueScopeElement$DefaultImpls.acceptEntities(VueScopeElement.kt:26)
	at org.jetbrains.vuejs.model.VueEntitiesContainer$DefaultImpls.acceptEntities(VueEntitiesContainer.kt)
	at org.jetbrains.vuejs.model.VueContainer$DefaultImpls.acceptEntities(VueContainer.kt)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.acceptEntities(VueSourceContainer.kt:13)
	at org.jetbrains.vuejs.model.VueScopeElement$DefaultImpls.acceptPropertiesAndMethods(VueScopeElement.kt:94)
	at org.jetbrains.vuejs.model.VueEntitiesContainer$DefaultImpls.acceptPropertiesAndMethods(VueEntitiesContainer.kt)
	at org.jetbrains.vuejs.model.VueContainer$DefaultImpls.acceptPropertiesAndMethods(VueContainer.kt)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.acceptPropertiesAndMethods(VueSourceContainer.kt:13)
	at org.jetbrains.vuejs.model.VueInstanceOwnerKt.contributeComponentProperties(VueInstanceOwner.kt:102)
	at org.jetbrains.vuejs.model.VueInstanceOwnerKt.buildInstanceType(VueInstanceOwner.kt:58)
	at org.jetbrains.vuejs.model.VueInstanceOwnerKt.access$buildInstanceType(VueInstanceOwner.kt:1)
	at org.jetbrains.vuejs.model.VueInstanceOwner$thisType$$inlined$let$lambda$1$1.compute(VueInstanceOwner.kt:34)
	at org.jetbrains.vuejs.model.VueInstanceOwner$thisType$$inlined$let$lambda$1$1.compute(VueInstanceOwner.kt:28)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at org.jetbrains.vuejs.model.VueInstanceOwner$thisType$$inlined$let$lambda$1.compute(VueInstanceOwner.kt:33)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at org.jetbrains.vuejs.model.VueInstanceOwner$DefaultImpls.getThisType(VueInstanceOwner.kt:32)
	at org.jetbrains.vuejs.model.VueEntitiesContainer$DefaultImpls.getThisType(VueEntitiesContainer.kt)
	at org.jetbrains.vuejs.model.VueContainer$DefaultImpls.getThisType(VueContainer.kt)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.getThisType(VueSourceContainer.kt:13)
	at org.jetbrains.vuejs.types.VuePropsType.substituteImpl(VuePropsType.kt:42)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substituteNoCache(JSTypeBaseImpl.java:652)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substituteAndOptimizeNoCache(JSTypeBaseImpl.java:644)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.lambda$substitute$1(JSTypeBaseImpl.java:633)
	at com.intellij.lang.javascript.psi.types.JSResolvedTypeIdCache.lambda$getLocalCachedValue$2(JSResolvedTypeIdCache.java:66)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.lambda$get$0(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.doPreventingRecursion(JSComplexityAwareRecursionGuard.java:94)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.get(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:72)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.getCachedValue(JSComplexityAwareRecursionGuard.java:40)
	at com.intellij.lang.javascript.psi.types.JSResolvedTypeIdCache.getLocalCachedValue(JSResolvedTypeIdCache.java:60)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl$JSResolvedTypeIdImpl.getLocalCachedValue(JSTypeBaseImpl.java:846)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substitute(JSTypeBaseImpl.java:632)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substitute(JSTypeBaseImpl.java:621)
	at com.intellij.lang.javascript.psi.resolve.JSCompleteTypeEvaluationProcessor.applyContextAndPrepare(JSCompleteTypeEvaluationProcessor.java:66)
	at com.intellij.lang.javascript.psi.resolve.JSCompleteTypeEvaluationProcessor.doAddType(JSCompleteTypeEvaluationProcessor.java:54)
	at com.intellij.lang.javascript.psi.resolve.JSCompleteTypeEvaluationProcessor.process(JSCompleteTypeEvaluationProcessor.java:46)
	at com.intellij.lang.javascript.psi.resolve.complexity.JSEvaluationResultElement.applyWithContext(JSEvaluationResultElement.java:79)
	at com.intellij.lang.javascript.psi.JSTypeEvaluationResult.applyToProcessor(JSTypeEvaluationResult.java:26)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluationCache$CacheProviderExpressionType.apply(JSEvaluationCache.java:28)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluationCache.lambda$doGetElementType$2(JSEvaluationCache.java:61)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.lambda$get$0(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.doPreventingRecursion(JSComplexityAwareRecursionGuard.java:94)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.get(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:72)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.getCachedValue(JSComplexityAwareRecursionGuard.java:40)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluationCache.doGetElementType(JSEvaluationCache.java:53)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluationCache.getElementType(JSEvaluationCache.java:47)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.getElementJSType(JSResolveUtil.java:175)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.getExpressionTypeInContext(JSTypeEvaluator.java:661)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.getTypeFromInitializer(JSTypeEvaluator.java:1276)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.addTypeFromVariableInitializer(JSTypeEvaluator.java:1200)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.addTypeFromVariableResolveResult(JSTypeEvaluator.java:1149)
	at com.intellij.lang.javascript.psi.types.evaluable.JSDestructuringTypeImpl.evaluate(JSDestructuringTypeImpl.java:36)
	at com.intellij.lang.javascript.psi.types.evaluable.JSEvaluableOnlyTypeBase.lambda$substituteImpl$0(JSEvaluableOnlyTypeBase.java:43)
	at com.intellij.lang.javascript.psi.types.evaluable.JSEvaluableOnlyTypeBase.substituteWithEvaluator(JSEvaluableOnlyTypeBase.java:55)
	at com.intellij.lang.javascript.psi.types.evaluable.JSEvaluableOnlyTypeBase.substituteImpl(JSEvaluableOnlyTypeBase.java:43)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substituteNoCache(JSTypeBaseImpl.java:652)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substituteAndOptimizeNoCache(JSTypeBaseImpl.java:644)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.lambda$substitute$1(JSTypeBaseImpl.java:633)
	at com.intellij.lang.javascript.psi.types.JSResolvedTypeIdCache.lambda$getLocalCachedValue$2(JSResolvedTypeIdCache.java:66)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.lambda$get$0(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.doPreventingRecursion(JSComplexityAwareRecursionGuard.java:94)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.get(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:72)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.getCachedValue(JSComplexityAwareRecursionGuard.java:40)
	at com.intellij.lang.javascript.psi.types.JSResolvedTypeIdCache.getLocalCachedValue(JSResolvedTypeIdCache.java:60)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl$JSResolvedTypeIdImpl.getLocalCachedValue(JSTypeBaseImpl.java:846)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substitute(JSTypeBaseImpl.java:632)
	at com.intellij.lang.javascript.psi.types.JSWidenType$SimpleWidening.apply(JSWidenType.java:90)
	at com.intellij.lang.javascript.psi.types.JSWidenType.substituteImpl(JSWidenType.java:539)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substituteNoCache(JSTypeBaseImpl.java:652)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substituteAndOptimizeNoCache(JSTypeBaseImpl.java:644)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.lambda$substitute$1(JSTypeBaseImpl.java:633)
	at com.intellij.lang.javascript.psi.types.JSResolvedTypeIdCache.lambda$getLocalCachedValue$2(JSResolvedTypeIdCache.java:66)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.lambda$get$0(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.doPreventingRecursion(JSComplexityAwareRecursionGuard.java:94)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.get(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:72)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.getCachedValue(JSComplexityAwareRecursionGuard.java:40)
	at com.intellij.lang.javascript.psi.types.JSResolvedTypeIdCache.getLocalCachedValue(JSResolvedTypeIdCache.java:60)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl$JSResolvedTypeIdImpl.getLocalCachedValue(JSTypeBaseImpl.java:846)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substitute(JSTypeBaseImpl.java:632)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substitute(JSTypeBaseImpl.java:621)
	at com.intellij.lang.javascript.psi.types.guard.JSTypeGuardChecker.getExactType(JSTypeGuardChecker.java:296)
	at com.intellij.lang.javascript.psi.types.guard.operations.JSApplyTypeOperationContextImpl.getDeclaredType(JSApplyTypeOperationContextImpl.java:36)
	at com.intellij.lang.javascript.psi.types.guard.operations.JSApplyTypeOperationContextImpl.lambda$new$0(JSApplyTypeOperationContextImpl.java:83)
	at com.intellij.openapi.util.NotNullLazyValue$1.compute(NotNullLazyValue.java:56)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:32)
	at com.intellij.lang.javascript.psi.types.guard.operations.JSApplyTypeOperationContextImpl.getDeclaredType(JSApplyTypeOperationContextImpl.java:107)
	at com.intellij.lang.javascript.psi.types.guard.JSTypeGuardChecker.getTypeFromOperation(JSTypeGuardChecker.java:200)
	at com.intellij.lang.javascript.psi.types.guard.JSTypeGuardChecker.getNarrowedType(JSTypeGuardChecker.java:224)
	at com.intellij.lang.javascript.psi.resolve.JSTypeGuardEvaluator.getTypeFromTypeGuard(JSTypeGuardEvaluator.java:75)
	at com.intellij.lang.javascript.psi.resolve.JSTypeGuardEvaluator.getGuardedTypeByEvaluateContext(JSTypeGuardEvaluator.java:57)
	at com.intellij.lang.javascript.psi.resolve.JSTypeGuardEvaluator.applyToExpressionType(JSTypeGuardEvaluator.java:31)
	at com.intellij.lang.javascript.psi.types.guard.JSTypeGuardUtil.getTypeIfAffectedByTypeGuard(JSTypeGuardUtil.java:255)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptAnnotatingVisitor.visitJSReferenceExpression(TypeScriptAnnotatingVisitor.java:144)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.accept(JSReferenceExpressionImpl.java:516)
	at com.intellij.lang.javascript.validation.JSAnnotator.annotate(JSAnnotator.java:17)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:344)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:303)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:306)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:306)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:606)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:219)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by izhangzhihao** [comment]
Thanks for your report! But actually, it's not a bug of this plugin, you can report it to [JetBrains](https://youtrack.jetbrains.com). Thanks again for your support~

**Comment by xu455255849** [comment]
> Thanks for your report! But actually, it's not a bug of this plugin, you can report it to [JetBrains](https://youtrack.jetbrains.com). Thanks again for your support~


Thanks
