### ISSUE TITLE
[IntelliJ IDEA] IDE Fatal Error: java.lang.Throwable: Non-idempotent computation

### ISSUE THREAD

**Issue by Zeratoxx** [izhangzhihao/intellij-rainbow-brackets#2435]
## Your programming languages
The error occurred while working on a Java project.

## Expected Behavior
* No error

## Current Behavior
* An error got thrown.

### Stacktrace ([downloadable text file here (stacktrace.txt)](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/7926605/stacktrace.txt)): 
```
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  LightVariableBuilder:result != LightVariableBuilder:result
  which is element of PsiElementResolveResult with class com.intellij.psi.impl.light.LightVariableBuilder: result and PsiElementResolveResult with class com.intellij.psi.impl.light.LightVariableBuilder: result
  which is 0th element of [PsiElementResolveResult with class com.intellij.psi.impl.light.LightVariableBuilder: result] and [PsiElementResolveResult with class com.intellij.psi.impl.light.LightVariableBuilder: result]

Recomputation gives [Lcom.intellij.psi.ResolveResult;@6ea7280a (class [Lcom.intellij.psi.ResolveResult;) which is different from both values
Recomputation log:
  Resolving result of class com.intellij.psi.impl.source.jsp.el.impl.ELReference
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:90)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:77)
	at com.intellij.psi.impl.source.resolve.ResolveCache.cache(ResolveCache.java:322)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:249)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at com.intellij.psi.impl.source.jsp.el.impl.ELReference.multiResolve(ELReference.java:557)
	at com.intellij.psi.impl.source.jsp.el.impl.ELReference.resolve(ELReference.java:133)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl$1.visitElement(HighlightVisitorImpl.java:82)
	at com.intellij.psi.impl.source.jsp.el.impl.ELExpressionBase.accept(ELExpressionBase.java:38)
	at com.intellij.psi.impl.source.jsp.el.impl.ELVariableImpl.accept(ELVariableImpl.java:30)
	at com.intellij.spring.el.psi.impl.SpringELVariableImpl.accept(SpringELVariableImpl.java:29)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:67)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:24)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:62)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:49)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:76)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl$1.visitElement(HighlightVisitorImpl.java:80)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:70)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$registerReferencesFromInjectedFragments$0(HighlightVisitorImpl.java:195)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.probeElementsUp(InjectedLanguageUtilBase.java:261)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.enumerate(InjectedLanguageUtilBase.java:177)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.enumerateEx(InjectedLanguageManagerImpl.java:331)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.registerReferencesFromInjectedFragments(HighlightVisitorImpl.java:195)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitLiteralExpression(HighlightVisitorImpl.java:907)
	at com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl.accept(PsiLiteralExpressionImpl.java:172)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:189)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$analyze$1(HighlightVisitorImpl.java:214)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:369)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:213)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

## Reproduction
* I quickly closed about 10 files by holding left shift and left clicking on the file tabs. 

## Your Environment

* Plugin version: 6.21
* IDE & Operating System version (I removed my name from the License):
```
IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Licensed to *********
Subscription is active until September 20, 2022.
For educational use only.
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: Batch Scripts Support (1.0.13), Dummy Text Generator (1.2.0), com.kite.intellij (1.9.4), com.mallowigi (36.0), com.shuzijun.markdown-editor (1.12), google-java-format (1.13.0.0), indent-rainbow.indent-rainbow (1.7.0), net.seesharpsoft.intellij.plugins.csv (2.18.2), mobi.hsz.idea.gitignore (4.1.0), some.awesome (1.14), String Manipulation (8.25.203.5981.1), MavenRunHelper (4.13.203.000.0), com.thoughtworks.gauge (211.6693.111), org.jetbrains.plugins.vue (211.6693.111), org.jetbrains.kotlin (211-1.5.0-release-759-IJ6693.72), zielu.gittoolbox (203.8.4), com.chrisrm.idea.MaterialThemeUI (6.7.2), com.haulmont.jpab (5.10-211), izhangzhihao.rainbow.brackets (6.21)
Kotlin: 211-1.5.0-release-759-IJ6693.72
```

**Comment by izhangzhihao** [comment]
Thanks for your report! But actually, it's not a bug of this plugin, you can report it to [JetBrains](https://youtrack.jetbrains.com). Thanks again for your support~
