### ISSUE TITLE
com.intellij.psi.stubs.UpToDateStubIndexMismatch: PSI and index do not match.

### ISSUE THREAD

**Issue by vasily-khodyrev** [izhangzhihao/intellij-rainbow-brackets#2437]
## Your programming languages
Java/js/ts/css
## Expected Behavior
*No exceptions from plugin

## Current Behavior
*Exception from plugin

## Your Environment

* Plugin version: 6.21
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
IntelliJ IDEA 2021.2.4 (Ultimate Edition)
Build #IU-212.5712.43, built on December 21, 2021
Licensed to Vasily Khodyrev
Subscription is active until April 1, 2022.
Runtime version: 11.0.13+8-b1504.49 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 6035M
Cores: 16
Non-Bundled Plugins: CMD Support (1.0.5), mobi.hsz.idea.gitignore (4.3.0), com.intellij.guice (212.5080.8), MavenRunHelper (4.19.212.000.1), com.laravel_idea.tailwind (1.3.1), org.jetbrains.plugins.vue (212.5457.27), com.intellij.react.css.modules (1.0.1), com.github.goldsubmarine.restfulhelper (0.2.2-stable), com.intellij.gwt (212.4746.52), izhangzhihao.rainbow.brackets (6.21), com.haulmont.jpab (2021.6.2-212)
Kotlin: 212-1.5.10-release-IJ5712.43
```
In file: file://C:/Work/devexperts/tdweb/dxtrade5-fe-resources/react-kit/table/components/table/theme/table.global.css

com.intellij.psi.stubs.UpToDateStubIndexMismatch: PSI and index do not match.
Please report the problem to JetBrains with the files attached
INDEXED VERSION IS THE CURRENT ONE file=CssFile:corporate-actions-alert.css, file.class=class com.intellij.psi.css.impl.CssFileImpl, file.lang=Language: CSS, modStamp=1
 tree consistent
 stub debugInfo=created in getStubTree(), with AST = false; with backReference
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=PsiFileStubImpl}844283739
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=com.intellij.psi.SingleRootFileViewProvider{vFile=file://C:/Work/devexperts/tdweb/dxtrade5-fe-resources/src/dx/widgets/widget-alerts/components/creation-alert-form/components/creation-alert-corporate-actions-form/components/grid-creation-alert-corporate-actions/theme/corporate-actions-alert.css, vFileId=47194, content=VirtualFileContent{size=2098}, eventSystemEnabled=true}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1642060535482; file length: 2098
 doc saved: true; doc stamp: 0; doc size: 1966; committed: true
indexing info: indexing timestamp = 1642060535482, binary = false, byte size = 2098, char size = 1966
	at com.intellij.psi.stubs.StubTreeLoader.handleUpToDateMismatch(StubTreeLoader.java:132)
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:126)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$3(CoreProgressManager.java:242)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:240)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:61)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:193)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:141)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:212)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:731)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:128)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.findChildByType(ASTDelegatePsiElement.java:183)
	at com.intellij.psi.css.impl.CssDeclarationImpl.getValue(CssDeclarationImpl.java:98)
	at com.intellij.psi.css.browse.CssColorAnnotator.annotateTerm(CssColorAnnotator.java:134)
	at com.intellij.psi.css.browse.CssColorAnnotator.annotate(CssColorAnnotator.java:52)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:134)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:114)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:94)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.AssertionError: Stub count doesn't match stubbed node length
	at com.intellij.psi.impl.source.FileTrees.lambda$reconcilePsi$4(FileTrees.java:181)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:494)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:174)
	... 40 more
```

**Comment by izhangzhihao** [comment]
Thanks for your report! But actually, it's not a bug of this plugin, you can report it to [JetBrains](https://youtrack.jetbrains.com). Thanks again for your support~
