### ISSUE TITLE
IDE Exception

### ISSUE THREAD

**Issue by deffjay** [izhangzhihao/intellij-rainbow-brackets#244]
```
java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged
	at com.intellij.openapi.diagnostic.Logger.checkException(Logger.java:196)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:101)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:170)
	at com.jetbrains.swift.codeinsight.resolve.requirements.SwiftRequirementSubstitutionInferrer.infer(SwiftRequirementSubstitutionInferrer.kt:40)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalker.inferSubstitutor$intellij_swift(SwiftSuperTypesWalker.kt:74)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.a(SwiftSuperTypesWalk.kt:73)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.processClassType$intellij_swift(SwiftSuperTypesWalk.kt:39)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalker.walk(SwiftSuperTypesWalker.kt:114)
	at com.jetbrains.swift.codeinsight.resolve.SwiftResolveUtil.processClassTypeMembers(SwiftResolveUtil.java:330)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceImpl.a(SwiftReferenceImpl.java:503)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceImpl.a(SwiftReferenceImpl.java:111)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceImpl.resolve(SwiftReferenceImpl.java:278)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceImpl.multiResolve(SwiftReferenceImpl.java:104)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftCallableReference.multiResolve(SwiftCallableReference.java:31)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.a(SwiftSymbolsManagerImpl.java:162)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.b(SwiftSymbolsManagerImpl.java:155)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:102)
	at com.jetbrains.swift.codeinsight.resolve.recursive.DependencyManager.run(DependencyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.b(RecursiveResolveContext.java:96)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:67)
	at com.jetbrains.swift.codeinsight.resolve.recursive.KeyManager.doWithKey(KeyManager.java:24)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.cacheOrGet(RecursiveResolveContext.java:66)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.multiResolve(SwiftSymbolsManagerImpl.java:155)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.multiResolve(SwiftSymbolsManagerImpl.java:223)
	at com.jetbrains.swift.codeinsight.resolve.SwiftResolveUtil.doMultiResolve(SwiftResolveUtil.java:814)
	at com.jetbrains.swift.psi.impl.expression.SwiftReferenceExpressionBase.doMultiResolve(SwiftReferenceExpressionBase.java:296)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftCallExpressionReference.multiResolve(SwiftCallExpressionReference.java:46)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftCallableReference.multiResolve(SwiftCallableReference.java:31)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.a(SwiftSymbolsManagerImpl.java:162)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.b(SwiftSymbolsManagerImpl.java:155)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:102)
	at com.jetbrains.swift.codeinsight.resolve.recursive.DependencyManager.run(DependencyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.b(RecursiveResolveContext.java:96)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:67)
	at com.jetbrains.swift.codeinsight.resolve.recursive.KeyManager.doWithKey(KeyManager.java:24)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.cacheOrGet(RecursiveResolveContext.java:66)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.multiResolve(SwiftSymbolsManagerImpl.java:155)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReference.multiResolve(SwiftReference.java:54)
	at com.jetbrains.swift.codeinsight.resolve.SwiftExpectedTypeProvider$MyVisitor.a(SwiftExpectedTypeProvider.java:118)
	at com.jetbrains.swift.codeinsight.resolve.SwiftExpectedTypeProvider$MyVisitor.visitCallExpression(SwiftExpectedTypeProvider.java:396)
	at com.jetbrains.swift.psi.impl.SwiftCallExpressionGenImpl.accept(SwiftCallExpressionGenImpl.java:21)
	at com.jetbrains.swift.psi.impl.SwiftCallExpressionGenImpl.accept(SwiftCallExpressionGenImpl.java:25)
	at com.jetbrains.swift.codeinsight.resolve.SwiftExpectedTypeProvider.a(SwiftExpectedTypeProvider.java:63)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.jetbrains.swift.codeinsight.resolve.SwiftExpectedTypeProvider.getExpectedTypes(SwiftExpectedTypeProvider.java:62)
	at com.jetbrains.swift.codeinsight.resolve.SwiftExpectedTypeProvider.getExpectedTypes(SwiftExpectedTypeProvider.java:47)
	at com.jetbrains.swift.psi.impl.expression.closure.SwiftClosureGenericValue.inferFallbackType(SwiftClosureGenericValue.kt:139)
	at com.jetbrains.swift.psi.impl.expression.closure.SwiftClosureExpressionImpl.inferType(SwiftClosureExpressionImpl.java:103)
	at com.jetbrains.swift.psi.impl.expression.SwiftExpressionImpl.a(SwiftExpressionImpl.java:27)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.a(SwiftSymbolsManagerImpl.java:138)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:102)
	at com.jetbrains.swift.codeinsight.resolve.recursive.DependencyManager.run(DependencyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.b(RecursiveResolveContext.java:96)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:67)
	at com.jetbrains.swift.codeinsight.resolve.recursive.KeyManager.doWithKey(KeyManager.java:24)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.cacheOrGet(RecursiveResolveContext.java:66)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.getType(SwiftSymbolsManagerImpl.java:138)
	at com.jetbrains.swift.psi.impl.expression.SwiftExpressionImpl.getType(SwiftExpressionImpl.java:27)
	at com.jetbrains.swift.symbols.impl.SwiftArgumentSymbol.getSwiftType(SwiftArgumentSymbol.java:45)
	at com.jetbrains.swift.psi.impl.types.sequence.SwiftFunctionCallMapper.checkTypes(SwiftFunctionCallMapper.kt:243)
	at com.jetbrains.swift.psi.impl.types.sequence.SwiftFunctionCallMapper.b(SwiftFunctionCallMapper.kt:239)
	at com.jetbrains.swift.psi.impl.types.sequence.SwiftFunctionCallMapper.a(SwiftFunctionCallMapper.kt:216)
	at com.jetbrains.swift.psi.impl.types.sequence.SwiftFunctionCallMapper.b(SwiftFunctionCallMapper.kt:63)
	at com.jetbrains.swift.psi.impl.types.sequence.SwiftFunctionCallMapper.map(SwiftFunctionCallMapper.kt:35)
	at com.jetbrains.swift.psi.impl.types.SwiftFunctionDomainTypeImpl.mapTupleArguments(SwiftFunctionDomainTypeImpl.java:102)
	at com.jetbrains.swift.codeinsight.resolve.recursive.TypeEquation$DefaultImpls.a(TypeEquation.kt:44)
	at com.jetbrains.swift.codeinsight.resolve.recursive.TypeEquation$DefaultImpls.resolve(TypeEquation.kt:32)
	at com.jetbrains.swift.codeinsight.resolve.recursive.ConcreteTypeEquation.resolve(ConcreteTypeEquation.kt:7)
	at com.jetbrains.swift.codeinsight.resolve.recursive.ResolveSession.a(ResolveSession.kt:56)
	at com.jetbrains.swift.codeinsight.resolve.recursive.ResolveSession.resolve(ResolveSession.kt:21)
	at com.jetbrains.swift.codeinsight.resolve.recursive.GenericResolverImpl.resolveEquations(GenericResolverImpl.kt:26)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:45)
	at com.jetbrains.swift.codeinsight.resolve.recursive.StackCacheManager.runOnNewStackFrame(StackCacheManager.java:50)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.tryRecursiveGenericInference(RecursiveResolveContext.java:39)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftRecursiveResolverProcessor.a(SwiftRecursiveResolverProcessor.java:336)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftRecursiveResolverProcessor.doRecursiveInference(SwiftRecursiveResolverProcessor.java:326)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftCallableResolverProcessor.doRecursiveInference(SwiftCallableResolverProcessor.kt:98)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftRecursiveResolverProcessor.a(SwiftRecursiveResolverProcessor.java:210)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftRecursiveResolverProcessor.a(SwiftRecursiveResolverProcessor.java:212)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftRecursiveResolverProcessor.getResults(SwiftRecursiveResolverProcessor.java:201)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceImpl.resolve(SwiftReferenceImpl.java:338)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceImpl.multiResolve(SwiftReferenceImpl.java:104)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftCallableReference.multiResolve(SwiftCallableReference.java:31)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.a(SwiftSymbolsManagerImpl.java:162)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.b(SwiftSymbolsManagerImpl.java:155)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:102)
	at com.jetbrains.swift.codeinsight.resolve.recursive.DependencyManager.run(DependencyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.b(RecursiveResolveContext.java:96)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:67)
	at com.jetbrains.swift.codeinsight.resolve.recursive.KeyManager.doWithKey(KeyManager.java:24)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.cacheOrGet(RecursiveResolveContext.java:66)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.multiResolve(SwiftSymbolsManagerImpl.java:155)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReference.multiResolve(SwiftReference.java:54)
	at com.jetbrains.swift.psi.impl.SwiftReferenceElementBase.doMultiResolve(SwiftReferenceElementBase.java:110)
	at com.jetbrains.swift.psi.impl.SwiftReferenceElementBase.advancedResolve(SwiftReferenceElementBase.java:96)
	at com.jetbrains.swift.codeinsight.highlighting.SwiftColorAnnotator.annotate(SwiftColorAnnotator.java:112)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:121)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:290)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:32)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:70)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:281)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:135)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:126)
	at com.intellij.codeInsight.daemon.impl.DaemonProgressIndicator.checkCanceled(DaemonProgressIndicator.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:130)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:214)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:49)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:159)
	at com.jetbrains.cidr.lang.symbols.OCSymbol.getContainingPsiFile(OCSymbol.java:186)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.c(SwiftSuperTypesWalk.kt:173)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.processExtensionsAndSuperTypes$intellij_swift(SwiftSuperTypesWalk.kt:147)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.processClassSymbol(SwiftSuperTypesWalk.kt:119)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.processClassType$intellij_swift(SwiftSuperTypesWalk.kt:60)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.a(SwiftSuperTypesWalk.kt:211)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.access$processSuperType(SwiftSuperTypesWalk.kt:26)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk$processSuperTypes$1.process(SwiftSuperTypesWalk.kt:191)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk$processSuperTypes$1.process(SwiftSuperTypesWalk.kt:26)
	at com.jetbrains.swift.psi.impl.types.SwiftTypeUtil.visitClassTypes(SwiftTypeUtil.java:171)
	at com.jetbrains.swift.psi.impl.types.SwiftTypeUtil.processClassTypes(SwiftTypeUtil.java:273)
	at com.jetbrains.swift.psi.impl.types.SwiftTypeUtil.b(SwiftTypeUtil.java:279)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:533)
	at com.jetbrains.swift.psi.impl.types.SwiftTypeUtil.processClassTypes(SwiftTypeUtil.java:279)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.a(SwiftSuperTypesWalk.kt:191)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.b(SwiftSuperTypesWalk.kt:178)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.processExtensionsAndSuperTypes$intellij_swift(SwiftSuperTypesWalk.kt:147)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.processClassSymbol(SwiftSuperTypesWalk.kt:119)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.processClassType$intellij_swift(SwiftSuperTypesWalk.kt:60)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.a(SwiftSuperTypesWalk.kt:211)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.access$processSuperType(SwiftSuperTypesWalk.kt:26)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk$processSuperTypes$1.process(SwiftSuperTypesWalk.kt:191)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk$processSuperTypes$1.process(SwiftSuperTypesWalk.kt:26)
	at com.jetbrains.swift.psi.impl.types.SwiftTypeUtil.processClassTypes(SwiftTypeUtil.java:275)
	at com.jetbrains.swift.psi.impl.types.SwiftTypeUtil.b(SwiftTypeUtil.java:279)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:533)
	at com.jetbrains.swift.psi.impl.types.SwiftTypeUtil.processClassTypes(SwiftTypeUtil.java:279)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.a(SwiftSuperTypesWalk.kt:191)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.b(SwiftSuperTypesWalk.kt:178)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.processExtensionsAndSuperTypes$intellij_swift(SwiftSuperTypesWalk.kt:147)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalk.processClassSymbol(SwiftSuperTypesWalk.kt:119)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalker.walk(SwiftSuperTypesWalker.kt:98)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSuperTypesWalker.walkUnsubstituted(SwiftSuperTypesWalker.kt:92)
	at com.jetbrains.swift.psi.impl.types.substitution.SwiftSubstitutionUtil.collectAssociatedTypes(SwiftSubstitutionUtil.java:261)
	at com.jetbrains.swift.codeinsight.resolve.requirements.SwiftRequirementSubstitutionInferrer$doInfer$1.invoke(SwiftRequirementSubstitutionInferrer.kt:67)
	at com.jetbrains.swift.codeinsight.resolve.requirements.SwiftRequirementSubstitutionInferrer$doInfer$1.invoke(SwiftRequirementSubstitutionInferrer.kt:26)
	at com.jetbrains.swift.codeinsight.resolve.requirements.SwiftRequirementSubstitutionInferrer.a(SwiftRequirementSubstitutionInferrer.kt:88)
	at com.jetbrains.swift.codeinsight.resolve.requirements.SwiftRequirementSubstitutionInferrer.a(SwiftRequirementSubstitutionInferrer.kt:63)
	at com.jetbrains.swift.codeinsight.resolve.requirements.SwiftRequirementSubstitutionInferrer.inferBuilder$intellij_swift(SwiftRequirementSubstitutionInferrer.kt:51)
	at com.jetbrains.swift.codeinsight.resolve.requirements.SwiftPartialSubstitutionBuilder.a(SwiftPartialSubstitutionBuilder.kt:136)
	at com.jetbrains.swift.codeinsight.resolve.requirements.SwiftPartialSubstitutionBuilder.a(SwiftPartialSubstitutionBuilder.kt:130)
	at com.jetbrains.swift.codeinsight.resolve.requirements.SwiftPartialSubstitutionBuilder.propagateConformances(SwiftPartialSubstitutionBuilder.kt:111)
	at com.jetbrains.swift.codeinsight.resolve.requirements.SwiftPartialSubstitutionBuilder.propagateConformances(SwiftPartialSubstitutionBuilder.kt:123)
	at com.jetbrains.swift.codeinsight.resolve.requirements.SwiftRequirementSubstitutionInferrer.inferBuilder$intellij_swift(SwiftRequirementSubstitutionInferrer.kt:52)
	at com.jetbrains.swift.codeinsight.resolve.requirements.SwiftRequirementSubstitutionInferrer.infer(SwiftRequirementSubstitutionInferrer.kt:37)
	... 132 more
```

**Please [support us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) before creating a feature request, thanks for your support 😁**

Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) before creating one.

## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [ ] This issue/feature request is not reported before.

## Expected Behavior
* If you're describing a bug, tell us what should happen
* If you're suggesting a change/improvement, tell us how it should work

## Current Behavior
* If describing a bug, tell us what happens instead of the expected behavior
* If suggesting a change/improvement, explain the difference from current behavior

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change.
Or what have you tried to resolve this issue.

## Code snippet for reproduce (for bugs)
Please provide code snippet for reproduce bugs.
*NOTE: If you are going to report a bug but WITHOUT your env information, your issue will been closed directly.*

## Your Environment

* Plugin version:
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue will been closed directly.

```
IntelliJ IDEA 2019.2 EAP (Ultimate Edition)
Build #IU-192.5118.30, built on June 13, 2019
Runtime version: 11.0.3+12-b304.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.windowSystem.autoShowProcessPopup=true, bigger.font.in.project.view=true, search.everywhere.settings=true, ide.mac.allowDarkWindowDecorations=true, debugger.watches.in.variables=false, git.explicit.commit.renames.prohibit.multiple.calls=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: izhangzhihao.rainbow.brackets, com.chrisrm.idea.MaterialThemeUI
```

**Comment by izhangzhihao** [comment]
OK, you are using an EAP version of intellij, and the error message said it "should never be logged", so this is a bug of intellij. I've created a issue [here](https://youtrack.jetbrains.com/issue/IDEA-221498).
