### ISSUE TITLE
[Auto Generated Report]java.lang.IllegalStateException: Decompiled data factory shouldn't be called on an unsupported file: jar://E

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#2452]
- Plugin Name: Material Theme UI
- Plugin Version: 6.17
- OS Name: Windows 10
- OS Version: 10.0
- Java Version: 11.0.10
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- Is Snapshot: false
- App Build: IU-203.7717.56
- StackTrace:

```
java.lang.IllegalStateException: Decompiled data factory shouldn't be called on an unsupported file: jar://E:/gradle-5.6.2/caches/modules-2/files-2.1/com.baomidou/mybatis-plus-extension/3.4.0/335c81c288ab0b8b77cfa3cfe322648c9279e99b/mybatis-plus-extension-3.4.0.jar!/com/baomidou/mybatisplus/extension/kotlin/KtQueryWrapper.class
	at org.jetbrains.kotlin.idea.decompiler.classFile.DeserializerForClassfileDecompilerKt.DeserializerForClassfileDecompiler(DeserializerForClassfileDecompiler.kt:38)
	at org.jetbrains.kotlin.idea.decompiler.classFile.KotlinClassFileDecompilerKt.buildDecompiledTextForClassFile$default(KotlinClassFileDecompiler.kt:57)
	at org.jetbrains.kotlin.idea.decompiler.classFile.KtClsFile$1.invoke(KotlinClassFileDecompiler.kt:48)
	at org.jetbrains.kotlin.idea.decompiler.classFile.KtClsFile$1.invoke(KotlinClassFileDecompiler.kt:48)
	at org.jetbrains.kotlin.idea.decompiler.KtDecompiledFile$decompiledText$1.invoke(KtDecompiledFile.kt:22)
	at org.jetbrains.kotlin.idea.decompiler.KtDecompiledFile$decompiledText$1.invoke(KtDecompiledFile.kt:16)
	at org.jetbrains.kotlin.utils.concurrent.block.LockedClearableLazyValue.get(concurrent.kt:36)
	at org.jetbrains.kotlin.idea.decompiler.KtDecompiledFile.hasDeclarationWithKey(KtDecompiledFile.kt:42)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledElementKt.findDeclarationInCompiledFile(LightMemberOriginForCompiledElement.kt:110)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledMethod$originalElement$2.invoke(LightMemberOriginForCompiledElement.kt:100)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledMethod$originalElement$2.invoke(LightMemberOriginForCompiledElement.kt:81)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledMethod.getOriginalElement(LightMemberOriginForCompiledElement.kt)
	at org.jetbrains.kotlin.idea.caches.lightClasses.decompiledDeclarations.KtLightMethodForDecompiledDeclaration.getKotlinOrigin(KtLightMethodForDecompiledDeclaration.kt:28)
	at org.jetbrains.kotlin.idea.caches.lightClasses.decompiledDeclarations.KtLightMethodForDecompiledDeclaration.getKotlinOrigin(KtLightMethodForDecompiledDeclaration.kt:22)
	at org.jetbrains.kotlin.asJava.LightClassUtil$getPsiMethodWrappers$2.invoke(LightClassUtil.kt:134)
	at org.jetbrains.kotlin.asJava.LightClassUtil$getPsiMethodWrappers$2.invoke(LightClassUtil.kt:34)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:742)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:772)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:763)
	at org.jetbrains.kotlin.asJava.LightClassUtil.getLightClassMethods(LightClassUtil.kt:124)
	at org.jetbrains.kotlin.idea.caches.KotlinShortNamesCache$processMethodsWithName$allFunctionsProcessed$1.process(KotlinShortNamesCache.kt:191)
	at org.jetbrains.kotlin.idea.caches.KotlinShortNamesCache$processMethodsWithName$allFunctionsProcessed$1.process(KotlinShortNamesCache.kt:40)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:73)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$2(StubIndexImpl.java:291)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:327)
	at org.jetbrains.kotlin.idea.caches.KotlinShortNamesCache.processMethodsWithName(KotlinShortNamesCache.kt:183)
	at com.intellij.psi.impl.CompositeShortNamesCache.processMethodsWithName(CompositeShortNamesCache.java:182)
	at com.intellij.psi.impl.CompositeShortNamesCache.processMethodsWithName(CompositeShortNamesCache.java:173)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportMethodFix.getMembersToImport(StaticImportMethodFix.java:49)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportMemberFix.<init>(StaticImportMemberFix.java:55)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportMethodFix.<init>(StaticImportMethodFix.java:22)
	at com.intellij.codeInsight.intention.impl.config.QuickFixFactoryImpl.createStaticImportMethodFix(QuickFixFactoryImpl.java:502)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightMethodUtil.registerStaticMethodQualifierFixes(HighlightMethodUtil.java:471)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightMethodUtil.registerMethodCallIntentions(HighlightMethodUtil.java:944)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightMethodUtil.checkAmbiguousMethodCallIdentifier(HighlightMethodUtil.java:786)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitReferenceExpression(HighlightVisitorImpl.java:1412)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.accept(PsiReferenceExpressionImpl.java:778)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:186)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:336)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:269)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$analyze$1(HighlightVisitorImpl.java:211)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:370)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:210)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by izhangzhihao** [comment]
Thanks for your report! But actually, it's not a bug of this plugin, you can report it to [JetBrains](https://youtrack.jetbrains.com). Thanks again for your support~
