### ISSUE TITLE
java.lang.Throwable: scope must be valid

### ISSUE THREAD

**Issue by avi12** [izhangzhihao/intellij-rainbow-brackets#2456]
Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/README.md) before creating one.

## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming languages
TypeScript in an Angular 12 project

## Current Behavior
Out of nowhere, I got this exception:
```
java.lang.Throwable: scope must be valid
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.findNamedElementsInScope(JSResolveUtil.java:1731)
	at com.intellij.lang.javascript.psi.impl.JSObjectLiteralExpressionImpl.findProperty(JSObjectLiteralExpressionImpl.java:70)
	at org.angular2.entities.source.Angular2SourceModule.collectSymbols(Angular2SourceModule.java:90)
	at org.angular2.entities.Angular2ModuleResolver.lambda$getResolvedModuleList$3(Angular2ModuleResolver.java:115)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.angular2.entities.Angular2ModuleResolver.getResolvedModuleList(Angular2ModuleResolver.java:115)
	at org.angular2.entities.Angular2ModuleResolver.getDeclarations(Angular2ModuleResolver.java:47)
	at org.angular2.entities.source.Angular2SourceModule.getDeclarations(Angular2SourceModule.java:44)
	at org.angular2.entities.Angular2EntitiesProvider.lambda$getDeclarationToModuleMap$12(Angular2EntitiesProvider.java:196)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.angular2.entities.Angular2EntitiesProvider.lambda$getDeclarationToModuleMap$13(Angular2EntitiesProvider.java:195)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at org.angular2.entities.Angular2EntitiesProvider.getDeclarationToModuleMap(Angular2EntitiesProvider.java:193)
	at org.angular2.entities.Angular2Declaration.getAllModules(Angular2Declaration.java:15)
	at org.angular2.codeInsight.Angular2DeclarationsScope.selectModule(Angular2DeclarationsScope.java:150)
	at org.angular2.codeInsight.Angular2DeclarationsScope.lambda$new$0(Angular2DeclarationsScope.java:49)
	at com.intellij.util.ObjectUtils.doIfNotNull(ObjectUtils.java:144)
	at org.angular2.codeInsight.Angular2DeclarationsScope.lambda$new$1(Angular2DeclarationsScope.java:48)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at org.angular2.codeInsight.Angular2DeclarationsScope.lambda$new$2(Angular2DeclarationsScope.java:47)
	at com.intellij.openapi.util.NotNullLazyValue$1.compute(NotNullLazyValue.java:56)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:32)
	at org.angular2.codeInsight.Angular2DeclarationsScope.contains(Angular2DeclarationsScope.java:76)
	at org.angular2.codeInsight.Angular2DeclarationsScope.getDeclarationProximity(Angular2DeclarationsScope.java:89)
	at org.angular2.web.Angular2WebSymbolsScope.apply(Angular2WebSymbolsScope.kt:68)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsCompoundScope.apply(WebSymbolsCompoundScope.kt:13)
	at com.intellij.javascript.web.symbols.WebSymbolsScope$Companion.applyScope(WebSymbolsScope.kt:30)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runNameMatchQuery$1.invoke(WebSymbolsRegistryImpl.kt:86)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runNameMatchQuery$1.invoke(WebSymbolsRegistryImpl.kt:15)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runQuery$2.compute(WebSymbolsRegistryImpl.kt:173)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runQuery$2.compute(WebSymbolsRegistryImpl.kt:15)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl.runQuery(WebSymbolsRegistryImpl.kt:157)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl.runNameMatchQuery$intellij_javascript_web(WebSymbolsRegistryImpl.kt:68)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl.runNameMatchQuery(WebSymbolsRegistryImpl.kt:58)
	at com.intellij.javascript.web.symbols.WebSymbolsRegistry.runNameMatchQuery(WebSymbolsRegistry.kt:33)
	at com.intellij.javascript.web.symbols.WebSymbolsRegistry.runNameMatchQuery$default(WebSymbolsRegistry.kt:32)
	at com.intellij.javascript.web.webTypes.json.WebTypesJsonUtilsKt.resolve(WebTypesJsonUtils.kt:127)
	at com.intellij.javascript.web.webTypes.json.WebTypesJsonUtilsKt.resolve$default(WebTypesJsonUtils.kt:123)
	at com.intellij.javascript.web.webTypes.WebTypesComplexPatternConfigProvider$PatternItemsProvider$matchName$1.invoke(WebTypesPatternUtils.kt:145)
	at com.intellij.javascript.web.webTypes.WebTypesComplexPatternConfigProvider$PatternItemsProvider$matchName$1.invoke(WebTypesPatternUtils.kt:132)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:311)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at com.intellij.javascript.web.webTypes.WebTypesComplexPatternConfigProvider$PatternItemsProvider.matchName(WebTypesPatternUtils.kt:153)
	at com.intellij.javascript.web.symbols.patterns.ItemPattern.match$intellij_javascript_web(ItemPattern.kt:26)
	at com.intellij.javascript.web.symbols.patterns.SequencePattern$match$1.invoke(SequencePattern.kt:31)
	at com.intellij.javascript.web.symbols.patterns.SequencePattern$match$1.invoke(SequencePattern.kt:9)
	at com.intellij.javascript.web.symbols.patterns.SequencePattern.process(SequencePattern.kt:389)
	at com.intellij.javascript.web.symbols.patterns.SequencePattern.match$intellij_javascript_web(SequencePattern.kt:29)
	at com.intellij.javascript.web.symbols.patterns.ComplexPattern.performPatternMatch(ComplexPattern.kt:236)
	at com.intellij.javascript.web.symbols.patterns.ComplexPattern.access$performPatternMatch(ComplexPattern.kt:18)
	at com.intellij.javascript.web.symbols.patterns.ComplexPattern$match$1.invoke(ComplexPattern.kt:65)
	at com.intellij.javascript.web.symbols.patterns.ComplexPattern$match$1.invoke(ComplexPattern.kt:18)
	at com.intellij.javascript.web.symbols.patterns.ComplexPattern.process(ComplexPattern.kt:201)
	at com.intellij.javascript.web.symbols.patterns.ComplexPattern.match$intellij_javascript_web(ComplexPattern.kt:63)
	at com.intellij.javascript.web.symbols.patterns.WebSymbolsPattern.match(WebSymbolsPattern.kt:70)
	at com.intellij.javascript.web.symbols.WebSymbolsUtils.match(utils.kt:83)
	at com.intellij.javascript.web.symbols.impl.SearchMap$collectPatternContributions$1.invoke(SearchMap.kt:115)
	at com.intellij.javascript.web.symbols.impl.SearchMap$collectPatternContributions$1.invoke(SearchMap.kt:12)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at com.intellij.javascript.web.symbols.impl.SearchMap.collectPatternContributions(SearchMap.kt:117)
	at com.intellij.javascript.web.symbols.impl.SearchMap.getSymbols$intellij_javascript_web(SearchMap.kt:64)
	at com.intellij.javascript.web.webTypes.WebTypesSymbolsContainerBase$getSymbols$1.invoke(WebTypesSymbolsContainerBase.kt:75)
	at com.intellij.javascript.web.webTypes.WebTypesSymbolsContainerBase$getSymbols$1.invoke(WebTypesSymbolsContainerBase.kt:25)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at com.intellij.javascript.web.webTypes.WebTypesSymbolsContainerBase.getSymbols(WebTypesSymbolsContainerBase.kt:76)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runNameMatchQuery$1$result$1.invoke(WebSymbolsRegistryImpl.kt:78)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runNameMatchQuery$1$result$1.invoke(WebSymbolsRegistryImpl.kt:15)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.DistinctIterator.computeNext(Sequences.kt:570)
	at kotlin.collections.AbstractIterator.tryToComputeNext(AbstractIterator.kt:42)
	at kotlin.collections.AbstractIterator.hasNext(AbstractIterator.kt:29)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runNameMatchQuery$1.invoke(WebSymbolsRegistryImpl.kt:83)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runNameMatchQuery$1.invoke(WebSymbolsRegistryImpl.kt:15)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runQuery$2.compute(WebSymbolsRegistryImpl.kt:173)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runQuery$2.compute(WebSymbolsRegistryImpl.kt:15)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl.runQuery(WebSymbolsRegistryImpl.kt:157)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl.runNameMatchQuery$intellij_javascript_web(WebSymbolsRegistryImpl.kt:68)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl.runNameMatchQuery(WebSymbolsRegistryImpl.kt:58)
	at com.intellij.javascript.web.symbols.WebSymbolsRegistry$DefaultImpls.runNameMatchQuery$default(WebSymbolsRegistry.kt:40)
	at com.intellij.javascript.web.codeInsight.html.elements.WebSymbolElementDescriptorsProvider.getDescriptor(WebSymbolElementDescriptorsProvider.kt:23)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.computeElementDescriptor(XmlTagDelegate.java:457)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate$1.compute(XmlTagDelegate.java:436)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getDescriptor(XmlTagDelegate.java:432)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getDescriptor(XmlTagImpl.java:128)
	at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider$1.getDescriptor(XmlEnumeratedValueReferenceProvider.java:93)
	at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider$1.getDescriptor(XmlEnumeratedValueReferenceProvider.java:89)
	at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider.getReferencesByElement(XmlEnumeratedValueReferenceProvider.java:63)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:199)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:162)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:141)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:39)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getReferencesImpl(XmlTagDelegate.java:161)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.lambda$getDefaultReferences$0(XmlTagDelegate.java:122)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getDefaultReferences(XmlTagDelegate.java:122)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getReferences(XmlTagImpl.java:94)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getReferences(XmlTagImpl.java:84)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlNsPrefixAnnotator.annotate(XmlNsPrefixAnnotator.java:43)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:344)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:303)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:306)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:306)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:606)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:219)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

## Code snippet for reproducing (for bugs)
I have no idea.

## Your Environment

* Plugin version: 6.21
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
WebStorm 2021.3.3
Build #WS-213.7172.31, built on March 18, 2022
Licensed to Next Software N.I.I ltd / Avi Wasserman
You have a perpetual fallback license for this version.
Subscription is active until January 1, 2023.
Runtime version: 11.0.14.1+1-b1751.46 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins:
    org.toml.lang (213.5744.224)
    com.github.czy211.licensetemplate (2.0.0)
    dev.blachut.svelte.lang (0.21.2)
    izhangzhihao.rainbow.brackets (6.21)
    ru.adelf.idea.dotenv (2022.1)
```

I cannot attach the IDE logs due to security reasons.

**Comment by izhangzhihao** [comment]
Thanks for your report! But actually, it's not a bug of this plugin, you can report it to [JetBrains](https://youtrack.jetbrains.com). Thanks again for your support~
