### ISSUE TITLE
Exceptions in IntelliJ 2022.1 for 6.21

### ISSUE THREAD

**Issue by nkiesel** [izhangzhihao/intellij-rainbow-brackets#2460]
Just got this 3 times while editing some Groovy code:
```
Incorrect CFG

java.lang.Throwable
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:127)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:192)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.types.TypesReachingDefinitionsInstance.fun(TypesReachingDefinitionsInstance.kt:28)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.types.TypesReachingDefinitionsInstance.fun(TypesReachingDefinitionsInstance.kt:13)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.DFAEngine.performDFA(DFAEngine.java:84)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.DFAEngine.performDFAWithTimeout(DFAEngine.java:65)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.types.TypeInferenceHelper.getDefUseMaps(TypeInferenceHelper.java:174)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.types.InferenceCache.lambda$new$0(InferenceCache.java:54)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.types.InferenceCache.getInferredType(InferenceCache.java:75)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.types.TypeInferenceHelper.getInferredType(TypeInferenceHelper.java:112)
	at org.jetbrains.plugins.groovy.lang.psi.impl.TopInferenceContext.getVariableType(TopInferenceContext.kt:16)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.getInferredTypes(GrReferenceExpressionImpl.java:318)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.calculateType(GrReferenceExpressionImpl.java:286)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.lambda$getType$0(GrReferenceExpressionImpl.java:351)
	at com.intellij.psi.util.CachedValuesManager.lambda$getProjectPsiDependentCache$0(CachedValuesManager.java:134)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getProjectPsiDependentCache(CachedValuesManager.java:132)
	at org.jetbrains.plugins.groovy.lang.psi.impl.TopInferenceContext.getExpressionType(TopInferenceContext.kt:27)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.getType(GrReferenceExpressionImpl.java:351)
	at org.jetbrains.plugins.groovy.lang.resolve.processors.inference.InferenceKt.getTopLevelType(inference.kt:37)
	at org.jetbrains.plugins.groovy.lang.resolve.api.ExpressionArgument$topLevelType$1.invoke(ExpressionArgument.kt:13)
	at org.jetbrains.plugins.groovy.lang.resolve.api.ExpressionArgument$topLevelType$1.invoke(ExpressionArgument.kt:9)
	at org.jetbrains.plugins.groovy.lang.resolve.api.ExpressionArgument$sam$java_util_function_Function$0.apply(ExpressionArgument.kt)
	at com.intellij.psi.util.CachedValuesManager.lambda$getProjectPsiDependentCache$0(CachedValuesManager.java:134)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getProjectPsiDependentCache(CachedValuesManager.java:132)
	at org.jetbrains.plugins.groovy.lang.psi.impl.TopInferenceContext.getCachedValue(TopInferenceContext.kt:19)
	at org.jetbrains.plugins.groovy.lang.resolve.api.ExpressionArgument.getTopLevelType(ExpressionArgument.kt:13)
	at org.jetbrains.plugins.groovy.lang.resolve.api.Argument$DefaultImpls.getRuntimeType(Argument.kt:13)
	at org.jetbrains.plugins.groovy.lang.resolve.api.ExpressionArgument.getRuntimeType(ExpressionArgument.kt:9)
	at org.jetbrains.plugins.groovy.lang.resolve.impl.ApplicabilityKt.mapApplicability(applicability.kt:20)
	at org.jetbrains.plugins.groovy.lang.resolve.impl.PositionalArgumentMapping.applicability(PositionalArgumentMapping.kt:46)
	at org.jetbrains.plugins.groovy.lang.resolve.BaseMethodResolveResult$myApplicability$2.invoke(BaseMethodResolveResult.kt:34)
	at org.jetbrains.plugins.groovy.lang.resolve.BaseMethodResolveResult$myApplicability$2.invoke(BaseMethodResolveResult.kt:21)
	at org.jetbrains.plugins.groovy.util.RecursionAwareSafePublicationLazy.getValue(RecursionAwareSafePublicationLazy.kt:33)
	at org.jetbrains.plugins.groovy.lang.resolve.BaseMethodResolveResult.getMyApplicability(BaseMethodResolveResult.kt)
	at org.jetbrains.plugins.groovy.lang.resolve.BaseMethodResolveResult.getApplicability(BaseMethodResolveResult.kt:30)
	at org.jetbrains.plugins.groovy.lang.resolve.processors.BaseMethodProcessor$computeApplicableCandidates$1.invoke(BaseMethodProcessor.kt:64)
	at org.jetbrains.plugins.groovy.lang.resolve.processors.BaseMethodProcessor$computeApplicableCandidates$1.invoke(BaseMethodProcessor.kt:20)
	at org.jetbrains.plugins.groovy.lang.resolve.impl.OverloadsKt.filterApplicable(overloads.kt:38)
	at org.jetbrains.plugins.groovy.lang.resolve.processors.BaseMethodProcessor.computeApplicableCandidates(BaseMethodProcessor.kt:64)
	at org.jetbrains.plugins.groovy.lang.resolve.processors.BaseMethodProcessor.handleEvent(BaseMethodProcessor.kt:57)
	at org.jetbrains.plugins.groovy.lang.resolve.NonCodeMembersContributor.runContributors(NonCodeMembersContributor.java:189)
	at org.jetbrains.plugins.groovy.lang.resolve.ResolveUtil.processNonCodeMembers(ResolveUtil.java:247)
	at org.jetbrains.plugins.groovy.lang.resolve.ResolveUtil.processScopeNonCodeMembers(ResolveUtil.java:168)
	at org.jetbrains.plugins.groovy.lang.resolve.ResolveUtil.doProcessDeclarations(ResolveUtil.java:138)
	at org.jetbrains.plugins.groovy.lang.resolve.ResolveUtil.lambda$treeWalkUp$0(ResolveUtil.java:108)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1272)
	at org.jetbrains.plugins.groovy.lang.resolve.ResolveUtil.treeWalkUp(ResolveUtil.java:106)
	at org.jetbrains.plugins.groovy.lang.resolve.ResolveUtilKt.treeWalkUp(ResolveUtil.kt:41)
	at org.jetbrains.plugins.groovy.lang.resolve.GrReferenceResolveRunner.resolveReferenceExpression(GrReferenceResolveRunner.kt:37)
	at org.jetbrains.plugins.groovy.lang.resolve.references.GrExplicitMethodCallReference.doResolve(GrExplicitMethodCallReference.kt:36)
	at org.jetbrains.plugins.groovy.lang.resolve.api.GroovyCachingReference$DefaultResolver.resolve(GroovyCachingReference.kt:21)
	at org.jetbrains.plugins.groovy.lang.resolve.api.GroovyCachingReference$DefaultResolver.resolve(GroovyCachingReference.kt:19)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:237)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:289)
	at org.jetbrains.plugins.groovy.lang.psi.impl.TopInferenceContext.resolveWithCaching(TopInferenceContext.kt:23)
	at org.jetbrains.plugins.groovy.lang.psi.impl.InferenceContext.resolve(InferenceContext.java:48)
	at org.jetbrains.plugins.groovy.lang.resolve.api.GroovyCachingReference.resolve(GroovyCachingReference.kt:16)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.resolve(GrReferenceExpressionImpl.java:555)
	at org.jetbrains.plugins.groovy.lang.psi.api.GroovyReference.advancedResolve(GroovyReference.java:29)
	at org.jetbrains.plugins.groovy.lang.psi.api.GroovyReference.resolve(GroovyReference.java:24)
	at org.jetbrains.plugins.groovy.annotator.GroovyAnnotator.checkFinalFieldAccess(GroovyAnnotator.java:337)
	at org.jetbrains.plugins.groovy.annotator.GroovyAnnotator.visitReferenceExpression(GroovyAnnotator.java:305)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.accept(GrReferenceExpressionImpl.java:74)
	at org.jetbrains.plugins.groovy.annotator.GrAnnotatorImpl.annotate(GrAnnotatorImpl.kt:27)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:343)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:276)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:302)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.analysis.JavaNamesHighlightVisitor.analyze(JavaNamesHighlightVisitor.java:60)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:214)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:273)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:218)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:419)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:411)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:387)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:213)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:385)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
with reported cfg:
```
[0(1) element: null, 1(2) WRITE 1, 2(3) WRITE 2, 3(4) WRITE 3, 4(5) READ 4, 5(6) READ 1, 6(7) ARGUMENTS element: Method call, 7(8) WRITE 5, 8(9) element: Closable block, 9(10) READ 3, 10(11) element: Reference expression MAYBE_RETURN, 11(12) element: null, 12(13) ARGUMENTS element: NEW expression, 13(14) READ 6, 14(15) READ 5, 15(16) ARGUMENTS element: Method call, 16(17) ARGUMENTS element: Method call, 17(18) WRITE 7, 18(19) WRITE 8, 19(20) WRITE 9, 20(21) READ 2, 21(22) element: Closable block, 22(23) WRITE 10, 23(24) READ 10, 24(25) ARGUMENTS element: Method call, 25(26) WRITE 11, 26(27) element: IF statement, 27(28) READ 10, 28(29,31) Condition Instanceof expression, 29(30) instanceof: condition.value instanceof LocalDateTime, 30(36)  Negating goto instruction, condition=28Instanceof expression, 31(32) instanceof: condition.value instanceof LocalDateTime, 32(33) READ 12, 33(34) READ 10, 34(35) ARGUMENTS element: Method call, 35(36) READ 10, 36(37) End element: IF statement, 37(38) READ 10, 38(39) READ 10, 39(40) element: Closable block, 40(41) WRITE 13, 41(42) READ 14, 42() WRITE 15, 43(44) READ 14, 44() WRITE 15, 45(46) READ 14, 46() WRITE 15, 47(48) READ 14, 48() WRITE 15, 49(50) READ 14, 50() WRITE 15, 51(52) READ 14, 52() WRITE 15, 53(54) element: null, 54(55) ARGUMENTS element: Method call, 55(56) WRITE 16, 56(57) READ 7, 57(58) READ 8, 58(59) ARGUMENTS element: Method call, 59(60) element: Closable block, 60(61) READ 9, 61(62) element: Reference expression MAYBE_RETURN, 62(63) element: null, 63(64) READ 16, 64(65) READ 10, 65(66) ARGUMENTS element: Method call, 66(67) element: Closable block, 67(68) READ 9, 68(69) element: Reference expression MAYBE_RETURN, 69(70) element: null, 70(71) READ 11, 71(72) ARGUMENTS element: Method call, 72(73) READ 17, 73(74) ARGUMENTS element: Method call, 74(75) WRITE 8, 75(76) READ 9, 76(77) WRITE 9, 77(78) element: Unary expression MAYBE_RETURN, 78(79) element: null, 79(80) ARGUMENTS element: Method call, 80(81) READ 18, 81(82) ARGUMENTS element: Method call, 82(83) WRITE 19, 83(84) READ 19, 84(85) ARGUMENTS element: Method call, 85(86) ARGUMENTS element: Method call, 86(87) element: Closable block, 87(88) WRITE 20, 88(89) element: Open block, 89(90) READ 7, 90(91) READ 20, 91(92,118) THROW. element: Unary expression, 92(93) ARGUMENTS element: Method call, 93(94,116) THROW. element: Method call, 94(95) WRITE 21, 95(96) element: IF statement, 96(97) READ 21, 97(98,114) THROW. element: Unary expression, 98(99,106,112) THROW. element: Relational expression, 99(100) element: Closable block, 100(101) READ 1, 101(102) element: Reference expression MAYBE_RETURN, 102(103) element: null, 103(104) ARGUMENTS element: NEW expression, 104(105,110) THROW. element: NEW expression, 105(107) THROW. element: THROW statement, 106(107) End element: IF statement, 107(108) READ 21, 108(120) element: Reference expression MAYBE_RETURN, 109(122) element: Finally clause, 110(109,111)  CALL 109, 111(128) AFTER CALL 110, 112(109,113)  CALL 109, 113(128) AFTER CALL 112, 114(109,115)  CALL 109, 115(128) AFTER CALL 114, 116(109,117)  CALL 109, 117(128) AFTER CALL 116, 118(109,119)  CALL 109, 119(128) AFTER CALL 118, 120(109,121)  CALL 109, 121(125) AFTER CALL 120, 122(123) READ 20, 123(124) ARGUMENTS element: Method call, 124(111,113,115,117,119,121)  RETURN, 125(126) element: null, 126(127) ARGUMENTS element: Method call, 127(128) element: Method call MAYBE_RETURN, 128() element: null]
```

* Plugin version: 6.21
* IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 11, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.16.0-6-amd64
GC: G1 Young Generation, G1 Old Generation
Memory: 6000M
Cores: 8
Non-Bundled Plugins:
    wu.seal.tool.jsontokotlin (3.7.2)
    org.nik.presentation-assistant (1.0.9)
    org.jetbrains.projector-plugin (1.10.0)
    com.sourcegraph.jetbrains (1.2.2)
    com.jetbrains.edu (2022.2-2021.3-864)
    com.intellij.marketplace (221.5080.210)
    ru.artyushov (1.2.0)
    io.codearte.props2yaml (1.0.2)
    de.wlsc.junit.converter.plugin (1.4.1)
    com.dmarcotte.handlebars (221.5080.210)
    cn.jxzhang.plugin.json-formatter (1.4)
    carbon-now-sh (1.3.0)
    Keymap exporter (2.2)
    Key Promoter X (2022.1.1)
    mobi.hsz.idea.gitignore (4.4.0)
    Error-prone plugin (221.5080.169)
    Docker (221.5080.126)
    DBN (3.3.1555.0)
    cn.bestwu.gdph (0.1.7)
    MavenRunHelper (4.20.213.3714.1)
    me.scana.okgradle (1.0.1)
    izhangzhihao.rainbow.brackets (6.21)
    MetricsReloaded (1.12)
    GradleDependenciesHelper (1.16)

Kotlin: 221-1.6.20-release-285-IJ5080.210
Current Desktop: GNOME

**Comment by izhangzhihao** [comment]
Thanks for your report!  I didn't know how to reproduce the error in my env, But actually, it's not a bug of this plugin according to the error log, you can report it to [JetBrains](https://youtrack.jetbrains.com). Thanks again for your support~
