### ISSUE TITLE
Warning "high nesting of suppressPrioritizing"

### ISSUE THREAD

**Issue by enerjazzer** [izhangzhihao/intellij-rainbow-brackets#2472]
CLion 2022.1

```
A suspiciously high nesting of suppressPrioritizing, forgot to call restorePrioritizing?

java.lang.Throwable
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:127)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.suppressPrioritizing(CoreProgressManager.java:843)
	at com.intellij.openapi.progress.impl.CoreProgressManager.avoidBlockingPrioritizingThread(CoreProgressManager.java:905)
	at com.intellij.openapi.progress.impl.CoreProgressManager.sleepIfNeededToGivePriorityToAnotherThread(CoreProgressManager.java:863)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.lambda$new$0(ProgressManagerImpl.java:28)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runCheckCanceledHooks(CoreProgressManager.java:129)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:148)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:211)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:687)
	at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:16)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getParent(SharedImplUtil.java:33)
	at com.intellij.extapi.psi.ASTWrapperPsiElement.getParent(ASTWrapperPsiElement.java:19)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getManager(ASTDelegatePsiElement.java:72)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getManager(ASTDelegatePsiElement.java:53)
	at com.intellij.psi.impl.PsiElementBase.getProject(PsiElementBase.java:213)
	at com.jetbrains.cidr.lang.types.OCReferenceTypeBuilder.tryMakeLocalReference(OCReferenceTypeBuilder.java:104)
	at com.jetbrains.cidr.lang.types.OCReferenceTypeBuilder.<init>(OCReferenceTypeBuilder.java:63)
	at com.jetbrains.cidr.lang.types.OCTypeBuilder.createReferenceType(OCTypeBuilder.java:494)
	at com.jetbrains.cidr.lang.types.OCTypeBuilder.getResult(OCTypeBuilder.java:453)
	at com.jetbrains.cidr.lang.symbols.OCBuilderDriver.processDeclarator(OCBuilderDriver.java:2362)
	at com.jetbrains.cidr.lang.symbols.OCBuilderDriver$1.process(OCBuilderDriver.java:1349)
	at com.jetbrains.cidr.lang.symbols.OCBuilderDriver.processDeclaration(OCBuilderDriver.java:1385)
	at com.jetbrains.cidr.lang.psi.impl.OCDeclaratorImpl.getLocalSymbol(OCDeclaratorImpl.java:120)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitLocalSymbolDeclarator(OCFileSymbols.java:80)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitDeclarator(OCVisitor.java:256)
	at com.jetbrains.cidr.lang.psi.impl.OCDeclaratorImpl.accept(OCDeclaratorImpl.java:510)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:71)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitDeclaration(OCVisitor.java:243)
	at com.jetbrains.cidr.lang.psi.impl.OCDeclarationImpl.accept(OCDeclarationImpl.java:88)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:71)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitStatement(OCVisitor.java:25)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitDeclarationStatement(OCVisitor.java:126)
	at com.jetbrains.cidr.lang.psi.impl.OCDeclarationStatementImpl.accept(OCDeclarationStatementImpl.java:25)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:71)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitStatement(OCVisitor.java:25)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitBlockStatement(OCVisitor.java:33)
	at com.jetbrains.cidr.lang.psi.impl.OCEagerBlockStatementImpl.accept(OCEagerBlockStatementImpl.java:31)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:71)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitStatement(OCVisitor.java:25)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitLoopStatement(OCVisitor.java:74)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitDoWhileStatement(OCVisitor.java:82)
	at com.jetbrains.cidr.lang.psi.impl.OCDoWhileStatementImpl.accept(OCDoWhileStatementImpl.java:66)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:71)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitStatement(OCVisitor.java:25)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitBlockStatement(OCVisitor.java:33)
	at com.jetbrains.cidr.lang.psi.impl.OCEagerBlockStatementImpl.accept(OCEagerBlockStatementImpl.java:31)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:71)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitStatement(OCVisitor.java:25)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitIfStatement(OCVisitor.java:29)
	at com.jetbrains.cidr.lang.psi.impl.OCIfStatementImpl.accept(OCIfStatementImpl.java:202)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:71)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitStatement(OCVisitor.java:25)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitBlockStatement(OCVisitor.java:33)
	at com.jetbrains.cidr.lang.psi.impl.OCEagerBlockStatementImpl.accept(OCEagerBlockStatementImpl.java:31)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:71)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitStatement(OCVisitor.java:25)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitLoopStatement(OCVisitor.java:74)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitDoWhileStatement(OCVisitor.java:82)
	at com.jetbrains.cidr.lang.psi.impl.OCDoWhileStatementImpl.accept(OCDoWhileStatementImpl.java:66)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:71)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitStatement(OCVisitor.java:25)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitBlockStatement(OCVisitor.java:33)
	at com.jetbrains.cidr.lang.psi.impl.OCEagerBlockStatementImpl.accept(OCEagerBlockStatementImpl.java:31)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:71)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitStatement(OCVisitor.java:25)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitIfStatement(OCVisitor.java:29)
	at com.jetbrains.cidr.lang.psi.impl.OCIfStatementImpl.accept(OCIfStatementImpl.java:202)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:71)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitStatement(OCVisitor.java:25)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitBlockStatement(OCVisitor.java:33)
	at com.jetbrains.cidr.lang.psi.impl.OCEagerBlockStatementImpl.accept(OCEagerBlockStatementImpl.java:31)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:71)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitStatement(OCVisitor.java:25)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitIfStatement(OCVisitor.java:29)
	at com.jetbrains.cidr.lang.psi.impl.OCIfStatementImpl.accept(OCIfStatementImpl.java:202)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:71)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitStatement(OCVisitor.java:25)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitIfStatement(OCVisitor.java:29)
	at com.jetbrains.cidr.lang.psi.impl.OCIfStatementImpl.accept(OCIfStatementImpl.java:202)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:71)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitStatement(OCVisitor.java:25)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitBlockStatement(OCVisitor.java:33)
	at com.jetbrains.cidr.lang.psi.impl.OCLazyBlockStatementImpl.accept(OCLazyBlockStatementImpl.java:28)
	at com.jetbrains.cidr.lang.psi.impl.OCLazyElementBase.accept(OCLazyElementBase.java:78)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:67)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitDeclaration(OCVisitor.java:243)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitFunctionDeclaration(OCVisitor.java:489)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitFunctionDefinition(OCVisitor.java:287)
	at com.jetbrains.cidr.lang.psi.impl.OCFunctionDefinitionImpl.accept(OCFunctionDefinitionImpl.java:76)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:13)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.visitOCElement(OCFileSymbols.java:71)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitNamespace(OCVisitor.java:331)
	at com.jetbrains.cidr.lang.psi.impl.OCCppNamespaceImpl.accept(OCCppNamespaceImpl.java:75)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:27)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCFile(OCVisitor.java:17)
	at com.jetbrains.cidr.lang.psi.impl.OCFileImpl.accept(OCFileImpl.java:430)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.lambda$static$0(OCFileSymbols.java:48)
	at com.intellij.openapi.util.NotNullLazyKey.getValue(NotNullLazyKey.java:24)
	at com.jetbrains.cidr.lang.legacy.symbols.symtable.OCFileSymbols.markImportsNeeded(OCFileSymbols.java:241)
	at com.jetbrains.cidr.lang.types.visitors.OCTypeResolveVisitor.visitReferenceType(OCTypeResolveVisitor.java:215)
	at com.jetbrains.cidr.lang.types.visitors.OCTypeResolveVisitor.visitReferenceType(OCTypeResolveVisitor.java:43)
	at com.jetbrains.cidr.lang.types.OCReferenceType.accept(OCReferenceType.java:71)
	at com.jetbrains.cidr.lang.types.OCType.transformType(OCType.java:608)
	at com.jetbrains.cidr.lang.types.visitors.OCTypeCloneVisitor.cloneKid(OCTypeCloneVisitor.java:46)
	at com.jetbrains.cidr.lang.types.visitors.OCTypeCloneVisitor.visitPointerType(OCTypeCloneVisitor.java:121)
	at com.jetbrains.cidr.lang.types.visitors.OCTypeResolveVisitor.visitPointerType(OCTypeResolveVisitor.java:178)
	at com.jetbrains.cidr.lang.types.visitors.OCTypeResolveVisitor.visitPointerType(OCTypeResolveVisitor.java:43)
	at com.jetbrains.cidr.lang.types.OCPointerType.accept(OCPointerType.java:155)
	at com.jetbrains.cidr.lang.types.OCType.transformType(OCType.java:608)
	at com.jetbrains.cidr.lang.types.visitors.OCTypeCloneVisitor.cloneKid(OCTypeCloneVisitor.java:46)
	at com.jetbrains.cidr.lang.types.visitors.OCTypeCloneVisitor.visitFunctionType(OCTypeCloneVisitor.java:78)
	at com.jetbrains.cidr.lang.types.visitors.OCTypeResolveVisitor.visitFunctionType(OCTypeResolveVisitor.java:85)
	at com.jetbrains.cidr.lang.types.visitors.OCTypeResolveVisitor.visitFunctionType(OCTypeResolveVisitor.java:43)
	at com.jetbrains.cidr.lang.types.OCFunctionType.accept(OCFunctionType.java:154)
	at com.jetbrains.cidr.lang.types.OCType.transformType(OCType.java:608)
	at com.jetbrains.cidr.lang.types.OCType.resolve(OCType.java:342)
	at com.jetbrains.cidr.lang.symbols.OCSymbol.getResolvedType(OCSymbol.java:75)
	at com.jetbrains.cidr.lang.search.OCFunctionAncestorsQuery.processResults(OCFunctionAncestorsQuery.java:75)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:83)
	at com.jetbrains.cidr.lang.daemon.OCHiddenNonVirtualFunctionAnnotator.findOverriddenCandidate(OCHiddenNonVirtualFunctionAnnotator.java:76)
	at com.jetbrains.cidr.lang.daemon.OCHiddenNonVirtualFunctionAnnotator.checkHiddenNonVirtualFunction(OCHiddenNonVirtualFunctionAnnotator.java:48)
	at com.jetbrains.cidr.lang.daemon.OCHiddenNonVirtualFunctionAnnotator.visitDeclarator(OCHiddenNonVirtualFunctionAnnotator.java:33)
	at com.jetbrains.cidr.lang.psi.impl.OCDeclaratorImpl.accept(OCDeclaratorImpl.java:510)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.daemon.OCAnnotator.annotate(OCAnnotator.java:86)
	at com.jetbrains.cidr.lang.daemon.OCAnnotator.annotate(OCAnnotator.java:65)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:343)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:276)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:302)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:273)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:218)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:419)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:411)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:387)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:213)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:385)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

**Comment by izhangzhihao** [comment]
Thanks for your report! But actually, it's not a bug of this plugin, you can report it to [JetBrains](https://youtrack.jetbrains.com). Thanks again for your support~
