### ISSUE TITLE
RuntimeExceptionWithAttachments: PSI and index do not match.

### ISSUE THREAD

**Issue by natros** [izhangzhihao/intellij-rainbow-brackets#2473]
Version: 6.23

```com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file=PsiFile:RecordingInput.class, file.class=class com.intellij.psi.impl.compiled.ClsFileImpl, file.lang=Language: JAVA, modStamp=0
 stub debugInfo=created from file content; with backReference
latestIndexedStub=null
 viewProvider=com.intellij.psi.ClassFileViewProvider{vFile=jrt:///Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home!/jdk.jfr/jdk/jfr/internal/consumer/RecordingInput.class, vFileId=354771, content=VirtualFileContent{size=9111}, eventSystemEnabled=true}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1641647924000; file length: 9111
indexing info: null
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:131)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:65)
	at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:151)
	at com.intellij.psi.stubs.StubProcessingHelperBase.checkType(StubProcessingHelperBase.java:93)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:72)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:140)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:187)
	at com.intellij.psi.impl.PsiShortNamesCacheImpl.processMethodsWithName(PsiShortNamesCacheImpl.java:193)
	at com.intellij.psi.impl.CompositeShortNamesCache.processMethodsWithName(CompositeShortNamesCache.java:182)
	at com.intellij.psi.impl.CompositeShortNamesCache.processMethodsWithName(CompositeShortNamesCache.java:173)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportMethodFix.getMembersToImport(StaticImportMethodFix.java:49)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportMemberFix.<init>(StaticImportMemberFix.java:52)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportMethodFix.<init>(StaticImportMethodFix.java:22)
	at com.intellij.codeInsight.intention.impl.config.QuickFixFactoryImpl.createStaticImportMethodFix(QuickFixFactoryImpl.java:555)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightMethodUtil.registerStaticMethodQualifierFixes(HighlightMethodUtil.java:477)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightMethodUtil.registerMethodCallIntentions(HighlightMethodUtil.java:975)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightMethodUtil.checkAmbiguousMethodCallIdentifier(HighlightMethodUtil.java:801)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitReferenceExpression(HighlightVisitorImpl.java:1308)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.accept(PsiReferenceExpressionImpl.java:782)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:185)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:343)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:276)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:302)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.analysis.JavaNamesHighlightVisitor.analyze(JavaNamesHighlightVisitor.java:60)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:214)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:273)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:218)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:419)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:411)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:387)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:213)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:385)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

```
PsiJavaFileStub [jdk.jfr.internal.consumer]
  PsiClassStub[name=RecordingInput fqn=jdk.jfr.internal.consumer.RecordingInput]
    PsiModifierListStub[mask=17]
    PsiTypeParameterListStub
    PsiRefListStub[EXTENDS_LIST:]
    PsiRefListStub[IMPLEMENTS_LIST:java.io.DataInput, java.lang.AutoCloseable]
    PsiClassStub[name=Block fqn=jdk.jfr.internal.consumer.RecordingInput.Block]
      PsiModifierListStub[mask=26]
      PsiTypeParameterListStub
      PsiRefListStub[EXTENDS_LIST:]
      PsiRefListStub[IMPLEMENTS_LIST:]
      PsiFieldStub[bytes:byte[]]
        PsiModifierListStub[mask=2]
      PsiFieldStub[blockPosition:long]
        PsiModifierListStub[mask=2]
      PsiFieldStub[blockPositionEnd:long]
        PsiModifierListStub[mask=2]
      PsiMethodStub[cons Block:void]
        PsiModifierListStub[mask=2]
        PsiTypeParameterListStub
        PsiParameterListStub
        PsiRefListStub[THROWS_LIST:]
      PsiMethodStub[contains:boolean]
        PsiModifierListStub[mask=4096]
        PsiTypeParameterListStub
        PsiParameterListStub
          PsiParameterStub[position:long]
            PsiModifierListStub[mask=0]
        PsiRefListStub[THROWS_LIST:]
      PsiMethodStub[read:void]
        PsiModifierListStub[mask=1]
        PsiTypeParameterListStub
        PsiParameterListStub
          PsiParameterStub[file:java.io.RandomAccessFile]
            PsiModifierListStub[mask=0]
          PsiParameterStub[amount:int]
            PsiModifierListStub[mask=0]
        PsiRefListStub[THROWS_LIST:java.io.IOException]
      PsiMethodStub[get:byte]
        PsiModifierListStub[mask=1]
        PsiTypeParameterListStub
        PsiParameterListStub
          PsiParameterStub[position:long]
            PsiModifierListStub[mask=0]
        PsiRefListStub[THROWS_LIST:]
      PsiMethodStub[reset:void]
        PsiModifierListStub[mask=1]
        PsiTypeParameterListStub
        PsiParameterListStub
        PsiRefListStub[THROWS_LIST:]
    PsiFieldStub[DEFAULT_BLOCK_SIZE:int=64000]
      PsiModifierListStub[mask=26]
    PsiFieldStub[blockSize:int]
      PsiModifierListStub[mask=18]
    PsiFieldStub[fileAccess:jdk.jfr.internal.consumer.FileAccess]
      PsiModifierListStub[mask=18]
    PsiFieldStub[pollCount:long]
      PsiModifierListStub[mask=2]
    PsiFieldStub[file:java.io.RandomAccessFile]
      PsiModifierListStub[mask=2]
    PsiFieldStub[filename:java.lang.String]
      PsiModifierListStub[mask=2]
    PsiFieldStub[currentBlock:jdk.jfr.internal.consumer.RecordingInput.Block]
      PsiModifierListStub[mask=2]
    PsiFieldStub[previousBlock:jdk.jfr.internal.consumer.RecordingInput.Block]
      PsiModifierListStub[mask=2]
    PsiFieldStub[position:long]
      PsiModifierListStub[mask=2]
    PsiFieldStub[size:long]
      PsiModifierListStub[mask=2]
    PsiMethodStub[cons RecordingInput:void]
      PsiModifierListStub[mask=4096]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[f:java.io.File]
          PsiModifierListStub[mask=0]
        PsiParameterStub[fileAccess:jdk.jfr.internal.consumer.FileAccess]
          PsiModifierListStub[mask=0]
        PsiParameterStub[blockSize:int]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[initialize:void]
      PsiModifierListStub[mask=2]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[f:java.io.File]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[cons RecordingInput:void]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[f:java.io.File]
          PsiModifierListStub[mask=0]
        PsiParameterStub[fileAccess:jdk.jfr.internal.consumer.FileAccess]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[positionPhysical:void]
      PsiModifierListStub[mask=4096]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[position:long]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readPhysicalByte:byte]
      PsiModifierListStub[mask=4096]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readPhysicalLong:long]
      PsiModifierListStub[mask=4096]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readByte:byte]
      PsiModifierListStub[mask=17]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readFully:void]
      PsiModifierListStub[mask=17]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[dest:byte[]]
          PsiModifierListStub[mask=0]
        PsiParameterStub[offset:int]
          PsiModifierListStub[mask=0]
        PsiParameterStub[length:int]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readFully:void]
      PsiModifierListStub[mask=17]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[dst:byte[]]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readRawShort:short]
      PsiModifierListStub[mask=4096]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readDouble:double]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readFloat:float]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readRawInt:int]
      PsiModifierListStub[mask=4096]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readRawLong:long]
      PsiModifierListStub[mask=4096]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[position:long]
      PsiModifierListStub[mask=17]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[position:void]
      PsiModifierListStub[mask=17]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[newPosition:long]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[trimToFileSize:long]
      PsiModifierListStub[mask=18]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[position:long]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[calculateBlockStart:long]
      PsiModifierListStub[mask=18]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[newPosition:long]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[size:long]
      PsiModifierListStub[mask=4096]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[close:void]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[skipBytes:int]
      PsiModifierListStub[mask=17]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[n:int]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readBoolean:boolean]
      PsiModifierListStub[mask=17]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readUnsignedByte:int]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readUnsignedShort:int]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readLine:java.lang.String]
      PsiModifierListStub[mask=17]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readUTF:java.lang.String]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readChar:char]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readShort:short]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readInt:int]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readLong:long]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[readLongSlow:long]
      PsiModifierListStub[mask=2]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[setValidSize:void]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[size:long]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[getFileSize:long]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[getFilename:java.lang.String]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[require:void]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[minimumBytes:int]
          PsiModifierListStub[mask=0]
        PsiParameterStub[errorMessage:java.lang.String]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[setFile:void]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
        PsiParameterStub[path:java.nio.file.Path]
          PsiModifierListStub[mask=0]
      PsiRefListStub[THROWS_LIST:java.io.IOException]
    PsiMethodStub[setStreamed:void]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:]
    PsiMethodStub[pollWait:void]
      PsiModifierListStub[mask=1]
      PsiTypeParameterListStub
      PsiParameterListStub
      PsiRefListStub[THROWS_LIST:java.io.IOException]
```

```
IntelliJ IDEA 2022.1.1 RC (Ultimate Edition)
Build #IU-221.5591.41, built on May 5, 2022
Runtime version: 11.0.14.1+1-b2043.45 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    ide.mac.file.chooser.native=false
    debugger.valueTooltipAutoShowOnSelection=true
    gradle.testLauncherAPI.enabled=true

Non-Bundled Plugins:
    lermitage.intellij.iconviewer (1.14.0.193)
    com.sburlyaev.terminal.plugin (0.4.5)
    com.intellij.plugins.watcher (221.5591.19)
    org.strangeway.msa (1.0.4)
    org.asciidoctor.intellij.asciidoc (0.37.17)
    com.intellij.java.rareRefactorings (221.5591.19)
    com.intellij.datagen (221.5591.19)
    com.intellij.guice (221.5591.19)
    YourKit Java Profiler 2022.3-b100 Integration (2022.3.100.0)
    String Manipulation (9.4.0)
    PlantUML integration (5.12.0)
    GrepConsole (12.12.211.6693.0)
    uk.co.ben-gibson.remote.repository.mapper (4.0.9)
    Dummy Text Generator (1.2.0)
    com.intellij.gwt (221.5591.19)
    org.mapstruct.intellij (1.3.1)
    izhangzhihao.rainbow.brackets (6.23)
    com.github.goldsubmarine.restfulhelper (0.2.5-stable)
    com.bruce.intellijplugin.generatesetter (2.8)
    com.baomidou.plugin.idea.mybatisx (1.5.4)
    Builder Generator (1.1.8)
    BrowseWordAtCaret (3.0.5)

Kotlin: 221-1.6.21-release-337-IJ5591.41
```

**Comment by izhangzhihao** [comment]
Thanks for your report! But actually, The msg said "Please report the problem to JetBrains with the files attached", so it's not a bug of this plugin, you can report it to [JetBrains](https://youtrack.jetbrains.com). Thanks again for your support~
