### ISSUE TITLE
java.lang.Throwable: Assertion failed: Reached closure end without closure start

### ISSUE THREAD

**Issue by petr-nehez** [izhangzhihao/intellij-rainbow-brackets#2481]
## Your programming languages
Gradle / Groovy

## Code snippet for reproduce (for bugs)
It just occurs quite often when I code in gradle and create new closures.

## Current Behavior
```
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:218)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.types.TypeDfaState.getTopClosureFrame(TypeDfaState.java:181)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.types.TypeDfaInstance.handleFunctionalExpression(TypeDfaInstance.java:104)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.types.TypeDfaInstance.fun(TypeDfaInstance.java:68)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.types.TypeDfaInstance.fun(TypeDfaInstance.java:26)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.DFAEngine.performDFA(DFAEngine.java:84)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.DFAEngine.performDFAWithTimeout(DFAEngine.java:65)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.types.InferenceCache.performTypeDfa(InferenceCache.java:104)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.types.InferenceCache.getInferredType(InferenceCache.java:84)
	at org.jetbrains.plugins.groovy.lang.psi.dataFlow.types.TypeInferenceHelper.getInferredType(TypeInferenceHelper.java:112)
	at org.jetbrains.plugins.groovy.lang.psi.impl.TopInferenceContext.getVariableType(TopInferenceContext.kt:16)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.getInferredTypes(GrReferenceExpressionImpl.java:318)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.calculateType(GrReferenceExpressionImpl.java:286)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.lambda$getType$0(GrReferenceExpressionImpl.java:351)
	at com.intellij.psi.util.CachedValuesManager.lambda$getProjectPsiDependentCache$0(CachedValuesManager.java:134)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getProjectPsiDependentCache(CachedValuesManager.java:132)
	at org.jetbrains.plugins.groovy.lang.psi.impl.TopInferenceContext.getExpressionType(TopInferenceContext.kt:27)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.getType(GrReferenceExpressionImpl.java:351)
	at org.jetbrains.plugins.groovy.lang.resolve.GrReferenceResolveRunner.processQualifier(GrReferenceResolveRunner.kt:58)
	at org.jetbrains.plugins.groovy.lang.resolve.GrReferenceResolveRunner.resolveReferenceExpression(GrReferenceResolveRunner.kt:48)
	at org.jetbrains.plugins.groovy.lang.resolve.references.GrExplicitMethodCallReference.doResolve(GrExplicitMethodCallReference.kt:36)
	at org.jetbrains.plugins.groovy.lang.resolve.api.GroovyCachingReference$DefaultResolver.resolve(GroovyCachingReference.kt:21)
	at org.jetbrains.plugins.groovy.lang.resolve.api.GroovyCachingReference$DefaultResolver.resolve(GroovyCachingReference.kt:19)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:237)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:289)
	at org.jetbrains.plugins.groovy.lang.psi.impl.TopInferenceContext.resolveWithCaching(TopInferenceContext.kt:23)
	at org.jetbrains.plugins.groovy.lang.psi.impl.InferenceContext.resolve(InferenceContext.java:48)
	at org.jetbrains.plugins.groovy.lang.resolve.api.GroovyCachingReference.resolve(GroovyCachingReference.kt:16)
	at org.jetbrains.plugins.groovy.lang.psi.api.GroovyReference.multiResolve(GroovyReference.java:43)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrMethodCallImpl.multiResolve(GrMethodCallImpl.java:88)
	at org.jetbrains.plugins.groovy.lang.psi.api.statements.expressions.GrCall.resolveMethod(GrCall.java:41)
	at org.jetbrains.plugins.groovy.lang.psi.patterns.GroovyClosurePattern$inMethod$1.accepts(GroovyClosurePattern.kt:21)
	at org.jetbrains.plugins.groovy.lang.psi.patterns.GroovyClosurePattern$inMethod$1.accepts(GroovyClosurePattern.kt:16)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:51)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:40)
	at org.jetbrains.plugins.groovy.ext.logback.LogbackDelegatesToProvider.getDelegatesToInfo(LogbackDelegatesToProvider.kt:22)
	at org.jetbrains.plugins.groovy.lang.resolve.delegatesTo.GrDelegatesToUtilKt.doGetDelegatesToInfo(grDelegatesToUtil.kt:42)
	at org.jetbrains.plugins.groovy.lang.resolve.delegatesTo.GrDelegatesToUtilKt.access$doGetDelegatesToInfo(grDelegatesToUtil.kt:1)
	at org.jetbrains.plugins.groovy.lang.resolve.delegatesTo.GrDelegatesToUtilKt$getDelegatesToInfo$1.invoke(grDelegatesToUtil.kt:37)
	at org.jetbrains.plugins.groovy.lang.resolve.delegatesTo.GrDelegatesToUtilKt$getDelegatesToInfo$1.invoke(grDelegatesToUtil.kt)
	at org.jetbrains.plugins.groovy.lang.resolve.delegatesTo.GrDelegatesToUtilKt$sam$java_util_function_Function$0.apply(grDelegatesToUtil.kt)
	at com.intellij.psi.util.CachedValuesManager.lambda$getProjectPsiDependentCache$0(CachedValuesManager.java:134)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getProjectPsiDependentCache(CachedValuesManager.java:132)
	at org.jetbrains.plugins.groovy.lang.psi.impl.TopInferenceContext.getCachedValue(TopInferenceContext.kt:19)
	at org.jetbrains.plugins.groovy.lang.resolve.delegatesTo.GrDelegatesToUtilKt.getDelegatesToInfo(grDelegatesToUtil.kt:37)
	at org.jetbrains.plugins.groovy.lang.psi.impl.FunctionalExpressionsKt.processDelegatesTo(functionalExpressions.kt:67)
	at org.jetbrains.plugins.groovy.lang.psi.impl.FunctionalExpressionsKt.processOwnerAndDelegate(functionalExpressions.kt:51)
	at org.jetbrains.plugins.groovy.lang.psi.impl.FunctionalExpressionsKt.processDeclarationsWithCallsite(functionalExpressions.kt:61)
	at org.jetbrains.plugins.groovy.lang.resolve.ResolveUtil.doProcessDeclarations(ResolveUtil.java:123)
	at org.jetbrains.plugins.groovy.lang.resolve.ResolveUtil.lambda$treeWalkUp$0(ResolveUtil.java:108)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1272)
	at org.jetbrains.plugins.groovy.lang.resolve.ResolveUtil.treeWalkUp(ResolveUtil.java:106)
	at org.jetbrains.plugins.groovy.lang.resolve.ResolveUtilKt.treeWalkUp(ResolveUtil.kt:41)
	at org.jetbrains.plugins.groovy.lang.resolve.GrReferenceResolveRunner.resolveReferenceExpression(GrReferenceResolveRunner.kt:37)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionReference.doResolveNonStatic(GrReferenceExpressionReference.kt:40)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionReference.doResolve(GrReferenceExpressionReference.kt:32)
	at org.jetbrains.plugins.groovy.lang.resolve.api.GroovyCachingReference$DefaultResolver.resolve(GroovyCachingReference.kt:21)
	at org.jetbrains.plugins.groovy.lang.resolve.api.GroovyCachingReference$DefaultResolver.resolve(GroovyCachingReference.kt:19)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:237)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:289)
	at org.jetbrains.plugins.groovy.lang.psi.impl.TopInferenceContext.resolveWithCaching(TopInferenceContext.kt:23)
	at org.jetbrains.plugins.groovy.lang.psi.impl.InferenceContext.resolve(InferenceContext.java:48)
	at org.jetbrains.plugins.groovy.lang.resolve.api.GroovyCachingReference.resolve(GroovyCachingReference.kt:16)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl$1.doResolve(GrReferenceExpressionImpl.java:523)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl$1.doResolve(GrReferenceExpressionImpl.java:465)
	at org.jetbrains.plugins.groovy.lang.resolve.DependentResolver.resolve(DependentResolver.kt:27)
	at org.jetbrains.plugins.groovy.lang.resolve.DependentResolver.resolve(DependentResolver.kt:10)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:237)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:289)
	at org.jetbrains.plugins.groovy.lang.psi.impl.TopInferenceContext.resolveWithCaching(TopInferenceContext.kt:23)
	at org.jetbrains.plugins.groovy.lang.psi.impl.InferenceContext.resolve(InferenceContext.java:48)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.resolve(GrReferenceExpressionImpl.java:558)
	at org.jetbrains.plugins.groovy.lang.psi.api.GroovyReference.advancedResolve(GroovyReference.java:29)
	at org.jetbrains.plugins.groovy.lang.psi.api.GroovyReference.resolve(GroovyReference.java:24)
	at org.jetbrains.plugins.groovy.annotator.GroovyAnnotator.checkFinalFieldAccess(GroovyAnnotator.java:337)
	at org.jetbrains.plugins.groovy.annotator.GroovyAnnotator.visitReferenceExpression(GroovyAnnotator.java:305)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.accept(GrReferenceExpressionImpl.java:74)
	at org.jetbrains.plugins.groovy.annotator.GrAnnotatorImpl.annotate(GrAnnotatorImpl.kt:27)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:343)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:276)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:302)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.analysis.JavaNamesHighlightVisitor.analyze(JavaNamesHighlightVisitor.java:60)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:214)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:273)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:218)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:419)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:411)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:387)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:213)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:385)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

## Your Environment
```
IntelliJ IDEA 2022.1.2 (Ultimate Edition)
Build #IU-221.5787.30, built on May 31, 2022
Subscription is active until November 28, 2022.
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 10500M
Cores: 12
Registry:
    documentation.show.toolbar=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    zielu.cleansheet (211.3.1)
    varme.pw.oceanic-dark-theme (1.1.2)
    ski.chrzanow.foldableprojectview (1.1.2)
    rasarts.espresso.light.theme (1.2.0)
    org.turbanov.run.configuration.as.action (1.4.5)
    org.rust.lang (0.4.171.4656-221)
    org.dandoh.favacts (0.0.3)
    nix-idea (0.4.0.4)
    net.seesharpsoft.intellij.plugins.file-preview (1.6.4)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    name.kropp.intellij.makefile (221.5787.15)
    lermitage.intellij.iconviewer (1.14.0.193)
    lermitage.intellij.extra.icons (2022.1.4)
    hunspell (221.5787.15)
    de.santiv.fastscrolling (1.2)
    de.ehmkah.projects.imgdiff (1.11.0)
    com.wakatime.intellij.plugin (13.1.14)
    com.tabnine.TabNine (0.7.0)
    com.layoutmanager (1.4.0)
    com.khmelyuk.multirun (1.13)
    com.jetbrains.CyanTheme (1.3)
    com.intellij.plugins.xwinkeymap (211.4961.30)
    com.intellij.plugins.watcher (221.5787.13)
    com.intellij.plugins.gnomekeymap (213.4250.391)
    com.intellij.nativeDebug (221.5787.34)
    com.intellij.javafx (1.0.4)
    com.intellij.ideolog (203.0.30.0)
    com.wix.sasslint (1.1.2)
    com.github.today-.theme.spaceday (1.12)
    com.github.setial (4.0.2)
    com.github.l0drex.intellijkdebreezetheme (0.3.1)
    com.github.beansoftapp.visualgc.plugin (2022.1.0)
    ch.raffael.idea.plugins.runpopup (1.3.0)
    com.intellij.javaee.ejb (221.5787.20)
    com.intellij.selenium (221.5890)
    VisualVMLauncher (1.21.211.6085.0)
    String Manipulation (9.4.1)
    PsiViewer (221-SNAPSHOT)
    Key Promoter X (2022.2)
    JFormDesigner-Marketplace-Edition (7.0.5.4)
    GrepConsole (12.12.211.6693.0)
    zielu.gittoolbox (212.9.0)
    org.sonarlint.idea (6.7.0.45926)
    mobi.hsz.idea.gitignore (4.4.0)
    com.mallowigi (64.0.0)
    com.majera.intellij.codereview.bitbucket (2022.2.1.221)
    EclipseCodeFormatter (22.0.203.000.0-Eclipse_2021-09)
    CheckStyle-IDEA (5.67.2)
    Batch Scripts Support (1.0.13)
    com.github.beansoft.devkit.helper (2022.1.0)
    com.intellij.plugins.html.instantEditing (221.5787.15)
    izhangzhihao.rainbow.brackets (6.23)
    pro.bashsupport (2.1.8.221)
    com.intellij.bigdatatools (221.4165.63)
    com.haulmont.jpab (2022.2.5-221)
    com.chrisrm.idea.MaterialThemeUI (7.5.1)

Kotlin: 221-1.6.21-release-337-IJ5787.30
```

**Comment by izhangzhihao** [comment]
Thanks for your report! But actually, it's not a bug of this plugin, you can report it to [JetBrains](https://youtrack.jetbrains.com). Thanks again for your support~

**Comment by petr-nehez** [comment]
FYI https://youtrack.jetbrains.com/issue/IDEA-295719
