### ISSUE TITLE
java.lang.ClassCastException: class com.intellij.lang.javascript.psi.impl.JSFunctionCachedData cannot be cast to class com.intellij.lang.javascript.index.gist.JSVariableBaseData

### ISSUE THREAD

**Issue by rklec** [izhangzhihao/intellij-rainbow-brackets#2507]
Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/README.md) before creating one.

## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming languages
TypeScript

This is an Angular project with jasmine etc.

## Expected Behavior
Not crash/no message.

## Current Behavior
Crash/message:
```
In file: file://****/****.component.spec.ts

java.lang.ClassCastException: class com.intellij.lang.javascript.psi.impl.JSFunctionCachedData cannot be cast to class com.intellij.lang.javascript.index.gist.JSVariableBaseData (com.intellij.lang.javascript.psi.impl.JSFunctionCachedData and com.intellij.lang.javascript.index.gist.JSVariableBaseData are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @5c9951e5)
	at com.intellij.lang.javascript.index.gist.JSStubElementGist.getData(JSStubElementGist.java:110)
	at com.intellij.lang.javascript.psi.impl.JSCachingTypeOwner.lambda$static$0(JSCachingTypeOwner.java:29)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:46)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:82)
	at com.intellij.lang.javascript.psi.impl.JSCachingTypeOwner.getJSType(JSCachingTypeOwner.java:87)
	at com.intellij.lang.javascript.psi.types.recordImpl.PropertySignatureCommonImpl.getMemberHashCode(PropertySignatureCommonImpl.java:123)
	at com.intellij.lang.javascript.ecmascript6.types.JSTypeHashCodeUtil.getMembersHashCode(JSTypeHashCodeUtil.java:27)
	at com.intellij.lang.javascript.psi.types.JSRecordTypeImpl.hashCodeImpl(JSRecordTypeImpl.java:1481)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.hashCode(JSTypeBaseImpl.java:950)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl$JSResolvedTypeIdImpl.hashCode(JSTypeBaseImpl.java:833)
	at java.base/java.util.HashMap.hash(HashMap.java:340)
	at java.base/java.util.HashMap.put(HashMap.java:608)
	at java.base/java.util.HashSet.add(HashSet.java:220)
	at com.intellij.lang.javascript.psi.types.JSRecursiveTypeUtil.startRecursiveTypesComparison(JSRecursiveTypeUtil.java:58)
	at com.intellij.lang.javascript.psi.types.JSRecursiveTypeUtil.computeWithRecursiveTypes(JSRecursiveTypeUtil.java:94)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.isDirectlyAssignableTypeWithCache(JSTypeBaseImpl.java:249)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.isDirectlyAssignableType(JSTypeBaseImpl.java:223)
	at com.intellij.lang.javascript.psi.types.JSFunctionTypeImpl.isDirectlyAssignableTypeImpl(JSFunctionTypeImpl.java:232)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.calculateAssignabilityWithoutCache(JSTypeBaseImpl.java:303)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.isDirectlyAssignableUnderRecursionProtection(JSTypeBaseImpl.java:266)
	at com.intellij.lang.javascript.psi.types.JSRecursiveTypeUtil.computeWithRecursiveTypes(JSRecursiveTypeUtil.java:107)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.isDirectlyAssignableTypeWithCache(JSTypeBaseImpl.java:249)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.isDirectlyAssignableType(JSTypeBaseImpl.java:223)
	at com.intellij.lang.javascript.psi.types.TypeScriptConditionalTypeJSTypeImpl.substituteInternal(TypeScriptConditionalTypeJSTypeImpl.java:156)
	at com.intellij.lang.javascript.psi.types.TypeScriptConditionalTypeJSTypeImpl.substituteImpl(TypeScriptConditionalTypeJSTypeImpl.java:103)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substituteNoCache(JSTypeBaseImpl.java:652)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substituteAndOptimizeNoCache(JSTypeBaseImpl.java:644)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.lambda$substitute$1(JSTypeBaseImpl.java:633)
	at com.intellij.lang.javascript.psi.types.JSResolvedTypeIdCache.lambda$getLocalCachedValue$2(JSResolvedTypeIdCache.java:66)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.lambda$get$0(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.doPreventingRecursion(JSComplexityAwareRecursionGuard.java:94)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.get(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:72)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.getCachedValue(JSComplexityAwareRecursionGuard.java:40)
	at com.intellij.lang.javascript.psi.types.JSResolvedTypeIdCache.getLocalCachedValue(JSResolvedTypeIdCache.java:60)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl$JSResolvedTypeIdImpl.getLocalCachedValue(JSTypeBaseImpl.java:846)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substitute(JSTypeBaseImpl.java:632)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substitute(JSTypeBaseImpl.java:621)
	at com.intellij.lang.javascript.psi.types.JSCompositeTypeBaseImpl.getTypeOfType(JSCompositeTypeBaseImpl.java:71)
	at com.intellij.lang.javascript.psi.types.JSCompositeTypeImpl.lambda$expandAndFlatten$3(JSCompositeTypeImpl.java:198)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at one.util.streamex.AbstractStreamEx.toArray(AbstractStreamEx.java:390)
	at one.util.streamex.AbstractStreamEx.toMutableList(AbstractStreamEx.java:1328)
	at one.util.streamex.AbstractStreamEx.toList(AbstractStreamEx.java:1309)
	at com.intellij.lang.javascript.psi.types.JSCompositeTypeImpl.flattenAndDeduplicate(JSCompositeTypeImpl.java:185)
	at com.intellij.lang.javascript.psi.types.JSCompositeTypeImpl.optimizeTypeIfUnionOrIntersection(JSCompositeTypeImpl.java:97)
	at com.intellij.lang.javascript.psi.types.JSCompositeTypeImpl.optimizeTypeIfComposite(JSCompositeTypeImpl.java:83)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.optimizeTypeInSubstitute(JSTypeBaseImpl.java:671)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substituteNoCache(JSTypeBaseImpl.java:657)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substituteAndOptimizeNoCache(JSTypeBaseImpl.java:644)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.lambda$substitute$1(JSTypeBaseImpl.java:633)
	at com.intellij.lang.javascript.psi.types.JSResolvedTypeIdCache.lambda$getLocalCachedValue$2(JSResolvedTypeIdCache.java:66)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.lambda$get$0(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.doPreventingRecursion(JSComplexityAwareRecursionGuard.java:94)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.get(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:72)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.getCachedValue(JSComplexityAwareRecursionGuard.java:40)
	at com.intellij.lang.javascript.psi.types.JSResolvedTypeIdCache.getLocalCachedValue(JSResolvedTypeIdCache.java:60)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl$JSResolvedTypeIdImpl.getLocalCachedValue(JSTypeBaseImpl.java:846)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substitute(JSTypeBaseImpl.java:632)
	at com.intellij.lang.javascript.psi.types.JSTypeSubstitutionContextImpl.substituteNested(JSTypeSubstitutionContextImpl.java:77)
	at com.intellij.lang.javascript.psi.types.JSGenericTypeImpl.lambda$expandForGenericType$6(JSGenericTypeImpl.java:476)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1797)
	at com.intellij.lang.javascript.psi.types.JSGenericTypeImpl.expandForGenericType(JSGenericTypeImpl.java:475)
	at com.intellij.lang.javascript.psi.types.JSGenericTypeImpl.substituteImpl(JSGenericTypeImpl.java:427)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substituteNoCache(JSTypeBaseImpl.java:652)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substituteAndOptimizeNoCache(JSTypeBaseImpl.java:644)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.lambda$substitute$1(JSTypeBaseImpl.java:633)
	at com.intellij.lang.javascript.psi.types.JSResolvedTypeIdCache.lambda$getLocalCachedValue$2(JSResolvedTypeIdCache.java:66)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.lambda$get$0(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.doPreventingRecursion(JSComplexityAwareRecursionGuard.java:94)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.get(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:72)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.getCachedValue(JSComplexityAwareRecursionGuard.java:40)
	at com.intellij.lang.javascript.psi.types.JSResolvedTypeIdCache.getLocalCachedValue(JSResolvedTypeIdCache.java:60)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl$JSResolvedTypeIdImpl.getLocalCachedValue(JSTypeBaseImpl.java:846)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substitute(JSTypeBaseImpl.java:632)
	at com.intellij.lang.javascript.psi.types.JSTypeBaseImpl.substitute(JSTypeBaseImpl.java:621)
	at com.intellij.lang.javascript.psi.resolve.QualifiedItemProcessor.process(QualifiedItemProcessor.java:136)
	at com.intellij.lang.javascript.psi.resolve.JSCompleteTypeEvaluationProcessor.passToBaseProcessor(JSCompleteTypeEvaluationProcessor.java:111)
	at com.intellij.lang.javascript.psi.resolve.JSCompleteTypeEvaluationProcessor.doAddType(JSCompleteTypeEvaluationProcessor.java:55)
	at com.intellij.lang.javascript.psi.resolve.JSCompleteTypeEvaluationProcessor.process(JSCompleteTypeEvaluationProcessor.java:40)
	at com.intellij.lang.javascript.psi.resolve.JSCompleteTypeEvaluationProcessor.evaluateTypes(JSCompleteTypeEvaluationProcessor.java:124)
	at com.intellij.lang.javascript.psi.resolve.QualifiedItemProcessor.evaluateExpressionOrElementType(QualifiedItemProcessor.java:627)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptReferenceExpressionResolver.doResolveReference(TypeScriptReferenceExpressionResolver.java:108)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptReferenceExpressionResolver.resolve(TypeScriptReferenceExpressionResolver.java:61)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptReferenceExpressionResolver.resolve(TypeScriptReferenceExpressionResolver.java:29)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$5.get(JSResolveUtil.java:1635)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$5.get(JSResolveUtil.java:1632)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:72)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.lambda$getCachedValue$0(JSComplexityAwareRecursionGuard.java:71)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$4.lambda$calculateWithCaching$0(JSResolveUtil.java:1648)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:289)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$4.calculateWithCaching(JSResolveUtil.java:1646)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.getCachedValue(JSComplexityAwareRecursionGuard.java:74)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.resolve(JSResolveUtil.java:1630)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.multiResolve(JSReferenceExpressionImpl.java:527)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.resolve(JSReferenceExpressionImpl.java:140)
	at com.intellij.lang.javascript.psi.types.guard.JSTypeGuardUtil.getTypeIfAffectedByTypeGuard(JSTypeGuardUtil.java:270)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptAnnotatingVisitor.visitJSReferenceExpression(TypeScriptAnnotatingVisitor.java:127)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.accept(JSReferenceExpressionImpl.java:515)
	at com.intellij.lang.javascript.validation.JSAnnotator.annotate(JSAnnotator.java:17)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:343)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:282)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:302)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:273)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:218)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:419)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:411)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:387)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:213)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:385)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

## Possible Solution
N/A

## Code snippet for reproduce (for bugs)
too big/cannot provide that here

## Your Environment

```
WebStorm 2022.1.4
Build #WS-221.6008.13, built on July 19, 2022
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins:
    some.awesome (1.14)
    monokai-pro (1.8.1)
    de.femtopedia.diffplugin (2.1.7)
    com.github.lppedd.idea-conventional-commit (0.21.0)
    com.crunch42.openapi (1.34)
    com.4lex4.intellij.solarized (2.4.0)
    zielu.gittoolbox (212.9.7)
    org.sonarlint.idea (6.8.0.50884)
    mobi.hsz.idea.gitignore (4.4.0)
    com.intellij.swagger (221.6008.14)
    izhangzhihao.rainbow.brackets (6.25)
    com.microsoft.vso.idea (1.162.0)
```

**Comment by izhangzhihao** [comment]
Thanks for your report! But actually, it's not a bug of this plugin, you can report it to [JetBrains](https://youtrack.jetbrains.com). Thanks again for your support~

**Comment by rklec** [comment]
Okay thanks, done in https://youtrack.jetbrains.com/issue/WEB-56695/javalangClassCastException-class-comintellijlangjavascriptpsiimplJSFunctionCachedData-cannot-be-cast-to-class. Then WebStorm showed me the wrong plugin to report it to.
