### ISSUE TITLE
Plugin crash

### ISSUE THREAD

**Issue by Alexsey** [izhangzhihao/intellij-rainbow-brackets#252]
## Please check

- [x] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming language(s)

JavaScript. The crash appeared, I think, when I was editing a JSON file

## Expected Behavior
The plugin should not crash

## Current Behavior

It crashes

## Code snippet for reproduce (for bugs)

stacktrace.txt
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/psi/impl/PsiManagerImpl.findFile must not be null
	at com.intellij.psi.impl.PsiManagerImpl.$$$reportNull$$$0(PsiManagerImpl.java)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.getRainbowInfo(RainbowIndentsPass.kt:469)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.access$getRainbowInfo(RainbowIndentsPass.kt:334)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.invoke(RainbowIndentsPass.kt:343)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.paint(RainbowIndentsPass.kt:334)
	at com.intellij.openapi.editor.impl.view.EditorPainter.lambda$paintCustomRenderers$1(EditorPainter.java:389)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.processRangeHighlightersOverlappingWith(MarkupModelImpl.java:247)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paintCustomRenderers(EditorPainter.java:382)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paint(EditorPainter.java:100)
	at com.intellij.openapi.editor.impl.view.EditorView.paint(EditorView.java:266)
	at com.intellij.openapi.editor.impl.EditorImpl.paint(EditorImpl.java:1902)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paintComponent(EditorComponentImpl.java:239)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:119)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:234)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1654)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1629)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1566)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:868)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

induced.txt
```
Following exceptions happened soon after this one, most probably they are induced.


2019-09-30T18:49:41.149
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/psi/impl/PsiManagerImpl.findFile must not be null
	at com.intellij.psi.impl.PsiManagerImpl.$$$reportNull$$$0(PsiManagerImpl.java)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.getRainbowInfo(RainbowIndentsPass.kt:469)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.access$getRainbowInfo(RainbowIndentsPass.kt:334)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.invoke(RainbowIndentsPass.kt:343)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.paint(RainbowIndentsPass.kt:334)
	at com.intellij.openapi.editor.impl.view.EditorPainter.lambda$paintCustomRenderers$1(EditorPainter.java:389)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.processRangeHighlightersOverlappingWith(MarkupModelImpl.java:247)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paintCustomRenderers(EditorPainter.java:382)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paint(EditorPainter.java:100)
	at com.intellij.openapi.editor.impl.view.EditorView.paint(EditorView.java:266)
	at com.intellij.openapi.editor.impl.EditorImpl.paint(EditorImpl.java:1902)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paintComponent(EditorComponentImpl.java:239)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:119)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:234)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1654)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1629)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1566)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:868)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

![rainbowCrash](https://user-images.githubusercontent.com/6392013/65895260-d8f38580-e3b3-11e9-8aec-ce2b5737a669.png)

## Your Environment

* Plugin version: 5.23
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue will been closed directly.

```
WebStorm 2019.2.3
Build #WS-192.6817.13, built on September 24, 2019
Licensed to Oleksii Bobyr
Subscription is active until November 3, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4096M
Cores: 4
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: com.alayouni.ansiHighlight, com.intellij.ideolog, com.jetbrains.jbre.bintray.downloader, com.intellij.database, izhangzhihao.rainbow.brackets, com.vladsch.idea.multimarkdown, org.mule.tooling.intellij.raml, quokka.js, ru.adelf.idea.dotenv, wallaby.js
```

**Comment by izhangzhihao** [comment]
@YiiGuxing

**Comment by jflecool2** [comment]
Have the same issue

**Comment by izhangzhihao** [comment]
Please try this snapshot build: 
[intellij-rainbow-brackets-5.23.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/3692881/intellij-rainbow-brackets-5.23.zip)
