### ISSUE TITLE
Crash with nginx.conf files

### ISSUE THREAD

**Issue by polaroidkidd** [izhangzhihao/intellij-rainbow-brackets#254]
## Expected Behavior
Well, I guess the plugin shouldn't crash?

## Current Behavior
The plugin crashes every time I open a nginx.conf file. This started happening ever since I installed the nginx support plugin (https://plugins.jetbrains.com/plugin/4415-nginx-support)

Ironically, it does mark the brackets in nginx.conf files when they're both enabled, but doesn't when I disable the nginx-support plugin (it also doesn't crash in this instance).

## Possible Solution
I've disabled the nginx-support plugin.

## Code snippet for reproduce (for bugs)
```
java.lang.RuntimeException: java.lang.NoSuchMethodException: net.ishchenko.idea.nginx.annotator.NginxAnnotatingVisitor.<init>()
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:116)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:408)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:376)
	at com.intellij.codeInsight.daemon.impl.ThreadLocalAnnotatorMap.cloneTemplates(ThreadLocalAnnotatorMap.java:46)
	at com.intellij.codeInsight.daemon.impl.ThreadLocalAnnotatorMap.get(ThreadLocalAnnotatorMap.java:66)
	at com.intellij.codeInsight.daemon.impl.CachedAnnotators.get(CachedAnnotators.java:31)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:105)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:284)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:32)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:70)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:281)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

## Your Environment

* Plugin version: 5.23
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 24, 2019
Licensed to daniel einars
You have a perpetual fallback license for this version
Subscription is active until September 14, 2020
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-43-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1886M
Cores: 8
Registry: compiler.automake.allow.when.app.running=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: HOCON Converter, Lombook Plugin, String Manipulation, com.github.redfoos.logstash-intellij-plugin, com.microsoft.vso.idea, com.shellcheck, com.thvardhan.gradianto, org.jetbrains.plugins.hocon, org.jetbrains.kotlin, com.chrisrm.idea.MaterialThemeUI, com.intellij.plugins.html.instantEditing, com.jetbrains.php, org.intellij.scala, Dart, io.flutter, izhangzhihao.rainbow.brackets, Pythonid, com.intellij.kubernetes, com.jetbrains.edu, de.mariushoefler.flutter_enhancement_suite, org.zalando.intellij.swagger
```

**Comment by izhangzhihao** [comment]
First of all, this is a bug of the 'Nginx-Support' plugin. You can report an issue [here](https://github.com/ishchenko/idea-nginx). 

As a workaround, you could disable Nginx support by [this](https://github.com/izhangzhihao/intellij-rainbow-brackets#disable-rainbow-brackets-for-specific-languages)

```xml
<application>
  <component name="RainbowSettings">
    <option name="languageBlacklist">
      <array>
        <option value="nginx" />
      </array>
    </option>
  </component>
</application>
```
