### ISSUE TITLE
Exception occurred when enable rainbow indent

### ISSUE THREAD

**Issue by luokuning** [izhangzhihao/intellij-rainbow-brackets#260]
Hi there, I just update the Rainbow Brackets to version 5.23, and very excited about the rainbow indent option, nice work! However, after enable the option, I pressed <kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>F</kbd> to search something in the project, and when I scroll the code area in the search pop up, an exception just occurred:

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/psi/impl/PsiManagerImpl.findFile must not be null
	at com.intellij.psi.impl.PsiManagerImpl.$$$reportNull$$$0(PsiManagerImpl.java)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.getRainbowInfo(RainbowIndentsPass.kt:469)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.access$getRainbowInfo(RainbowIndentsPass.kt:334)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.invoke(RainbowIndentsPass.kt:343)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.paint(RainbowIndentsPass.kt:334)
	at com.intellij.openapi.editor.impl.view.EditorPainter.lambda$paintCustomRenderers$1(EditorPainter.java:389)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.processRangeHighlightersOverlappingWith(MarkupModelImpl.java:247)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paintCustomRenderers(EditorPainter.java:382)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paint(EditorPainter.java:100)
	at com.intellij.openapi.editor.impl.view.EditorView.paint(EditorView.java:266)
	at com.intellij.openapi.editor.impl.EditorImpl.paint(EditorImpl.java:1902)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paintComponent(EditorComponentImpl.java:239)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:119)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:234)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:868)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
When the rainbow indent option disabled, everything works fine.

My system info is:
```
WebStorm 2019.2.3
Build #WS-192.6817.13, built on September 24, 2019
Licensed to K L
You have a perpetual fallback license for this version
Subscription is active until November 5, 2020
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.intellij.laf.enable.animation=true, search.everywhere.settings=true, ide.mac.allowDarkWindowDecorations=true, ide.tooltip.initialDelay=705, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.vermouthx.idea, mobi.hsz.idea.gitignore, BashSupport, com.deadlock.scsyntax, izhangzhihao.rainbow.brackets, org.toml.lang, org.rust.lang
```

**Comment by izhangzhihao** [comment]
please upgrade to 5.24

在 2019年10月8日，上午10:44，LK <notifications@github.com> 写道：

﻿

Hi there, I just update the Rainbow Brackets to version 5.23, and very excited about the rainbow indent option, nice work! However, after enable the option, I pressed cmd + shift + F to search something in the project, and when I scroll the code area in the search pop up, an exception just occurred:

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/psi/impl/PsiManagerImpl.findFile must not be null
        at com.intellij.psi.impl.PsiManagerImpl.$$$reportNull$$$0(PsiManagerImpl.java)
        at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java)
        at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.getRainbowInfo(RainbowIndentsPass.kt:469)
        at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.access$getRainbowInfo(RainbowIndentsPass.kt:334)
        at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.invoke(RainbowIndentsPass.kt:343)
        at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.paint(RainbowIndentsPass.kt:334)
        at com.intellij.openapi.editor.impl.view.EditorPainter.lambda$paintCustomRenderers$1(EditorPainter.java:389)
        at com.intellij.openapi.editor.impl.MarkupModelImpl.processRangeHighlightersOverlappingWith(MarkupModelImpl.java:247)
        at com.intellij.openapi.editor.impl.view.EditorPainter.paintCustomRenderers(EditorPainter.java:382)
        at com.intellij.openapi.editor.impl.view.EditorPainter.paint(EditorPainter.java:100)
        at com.intellij.openapi.editor.impl.view.EditorView.paint(EditorView.java:266)
        at com.intellij.openapi.editor.impl.EditorImpl.paint(EditorImpl.java:1902)
        at com.intellij.openapi.editor.impl.EditorComponentImpl.paintComponent(EditorComponentImpl.java:239)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
        at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:119)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
        at com.intellij.ui.components.JBViewport.paint(JBViewport.java:234)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
        at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
        at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
        at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
        at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:868)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
        at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
        at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)


When the rainbow indent option disabled, everything works fine.

My system info is:

WebStorm 2019.2.3
Build #WS-192.6817.13, built on September 24, 2019
Licensed to K L
You have a perpetual fallback license for this version
Subscription is active until November 5, 2020
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.intellij.laf.enable.animation=true, search.everywhere.settings=true, ide.mac.allowDarkWindowDecorations=true, ide.tooltip.initialDelay=705, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.vermouthx.idea, mobi.hsz.idea.gitignore, BashSupport, com.deadlock.scsyntax, izhangzhihao.rainbow.brackets, org.toml.lang, org.rust.lang

**Comment by luokuning** [comment]
Thanks, v5.24 works fine. But I notice that there is no indent line in the search pop up when rainbow indent enabled, is this normal?

**Comment by izhangzhihao** [comment]
Any screenshots?

**Comment by luokuning** [comment]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/12708534/66373391-20dd6280-e9db-11e9-925d-9dfbfbe6a5ad.png">

**Comment by izhangzhihao** [comment]
Yes, I think.
