### ISSUE TITLE
Could not type Chinese in comments after set `Current scope highlight` option as `Border`

### ISSUE THREAD

**Issue by fanchw** [izhangzhihao/intellij-rainbow-brackets#2647]
## Your programming languages
Java
## Expected Behavior
*能够正确输入多个中文

## Current Behavior
* 只能输入第一个中文并且idea出现异常
<img width="602" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/52556759/5b6b2bca-6698-4b80-8cc0-16c16fcad255">
<img width="459" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/52556759/c357ea59-83c2-4200-a041-dd275518df15">

idea的异常
<img width="977" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/52556759/e72b90c0-6aac-4f9d-9e39-84d2185125f2">
```
java.lang.IllegalArgumentException: Invalid offsets: start=354; end=461; document length=457
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:53)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:35)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.<init>(RangeHighlighterImpl.java:74)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighterAndChangeAttributes(MarkupModelImpl.java:152)
	at com.intellij.codeInsight.highlighting.HighlightManagerImpl.addOccurrenceHighlight(HighlightManagerImpl.java:170)
	at com.intellij.codeInsight.highlighting.HighlightManagerImpl.addRangeHighlight(HighlightManagerImpl.java:252)
	at com.intellij.codeInsight.highlighting.HighlightManagerImpl.addRangeHighlight(HighlightManagerImpl.java:220)
	at ಲᆞ.ಞパ(Unknown Source)
	at ਲ਼ॠ.ಞパ(Unknown Source)
	at ਲ਼ॠ.caretPositionChanged(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:118)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:83)
	at jdk.proxy1/jdk.proxy1.$Proxy164.caretPositionChanged(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:118)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:83)
	at jdk.proxy1/jdk.proxy1.$Proxy164.caretPositionChanged(Unknown Source)
	at com.intellij.openapi.editor.impl.CaretModelImpl.fireCaretPositionChanged(CaretModelImpl.java:543)
	at com.intellij.openapi.editor.impl.CaretImpl.doMoveToVisualPosition(CaretImpl.java:596)
	at com.intellij.openapi.editor.impl.CaretImpl.lambda$moveToVisualPosition$4(CaretImpl.java:534)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:414)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToVisualPosition(CaretImpl.java:534)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToVisualPosition(CaretImpl.java:530)
	at com.intellij.openapi.editor.CaretModel.moveToVisualPosition(CaretModel.java:68)
	at com.intellij.openapi.editor.EditorModificationUtilEx.insertStringAtCaretNoScrolling(EditorModificationUtilEx.java:107)
	at com.intellij.openapi.editor.EditorModificationUtilEx.insertStringAtCaret(EditorModificationUtilEx.java:55)
	at com.intellij.openapi.editor.EditorModificationUtilEx.insertStringAtCaret(EditorModificationUtilEx.java:47)
	at com.intellij.codeInsight.editorActions.TypedHandler.type(TypedHandler.java:262)
	at com.intellij.codeInsight.editorActions.TypedHandler.lambda$doExecute$1(TypedHandler.java:204)
	at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$runForEachCaret$3(CaretModelImpl.java:310)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:419)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:319)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:296)
	at com.intellij.codeInsight.editorActions.TypedHandler.doExecute(TypedHandler.java:156)
	at com.intellij.codeInsight.editorActions.TypedHandler.execute(TypedHandler.java:134)
	at com.intellij.codeInsight.lookup.impl.LookupTypedHandler.execute(LookupTypedHandler.java:73)
	at com.intellij.codeInsight.template.emmet.EmmetPreviewTypedHandler.execute(EmmetPreviewTypedHandler.java:43)
	at com.intellij.execution.impl.ConsoleViewImpl$MyTypedHandler.execute(ConsoleViewImpl.java:1170)
	at com.intellij.openapi.editor.impl.DefaultRawTypedHandler$1.run(DefaultRawTypedHandler.java:55)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:992)
	at com.intellij.openapi.editor.impl.DefaultRawTypedHandler.execute(DefaultRawTypedHandler.java:49)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl$MyRawTypedHandler.execute(EditorFactoryImpl.java:316)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$2(TypedAction.java:201)
	at com.intellij.reporting.FreezeLoggerImpl.runUnderPerformanceMonitor(FreezeLoggerImpl.java:28)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:200)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTypedNormally(EditorImpl.java:1341)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1323)
	at com.intellij.openapi.editor.impl.EditorImpl$MyInputMethodHandler.replaceInputMethodText(EditorImpl.java:3873)
	at com.intellij.openapi.editor.impl.EditorImpl.replaceInputMethodText(EditorImpl.java:3501)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.processInputMethodEvent(EditorComponentImpl.java:234)
	at java.desktop/java.awt.Component.processEvent(Component.java:6439)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:791)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:762)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)


```

## Code snippet for reproduce (for bugs)
Please provide code snippet for reproduce bugs.

## Your Environment

* Plugin version:
<img width="1100" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/52556759/ed9aac24-b3de-4fe6-8cd8-0ffb9b618793">

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/52556759/4849dadb-2abf-4187-be51-e4079c7ef151)

* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
```
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Licensed to xxx
You have a perpetual fallback license for this version.
Subscription is active until September 25, 2025.
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 3064M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    documentation.show.toolbar=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.minimap.enabled=true

Non-Bundled Plugins:
    jms-messenger (2.0.1)
    Batch Scripts Support (1.0.13)
    com.thvardhan.gradianto (5.3)
    com.github.copilot (1.2.15.2816)
    net.seesharpsoft.intellij.plugins.file-preview (1.6.4)
    manjaro.mpb (1.8)
    leetcode-editor (8.8)
    org.ermadan.kafkalytic (0.10.5)
    org.rust.lang (0.4.199.5415-232)
    com.intellij.ideolog (222.1.0.0)
    Statistic (4.2.7)
    CMD Support (1.0.5)
    icu.jogeen.fishbook.id (1.4)
    com.intellij.nativeDebug (232.8660.142)
    mobi.hsz.idea.gitignore (4.5.1)
    ink.organics.pojo2json (1.2.6)
    com.github.wangji92.arthas.plugin (2.44)
    SVN Disconnect (1.1.1)
    Builder Generator (1.3.0)
    com.intellij.spring.websocket (232.8660.142)
    String Manipulation (9.9.0)
    org.jetbrains.plugins.hocon (2023.1.0)
    com.intellij.drools (232.8660.142)
    net.hexar.json2pojo (1.1.0)
    com.jetbrains.packagesearch.intellij-plugin (232.8660.142)
    com.intellij.guice (232.8660.142)
    VisualVMLauncher (1.21.211.6085.0)
    com.bruce.easycode.mybatiscodehelper (1.3.2-java.RELEASE)
    com.intellij.bigdatatools.core (232.8660.185)
    com.intellij.bigdatatools.kafka (232.8660.185)
    com.intellij.bigdatatools.binary.files (232.8660.185)
    com.intellij.bigdatatools.rfs (232.8660.185)
    com.intellij.bigdatatools.metastore.core (232.8660.185)
    com.intellij.bigdatatools.flink (232.8660.185)
    com.intellij.bigdatatools.spark (232.8660.185)
    org.mapstruct.intellij (1.6.1)
    com.viartemev.requestmapper (1.0)
    io.github.kings1990.FastRequest (2023.1.7.1)
    org.intellij.scala (2023.2.17)
    SequenceDiagram (3.0.5)
    com.intellij.bigdatatools.zeppelin (232.8660.142)
    com.intellij.bigdatatools (232.8660.142)
    JRebelPlugin (2023.3.0)
    com.haulmont.jpab (2023.3.1-232)
    GrepConsole (12.19.211.6693.0)
    com.majera.intellij.codereview.gitlab (2023.3.2.232)
    zielu.gittoolbox (500.0.13+213)
    cn.yiiguxing.plugin.translate (3.5.1)
    com.ccnode.codegenerator.MyBatisCodeHelperPro (3.2.1)
    com.intellij.plugins.html.instantEditing (232.8660.142)
    com.jetbrains.plugins.jade (232.8660.142)
    izhangzhihao.rainbow.brackets (2023.3.2)

Kotlin: 232-1.9.0-IJ8660.185
```

**Comment by fanchw** [comment]
补充说明，目前只在doc注释上发现该问题。

**Comment by izhangzhihao** [comment]
Please use this build snapshot: 
[intellij-rainbow-brackets-2023.3.2.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/12181288/intellij-rainbow-brackets-2023.3.2.zip)

**Comment by fanchw** [comment]
> Please use this build snapshot: [intellij-rainbow-brackets-2023.3.2.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/12181288/intellij-rainbow-brackets-2023.3.2.zip)

BUG fixed👌
