### ISSUE TITLE
Error while opening fleet

### ISSUE THREAD

**Issue by tyumen-777** [izhangzhihao/intellij-rainbow-brackets#2735]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Javascript

### Free or paid?

Free users

### Expected Behavior

Should open IDE with colorized brackets

### Current Behavior

```
Exception in DefaultDispatcher-worker-17
org.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]at org.json@20240205/org.json.JSONTokener.syntaxError(JSONTokener.java:503)
  at org.json@20240205/org.json.JSONObject.<init>(JSONObject.java:211)
  at org.json@20240205/org.json.JSONObject.<init>(JSONObject.java:429)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin.appendColorSchemaIfNotExists(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin.initColorSchema(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin.access$initColorSchema(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin$load$1.invokeSuspend(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin$load$1.invoke(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin$load$1.invoke(Unknown Source)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1$1.invokeSuspend(Worker.kt:46)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1$1.invoke(Worker.kt)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1$1.invoke(Worker.kt)
  at kotlinx.coroutines.core/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
  at kotlinx.coroutines.core/kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
  at kotlinx.coroutines.core/kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope(Tracing.kt:61)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope(Tracing.kt:56)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope$default(Tracing.kt:55)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1.invokeSuspend(Worker.kt:45)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1.invoke(Worker.kt)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1.invoke(Worker.kt)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invokeSuspend(Durable.kt:20)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invoke(Durable.kt)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invoke(Durable.kt)
  at kotlinx.coroutines.core/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
  at kotlinx.coroutines.core/kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
  at fleet.rpc/fleet.rpc.client.DurableKt.durable(Durable.kt:20)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1.invokeSuspend(Worker.kt:44)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1.invoke(Worker.kt)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1.invoke(Worker.kt)
  at fleet.kernel/fleet.kernel.TrackedQueryKt$launchOnEachEntity$3$1.invokeSuspend(TrackedQuery.kt:36)
  at fleet.kernel/fleet.kernel.TrackedQueryKt$launchOnEachEntity$3$1.invoke(TrackedQuery.kt)
  at fleet.kernel/fleet.kernel.TrackedQueryKt$launchOnEachEntity$3$1.invoke(TrackedQuery.kt)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invokeSuspend(Durable.kt:20)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invoke(Durable.kt)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invoke(Durable.kt)
  at kotlinx.coroutines.core/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
  at kotlinx.coroutines.core/kotlinx.coroutines.Coro…
```

### Code snippet for reproduce

-

### Your Environment

Fleet version: build 1.34.94
OS: Mac OS X (14.4.1, aarch64)

**Comment by izhangzhihao** [comment]
Can you show me your theme under ~/.fleet/themes

**Comment by tyumen-777** [comment]
dark_purple-edited.json 
It's only 1 file in this directory

**Comment by izhangzhihao** [comment]
Can you upload it?

**Comment by tyumen-777** [comment]
[dark_purple-edited.json](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/15289599/dark_purple-edited.json)

**Comment by izhangzhihao** [comment]
It works for me without error:
<img width="1142" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/56ba9ff2-b81e-46d9-a055-b2ab5106cd8b">

Can you delete this file and re-edit it again?

Or can you replace your json with this [dark_purple-edited.json](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/15289624/dark_purple-edited.json)?

**Comment by tyumen-777** [comment]
Same error. 
<img width="375" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/75023241/3a88f376-4ba1-4205-a1e3-73c675728eeb">

**Comment by izhangzhihao** [comment]
is your ~/.fleet/themes dir readable? or writeable?

**Comment by tyumen-777** [comment]
yes sure

**Comment by izhangzhihao** [comment]
Can you try backup all your files under `~/.fleet` then delete the `~/.fleet` folder, and try again?

**Comment by izhangzhihao** [comment]
Any updates since ver 0.2.5 released days ago

**Comment by izhangzhihao** [comment]
closed because of no update.
