### ISSUE TITLE
[IJPL-90 Single project-level activity EP] Migrate to ProjectActivity

### ISSUE THREAD

**Issue by steven7mwesigwa** [izhangzhihao/intellij-rainbow-brackets#2739]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

PHP

### Free or paid?

Free users

### Expected Behavior

I don't expect any warnings in the Jetbrains IDEA logs.

### Current Behavior

I repetitively receive warnings in the Jetbrains IDEA logs.

### Code snippet for reproduce

2024-05-23 11:18:41,192 [266067865]   INFO - #c.i.o.p.InitialVfsRefreshService - ab713347: initial VFS refresh finished in 88 ms
2024-05-23 11:18:41,384 [266068057]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:44,181 [266070854]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:44,183 [266070856]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:44,184 [266070857]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:44,185 [266070858]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:44,186 [266070859]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:45,155 [266071828]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:45,156 [266071829]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:45,158 [266071831]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:45,161 [266071834]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:45,164 [266071837]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:49,935 [266076608]   WARN - #c.i.o.a.i.ActionUpdater - 4490 ms to call on BGT BranchesDashboardActions$UpdateSelectedBranchAction#presentation@Git.Log.Branches (git4idea.ui.branch.dashboard.BranchesDashboardActions$UpdateSelectedBranchAction)
2024-05-23 11:18:50,083 [266076756]   INFO - #c.i.o.a.i.ActionUpdater - 4495 ms to grab EDT for BranchesDashboardActions$HideBranchesAction#presentation@Git.Log.Branches (git4idea.ui.branch.dashboard.BranchesDashboardActions$HideBranchesAction)
2024-05-23 11:18:50,083 [266076756]   INFO - #c.i.o.a.i.ActionUpdater - 4495 ms to grab EDT for BranchesDashboardActions$NewBranchAction#presentation@Git.Log.Branches (git4idea.ui.branch.dashboard.BranchesDashboardActions$NewBranchAction)
2024-05-23 11:18:50,126 [266076799]   WARN - #c.i.o.a.i.ActionUpdater - 9128 ms total to grab EDT 13 times to expand DefaultActionGroup@Git.Log.Branches (com.intellij.openapi.actionSystem.DefaultActionGroup). Use `ActionUpdateThread.BGT`.
2024-05-23 11:18:51,016 [266077689]   INFO - #c.i.x.Html5SchemaProvider - CHARS_DTD_LOCATION = C:/Program Files/JetBrains/PhpStorm 2024.1/lib/app.jar!/resources/html5-schema/html5chars.ent
2024-05-23 11:18:51,452 [266078125]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:51,454 [266078127]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:51,455 [266078128]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:51,457 [266078130]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:51,458 [266078131]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(StickyLine)==false. Use ActionPlaces.getPopupPlace.
2024-05-23 11:18:52,573 [266079246]   INFO - #c.i.o.v.i.p.NewMappings - VCS Root: [Git] - [<Project>]
2024-05-23 11:18:52,587 [266079260]   WARN - #c.i.i.s.i.StartupManagerImpl - Migrate Ờの to ProjectActivity [Plugin: izhangzhihao.rainbow.brackets]
com.intellij.diagnostic.PluginException: Migrate Ờの to ProjectActivity [Plugin: izhangzhihao.rainbow.brackets]
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:275)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:68)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invokeSuspend(StartupManagerImpl.kt:191)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3.invokeSuspend(StartupManagerImpl.kt:190)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-05-23 11:18:52,589 [266079262]   WARN - #c.i.i.s.i.StartupManagerImpl - Migrate طẉ to ProjectActivity [Plugin: izhangzhihao.rainbow.brackets]
com.intellij.diagnostic.PluginException: Migrate طẉ to ProjectActivity [Plugin: izhangzhihao.rainbow.brackets]
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:275)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:68)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invokeSuspend(StartupManagerImpl.kt:191)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3.invokeSuspend(StartupManagerImpl.kt:190)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-05-23 11:18:52,633 [266079306]   INFO - #c.i.o.e.s.p.m.ExternalProjectsDataStorage - Load external projects data in 1 millis (read time: 1)
2024-05-23 11:18:52,681 [266079354]   INFO - #c.i.o.v.i.p.NewMappings - Mapped Roots: 1
2024-05-23 11:18:52,682 [266079355]   INFO - #c.i.o.v.i.p.NewMappings - Detected mapped Root: [Git] - [D:/xampp/htdocs/ecommerceapp]
2024-05-23 11:18:52,806 [266079479]   INFO - #c.i.i.s.p.i.BundledSharedIndexPostStartupActivity - Attached 2 pre-built shared indexes: bundled-js-predefined-1d06a55b98c1-74d2a5396914-JavaScript-PS-241.14494.237, bundled-php-predefined-ba97393d7c68-8f0632a2a215-com.jetbrains.php.sharedIndexes-PS-241.14494.237
2024-05-23 11:18:52,836 [266079509]   INFO - #c.i.o.p.SmartModeScheduler - Post-startup activity executed. Current mode: 4

### Your Environment

PhpStorm 2024.1
Build #PS-241.14494.237, built on March 27, 2024
Licensed to XXXXX XXXXX
You have a perpetual fallback license for this version.
Subscription is active until April 13, 2025.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry:
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
Non-Bundled Plugins:
  net.sjrx.intellij.plugins.systemdunitfiles (223.240127.136)
  com.jetbrains.CyanTheme (1.3)
  Key Promoter X (2024.1.0)
  com.intellij.ml.llm (241.14494.320)
  com.jetbrains.lang.ejs (241.14494.140)
  mobi.hsz.idea.gitignore (4.5.3)
  com.intellij.plugins.html.instantEditing (241.14494.140)
  izhangzhihao.rainbow.brackets (2024.2.3-241)
  ru.adelf.idea.dotenv (2024.1)

**Comment by izhangzhihao** [comment]
Not now, because of

```
Unhandled exception in [ComponentManager(ProjectImpl@1496020878), CoroutineName(run activity), run activity, StandaloneCoroutine{Cancelling}@b194547, Dispatchers.Default]

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of com/github/izhangzhihao/rainbow/brackets/RainbowStartUpActivity.execute must not be null
	
```

https://youtrack.jetbrains.com/issue/IDEA-354324/ProjectActivity-gives-null-as-project

**Comment by izhangzhihao** [comment]
The `ProjectActivity` seems still unstable and is missing abilities(https://youtrack.jetbrains.com/issue/IJPL-90/Single-project-level-activity-EP) Some other plugins migrated to `ProjectActivity` and reverted because it works not as expected. So I will not commit to this migration until it's stable and workable(since it does not work as I expected either).
