### ISSUE TITLE
[FL-27534 SimpleNodeHighlighter does not work since fleet 1.37] [Fleet version: build 1.37.84] ASTHighlighter error

### ISSUE THREAD

**Issue by danny-su** [izhangzhihao/intellij-rainbow-brackets#2747]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

java

### Free or paid?

Paid users

### Expected Behavior

N/A

### Current Behavior

ASTHighlighter error
java.lang.NoClassDefFoundError: fleet/ast/TreeWalker
at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.DefaultHighlighter.invoke(Unknown Source)
  at fleet.frontend.lang/fleet.frontend.lang.LangApiKt$nodeHighlighter$1.invoke(LangApi.kt:70)
  at fleet.frontend.lang/fleet.frontend.lang.LangApiKt$nodeHighlighter$1.invoke(LangApi.kt:70)
  at fleet.frontend.lang/fleet.frontend.lang.ASTHighlighterKt$highlightingZipper$1.invoke(ASTHighlighter.kt:27)
  at fleet.frontend.lang/fleet.frontend.lang.ASTHighlighterKt$highlightingZipper$1.invoke(ASTHighlighter.kt:26)
  at fleet.ast.core/fleet.ast.ReducingZipper$acc$2.invoke(ReducingZipper.kt:63)
  at fleet.kotlin.runtime/kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
  at fleet.ast.core/fleet.ast.ReducingZipper.getAcc(ReducingZipper.kt:56)
  at fleet.frontend.lang/fleet.frontend.lang.ASTHighlighterKt$highlightSyntax$newAstZipper$1.invoke(ASTHighlighter.kt:85)
  at fleet.frontend.lang/fleet.frontend.lang.ASTHighlighterKt$highlightSyntax$newAstZipper$1.invoke(ASTHighlighter.kt:74)
  at fleet.frontend.lang/fleet.frontend.lang.ASTHighlighterKt.visitRange(ASTHighlighter.kt:132)
  at fleet.frontend.lang/fleet.frontend.lang.ASTHighlighterKt.highlightSyntax(ASTHighlighter.kt:74)
  at fleet.frontend.lang/fleet.frontend.lang.ASTHighlighterKt.access$highlightSyntax(ASTHighlighter.kt:1)
  at fleet.frontend.lang/fleet.frontend.lang.ASTHighlighter.highlightRange(ASTHighlighter.kt:115)
  at fleet.frontend.lang/fleet.frontend.lang.ASTHighlighter.highlightRange(ASTHighlighter.kt:99)
  at fleet.noria.ui/noria.model.components.editor.HighlightingKt$close$1.highlightRange(Highlighting.kt:88)
  at fleet.noria.ui/noria.ui.components.editor.EditorViewportKt.reconcileTextChunk-A_YhgmE(EditorViewport.kt:980)
  at fleet.noria.ui/noria.ui.components.editor.EditorViewportKt.emitChunk(EditorViewport.kt:790)
  at fleet.noria.ui/noria.ui.components.editor.EditorViewportKt.buildTextChunks(EditorViewport.kt:858)
  at fleet.noria.ui/noria.ui.components.editor.EditorViewportKt.layoutLine-fTXFza4(EditorViewport.kt:525)
  at fleet.noria.ui/noria.ui.components.editor.EditorViewportKt.editorViewport-UroLW1Q(EditorViewport.kt:249)
  at fleet.noria.ui/noria.ui.components.editor.EditorViewKt$editorView$1$2$1$1$1$2$2.invoke(EditorView.kt:1108)
  at fleet.noria.ui/noria.ui.components.editor.EditorViewKt$editorView$1$2$1$1$1$2$2.invoke(EditorView.kt:1084)
  at fleet.noria.cells/noria.impl.Closure.invoke(Closure.kt:36)
  at fleet.noria.ui/noria.ui.core.FocusKt$withFocusNode$2.invoke(Focus.kt:78)
  at fleet.noria.ui/noria.ui.core.FocusKt$withFocusNode$2.invoke(Focus.kt:78)
  at fleet.noria.cells/noria.impl.Closure.invoke(Closure.kt:36)
  at fleet.noria.cells/noria.NoriaContextKt.withBindingsImpl(NoriaContext.kt:157)
  at fleet.noria.cells/androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:249)
  at fleet.noria.ui/noria.ui.core.FocusKt.withFocusNode(Focus.kt:75)
  at fleet.noria.ui/fleet.compose.foundation.FocusBindingTargetModifier$wrap$1.invoke(FocusBinding.kt:104)
  at fleet.noria.ui/fleet.compose.foundation.FocusBindingTargetModifier$wrap$1.invoke(FocusBinding.kt:81)
  at fleet.noria.cells/noria.impl.Closure.invoke(Closure.kt:36)
  at fleet.noria.ui/noria.ui.core.FocusKt$withFocusNode$3.invoke(Focus.kt:82)
  at fleet.noria.ui/noria.ui.core.FocusKt$withFocusNode$3.invoke(Focus.kt:82)
  at fleet.noria.cells/noria.impl.Closure.invoke(Closure.kt:36)
  at fleet.noria.cells/noria.NoriaContextKt.withBindingsImpl(NoriaContext.kt:157)
  at fleet.noria.cells/androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:249)
  at fleet.noria.ui/noria.ui.core.FocusKt.withFocusNode(Focus.kt:82)
  at fleet.noria.ui/androidx.compose.ui.focus.OnFocusChangedModifier$wrap$1.invoke(FocusChangedModifier.kt:73)
  at fleet.noria.ui/androidx.compose.ui.focus.OnFocusChangedModifier$wrap$1.invoke(FocusChangedM…

### Code snippet for reproduce

N/A

### Your Environment

Fleet version: build 1.37.84
OS: Mac OS X (14.5, aarch64)

**Comment by izhangzhihao** [comment]
An update is one the way

**Comment by izhangzhihao** [comment]
Java highlighter stop working in the latest Fleet version, I created a ticket for JetBrains: https://youtrack.jetbrains.com/issue/FL-27534/SimpleNodeHighlighter-does-not-work-since-fleet-1.37

**Comment by izhangzhihao** [comment]
Latest release resolved this issue.
