### ISSUE TITLE
JSONException: JSONObject["text-attributes"] not found

### ISSUE THREAD

**Issue by weirdo-adam** [izhangzhihao/intellij-rainbow-brackets#2752]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Your programming languages

java

### Free or paid?

None

### Expected Behavior

不支持fleet最新版本

### Current Behavior

不生产

### Code snippet for reproduce

Exception in DefaultDispatcher-worker-26
org.json.JSONException: JSONObject["text-attributes"] not found.
at org.json@20240205/org.json.JSONObject.get(JSONObject.java:595)
  at org.json@20240205/org.json.JSONObject.getJSONObject(JSONObject.java:805)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin.appendColorSchemaIfNotExists(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin.initColorSchema(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin.access$initColorSchema(Unknown Source)
  at com.github.izhang

### Your Environment

fleet 1.37.84

**Comment by weirdo-adam** [comment]
"rainbow.brackets.version": "0.3.2"

**Comment by izhangzhihao** [comment]
- [ ] is your ~/.fleet/themes dir readable? or writeable?
- [ ] can you try delete your ~/.fleet/themes dir and copy a new theme?

duplicated with https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2735

**Comment by weirdo-adam** [comment]
~/.fleet/themes 权限是755
fleet尝试卸载，重新安装插件依旧不生效

**Comment by izhangzhihao** [comment]
pls do `rm -rf ~/.fleet/themes` and re-copy existing themes again.

**Comment by weirdo-adam** [comment]
还是报错
Exception in DefaultDispatcher-worker-15
org.json.JSONException: JSONObject["text-attributes"] not found.
at org.json@20240205/org.json.JSONObject.get(JSONObject.java:595)
  at org.json@20240205/org.json.JSONObject.getJSONObject(JSONObject.java:805)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin.appendColorSchemaIfNotExists(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin.initColorSchema(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin.access$initColorSchema(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin$load$1.invokeSuspend(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin$load$1.invoke(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin$load$1.invoke(Unknown Source)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1$1.invokeSuspend(Worker.kt:46)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1$1.invoke(Worker.kt)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1$1.invoke(Worker.kt)
  at fleet.kotlin.runtime/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope(Tracing.kt:61)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope(Tracing.kt:56)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope$default(Tracing.kt:55)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1.invokeSuspend(Worker.kt:45)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1.invoke(Worker.kt)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1.invoke(Worker.kt)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invokeSuspend(Durable.kt:20)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invoke(Durable.kt)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invoke(Durable.kt)
  at fleet.kotlin.runtime/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
  at fleet.kotlin.runtime/kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
  at fleet.rpc/fleet.rpc.client.DurableKt.durable(Durable.kt:20)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1.invokeSuspend(Worker.kt:44)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1.invoke(Worker.kt)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1.invoke(Worker.kt)
  at fleet.kernel/fleet.kernel.TrackedQueryKt$launchOnEachEntity$3$1.invokeSuspend(TrackedQuery.kt:33)
  at fleet.kernel/fleet.kernel.TrackedQueryKt$launchOnEachEntity$3$1.invoke(TrackedQuery.kt)
  at fleet.kernel/fleet.kernel.TrackedQueryKt$launchOnEachEntity$3$1.invoke(TrackedQuery.kt)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invokeSuspend(Durable.kt:20)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invoke(Durable.kt)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invoke(Durable.kt)
  at fleet.kotlin.runtime/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
  at fleet.kotlin.runtime/kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
  at fleet.rpc/fleet.rpc.client.DurableKt.durable(Durable.kt:20)
 …

**Comment by weirdo-adam** [comment]
-rw-r--r-- 38K Jul 17 16:21 dark-edited.json

**Comment by izhangzhihao** [comment]
An update is on the way, pls upgrade to the latest version(0.3.3） and recreate the themes file
