### ISSUE TITLE
[Fleet] org.json.JSONException: JSONObject["textAttributes"] not found.

### ISSUE THREAD

**Issue by DmitryTronin** [izhangzhihao/intellij-rainbow-brackets#2755]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Have you checked the internal mode turns on?

Yes

### Your programming languages

json

### Expected Behavior

no exceptions

### Current Behavior

The following exception is reported by Fleet users:

```
org.json.JSONException: JSONObject["textAttributes"] not found.
  at org.json@20240205/org.json.JSONObject.get(JSONObject.java:595)
  at org.json@20240205/org.json.JSONObject.getJSONObject(JSONObject.java:805)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin.appendColorSchemaIfNotExists(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin.initColorSchema(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin.access$initColorSchema(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin$load$1.invokeSuspend(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin$load$1.invoke(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin$load$1.invoke(Unknown Source)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1$1.invokeSuspend(Worker.kt:46)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1$1.invoke(Worker.kt)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1$1.invoke(Worker.kt)
  at fleet.kotlin.runtime/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope(Tracing.kt:61)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope(Tracing.kt:56)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope$default(Tracing.kt:55)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1.invokeSuspend(Worker.kt:45)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1.invoke(Worker.kt)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1$1.invoke(Worker.kt)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invokeSuspend(Durable.kt:20)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invoke(Durable.kt)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invoke(Durable.kt)
  at fleet.kotlin.runtime/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
  at fleet.kotlin.runtime/kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
  at fleet.rpc/fleet.rpc.client.DurableKt.durable(Durable.kt:20)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1.invokeSuspend(Worker.kt:44)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1.invoke(Worker.kt)
  at fleet.kernel.plugins/fleet.kernel.plugins.WorkerKt$withWorkers$2$1$1.invoke(Worker.kt)
  at fleet.kernel/fleet.kernel.TrackedQueryKt$launchOnEachEntity$3$1.invokeSuspend(TrackedQuery.kt:33)
  at fleet.kernel/fleet.kernel.TrackedQueryKt$launchOnEachEntity$3$1.invoke(TrackedQuery.kt)
  at fleet.kernel/fleet.kernel.TrackedQueryKt$launchOnEachEntity$3$1.invoke(TrackedQuery.kt)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invokeSuspend(Durable.kt:20)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invoke(Durable.kt)
  at fleet.rpc/fleet.rpc.client.DurableKt$durable$2.invoke(Durable.kt)
  at fleet.kotlin.runtime/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
  at fleet.kotlin.runtime/kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
  at fleet.rpc/fleet.rpc.client.DurableKt.durable(Durable.kt:20)
  at fleet.kernel/fleet.kernel.TrackedQueryKt$launchOnEachEntity$3.invokeSuspend(TrackedQuery.kt:33)
  at fleet.kernel/fleet.kernel.TrackedQueryKt$launchOnEachEntity$3.invoke(TrackedQuery.kt)
  at fleet.kernel/fleet.kernel.TrackedQueryKt$launchOnEachEntity$3.invoke(TrackedQuery.kt)
  at fleet.kernel/fleet.kernel.rete.ReteKt$withMatch$2$1.invokeSuspend(Rete.kt:107)
  at fleet.kernel/fleet.kernel.rete.ReteKt$withMatch$2$1.invoke(Rete.kt)
  at fleet.kernel/fleet.kernel.rete.ReteKt$withMatch$2$1.invoke(Rete.kt)
  at fleet.kernel/fleet.kernel.rete.ObservableMatchKt$withObservableMatches$3$1$def$1.invokeSuspend(ObservableMatch.kt:40)
  at fleet.kernel/fleet.kernel.rete.ObservableMatchKt$withObservableMatches$3$1$def$1.invoke(ObservableMatch.kt)
  at fleet.kernel/fleet.kernel.rete.ObservableMatchKt$withObservableMatches$3$1$def$1.invoke(ObservableMatch.kt)
  at fleet.kotlin.runtime/kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:27)
  at fleet.kotlin.runtime/kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:90)
  at fleet.kotlin.runtime/kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt__Builders_commonKt.async(Builders.common.kt:87)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt.async(Unknown Source)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default(Builders.common.kt:78)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt.async$default(Unknown Source)
  at fleet.kernel/fleet.kernel.rete.ObservableMatchKt$withObservableMatches$3$1.invokeSuspend(ObservableMatch.kt:37)
  at fleet.kernel/fleet.kernel.rete.ObservableMatchKt$withObservableMatches$3$1.invoke(ObservableMatch.kt)
  at fleet.kernel/fleet.kernel.rete.ObservableMatchKt$withObservableMatches$3$1.invoke(ObservableMatch.kt)
  at fleet.kotlin.runtime/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
  at fleet.kernel/fleet.kernel.rete.ObservableMatchKt$withObservableMatches$3.invokeSuspend(ObservableMatch.kt:36)
  at fleet.kernel/fleet.kernel.rete.ObservableMatchKt$withObservableMatches$3.invoke(ObservableMatch.kt)
  at fleet.kernel/fleet.kernel.rete.ObservableMatchKt$withObservableMatches$3.invoke(ObservableMatch.kt)
  at fleet.kernel/fleet.kernel.rete.ReteKt$withReteDbSource$3$1.invokeSuspend(Rete.kt:232)
  at fleet.kernel/fleet.kernel.rete.ReteKt$withReteDbSource$3$1.invoke(Rete.kt)
  at fleet.kernel/fleet.kernel.rete.ReteKt$withReteDbSource$3$1.invoke(Rete.kt)
  at fleet.kotlin.runtime/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
  at fleet.kernel/fleet.kernel.rete.ReteKt.withReteDbSource(Rete.kt:231)
  at fleet.kernel/fleet.kernel.rete.ObservableMatchKt.withObservableMatches(ObservableMatch.kt:35)
  at fleet.kernel/fleet.kernel.rete.ReteKt.withMatch(Rete.kt:107)
  at fleet.kernel/fleet.kernel.rete.ReteKt$launchOnEach$2$1$2$1.invokeSuspend(Rete.kt:259)
  at fleet.kotlin.runtime/kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at fleet.kotlin.runtime/kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
  at fleet.kotlin.runtime/kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
  at fleet.kotlin.runtime/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
  at fleet.kotlin.runtime/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
  at fleet.kotlin.runtime/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
```

### Code snippet for reproduce

none

### Your Environment

Builds: 1.37.15 to 1.39.33
any OS

**Comment by izhangzhihao** [comment]
Duplicate with #2752


pls do `rm -rf ~/.fleet/themes` and re-copy existing themes again.
