### ISSUE TITLE
[lite version] Class initialization must not depend on services

### ISSUE THREAD

**Issue by DavidAntliff** [izhangzhihao/intellij-rainbow-brackets#2758]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Rust

### Free or paid?

Free users

### Expected Behavior

RustRover should start normally. I wasn't expecting an IDE Internal Error to occur.

### Current Behavior

RustRover reports:

```
java.lang.Throwable: com.github.izhangzhihao.rainbow.brackets.lite.BracePairs <clinit> requests com.intellij.codeInsight.highlighting.FileTypeBraceMatcher instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1577)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1546)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:746)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
	at com.intellij.codeInsight.highlighting.FileTypeBraceMatcher.getInstance(FileTypeBraceMatcher.java:11)
	at com.intellij.codeInsight.highlighting.BraceMatchingUtil.getBraceMatcherByFileType(BraceMatchingUtil.java:470)
	at com.intellij.codeInsight.highlighting.BraceMatchingUtil.getBraceMatcher(BraceMatchingUtil.java:444)
	at com.github.izhangzhihao.rainbow.brackets.lite.BracePairs.<clinit>(BracePairs.kt:24)
	at com.github.izhangzhihao.rainbow.brackets.lite.visitor.DefaultRainbowVisitor$Companion.filterPairs(DefaultRainbowVisitor.kt:179)
	at com.github.izhangzhihao.rainbow.brackets.lite.visitor.DefaultRainbowVisitor$Companion.access$filterPairs(DefaultRainbowVisitor.kt:41)
	at com.github.izhangzhihao.rainbow.brackets.lite.visitor.DefaultRainbowVisitor.visit(DefaultRainbowVisitor.kt:20)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.runVisitor(HighlightVisitorRunner.java:194)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.lambda$runVisitors$3(HighlightVisitorRunner.java:122)
	at com.github.izhangzhihao.rainbow.brackets.lite.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:34)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.lambda$runVisitors$4(HighlightVisitorRunner.java:120)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:139)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:108)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:86)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:179)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:759)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

### Code snippet for reproduce

N/A

### Your Environment

RustRover 2024.2 EAP
Build #RR-242.19890.43, built on July 20, 2024
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.5.0-45-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  debugger.new.tool.window.layout=true
  debugger.attach.dialog.enabled=true
  run.processes.with.pty=true
  ide.experimental.ui=true
  llm.ai.assistant.toolwindow.activation.on.start=false
  terminal.new.ui=false
  org.toml.json.schema=false
  terminal.new.ui.show.promotion=false
  transferSettings.vscode.onlyCargoToml=true
Non-Bundled Plugins:
  de.markiewb.idea.externalrunconfiguration (1.2)
  PythonCore (242.19890.14)
  izhangzhihao.rainbow.brackets.lite (1.1.0)
  com.thvardhan.gradianto (5.5)
  com.intellij.ml.llm (242.19890.39)
  org.exbin.deltahex.intellij (0.2.10.1)
Current Desktop: i3

**Comment by izhangzhihao** [comment]
A new version is now available in the marketplace.

**Comment by DavidAntliff** [comment]
Thank you, seems to have resolved it.
