### ISSUE TITLE
Error reported in idea version 2024.2

### ISSUE THREAD

**Issue by buaazyl** [izhangzhihao/intellij-rainbow-brackets#2765]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Java Python

### Free or paid?

Free users

### Expected Behavior

It runs normally and no errors are reported.

### Current Behavior

java.lang.Throwable: com.github.izhangzhihao.rainbow.brackets.lite.BracePairs <clinit> requests com.intellij.codeInsight.highlighting.FileTypeBraceMatcher instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1588)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1557)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:746)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
	at com.intellij.codeInsight.highlighting.FileTypeBraceMatcher.getInstance(FileTypeBraceMatcher.java:11)
	at com.intellij.codeInsight.highlighting.BraceMatchingUtil.getBraceMatcherByFileType(BraceMatchingUtil.java:470)
	at com.intellij.codeInsight.highlighting.BraceMatchingUtil.getBraceMatcher(BraceMatchingUtil.java:444)
	at com.github.izhangzhihao.rainbow.brackets.lite.BracePairs.<clinit>(BracePairs.kt:24)
	at com.github.izhangzhihao.rainbow.brackets.lite.visitor.DefaultRainbowVisitor$Companion.filterPairs(DefaultRainbowVisitor.kt:179)
	at com.github.izhangzhihao.rainbow.brackets.lite.visitor.DefaultRainbowVisitor$Companion.access$filterPairs(DefaultRainbowVisitor.kt:41)
	at com.github.izhangzhihao.rainbow.brackets.lite.visitor.DefaultRainbowVisitor.visit(DefaultRainbowVisitor.kt:20)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.runVisitor(HighlightVisitorRunner.java:194)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.lambda$runVisitors$3(HighlightVisitorRunner.java:122)
	at com.github.izhangzhihao.rainbow.brackets.lite.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:34)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.lambda$runVisitors$4(HighlightVisitorRunner.java:120)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:139)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:279)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:108)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:86)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:179)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:66)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:52)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.runVisitors(HighlightVisitorRunner.java:112)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$runAnnotatorsAndVisitorsOnInjectedPsi$10(InjectedGeneralHighlightingPass.java:203)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.createHighlightVisitorsFor(HighlightVisitorRunner.java:84)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$runAnnotatorsAndVisitorsOnInjectedPsi$11(InjectedGeneralHighlightingPass.java:201)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotatorsAsync$2(AnnotatorRunner.java:76)
	at com.intellij.concurrency.JobLauncherImpl.procInOrderAsync(JobLauncherImpl.java:539)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.runAnnotatorsAsync(AnnotatorRunner.java:67)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$runAnnotatorsAndVisitorsOnInjectedPsi$12(InjectedGeneralHighlightingPass.java:222)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:97)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideAllRoots(Divider.java:63)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.runAnnotatorsAndVisitorsOnInjectedPsi(InjectedGeneralHighlightingPass.java:195)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$collectInformationWithProgress$3(InjectedGeneralHighlightingPass.java:92)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$processInjectedPsiFiles$5(InjectedGeneralHighlightingPass.java:160)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.probeElementsUpInner(InjectedLanguageUtilBase.java:251)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.lambda$probeElementsUp$0(InjectedLanguageUtilBase.java:217)
	at com.intellij.openapi.application.impl.ReadActionCacheImpl$allowInWriteAction$1.invoke(ReadActionCacheImpl.kt:41)
	at com.intellij.openapi.application.impl.ReadActionCacheImpl$allowInWriteAction$1.invoke(ReadActionCacheImpl.kt:41)
	at com.intellij.openapi.application.impl.ReadActionCacheImpl.allowInWriteAction(ReadActionCacheImpl.kt:29)
	at com.intellij.openapi.application.impl.ReadActionCacheImpl.allowInWriteAction(ReadActionCacheImpl.kt:41)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.probeElementsUp(InjectedLanguageUtilBase.java:216)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.enumerate(InjectedLanguageUtilBase.java:159)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.enumerateEx(InjectedLanguageManagerImpl.java:379)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$processInjectedPsiFiles$6(InjectedGeneralHighlightingPass.java:158)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:139)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:152)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:152)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:152)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:108)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:86)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:179)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:759)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
<img width="824" alt="iShot_2024-08-16_08 42 23" src="https://github.com/user-attachments/assets/8f03a51c-3524-4de4-930a-b4c2e75b300d">

### Code snippet for reproduce

Not code-specific.

### Your Environment

IntelliJ IDEA 2024.2 (Ultimate Edition)
Build #IU-242.20224.300, built on August 7, 2024
Licensed to yulai zhang
Subscription is active until April 28, 2025.
Runtime version: 21.0.3+13-b509.4 x86_64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  de.netnexus.camelcaseplugin (3.0.12)
  com.biyusheng.plugins (1.3.3)
  Key Promoter X (2024.2.0)
  SequenceDiagram (4.0.2)
  MavenRunHelper (4.28.0-IJ2022.2)
  izhangzhihao.rainbow.brackets.lite (1.1.0)
  zielu.gittoolbox (500.2.14+242)
  io.github.godfather1103.alibaba.p3c (1.7-2024.2-2.1.1-ext-6)
  com.baomidou.plugin.idea.mybatisx (1.6.3)
  cn.yiiguxing.plugin.translate (3.6.4)
Kotlin: 242.20224.300-IJ

**Comment by izhangzhihao** [comment]
duplicated with #2758
