### ISSUE TITLE
NSME: RainbowBracketsPlugin.load for Fleet plugin

### ISSUE THREAD

**Issue by OljaKli** [izhangzhihao/intellij-rainbow-brackets#2796]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Are you using JetBrains Client / Code With Me / IntelliJ Remote Development?

No

### Your programming languages

-

### Free or paid?

None

### Expected Behavior

No exception

### Current Behavior

```
java.lang.RuntimeException: The message has been stripped due to GDPR
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPluginLayer$2$2$1$1$1$1.invoke(PluginLoading.kt:196)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPluginLayer$2$2$1$1$1$1.invoke(PluginLoading.kt:183)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$PluginScope$2$1$contribute$1$1$1.invoke(PluginLoading.kt:219)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$PluginScope$2$1$contribute$1$1$1.invoke(PluginLoading.kt:216)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt.withPluginLayer(PluginLoading.kt:261)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt.access$withPluginLayer(PluginLoading.kt:1)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$PluginScope$2$1.contribute(PluginLoading.kt:216)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPluginLayer$2$2$1.invoke(PluginLoading.kt:183)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPluginLayer$2$2$1.invoke(PluginLoading.kt:167)
  at fleet.kernel/fleet.kernel.TransactorMiddleware$Identity.performChange(TransactorMiddleware.kt:12)
  at fleet.kernel/fleet.kernel.TransactorMiddleware$plus$1.performChange$lambda$2$lambda$1(TransactorMiddleware.kt:23)
  at fleet.kernel/fleet.kernel.TransactorViewKt$kernelViewMiddleware$1.performChange$lambda$4$lambda$0(TransactorView.kt:237)
  at fleet.kernel/fleet.kernel.TransactorViewKt.withTransactorView(TransactorView.kt:217)
  at fleet.kernel/fleet.kernel.TransactorViewKt.access$withTransactorView(TransactorView.kt:1)
  at fleet.kernel/fleet.kernel.TransactorViewKt$kernelViewMiddleware$1.performChange(TransactorView.kt:236)
  at fleet.kernel/fleet.kernel.TransactorMiddleware$plus$1.performChange(TransactorMiddleware.kt:23)
  at fleet.kernel/fleet.kernel.TransactorMiddleware$plus$1.performChange$lambda$2$lambda$1(TransactorMiddleware.kt:23)
  at fleet.kernel/fleet.kernel.rebase.LeaderTransactorMiddleware.performChange(LeaderTransactorMiddleware.kt:51)
  at fleet.kernel/fleet.kernel.TransactorMiddleware$plus$1.performChange(TransactorMiddleware.kt:23)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPluginLayer$2.invoke(PluginLoading.kt:167)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPluginLayer$2.invoke(PluginLoading.kt:140)
  at fleet.reporting.api/fleet.tracing.TracingKt.withCurrentSpan(Tracing.kt:36)
  at fleet.reporting.api/fleet.tracing.TracingKt.span(Tracing.kt:48)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt.loadPluginLayer(PluginLoading.kt:140)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt.pluginTransaction(PluginLoading.kt:514)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt.access$pluginTransaction(PluginLoading.kt:1)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3$5$1.invoke(PluginLoading.kt:614)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3$5$1.invoke(PluginLoading.kt:613)
  at fleet.kernel/fleet.kernel.HackyNonBlockingChangeKt$hackyNonBlockingChange$2.invokeSuspend$lambda$6$lambda$5$lambda$4$lambda$3$lambda$2(HackyNonBlockingChange.kt:21)
  at fleet.kernel/fleet.kernel.rebase.LeaderTransactorMiddleware.performChange(LeaderTransactorMiddleware.kt:51)
  at fleet.kernel/fleet.kernel.HackyNonBlockingChangeKt$hackyNonBlockingChange$2.invokeSuspend$lambda$6$lambda$5$lambda$4(HackyNonBlockingChange.kt:18)
  at fleet.rhizomedb/com.jetbrains.rhizomedb.ChangeKt.change$lambda$4$lambda$3$lambda$2(Change.kt:43)
  at fleet.rhizomedb/com.jetbrains.rhizomedb.ChangeScopeKt.withChangeScope(ChangeScope.kt:21)
  at fleet.rhizomedb/com.jetbrains.rhizomedb.ChangeKt.change$lambda$4$lambda$3(Change.kt:41)
  at fleet.rhizomedb/com.jetbrains.rhizomedb.DbContextKt.asOf(DbContext.kt:111)
  at fleet.rhizomedb/com.jetbrains.rhizomedb.ChangeKt.change(Change.kt:40)
  at fleet.kernel/fleet.kernel.HackyNonBlockingChangeKt$hackyNonBlockingChange$2.invokeSuspend$lambda$6(HackyNonBlockingChange.kt:16)
  at fleet.reporting.api/fleet.tracing.TracingKt.withCurrentSpan(Tracing.kt:36)
  at fleet.reporting.api/fleet.tracing.TracingKt.span(Tracing.kt:48)
  at fleet.reporting.api/fleet.tracing.TracingKt.span$default(Tracing.kt:43)
  at fleet.kernel/fleet.kernel.HackyNonBlockingChangeKt$hackyNonBlockingChange$2.invokeSuspend(HackyNonBlockingChange.kt:14)
  at fleet.kernel/fleet.kernel.HackyNonBlockingChangeKt$hackyNonBlockingChange$2.invoke(HackyNonBlockingChange.kt)
  at fleet.kernel/fleet.kernel.HackyNonBlockingChangeKt$hackyNonBlockingChange$2.invoke(HackyNonBlockingChange.kt)
  at fleet.kotlin.runtime/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope(Tracing.kt:62)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope(Tracing.kt:57)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope$default(Tracing.kt:56)
  at fleet.kernel/fleet.kernel.HackyNonBlockingChangeKt.hackyNonBlockingChange(HackyNonBlockingChange.kt:9)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3$5.invokeSuspend(PluginLoading.kt:613)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3$5.invoke(PluginLoading.kt)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3$5.invoke(PluginLoading.kt)
  at fleet.util.core/fleet.util.async.CoroutineUtilsKt$catching$2.invokeSuspend(CoroutineUtils.kt:33)
  at fleet.util.core/fleet.util.async.CoroutineUtilsKt$catching$2.invoke(CoroutineUtils.kt)
  at fleet.util.core/fleet.util.async.CoroutineUtilsKt$catching$2.invoke(CoroutineUtils.kt)
  at fleet.kotlin.runtime/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
  at fleet.kotlin.runtime/kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
  at fleet.util.core/fleet.util.async.CoroutineUtilsKt.catching(CoroutineUtils.kt:33)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3.invokeSuspend(PluginLoading.kt:575)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3.invoke(PluginLoading.kt)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3.invoke(PluginLoading.kt)
  at fleet.kotlin.runtime/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope(Tracing.kt:62)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope(Tracing.kt:57)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt.loadPlugin(PluginLoading.kt:537)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt.access$loadPlugin(PluginLoading.kt:1)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$applyResolvedPluginsConfig$3$2$1$2$1.invokeSuspend(PluginLoading.kt:470)
  at fleet.kotlin.runtime/kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at fleet.kotlin.runtime/kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
  at fleet.kotlin.runtime/kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
  at fleet.kotlin.runtime/kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
  at fleet.kotlin.runtime/kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
  at fleet.kotlin.runtime/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
  at fleet.kotlin.runtime/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
  at fleet.kotlin.runtime/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
  Caused by: java.lang.NoSuchMethodError: The message has been stripped due to GDPR  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin.load(Unknown Source)
  at com.github.izhangzhihao.rainbow.brackets.frontendImpl/com.github.izhangzhihao.rainbow.brackets.frontendImpl.RainbowBracketsPlugin.load(Unknown Source)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPluginLayer$2$2$1$1$1$1$2.invoke(PluginLoading.kt:186)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPluginLayer$2$2$1$1$1$1$2.invoke(PluginLoading.kt:185)
  at fleet.reporting.api/fleet.tracing.TracingKt.withCurrentSpan(Tracing.kt:36)
  at fleet.reporting.api/fleet.tracing.TracingKt.span(Tracing.kt:48)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPluginLayer$2$2$1$1$1$1.invoke(PluginLoading.kt:185)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPluginLayer$2$2$1$1$1$1.invoke(PluginLoading.kt:183)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$PluginScope$2$1$contribute$1$1$1.invoke(PluginLoading.kt:219)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$PluginScope$2$1$contribute$1$1$1.invoke(PluginLoading.kt:216)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt.withPluginLayer(PluginLoading.kt:261)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt.access$withPluginLayer(PluginLoading.kt:1)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$PluginScope$2$1.contribute(PluginLoading.kt:216)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPluginLayer$2$2$1.invoke(PluginLoading.kt:183)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPluginLayer$2$2$1.invoke(PluginLoading.kt:167)
  at fleet.kernel/fleet.kernel.TransactorMiddleware$Identity.performChange(TransactorMiddleware.kt:12)
  at fleet.kernel/fleet.kernel.TransactorMiddleware$plus$1.performChange$lambda$2$lambda$1(TransactorMiddleware.kt:23)
  at fleet.kernel/fleet.kernel.TransactorViewKt$kernelViewMiddleware$1.performChange$lambda$4$lambda$0(TransactorView.kt:237)
  at fleet.kernel/fleet.kernel.TransactorViewKt.withTransactorView(TransactorView.kt:217)
  at fleet.kernel/fleet.kernel.TransactorViewKt.access$withTransactorView(TransactorView.kt:1)
  at fleet.kernel/fleet.kernel.TransactorViewKt$kernelViewMiddleware$1.performChange(TransactorView.kt:236)
  at fleet.kernel/fleet.kernel.TransactorMiddleware$plus$1.performChange(TransactorMiddleware.kt:23)
  at fleet.kernel/fleet.kernel.TransactorMiddleware$plus$1.performChange$lambda$2$lambda$1(TransactorMiddleware.kt:23)
  at fleet.kernel/fleet.kernel.rebase.LeaderTransactorMiddleware.performChange(LeaderTransactorMiddleware.kt:51)
  at fleet.kernel/fleet.kernel.TransactorMiddleware$plus$1.performChange(TransactorMiddleware.kt:23)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPluginLayer$2.invoke(PluginLoading.kt:167)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPluginLayer$2.invoke(PluginLoading.kt:140)
  at fleet.reporting.api/fleet.tracing.TracingKt.withCurrentSpan(Tracing.kt:36)
  at fleet.reporting.api/fleet.tracing.TracingKt.span(Tracing.kt:48)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt.loadPluginLayer(PluginLoading.kt:140)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt.pluginTransaction(PluginLoading.kt:514)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt.access$pluginTransaction(PluginLoading.kt:1)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3$5$1.invoke(PluginLoading.kt:614)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3$5$1.invoke(PluginLoading.kt:613)
  at fleet.kernel/fleet.kernel.HackyNonBlockingChangeKt$hackyNonBlockingChange$2.invokeSuspend$lambda$6$lambda$5$lambda$4$lambda$3$lambda$2(HackyNonBlockingChange.kt:21)
  at fleet.kernel/fleet.kernel.rebase.LeaderTransactorMiddleware.performChange(LeaderTransactorMiddleware.kt:51)
  at fleet.kernel/fleet.kernel.HackyNonBlockingChangeKt$hackyNonBlockingChange$2.invokeSuspend$lambda$6$lambda$5$lambda$4(HackyNonBlockingChange.kt:18)
  at fleet.rhizomedb/com.jetbrains.rhizomedb.ChangeKt.change$lambda$4$lambda$3$lambda$2(Change.kt:43)
  at fleet.rhizomedb/com.jetbrains.rhizomedb.ChangeScopeKt.withChangeScope(ChangeScope.kt:21)
  at fleet.rhizomedb/com.jetbrains.rhizomedb.ChangeKt.change$lambda$4$lambda$3(Change.kt:41)
  at fleet.rhizomedb/com.jetbrains.rhizomedb.DbContextKt.asOf(DbContext.kt:111)
  at fleet.rhizomedb/com.jetbrains.rhizomedb.ChangeKt.change(Change.kt:40)
  at fleet.kernel/fleet.kernel.HackyNonBlockingChangeKt$hackyNonBlockingChange$2.invokeSuspend$lambda$6(HackyNonBlockingChange.kt:16)
  at fleet.reporting.api/fleet.tracing.TracingKt.withCurrentSpan(Tracing.kt:36)
  at fleet.reporting.api/fleet.tracing.TracingKt.span(Tracing.kt:48)
  at fleet.reporting.api/fleet.tracing.TracingKt.span$default(Tracing.kt:43)
  at fleet.kernel/fleet.kernel.HackyNonBlockingChangeKt$hackyNonBlockingChange$2.invokeSuspend(HackyNonBlockingChange.kt:14)
  at fleet.kernel/fleet.kernel.HackyNonBlockingChangeKt$hackyNonBlockingChange$2.invoke(HackyNonBlockingChange.kt)
  at fleet.kernel/fleet.kernel.HackyNonBlockingChangeKt$hackyNonBlockingChange$2.invoke(HackyNonBlockingChange.kt)
  at fleet.kotlin.runtime/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope(Tracing.kt:62)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope(Tracing.kt:57)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope$default(Tracing.kt:56)
  at fleet.kernel/fleet.kernel.HackyNonBlockingChangeKt.hackyNonBlockingChange(HackyNonBlockingChange.kt:9)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3$5.invokeSuspend(PluginLoading.kt:613)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3$5.invoke(PluginLoading.kt)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3$5.invoke(PluginLoading.kt)
  at fleet.util.core/fleet.util.async.CoroutineUtilsKt$catching$2.invokeSuspend(CoroutineUtils.kt:33)
  at fleet.util.core/fleet.util.async.CoroutineUtilsKt$catching$2.invoke(CoroutineUtils.kt)
  at fleet.util.core/fleet.util.async.CoroutineUtilsKt$catching$2.invoke(CoroutineUtils.kt)
  at fleet.kotlin.runtime/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
  at fleet.kotlin.runtime/kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
  at fleet.util.core/fleet.util.async.CoroutineUtilsKt.catching(CoroutineUtils.kt:33)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3.invokeSuspend(PluginLoading.kt:575)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3.invoke(PluginLoading.kt)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$loadPlugin$3.invoke(PluginLoading.kt)
  at fleet.kotlin.runtime/kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
  at fleet.kotlin.runtime/kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope(Tracing.kt:62)
  at fleet.reporting.api/fleet.tracing.TracingKt.spannedScope(Tracing.kt:57)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt.loadPlugin(PluginLoading.kt:537)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt.access$loadPlugin(PluginLoading.kt:1)
  at fleet.kernel.plugins/fleet.kernel.plugins.PluginLoadingKt$applyResolvedPluginsConfig$3$2$1$2$1.invokeSuspend(PluginLoading.kt:470)
  at fleet.kotlin.runtime/kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at fleet.kotlin.runtime/kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
  at fleet.kotlin.runtime/kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
  at fleet.kotlin.runtime/kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
  at fleet.kotlin.runtime/kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
  at fleet.kotlin.runtime/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
  at fleet.kotlin.runtime/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
  at fleet.kotlin.runtime/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
```

### Code snippet for reproduce

```shell
Original issue: https://youtrack.jetbrains.com/issue/FL-31105/NSME-RainbowBracketsPlugin.load
```

### Your Environment

```shell
MacOS
Fleet versions:
Since: 1.42.2
Until: 1.44.35
```

**Comment by izhangzhihao** [comment]
The link seems private: https://youtrack.jetbrains.com/issue/FL-31105/NSME-RainbowBracketsPlugin.load

And I still don't know how to reproduce your issue

**Comment by izhangzhihao** [comment]
Closed because no update. If you have more information to provide, pls leave a comment.
