### ISSUE TITLE
[Auto Generated Report]java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#321]
- Plugin Name: Material Theme UI
- Plugin Version: 5.26
- OS Name: Linux
- OS Version: 5.3.0-19-generic
- Java Version: 11.0.4
- App Name: RubyMine
- App Full Name: RubyMine
- Is Snapshot: false
- App Build: RM-192.6817.16
- Last Action: null

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.remove(ArrayList.java:535)
	at org.yaml.snakeyaml.scanner.ScannerImpl.getToken(ScannerImpl.java:260)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseStreamStart.produce(ParserImpl.java:184)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:104)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:453)
	at org.jetbrains.plugins.ruby.ruby.RubyUtil.loadYaml(RubyUtil.java:68)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.YamlDynamicExtensionsLoader.a(YamlDynamicExtensionsLoader.java:265)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.YamlDynamicExtensionsLoader.c(YamlDynamicExtensionsLoader.java:64)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.YamlDynamicExtensionsLoader.b(YamlDynamicExtensionsLoader.java:49)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:908)
	at com.intellij.util.containers.JBIterable.processEach(JBIterable.java:219)
	at com.intellij.openapi.util.io.FileUtil.processFilesRecursively(FileUtil.java:1073)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.YamlDynamicExtensionsLoader.a(YamlDynamicExtensionsLoader.java:45)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.YamlDynamicExtensionsLoader.<init>(YamlDynamicExtensionsLoader.java:37)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:88)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.createAndInitialize(ServiceManagerImpl.java:243)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.lambda$getComponentInstance$0(ServiceManagerImpl.java:232)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:197)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:231)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:75)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:44)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.YamlDynamicExtensionsLoader.getInstance(YamlDynamicExtensionsLoader.java:60)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.RubyDynamicExtensionsProvider.a(RubyDynamicExtensionsProvider.java:216)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.RubyDynamicExtensionsProvider.createTypeBySymbol(RubyDynamicExtensionsProvider.java:55)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.types.RubyTypeProvider.createTypeBySymbolFromProviders(RubyTypeProvider.java:51)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.types.impl.RSymbolTypeImpl.create(RSymbolTypeImpl.java:129)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.types.RTypeFactory.createTypeBySymbol(RTypeFactory.java:102)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.symbols.structure.SymbolUtil.lookupSymbolInHierarchy(SymbolUtil.java:347)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.symbols.structure.SymbolUtil.lookupMethod(SymbolUtil.java:283)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RPsiPolyVariantReferenceBase.resolveToSymbol(RPsiPolyVariantReferenceBase.java:158)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RPsiPolyVariantReferenceBase.resolveToSymbol(RPsiPolyVariantReferenceBase.java:133)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RIdentifierReference.resolveToSymbol(RIdentifierReference.java:51)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RPsiPolyVariantReferenceBase.multiResolveInner(RPsiPolyVariantReferenceBase.java:77)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RubyPolyVariantReferenceBase$MyResolver.resolve(RubyPolyVariantReferenceBase.java:121)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RubyPolyVariantReferenceBase$MyResolver.resolve(RubyPolyVariantReferenceBase.java:117)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:149)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:179)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:171)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RubyPolyVariantReferenceBase.multiResolve(RubyPolyVariantReferenceBase.java:63)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.resolve.ResolveUtil.resolveToSymbolWithCaching(ResolveUtil.java:170)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.paramDefs.matcher.ParamDefMatcher.match(ParamDefMatcher.java:81)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.paramDefs.matcher.ParamDefMatcher.match(ParamDefMatcher.java:37)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.paramDefs.matcher.ParamDefMatcher.createParamDefReference(ParamDefMatcher.java:120)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.ruby19.impl.RAssocKeyImpl.getReferenceEx(RAssocKeyImpl.java:48)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.ruby19.impl.RAssocKeyImpl.a(RAssocKeyImpl.java:42)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.ruby19.impl.RAssocKeyImpl.getReference(RAssocKeyImpl.java:42)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.getReferences(SharedPsiElementImplUtil.java:77)
	at com.intellij.psi.impl.PsiElementBase.getReferences(PsiElementBase.java:82)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:28)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:121)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:284)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:32)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:32)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:598)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:70)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:281)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: null
- Plugin Version: 5.26
- OS Name: Mac OS X
- OS Version: 10.15.1
- Java Version: 11.0.4
- App Name: RubyMine
- App Full Name: RubyMine
- Is Snapshot: false
- App Build: RM-192.7142.37
- Last Action: null

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.symbolicExecution.instance.TypeInferenceInstance.a(TypeInferenceInstance.java:348)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.symbolicExecution.instance.TypeInferenceInstance.a(TypeInferenceInstance.java:214)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.symbolicExecution.instance.TypeInferenceInstance.fun(TypeInferenceInstance.java:125)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.symbolicExecution.instance.TypeInferenceInstance.fun(TypeInferenceInstance.java:69)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.symbolicExecution.SymbolicExecutionEngine.a(SymbolicExecutionEngine.java:82)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.symbolicExecution.SymbolicExecutionEngine.performSymbolicExecution(SymbolicExecutionEngine.java:51)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.symbolicExecution.TypeInferenceResultImpl.performAnalysis(TypeInferenceResultImpl.java:97)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.types.TypeInferenceContext.doInferControlFlowBasedType(TypeInferenceContext.java:107)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.types.TypeInferenceContext.a(TypeInferenceContext.java:161)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.types.TypeInferenceContext.a(TypeInferenceContext.java:160)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.types.TypeInferenceContext.c(TypeInferenceContext.java:49)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.types.TypeInferenceContext.a(TypeInferenceContext.java:78)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.types.TypeInferenceContext.getCachedOrComputeType(TypeInferenceContext.java:78)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.variables.RConstantImpl.getType(RConstantImpl.java:197)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RQualifiedReference.getRefObjectType(RQualifiedReference.java:232)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RQualifiedReferenceBase.resolveToSymbol(RQualifiedReferenceBase.java:106)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RQualifiedReferenceBase.multiResolveInner(RQualifiedReferenceBase.java:60)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RubyPolyVariantReferenceBase$MyResolver.resolve(RubyPolyVariantReferenceBase.java:121)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RubyPolyVariantReferenceBase$MyResolver.resolve(RubyPolyVariantReferenceBase.java:117)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:149)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:179)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:171)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RubyPolyVariantReferenceBase.multiResolve(RubyPolyVariantReferenceBase.java:63)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.resolve.ResolveUtil.resolveToSymbolWithCaching(ResolveUtil.java:170)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.paramDefs.matcher.ParamDefMatcher.match(ParamDefMatcher.java:81)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.paramDefs.matcher.ParamDefMatcher.match(ParamDefMatcher.java:37)
	at org.jetbrains.plugins.ruby.ruby.codeInsight.paramDefs.matcher.ParamDefMatcher.createParamDefReference(ParamDefMatcher.java:120)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.basicTypes.RSymbolImpl.getReferenceEx(RSymbolImpl.java:85)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.basicTypes.RSymbolImpl.a(RSymbolImpl.java:65)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.basicTypes.RSymbolImpl.getReference(RSymbolImpl.java:65)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.getReferences(SharedPsiElementImplUtil.java:77)
	at com.intellij.psi.impl.PsiElementBase.getReferences(PsiElementBase.java:82)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:28)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:121)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:284)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:32)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:70)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:281)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
