### ISSUE TITLE
[Auto Generated Report]java.lang.IllegalArgumentException: Components of QualifiedName cannot contain dots inside them, but got: Answer.Tag

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#328]
- Plugin Name: Material Theme UI
- Plugin Version: 5.26
- OS Name: Linux
- OS Version: 5.0.0-32-generic
- Java Version: 11.0.4
- App Name: PyCharm
- App Full Name: PyCharm
- Is Snapshot: false
- App Build: PY-192.7142.42
- Last Action: null

```
java.lang.IllegalArgumentException: Components of QualifiedName cannot contain dots inside them, but got: Answer.Tag
	at com.intellij.psi.util.QualifiedName.assertNoDots(QualifiedName.java:220)
	at com.intellij.psi.util.QualifiedName.fromComponents(QualifiedName.java:52)
	at com.jetbrains.python.psi.impl.stubs.PyTypingNewTypeStubImpl.getCalleeName(PyTypingNewTypeStubImpl.kt:25)
	at com.jetbrains.python.psi.impl.PyTargetExpressionImpl.getCalleeName(PyTargetExpressionImpl.java:597)
	at com.jetbrains.django.codeInsight.djangoForms.DjangoFormTypeProvider.getReferenceType(DjangoFormTypeProvider.java:76)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.getReferenceTypeFromProviders(PyReferenceExpressionImpl.java:536)
	at com.jetbrains.python.psi.impl.PyTargetExpressionImpl.getType(PyTargetExpressionImpl.java:134)
	at com.jetbrains.python.psi.types.TypeEvalContext.getType(TypeEvalContext.java:193)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:924)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:847)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getType(PyTypingTypeProvider.java:773)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.b(PyTypingTypeProvider.java:863)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:842)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getType(PyTypingTypeProvider.java:773)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:1298)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.i(PyTypingTypeProvider.java:1316)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:818)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getType(PyTypingTypeProvider.java:773)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:1298)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.g(PyTypingTypeProvider.java:1242)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:798)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getType(PyTypingTypeProvider.java:773)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:1298)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.i(PyTypingTypeProvider.java:1316)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:818)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getType(PyTypingTypeProvider.java:773)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:1298)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.i(PyTypingTypeProvider.java:1316)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:818)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getType(PyTypingTypeProvider.java:773)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:1298)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.i(PyTypingTypeProvider.java:1316)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:818)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getType(PyTypingTypeProvider.java:773)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:275)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.b(PyTypingTypeProvider.java:275)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getParameterType(PyTypingTypeProvider.java:196)
	at com.jetbrains.python.psi.impl.PyNamedParameterImpl.getType(PyNamedParameterImpl.java:230)
	at com.jetbrains.python.psi.types.TypeEvalContext.getType(TypeEvalContext.java:193)
	at com.jetbrains.python.psi.types.PyCallableParameterImpl.getType(PyCallableParameterImpl.java:109)
	at com.jetbrains.python.psi.impl.PyFunctionImpl.a(PyFunctionImpl.java:363)
	at com.jetbrains.python.psi.impl.PyFunctionImpl.a(PyFunctionImpl.java:285)
	at com.jetbrains.python.psi.impl.PyFunctionImpl.getCallType(PyFunctionImpl.java:265)
	at com.jetbrains.python.psi.impl.PyFunctionImpl.getCallType(PyFunctionImpl.java:248)
	at com.jetbrains.python.psi.impl.PyCallExpressionHelper.b(PyCallExpressionHelper.java:579)
	at com.jetbrains.python.psi.impl.PyCallExpressionHelper.a(PyCallExpressionHelper.java:464)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at one.util.streamex.AbstractStreamEx.toArray(AbstractStreamEx.java:344)
	at one.util.streamex.AbstractStreamEx.toList(AbstractStreamEx.java:1186)
	at com.jetbrains.python.psi.impl.PyCallExpressionHelper.getCallType(PyCallExpressionHelper.java:467)
	at com.jetbrains.python.psi.impl.PyCallExpressionImpl.getType(PyCallExpressionImpl.java:60)
	at com.jetbrains.python.psi.types.TypeEvalContext.getType(TypeEvalContext.java:193)
	at com.jetbrains.django.codeInsight.djangoForms.DjangoFormsReferenceProvider.isForm(DjangoFormsReferenceProvider.java:232)
	at com.jetbrains.django.codeInsight.djangoForms.DjangoModelFactoryBasedBinding.getFormFieldForLiteral(DjangoModelFactoryBasedBinding.java:55)
	at com.jetbrains.django.codeInsight.djangoForms.DjangoFormsReferenceProvider.a(DjangoFormsReferenceProvider.java:98)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at one.util.streamex.AbstractStreamEx.findFirst(AbstractStreamEx.java:462)
	at com.jetbrains.django.codeInsight.djangoForms.DjangoFormWrapper.getFromBinding(DjangoFormWrapper.java:268)
	at com.jetbrains.django.codeInsight.djangoForms.DjangoFormsReferenceProvider.b(DjangoFormsReferenceProvider.java:98)
	at com.jetbrains.django.codeInsight.djangoForms.DjangoFormsReferenceProvider.getReferencesByElement(DjangoFormsReferenceProvider.java:46)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:156)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:126)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:105)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:56)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:55)
	at com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl.getReferences(PyStringLiteralExpressionImpl.java:192)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:28)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:121)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:284)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:32)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:70)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:281)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: Material Theme UI
- Plugin Version: 5.26
- OS Name: Linux
- OS Version: 5.0.0-32-generic
- Java Version: 11.0.4
- App Name: PyCharm
- App Full Name: PyCharm
- Is Snapshot: false
- App Build: PY-192.7142.42
- Last Action: null

```
java.lang.IllegalArgumentException: Components of QualifiedName cannot contain dots inside them, but got: Answer.Tag
	at com.intellij.psi.util.QualifiedName.assertNoDots(QualifiedName.java:220)
	at com.intellij.psi.util.QualifiedName.fromComponents(QualifiedName.java:52)
	at com.jetbrains.python.psi.impl.stubs.PyTypingNewTypeStubImpl.getCalleeName(PyTypingNewTypeStubImpl.kt:25)
	at com.jetbrains.python.psi.impl.PyTargetExpressionImpl.getCalleeName(PyTargetExpressionImpl.java:597)
	at com.jetbrains.django.codeInsight.djangoForms.DjangoFormTypeProvider.getReferenceType(DjangoFormTypeProvider.java:76)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.getReferenceTypeFromProviders(PyReferenceExpressionImpl.java:536)
	at com.jetbrains.python.psi.impl.PyTargetExpressionImpl.getType(PyTargetExpressionImpl.java:134)
	at com.jetbrains.python.psi.types.TypeEvalContext.getType(TypeEvalContext.java:193)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:924)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:847)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getType(PyTypingTypeProvider.java:773)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.b(PyTypingTypeProvider.java:863)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:842)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getType(PyTypingTypeProvider.java:773)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:1298)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.i(PyTypingTypeProvider.java:1316)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:818)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getType(PyTypingTypeProvider.java:773)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:1298)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.g(PyTypingTypeProvider.java:1242)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:798)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getType(PyTypingTypeProvider.java:773)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:1298)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.i(PyTypingTypeProvider.java:1316)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:818)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getType(PyTypingTypeProvider.java:773)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:1298)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.i(PyTypingTypeProvider.java:1316)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:818)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getType(PyTypingTypeProvider.java:773)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:1298)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.i(PyTypingTypeProvider.java:1316)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:818)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getType(PyTypingTypeProvider.java:773)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.a(PyTypingTypeProvider.java:275)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.b(PyTypingTypeProvider.java:275)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.getParameterType(PyTypingTypeProvider.java:196)
	at com.jetbrains.python.psi.impl.PyNamedParameterImpl.getType(PyNamedParameterImpl.java:230)
	at com.jetbrains.python.psi.types.TypeEvalContext.getType(TypeEvalContext.java:193)
	at com.jetbrains.python.psi.types.PyCallableParameterImpl.getType(PyCallableParameterImpl.java:109)
	at com.jetbrains.python.psi.impl.PyFunctionImpl.a(PyFunctionImpl.java:363)
	at com.jetbrains.python.psi.impl.PyFunctionImpl.a(PyFunctionImpl.java:285)
	at com.jetbrains.python.psi.impl.PyFunctionImpl.getCallType(PyFunctionImpl.java:265)
	at com.jetbrains.python.psi.impl.PyFunctionImpl.getCallType(PyFunctionImpl.java:248)
	at com.jetbrains.python.psi.impl.PyCallExpressionHelper.b(PyCallExpressionHelper.java:579)
	at com.jetbrains.python.psi.impl.PyCallExpressionHelper.a(PyCallExpressionHelper.java:464)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at one.util.streamex.AbstractStreamEx.toArray(AbstractStreamEx.java:344)
	at one.util.streamex.AbstractStreamEx.toList(AbstractStreamEx.java:1186)
	at com.jetbrains.python.psi.impl.PyCallExpressionHelper.getCallType(PyCallExpressionHelper.java:467)
	at com.jetbrains.python.psi.impl.PyCallExpressionImpl.getType(PyCallExpressionImpl.java:60)
	at com.jetbrains.python.psi.types.TypeEvalContext.getType(TypeEvalContext.java:193)
	at com.jetbrains.django.codeInsight.djangoForms.DjangoFormsReferenceProvider.isForm(DjangoFormsReferenceProvider.java:232)
	at com.jetbrains.django.codeInsight.djangoForms.DjangoModelFactoryBasedBinding.getFormFieldForLiteral(DjangoModelFactoryBasedBinding.java:55)
	at com.jetbrains.django.codeInsight.djangoForms.DjangoFormsReferenceProvider.a(DjangoFormsReferenceProvider.java:98)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at one.util.streamex.AbstractStreamEx.findFirst(AbstractStreamEx.java:462)
	at com.jetbrains.django.codeInsight.djangoForms.DjangoFormWrapper.getFromBinding(DjangoFormWrapper.java:268)
	at com.jetbrains.django.codeInsight.djangoForms.DjangoFormsReferenceProvider.b(DjangoFormsReferenceProvider.java:98)
	at com.jetbrains.django.codeInsight.djangoForms.DjangoFormsReferenceProvider.getReferencesByElement(DjangoFormsReferenceProvider.java:46)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:156)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:126)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:105)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:56)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:55)
	at com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl.getReferences(PyStringLiteralExpressionImpl.java:192)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:28)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:121)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:284)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:32)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:70)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:281)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
