### ISSUE TITLE
[Auto Generated Report]java.lang.Throwable: Unbalanced tree. Most probably caused by unbalanced markers. Try calling setDebugMode(true) against PsiBuilder passed to identify exact location of the problem

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#340]
- Plugin Name: null
- Plugin Version: 5.26
- OS Name: Linux
- OS Version: 5.0.0-32-generic
- Java Version: 11.0.3
- App Name: CLion
- App Full Name: CLion
- Is Snapshot: false
- App Build: CL-192.6262.62
- Last Action: Vcs.ShowTabbedFileHistory

```
java.lang.Throwable: Unbalanced tree. Most probably caused by unbalanced markers. Try calling setDebugMode(true) against PsiBuilder passed to identify exact location of the problem
language: 
context: '<none>'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.lang.impl.PsiBuilderImpl.reportUnbalancedMarkers(PsiBuilderImpl.java:1112)
	at com.intellij.lang.impl.PsiBuilderImpl.assertMarkersBalanced(PsiBuilderImpl.java:1104)
	at com.intellij.lang.impl.PsiBuilderImpl.prepareLightTree(PsiBuilderImpl.java:1073)
	at com.intellij.lang.impl.PsiBuilderImpl.getLightTree(PsiBuilderImpl.java:955)
	at com.jetbrains.cidr.lang.symbols.symtable.OCSymbolTableProvider.calcTable(OCSymbolTableProvider.java:155)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache.forFile(FileSymbolTablesCache.java:468)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.forFile(FileSymbolTable.java:221)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.forFile(FileSymbolTable.java:211)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextImpl.preprocessInclude(OCInclusionContextImpl.java:921)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextImpl.preprocessInclude(OCInclusionContextImpl.java:904)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextImpl.preprocessInclude(OCInclusionContextImpl.java:887)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph.a(OCImportGraph.java:117)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph.buildSymbolAndRootHeaderCache(OCImportGraph.java:102)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTableUpdater.a(FileSymbolTableUpdater.java:202)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTableUpdater.b(FileSymbolTableUpdater.java:127)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTableUpdater.ensurePendingFilesProcessed(FileSymbolTableUpdater.java:62)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache.ensurePendingFilesProcessed(FileSymbolTablesCache.java:687)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache.ensurePendingFilesProcessed(FileSymbolTablesCache.java:683)
	at com.jetbrains.cidr.lang.symbols.symtable.AbstractGlobalProjectSymbolsCache.processTopLevelAndMemberSymbols(AbstractGlobalProjectSymbolsCache.java:197)
	at com.jetbrains.cidr.lang.symbols.symtable.AbstractGlobalProjectSymbolsCache.processTopLevelAndMemberSymbols(AbstractGlobalProjectSymbolsCache.java:171)
	at com.jetbrains.cidr.lang.symbols.symtable.OCGlobalProjectSymbolsCache.processTopLevelAndMemberSymbols(OCGlobalProjectSymbolsCache.java:125)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedNameImpl.processSameSymbols(OCSymbolWithQualifiedNameImpl.java:388)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedName.processSameSymbols(OCSymbolWithQualifiedName.java:142)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedNameImpl.processSameSymbols(OCSymbolWithQualifiedNameImpl.java:329)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedNameImpl.getDefinitionSymbol(OCSymbolWithQualifiedNameImpl.java:296)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedNameImpl.processAssociatedSymbols(OCSymbolWithQualifiedNameImpl.java:397)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedNameImpl.getAssociatedSymbol(OCSymbolWithQualifiedNameImpl.java:601)
	at com.jetbrains.cidr.lang.dfa.OCInfiniteRecursionFinder$1.visitCallExpression(OCInfiniteRecursionFinder.java:67)
	at com.jetbrains.cidr.lang.psi.impl.OCCallExpressionImpl.accept(OCCallExpressionImpl.java:111)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:91)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:26)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:12)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitExpression(OCVisitor.java:20)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitAssignmentExpression(OCVisitor.java:129)
	at com.jetbrains.cidr.lang.psi.impl.OCAssignmentExpressionImpl.accept(OCAssignmentExpressionImpl.java:107)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:91)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:26)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:12)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitStatement(OCVisitor.java:24)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitExpressionStatement(OCVisitor.java:41)
	at com.jetbrains.cidr.lang.psi.impl.OCExpressionStatementImpl.accept(OCExpressionStatementImpl.java:25)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:91)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:26)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:12)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitStatement(OCVisitor.java:24)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitBlockStatement(OCVisitor.java:32)
	at com.jetbrains.cidr.lang.psi.impl.OCLazyBlockStatementImpl.accept(OCLazyBlockStatementImpl.java:28)
	at com.jetbrains.cidr.lang.psi.impl.OCLazyElementBase.accept(OCLazyElementBase.java:77)
	at com.jetbrains.cidr.lang.psi.visitors.OCRecursiveVisitor.visitElement(OCRecursiveVisitor.java:26)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitOCElement(OCVisitor.java:12)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitDeclaration(OCVisitor.java:234)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitFunctionDeclaration(OCVisitor.java:449)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitFunctionDefinition(OCVisitor.java:272)
	at com.jetbrains.cidr.lang.psi.impl.OCFunctionDefinitionImpl.accept(OCFunctionDefinitionImpl.java:76)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:91)
	at com.jetbrains.cidr.lang.dfa.OCInfiniteRecursionFinder.process(OCInfiniteRecursionFinder.java:43)
	at com.jetbrains.cidr.lang.dfa.OCDataFlowAnalyzer.buildControlFlowGraph(OCDataFlowAnalyzer.java:169)
	at com.jetbrains.cidr.lang.daemon.OCDataFlowBasedAnnotator.visitCallable(OCDataFlowBasedAnnotator.java:35)
	at com.jetbrains.cidr.lang.psi.visitors.OCVisitor.visitFunctionDefinition(OCVisitor.java:273)
	at com.jetbrains.cidr.lang.psi.impl.OCFunctionDefinitionImpl.accept(OCFunctionDefinitionImpl.java:76)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:91)
	at com.jetbrains.cidr.lang.daemon.OCAnnotator.annotate(OCAnnotator.java:84)
	at com.jetbrains.cidr.lang.daemon.OCAnnotator.annotate(OCAnnotator.java:65)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:121)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:290)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:32)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.RainbowVisitor.analyze(RainbowVisitor.java:50)
	at com.jetbrains.cidr.lang.daemon.OCRainbowVisitor.analyze(OCRainbowVisitor.java:55)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:70)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:281)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: Material Theme UI
- Plugin Version: 5.27
- OS Name: Mac OS X
- OS Version: 10.15.1
- Java Version: 11.0.4
- App Name: CLion
- App Full Name: CLion
- Is Snapshot: false
- App Build: CL-193.5233.144
- Last Action: ShowIntentionActions

```
java.lang.Throwable: Unbalanced tree. Most probably caused by unbalanced markers. Try calling setDebugMode(true) against PsiBuilder passed to identify exact location of the problem
language: 
context: '<none>'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.lang.impl.PsiBuilderImpl.reportUnbalancedMarkers(PsiBuilderImpl.java:1092)
	at com.intellij.lang.impl.PsiBuilderImpl.assertMarkersBalanced(PsiBuilderImpl.java:1084)
	at com.intellij.lang.impl.PsiBuilderImpl.prepareLightTree(PsiBuilderImpl.java:1053)
	at com.intellij.lang.impl.PsiBuilderImpl.getLightTree(PsiBuilderImpl.java:936)
	at com.jetbrains.cidr.lang.symbols.symtable.OCSymbolTableProvider.calcTable(OCSymbolTableProvider.java:162)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache.forFile(FileSymbolTablesCache.java:492)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.forFile(FileSymbolTable.java:220)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.forFile(FileSymbolTable.java:209)
	at com.jetbrains.cidr.lang.psi.impl.OCFileImpl.getSymbolTable(OCFileImpl.java:272)
	at com.jetbrains.cidr.lang.psi.impl.OCFileImpl.findSymbol(OCFileImpl.java:247)
	at com.jetbrains.cidr.lang.psi.impl.OCDeclaratorImpl.getSymbol(OCDeclaratorImpl.java:86)
	at com.jetbrains.cidr.lang.daemon.OCHiddenNonVirtualFunctionAnnotator.visitDeclarator(OCHiddenNonVirtualFunctionAnnotator.java:32)
	at com.jetbrains.cidr.lang.psi.impl.OCDeclaratorImpl.accept(OCDeclaratorImpl.java:473)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.daemon.OCAnnotator.annotate(OCAnnotator.java:88)
	at com.jetbrains.cidr.lang.daemon.OCAnnotator.annotate(OCAnnotator.java:65)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:126)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:285)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:32)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at org.igu.plugins.bettercomments.visitor.DefaultCommentsVisitor.analyze(DefaultCommentsVisitor.kt:32)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:282)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:227)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
