### ISSUE TITLE
[Auto Generated Report]java.lang.Throwable: Invalid iOS version format: 10

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#371]
- Plugin Name: null
- Plugin Version: 5.27
- OS Name: Mac OS X
- OS Version: 10.15.1
- Java Version: 11.0.4
- App Name: AppCode
- App Full Name: AppCode
- Is Snapshot: false
- App Build: OC-193.5233.118
- Last Action: EditorBackSpace

```
java.lang.Throwable: Invalid iOS version format: 10
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.jetbrains.cidr.lang.daemon.OCAppCodeAnnotatorHelper.convertVersion(OCAppCodeAnnotatorHelper.java:210)
	at com.jetbrains.cidr.lang.daemon.OCAppCodeAnnotatorHelper.isVersionAllowed(OCAppCodeAnnotatorHelper.java:144)
	at com.jetbrains.cidr.lang.daemon.OCAppCodeAnnotatorHelper.a(OCAppCodeAnnotatorHelper.java:91)
	at com.jetbrains.cidr.lang.daemon.OCAppCodeAnnotatorHelper.checkAvailability(OCAppCodeAnnotatorHelper.java:49)
	at com.jetbrains.cidr.lang.resolve.OCResolveUtil.checkAvailability(OCResolveUtil.java:101)
	at com.jetbrains.cidr.lang.legacy.daemon.OCResolveAnnotator.a(OCResolveAnnotator.java:203)
	at com.jetbrains.cidr.lang.legacy.daemon.OCResolveAnnotator.visitReferenceElement(OCResolveAnnotator.java:297)
	at com.jetbrains.cidr.lang.psi.impl.OCReferenceElementImpl.accept(OCReferenceElementImpl.java:89)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.daemon.OCAnnotator.annotate(OCAnnotator.java:88)
	at com.jetbrains.cidr.lang.daemon.OCAnnotator.annotate(OCAnnotator.java:65)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:126)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:285)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:32)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:282)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:227)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: null
- Plugin Version: 5.27
- OS Name: Mac OS X
- OS Version: 10.15.2
- Java Version: 11.0.4
- App Name: AppCode
- App Full Name: AppCode
- Is Snapshot: false
- App Build: OC-193.5233.118
- Last Action: EditorBackSpace

```
java.lang.Throwable: Invalid iOS version format: 10
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.jetbrains.cidr.lang.daemon.OCAppCodeAnnotatorHelper.convertVersion(OCAppCodeAnnotatorHelper.java:210)
	at com.jetbrains.cidr.lang.daemon.OCAppCodeAnnotatorHelper.isVersionAllowed(OCAppCodeAnnotatorHelper.java:144)
	at com.jetbrains.cidr.lang.daemon.OCAppCodeAnnotatorHelper.a(OCAppCodeAnnotatorHelper.java:91)
	at com.jetbrains.cidr.lang.daemon.OCAppCodeAnnotatorHelper.checkAvailability(OCAppCodeAnnotatorHelper.java:49)
	at com.jetbrains.cidr.lang.resolve.OCResolveUtil.checkAvailability(OCResolveUtil.java:101)
	at com.jetbrains.cidr.lang.legacy.daemon.OCResolveAnnotator.a(OCResolveAnnotator.java:203)
	at com.jetbrains.cidr.lang.legacy.daemon.OCResolveAnnotator.visitReferenceElement(OCResolveAnnotator.java:297)
	at com.jetbrains.cidr.lang.psi.impl.OCReferenceElementImpl.accept(OCReferenceElementImpl.java:89)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:92)
	at com.jetbrains.cidr.lang.daemon.OCAnnotator.annotate(OCAnnotator.java:88)
	at com.jetbrains.cidr.lang.daemon.OCAnnotator.annotate(OCAnnotator.java:65)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:126)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:285)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:32)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:282)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:227)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
