### ISSUE TITLE
Add JSX (React) Support

### ISSUE THREAD

**Issue by dpweberza** [izhangzhihao/intellij-rainbow-brackets#38]
## Expected Behavior
Please add support for JSX (React) highlighting
[Intro to React JSX](https://reactjs.org/docs/introducing-jsx.html)

## Current Behavior
* HTML tags within a JSX expression doesn't have bracket highlighting.

## Code snippet for reproducing
`
const element = (
    <div>
        <h1>Hello, world!</h1>
    </div>
);
`

## Your Environment
* Plugin version: 5.0 RC3
* IDEA version: Rider 2017.3.1
* Operating System and version: Windows 10

**Comment by izhangzhihao** [comment]
Could you test [this snapshot version](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/1836039/intellij-rainbow-brackets-5.0-RC4.zip) ? Thanks.

**Comment by izhangzhihao** [comment]
See [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000117450-My-HighlightVisitor-been-covered-by-intellij-built-in-functionality)

**Comment by dpweberza** [comment]
RC4 doesn't work at all in Jetbrains Rider 2017.3.1.

> 23/03/2018
9:16 AM	Rainbow Brackets updated to 5.0-RC4
				Thank you for downloading Rainbow Brackets!
				If you find my plugin helpful, Please give me a star on github
				If you find any issue, Please feel free to raise a issue
				See Changelog for more details.
9:17 AM	NoClassDefFoundError: com/intellij/lang/javascript/DialectDetector
				--- JAVA_EXCEPTION ---
				java.lang.NoClassDefFoundError: com/intellij/lang/javascript/DialectDetector
				at com.github.izhangzhihao.rainbow.brackets.ReactRainbowVisitor.suitableForFile(ReactRainbowVisitor.kt:10)
				at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:151)
				at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.getHighlightVisitors(GeneralHighlightingPass.java:171)
				at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:191)
				at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
				at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
				at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
				at com.intellij.openapi.application.impl.Applica... (show balloon)

**Comment by izhangzhihao** [comment]
Emmmmm.... It seems like Riser dosen't have a built-in JavaScript plugin...

**Comment by izhangzhihao** [comment]
I could build another snapshot which have a optional depend on JavaScript plugin, but the functionality is depend on JavaScript plugin... So I couldn't help you if Rider doesn't have a built-in JavaScript plugin

**Comment by izhangzhihao** [comment]
Try this [intellij-rainbow-brackets-5.0-RC4.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/1839778/intellij-rainbow-brackets-5.0-RC4.zip) please.

**Comment by dpweberza** [comment]
That worked, thanks, @izhangzhihao!!! Amazing and fast support.
