### ISSUE TITLE
[Auto Generated Report]java.lang.IndexOutOfBoundsException: Wrong index: 0

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#384]
- Plugin Name: null
- Plugin Version: 5.27
- OS Name: Mac OS X
- OS Version: 10.15.2
- Java Version: 11.0.5
- App Name: PhpStorm
- App Full Name: PhpStorm
- Is Snapshot: false
- App Build: PS-193.5662.16
- Last Action: EditorBackSpace

```
java.lang.IndexOutOfBoundsException: Wrong index: 0
	at com.intellij.openapi.editor.ex.util.SegmentArrayWithData.getSegmentData(SegmentArrayWithData.java:84)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter$HighlighterIteratorImpl.getTokenType(LexerEditorHighlighter.java:631)
	at com.intellij.openapi.editor.ex.util.LayeredLexerEditorHighlighter$LayeredHighlighterIteratorImpl.getTokenType(LayeredLexerEditorHighlighter.java:565)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$IndentsCalculator.isComment(RainbowIndentsPass.kt:318)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$IndentsCalculator.calculate$intellij_rainbow_brackets(RainbowIndentsPass.kt:276)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass.buildDescriptors(RainbowIndentsPass.kt:158)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass.doCollectInformation(RainbowIndentsPass.kt:63)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: null
- Plugin Version: 5.27
- OS Name: Windows 10
- OS Version: 10.0
- Java Version: 11.0.5
- App Name: PhpStorm
- App Full Name: PhpStorm
- Is Snapshot: false
- App Build: PS-193.5662.63
- Last Action: Git.ResolveConflicts

```
java.lang.IndexOutOfBoundsException: Wrong index: 0
	at com.intellij.openapi.editor.ex.util.SegmentArrayWithData.getSegmentData(SegmentArrayWithData.java:84)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter$HighlighterIteratorImpl.getTokenType(LexerEditorHighlighter.java:631)
	at com.intellij.openapi.editor.ex.util.LayeredLexerEditorHighlighter$LayeredHighlighterIteratorImpl.getTokenType(LayeredLexerEditorHighlighter.java:565)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$IndentsCalculator.isComment(RainbowIndentsPass.kt:318)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$IndentsCalculator.calculate$intellij_rainbow_brackets(RainbowIndentsPass.kt:276)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass.buildDescriptors(RainbowIndentsPass.kt:158)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass.doCollectInformation(RainbowIndentsPass.kt:63)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
