### ISSUE TITLE
[Auto Generated Report]java.lang.AssertionError: Inconsistent tokens stream from com.jetbrains.web2py.templates.lexer.Web2PyIndentingLexer[FlexAdapter for com.jetbrains.web2py.templates.lexer._Web2PyFlexLexer]: '\n' (25861,25862) followed by 'if' (25864,25866)

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#395]
- Plugin Name: null
- Plugin Version: 5.27
- OS Name: Linux
- OS Version: 5.3.0-29-generic
- Java Version: 11.0.2
- App Name: PyCharm
- App Full Name: PyCharm
- Is Snapshot: false
- App Build: PY-191.7479.30
- Last Action: null

```
java.lang.AssertionError: Inconsistent tokens stream from com.jetbrains.web2py.templates.lexer.Web2PyIndentingLexer[FlexAdapter for com.jetbrains.web2py.templates.lexer._Web2PyFlexLexer]: '\n' (25861,25862) followed by 'if' (25864,25866)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.createTemplateText(TemplateDataElementType.java:157)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.createTemplateFile(TemplateDataElementType.java:133)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.parseContents(TemplateDataElementType.java:90)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:206)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:205)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:254)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:139)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:46)
	at com.intellij.psi.AbstractFileViewProvider.findElementAt(AbstractFileViewProvider.java:260)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.findElementAt(MultiplePsiFilesPerDocumentFileViewProvider.java:157)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.findElementAt(MultiplePsiFilesPerDocumentFileViewProvider.java:169)
	at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:503)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.getRainbowInfo(RainbowIndentsPass.kt:479)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.access$getRainbowInfo(RainbowIndentsPass.kt:336)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.invoke(RainbowIndentsPass.kt:351)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.paint(RainbowIndentsPass.kt:336)
	at com.intellij.openapi.editor.impl.view.EditorPainter.lambda$paintCustomRenderers$1(EditorPainter.java:388)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.processRangeHighlightersOverlappingWith(MarkupModelImpl.java:247)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paintCustomRenderers(EditorPainter.java:381)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paint(EditorPainter.java:99)
	at com.intellij.openapi.editor.impl.view.EditorView.paint(EditorView.java:264)
	at com.intellij.openapi.editor.impl.EditorImpl.paint(EditorImpl.java:1914)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paintComponent(EditorComponentImpl.java:240)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:120)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JViewport.paint(Unknown Source)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:234)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent._paintImmediately(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by intellij-rainbow-brackets** [comment]
removed closing brackets of {{ if :}} block in .html view of web2py

----------------------

- Plugin Name: null
- Plugin Version: 5.27
- OS Name: Linux
- OS Version: 5.3.0-29-generic
- Java Version: 11.0.2
- App Name: PyCharm
- App Full Name: PyCharm
- Is Snapshot: false
- App Build: PY-191.7479.30
- Last Action: EditorBackSpace

```
java.lang.AssertionError: Inconsistent tokens stream from com.jetbrains.web2py.templates.lexer.Web2PyIndentingLexer[FlexAdapter for com.jetbrains.web2py.templates.lexer._Web2PyFlexLexer]: '\n' (25861,25862) followed by 'if' (25864,25866)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.createTemplateText(TemplateDataElementType.java:157)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.createTemplateFile(TemplateDataElementType.java:133)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.parseContents(TemplateDataElementType.java:90)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:206)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:205)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:254)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:139)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:46)
	at com.intellij.psi.AbstractFileViewProvider.findElementAt(AbstractFileViewProvider.java:260)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.findElementAt(MultiplePsiFilesPerDocumentFileViewProvider.java:157)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.findElementAt(MultiplePsiFilesPerDocumentFileViewProvider.java:169)
	at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:503)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.getRainbowInfo(RainbowIndentsPass.kt:479)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.access$getRainbowInfo(RainbowIndentsPass.kt:336)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.invoke(RainbowIndentsPass.kt:351)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.paint(RainbowIndentsPass.kt:336)
	at com.intellij.openapi.editor.impl.view.EditorPainter.lambda$paintCustomRenderers$1(EditorPainter.java:388)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.processRangeHighlightersOverlappingWith(MarkupModelImpl.java:247)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paintCustomRenderers(EditorPainter.java:381)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paint(EditorPainter.java:99)
	at com.intellij.openapi.editor.impl.view.EditorView.paint(EditorView.java:264)
	at com.intellij.openapi.editor.impl.EditorImpl.paint(EditorImpl.java:1914)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paintComponent(EditorComponentImpl.java:240)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:120)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JViewport.paint(Unknown Source)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:234)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JLayeredPane.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JLayeredPane.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at com.intellij.ui.tabs.impl.JBTabsImpl.paintChildren(JBTabsImpl.java:2302)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at com.intellij.ui.tabs.impl.JBTabsImpl.paint(JBTabsImpl.java:2297)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JLayeredPane.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JLayeredPane.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JLayeredPane.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
	at java.desktop/java.awt.Container.paint(Unknown Source)
	at java.desktop/java.awt.Window.paint(Unknown Source)
	at com.intellij.openapi.wm.impl.IdeFrameImpl.paint(IdeFrameImpl.java:564)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: null
- Plugin Version: 5.27
- OS Name: Linux
- OS Version: 5.3.0-29-generic
- Java Version: 11.0.2
- App Name: PyCharm
- App Full Name: PyCharm
- Is Snapshot: false
- App Build: PY-191.7479.30
- Last Action: null

```
java.lang.AssertionError: Inconsistent tokens stream from com.jetbrains.web2py.templates.lexer.Web2PyIndentingLexer[FlexAdapter for com.jetbrains.web2py.templates.lexer._Web2PyFlexLexer]: '\n' (25861,25862) followed by 'if' (25864,25866)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.createTemplateText(TemplateDataElementType.java:157)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.createTemplateFile(TemplateDataElementType.java:133)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.parseContents(TemplateDataElementType.java:90)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:206)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:205)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:254)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:139)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:46)
	at com.intellij.psi.AbstractFileViewProvider.findElementAt(AbstractFileViewProvider.java:260)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.findElementAt(MultiplePsiFilesPerDocumentFileViewProvider.java:157)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.findElementAt(MultiplePsiFilesPerDocumentFileViewProvider.java:169)
	at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:503)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.getRainbowInfo(RainbowIndentsPass.kt:479)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.access$getRainbowInfo(RainbowIndentsPass.kt:336)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.invoke(RainbowIndentsPass.kt:351)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.paint(RainbowIndentsPass.kt:336)
	at com.intellij.openapi.editor.impl.view.EditorPainter.lambda$paintCustomRenderers$1(EditorPainter.java:388)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.processRangeHighlightersOverlappingWith(MarkupModelImpl.java:247)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paintCustomRenderers(EditorPainter.java:381)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paint(EditorPainter.java:99)
	at com.intellij.openapi.editor.impl.view.EditorView.paint(EditorView.java:264)
	at com.intellij.openapi.editor.impl.EditorImpl.paint(EditorImpl.java:1914)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paintComponent(EditorComponentImpl.java:240)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:120)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JViewport.paint(Unknown Source)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:234)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JLayeredPane.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent._paintImmediately(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: null
- Plugin Version: 5.27
- OS Name: Linux
- OS Version: 5.3.0-29-generic
- Java Version: 11.0.2
- App Name: PyCharm
- App Full Name: PyCharm
- Is Snapshot: false
- App Build: PY-191.7479.30
- Last Action: null

```
java.lang.AssertionError: Inconsistent tokens stream from com.jetbrains.web2py.templates.lexer.Web2PyIndentingLexer[FlexAdapter for com.jetbrains.web2py.templates.lexer._Web2PyFlexLexer]: '\n' (25861,25862) followed by 'if' (25864,25866)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.createTemplateText(TemplateDataElementType.java:157)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.createTemplateFile(TemplateDataElementType.java:133)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.parseContents(TemplateDataElementType.java:90)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:206)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:205)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:254)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:139)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:46)
	at com.intellij.psi.AbstractFileViewProvider.findElementAt(AbstractFileViewProvider.java:260)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.findElementAt(MultiplePsiFilesPerDocumentFileViewProvider.java:157)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.findElementAt(MultiplePsiFilesPerDocumentFileViewProvider.java:169)
	at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:503)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.getRainbowInfo(RainbowIndentsPass.kt:479)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion.access$getRainbowInfo(RainbowIndentsPass.kt:336)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.invoke(RainbowIndentsPass.kt:351)
	at com.github.izhangzhihao.rainbow.brackets.indents.RainbowIndentsPass$Companion$RENDERER$1.paint(RainbowIndentsPass.kt:336)
	at com.intellij.openapi.editor.impl.view.EditorPainter.lambda$paintCustomRenderers$1(EditorPainter.java:388)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.processRangeHighlightersOverlappingWith(MarkupModelImpl.java:247)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paintCustomRenderers(EditorPainter.java:381)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paint(EditorPainter.java:99)
	at com.intellij.openapi.editor.impl.view.EditorView.paint(EditorView.java:264)
	at com.intellij.openapi.editor.impl.EditorImpl.paint(EditorImpl.java:1914)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paintComponent(EditorComponentImpl.java:240)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:120)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent._paintImmediately(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```
