### ISSUE TITLE
Caused by: java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by HaroldLoui** [izhangzhihao/intellij-rainbow-brackets#412]
I upgraded the plugin to 6.1, and it reported an error to me:
```java
com.intellij.diagnostic.PluginException: While loading class com.github.izhangzhihao.rainbow.brackets.RainbowUpdateNotifyActivity: com/github/izhangzhihao/rainbow/brackets/RainbowUpdateNotifyActivity has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 [Plugin: izhangzhihao.rainbow.brackets]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:262)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:205)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:113)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getImplementationClass(ExtensionComponentAdapter.java:80)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:39)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:68)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:446)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:433)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.lambda$null$15(ExtensionPointImpl.java:878)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:2100)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.lambda$null$16(ExtensionPointImpl.java:877)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.notifyListeners(ExtensionPointImpl.java:677)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.lambda$registerExtensions$17(ExtensionPointImpl.java:876)
	at com.intellij.ide.plugins.DynamicPlugins.loadPluginDescriptor(DynamicPlugins.kt:544)
	at com.intellij.ide.plugins.DynamicPlugins.access$loadPluginDescriptor(DynamicPlugins.kt:89)
	at com.intellij.ide.plugins.DynamicPlugins$loadPlugin$1.run(DynamicPlugins.kt:494)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:976)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:491)
	at com.intellij.ide.plugins.PluginEnabler.updatePluginEnabledState(PluginEnabler.java:65)
	at com.intellij.ide.plugins.newui.MyPluginModel.applyEnableDisablePlugins(MyPluginModel.java:231)
	at com.intellij.ide.plugins.newui.MyPluginModel.apply(MyPluginModel.java:190)
	at com.intellij.ide.plugins.PluginManagerConfigurable.apply(PluginManagerConfigurable.java:1656)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.apply(ConfigurableWrapper.java:172)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.apply(ConfigurableEditor.java:324)
	at com.intellij.openapi.options.newEditor.SettingsEditor$5.apply(SettingsEditor.java:173)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$2.actionPerformed(ConfigurableEditor.java:64)
	... more
Caused by: java.lang.UnsupportedClassVersionError: com/github/izhangzhihao/rainbow/brackets/RainbowUpdateNotifyActivity has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:636)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:380)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:376)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:340)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:259)
	... 125 more
```

## My Machine Environment

```
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 1.8.0_242-b08 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 5.6.3-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 943M
Cores: 8
Non-Bundled Plugins: Lombook Plugin, com.mallowigi, com.markskelton.one-dark-theme, net.vektah.codeglance, cn.wuzhizhan.plugin.mybatis, some.awesome, izhangzhihao.rainbow.brackets
Current Desktop: KDE
```
## My Java Version
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

**This error was only found after I upgraded the plugin. I didn't have it before.**

**Comment by izhangzhihao** [comment]
Yes, start from 6.0, this plugin is build against with Java 11

**Comment by izhangzhihao** [comment]
By the way, how did you get your IntelliJ installed?

**Comment by izhangzhihao** [comment]
And from 2020.1 java 8 is not officially supported by IntelliJ based IDEs.

**Comment by HaroldLoui** [comment]
> By the way, how did you get your IntelliJ installed?

Downloaded from Jetbrains.com, and actived with my edu email.

**Comment by izhangzhihao** [comment]
Did you download the `2020.1 for Linux without JBR (tar.gz)`?

**Comment by HaroldLoui** [comment]
> And from 2020.1 java 8 is not officially supported by IntelliJ based IDEs.

So I have to upgrade my java to 11?

**Comment by izhangzhihao** [comment]
Yep

**Comment by izhangzhihao** [comment]
Java 8 is not supported anymore(if you are using 2020.1 and above)

**Comment by HaroldLoui** [comment]
> Java 8 is not supported anymore(if you are using 2020.1 and above)

Ok, thanks.
