### ISSUE TITLE
NullPointException throw in idea 2020.1

### ISSUE THREAD

**Issue by wayne0332** [izhangzhihao/intellij-rainbow-brackets#420]
## Your programming language(s)
Java

## Current Behavior
when i click the `Use color generator`,the idea report error.
```
java.lang.NullPointerException
	at com.github.izhangzhihao.rainbow.brackets.RandomColorGenerator.randomColor(RandomColorGenerator.kt:16)
	at com.github.izhangzhihao.rainbow.brackets.RainbowHighlighter.genByOption(RainbowHighlighter.kt:130)
	at com.github.izhangzhihao.rainbow.brackets.RainbowHighlighter.generateColor(RainbowHighlighter.kt:126)
	at com.github.izhangzhihao.rainbow.brackets.RainbowHighlighter.access$generateColor(RainbowHighlighter.kt:23)
	at com.github.izhangzhihao.rainbow.brackets.RainbowHighlighter$memGetRainbowColorByLevel$1.invoke(RainbowHighlighter.kt:132)
	at com.github.izhangzhihao.rainbow.brackets.RainbowHighlighter$memGetRainbowColorByLevel$1.invoke(RainbowHighlighter.kt:23)
	at com.github.izhangzhihao.rainbow.brackets.util.MemoizeKey3.invoke(Memoize.kt:39)
	at com.github.izhangzhihao.rainbow.brackets.util.MemoizeKey3.invoke(Memoize.kt:38)
	at com.github.izhangzhihao.rainbow.brackets.util.MemoizedHandler.invoke(Memoize.kt:27)
	at com.github.izhangzhihao.rainbow.brackets.util.MemoizeKt$memoize$3.invoke(Memoize.kt:17)
	at com.github.izhangzhihao.rainbow.brackets.RainbowHighlighter.getRainbowColorByLevel(RainbowHighlighter.kt:106)
	at com.github.izhangzhihao.rainbow.brackets.RainbowHighlighter.getTextAttributes(RainbowHighlighter.kt:158)
	at com.github.izhangzhihao.rainbow.brackets.RainbowHighlighter.getHighlightInfo(RainbowHighlighter.kt:162)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.setHighlightInfo(RainbowHighlightVisitor.kt:52)
	at com.github.izhangzhihao.rainbow.brackets.visitor.DefaultRainbowVisitor.rainbowPairs(DefaultRainbowVisitor.kt:46)
	at com.github.izhangzhihao.rainbow.brackets.visitor.DefaultRainbowVisitor.visit(DefaultRainbowVisitor.kt:38)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:346)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:280)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:309)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$analyze$1(HighlightVisitorImpl.java:208)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:362)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:222)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:427)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:402)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:400)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

## Your Environment

* Plugin version: 6.3
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue will be closed directly.

```
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Licensed to ********************
Subscription is active until May 24, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2046M
Cores: 12
Registry: debugger.valueTooltipAutoShowOnSelection=true, compiler.automake.allow.when.app.running=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: PlantUML integration, GrepConsole, Lombook Plugin, MyBatisLogPlugin, VisualVMLauncher, br.com.br.com.breakpoint.breakpoint.toogleAll, com.alibaba.scrat, com.intellij.zh, com.jetbrains.CyanTheme, com.jetbrains.darkPurpleTheme, com.jetbrains.grayTheme, com.robohorse.robopojogenerator, AliP3CPlugin, MavenRunHelper, BashSupport, JRebelPlugin, izhangzhihao.rainbow.brackets, cn.yiiguxing.plugin.translate, com.alibaba.aligenerator.plugin.id, com.ccnode.codegenerator.MyBatisCodeHelperPro
```

**Comment by izhangzhihao** [comment]
Can you help me to confirm [this snapshot build](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/4545153/intellij-rainbow-brackets-6.3.zip) works for you?

**Comment by wayne0332** [comment]
yes! this build works!

**Comment by izhangzhihao** [comment]
Great then.
