### ISSUE TITLE
Exception when loading Rainbow Brackets plugin in IntelliJ

### ISSUE THREAD

**Issue by glopezjr** [izhangzhihao/intellij-rainbow-brackets#430]
Exception in Plugin Rainbow Brackets...

Cannot create listener

com.intellij.diagnostic.PluginException: Cannot create listener com.github.izhangzhihao.rainbow.brackets.listener.RainbowColorsSchemeListener [Plugin: izhangzhihao.rainbow.brackets]
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:716)
	at com.intellij.util.messages.impl.MessageBusImpl.subscribeLazyListeners(MessageBusImpl.java:204)
	at com.intellij.util.messages.impl.MessageBusImpl.calcSubscribers(MessageBusImpl.java:320)
	at com.intellij.util.messages.impl.MessageBusImpl.getTopicSubscribers(MessageBusImpl.java:366)
	at com.intellij.util.messages.impl.MessageBusImpl.postMessage(MessageBusImpl.java:344)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:396)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:237)
	at com.sun.proxy.$Proxy31.globalSchemeChange(Unknown Source)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.schemeChangedOrSwitched(EditorColorsManagerImpl.java:305)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$1EditorColorSchemeProcessor.handleCurrentSchemeSwitched(EditorColorsManagerImpl.java:138)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$1EditorColorSchemeProcessor.lambda$onCurrentSchemeSwitched$0(EditorColorsManagerImpl.java:131)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.diagnostic.PluginException: While loading class com.github.izhangzhihao.rainbow.brackets.listener.RainbowColorsSchemeListener: com/github/izhangzhihao/rainbow/brackets/listener/RainbowColorsSchemeListener has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 [Plugin: izhangzhihao.rainbow.brackets]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:262)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:205)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:113)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:713)
	... 38 more
Caused by: java.lang.UnsupportedClassVersionError: com/github/izhangzhihao/rainbow/brackets/listener/RainbowColorsSchemeListener has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:635)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:380)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:376)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:340)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:259)
	... 44 more

## Your Environment

* Plugin version:
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue will be closed directly.

```
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, izhangzhihao.rainbow.brackets
```

**Comment by izhangzhihao** [comment]
That’s interesting because the error says you are using JDK8 to run the ide. But according to your environment info, you are using Java 11

在 2020年5月14日，下午10:18，open-collective-bot[bot] <notifications@github.com> 写道：

﻿

**Comment by glopezjr** [comment]
I have 3 jdks in my setup, I manage them using jenv on my mac.
So does the plugin support JDK 8 ?  if not I can probably get rid of the bundled JDK8 that comes with intelliJ, perhaps this is causing the issue ?

**Comment by izhangzhihao** [comment]
Yup, this plugin does not support jdk8 any more

在 2020年5月15日，上午2:02，Gabriel <notifications@github.com> 写道：

﻿

I have 3 jdks in my setup, I manage them using jenv on my mac.
So does the plugin support JDK 8 ? if not I can probably get rid of the bundled JDK8 that comes with intelliJ, perhaps this is causing the issue ?
