### ISSUE TITLE
Plugin Incompatibility: Android Studio 4.2 Alpha 8

### ISSUE THREAD

**Issue by JvmName** [izhangzhihao/intellij-rainbow-brackets#480]
**Env:**

* Plugin version: `6.9.1`
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
	```Android Studio 4.2 Canary 8
	Build #AI-202.6397.94.42.6787931, built on August 24, 2020
	Runtime version: 11.0.7+10-b765.53 x86_64
	VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
	macOS 10.15.5
	GC: G1 Young Generation, G1 Old Generation
	Memory: 4096M
	Cores: 12
	Registry: ide.tooltip.initialDelay=310
	Non-Bundled Plugins: com.squareup.sqldelight
	```

**Description:**
I recently upgraded from Android Studio 4.2 Alpha 7 to Alpha 8, and Android Studio complained that the plugin wasn't compatible: 
![image](https://user-images.githubusercontent.com/1294660/91577223-6918b280-e916-11ea-8a0f-39224c640f43.png). 
Everything worked as expected with Alpha 7, which is weird. 

Looking in `idea.log`, I saw this:

```java.lang.Throwable
	at com.intellij.openapi.diagnostic.FrequentEventDetector.generateMessage(FrequentEventDetector.java:83)
	at com.intellij.openapi.diagnostic.FrequentEventDetector.getMessageOnEvent(FrequentEventDetector.java:62)
	at com.intellij.ide.IdeEventQueue.doPostEvent(IdeEventQueue.java:1377)
	at com.intellij.ide.IdeEventQueue.postEvent(IdeEventQueue.java:1270)
	at java.awt.EventQueue.invokeLater(EventQueue.java:1300)
	at javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1295)
	at com.intellij.openapi.application.impl.FlushQueue.scheduleFlush(FlushQueue.java:37)
	at com.intellij.openapi.application.impl.LaterInvocator.requestFlush(LaterInvocator.java:348)
	at com.intellij.openapi.application.impl.LaterInvocator.invokeLaterWithCallback(LaterInvocator.java:112)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeLater(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeLater(ApplicationImpl.java:304)
	at com.intellij.codeInsight.daemon.impl.HighlightingSessionImpl$1.schedule(HighlightingSessionImpl.java:63)
	at com.intellij.util.containers.TransferToEDTQueue.scheduleUpdate(TransferToEDTQueue.java:156)
	at com.intellij.util.containers.TransferToEDTQueue.offer(TransferToEDTQueue.java:135)
	at com.intellij.codeInsight.daemon.impl.HighlightingSessionImpl.applyInEDT(HighlightingSessionImpl.java:71)
	at com.intellij.codeInsight.daemon.impl.HighlightingSessionImpl.queueHighlightInfo(HighlightingSessionImpl.java:137)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightInfoProcessor.infoIsAvailable(DefaultHighlightInfoProcessor.java:135)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.queueInfoToUpdateIncrementally(GeneralHighlightingPass.java:504)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$1.queueToUpdateIncrementally(GeneralHighlightingPass.java:489)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:357)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:292)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:312)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:315)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:315)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:315)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$analyze$1(HighlightVisitorImpl.java:208)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:362)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:315)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:315)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:315)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:283)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:224)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1109)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:434)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:410)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171)
```

I've also uploaded the entire `idea.log` here, in case it's useful: [idea.log.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/5142513/idea.log.zip)

If there's other information I can provide, let me know!

**Comment by tinder-haroldmartin** [comment]
Looks like Android Studio has been blacklisted... https://github.com/izhangzhihao/intellij-rainbow-brackets/commit/fbf193162e20940610f7045108b2e029c22e11fd

**Comment by JvmName** [comment]
@izhangzhihao can you help me understand why Android Studio support has been removed? If this is temporary in order to fix an issue, I'd love to help however I can.

**Comment by JvmName** [comment]
A note regarding Android Studio 4.2 Alpha 8 is that it sets JDK 11 as the default - I don't know if that changes any decision for you?

**Comment by izhangzhihao** [comment]
Oh, sorry, this line should be removed.

**Comment by JvmName** [comment]
Awesome, thanks so much! 🙏🏾

**Comment by izhangzhihao** [comment]
Please let me know if this snapshot build works for you. 
[intellij-rainbow-brackets-6.9.1.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/5144611/intellij-rainbow-brackets-6.9.1.zip)

**Comment by izhangzhihao** [comment]
Still does not work?

**Comment by JvmName** [comment]
It works! 🎉 Thanks so much!

**Comment by izhangzhihao** [comment]
Great, then, a new release on the way.
