### ISSUE TITLE
[Auto Generated Report]java.lang.IllegalStateException: Decompiled data factory shouldn't be called on an unsupported file: jar://C

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#494]
- Plugin Name: Material Theme UI
- Plugin Version: 6.11
- OS Name: Windows 10
- OS Version: 10.0
- Java Version: 11.0.8
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- Is Snapshot: false
- App Build: IU-203.3645.34
- StackTrace:

```
java.lang.IllegalStateException: Decompiled data factory shouldn't be called on an unsupported file: jar://C:/Users/sebo/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.3.71/898273189ad22779da6bed88ded39b14cb5fd432/kotlin-stdlib-1.3.71.jar!/kotlin/js/JsName.class
	at org.jetbrains.kotlin.idea.decompiler.classFile.DeserializerForClassfileDecompilerKt.DeserializerForClassfileDecompiler(DeserializerForClassfileDecompiler.kt:38)
	at org.jetbrains.kotlin.idea.decompiler.classFile.KotlinClassFileDecompilerKt.buildDecompiledTextForClassFile$default(KotlinClassFileDecompiler.kt:57)
	at org.jetbrains.kotlin.idea.decompiler.classFile.KtClsFile$1.invoke(KotlinClassFileDecompiler.kt:48)
	at org.jetbrains.kotlin.idea.decompiler.classFile.KtClsFile$1.invoke(KotlinClassFileDecompiler.kt:48)
	at org.jetbrains.kotlin.idea.decompiler.KtDecompiledFile$decompiledText$1.invoke(KtDecompiledFile.kt:22)
	at org.jetbrains.kotlin.idea.decompiler.KtDecompiledFile$decompiledText$1.invoke(KtDecompiledFile.kt:16)
	at org.jetbrains.kotlin.utils.concurrent.block.LockedClearableLazyValue.get(concurrent.kt:36)
	at org.jetbrains.kotlin.idea.decompiler.KtDecompiledFile.hasDeclarationWithKey(KtDecompiledFile.kt:42)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledElementKt.findDeclarationInCompiledFile(LightMemberOriginForCompiledElement.kt:110)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledElementKt.access$findDeclarationInCompiledFile(LightMemberOriginForCompiledElement.kt:1)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledMethod$originalElement$2.invoke(LightMemberOriginForCompiledElement.kt:100)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledMethod$originalElement$2.invoke(LightMemberOriginForCompiledElement.kt:81)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledMethod.getOriginalElement(LightMemberOriginForCompiledElement.kt)
	at org.jetbrains.kotlin.asJava.elements.KtLightMemberImpl.getKotlinOrigin(KtLightMemberImpl.kt:62)
	at org.jetbrains.kotlin.asJava.elements.KtLightMemberImpl.getKotlinOrigin(KtLightMemberImpl.kt:35)
	at org.jetbrains.kotlin.asJava.LightClassUtil$getPsiMethodWrappers$2.invoke(LightClassUtil.kt:134)
	at org.jetbrains.kotlin.asJava.LightClassUtil$getPsiMethodWrappers$2.invoke(LightClassUtil.kt:34)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at org.jetbrains.kotlin.asJava.LightClassUtil.extractPropertyAccessors(LightClassUtil.kt:268)
	at org.jetbrains.kotlin.asJava.LightClassUtil.getLightClassPropertyMethods(LightClassUtil.kt:81)
	at org.jetbrains.kotlin.asJava.LightClassUtilKt.getAccessorLightMethods(LightClassUtil.kt:251)
	at org.jetbrains.kotlin.idea.caches.KotlinShortNamesCache$processMethodsWithName$allProcessed$1.process(KotlinShortNamesCache.kt:209)
	at org.jetbrains.kotlin.idea.caches.KotlinShortNamesCache$processMethodsWithName$allProcessed$1.process(KotlinShortNamesCache.kt:40)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:73)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$2(StubIndexImpl.java:288)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:324)
	at org.jetbrains.kotlin.idea.caches.KotlinShortNamesCache.processMethodsWithName(KotlinShortNamesCache.kt:201)
	at com.intellij.psi.impl.CompositeShortNamesCache.processMethodsWithName(CompositeShortNamesCache.java:182)
	at com.intellij.psi.impl.CompositeShortNamesCache.processMethodsWithName(CompositeShortNamesCache.java:173)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportMethodFix.getMembersToImport(StaticImportMethodFix.java:49)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportMemberFix.<init>(StaticImportMemberFix.java:55)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportMethodFix.<init>(StaticImportMethodFix.java:22)
	at com.intellij.codeInsight.intention.impl.config.QuickFixFactoryImpl.createStaticImportMethodFix(QuickFixFactoryImpl.java:502)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightMethodUtil.registerStaticMethodQualifierFixes(HighlightMethodUtil.java:474)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightMethodUtil.registerMethodCallIntentions(HighlightMethodUtil.java:945)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightMethodUtil.checkAmbiguousMethodCallIdentifier(HighlightMethodUtil.java:787)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitReferenceExpression(HighlightVisitorImpl.java:1410)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.accept(PsiReferenceExpressionImpl.java:784)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:185)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:336)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:269)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$analyze$1(HighlightVisitorImpl.java:210)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:370)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:209)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1138)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:62)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:185)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: 
- Plugin Version: 6.12.1
- OS Name: Windows 10
- OS Version: 10.0
- Java Version: 11.0.9
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- Is Snapshot: false
- App Build: IU-203.5784.10
- StackTrace:

```
java.lang.IllegalStateException: Decompiled data factory shouldn't be called on an unsupported file: jar://C:/Program Files/JetBrains/IntelliJ IDEA 203.5600.34/plugins/DatabaseTools/lib/database-dialects.jar!/com/intellij/database/dialects/postgresgreenplumbase/introspector/PgGPlumBaseIntroQueries.class
	at org.jetbrains.kotlin.idea.decompiler.classFile.DeserializerForClassfileDecompilerKt.DeserializerForClassfileDecompiler(DeserializerForClassfileDecompiler.kt:38)
	at org.jetbrains.kotlin.idea.decompiler.classFile.KotlinClassFileDecompilerKt.buildDecompiledTextForClassFile$default(KotlinClassFileDecompiler.kt:57)
	at org.jetbrains.kotlin.idea.decompiler.classFile.KtClsFile$1.invoke(KotlinClassFileDecompiler.kt:48)
	at org.jetbrains.kotlin.idea.decompiler.classFile.KtClsFile$1.invoke(KotlinClassFileDecompiler.kt:48)
	at org.jetbrains.kotlin.idea.decompiler.KtDecompiledFile$decompiledText$1.invoke(KtDecompiledFile.kt:22)
	at org.jetbrains.kotlin.idea.decompiler.KtDecompiledFile$decompiledText$1.invoke(KtDecompiledFile.kt:16)
	at org.jetbrains.kotlin.utils.concurrent.block.LockedClearableLazyValue.get(concurrent.kt:36)
	at org.jetbrains.kotlin.idea.decompiler.KtDecompiledFile.hasDeclarationWithKey(KtDecompiledFile.kt:42)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledElementKt.findDeclarationInCompiledFile(LightMemberOriginForCompiledElement.kt:110)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledMethod$originalElement$2.invoke(LightMemberOriginForCompiledElement.kt:100)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledMethod$originalElement$2.invoke(LightMemberOriginForCompiledElement.kt:81)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledMethod.getOriginalElement(LightMemberOriginForCompiledElement.kt)
	at org.jetbrains.kotlin.idea.caches.lightClasses.decompiledDeclarations.KtLightMethodForDecompiledDeclaration.getKotlinOrigin(KtLightMethodForDecompiledDeclaration.kt:28)
	at org.jetbrains.kotlin.idea.caches.lightClasses.decompiledDeclarations.KtLightMethodForDecompiledDeclaration.getKotlinOrigin(KtLightMethodForDecompiledDeclaration.kt:22)
	at org.jetbrains.kotlin.asJava.LightClassUtil$getPsiMethodWrappers$2.invoke(LightClassUtil.kt:134)
	at org.jetbrains.kotlin.asJava.LightClassUtil$getPsiMethodWrappers$2.invoke(LightClassUtil.kt:34)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at org.jetbrains.kotlin.asJava.LightClassUtil.extractPropertyAccessors(LightClassUtil.kt:268)
	at org.jetbrains.kotlin.asJava.LightClassUtil.getLightClassPropertyMethods(LightClassUtil.kt:81)
	at org.jetbrains.kotlin.asJava.LightClassUtilKt.getAccessorLightMethods(LightClassUtil.kt:251)
	at org.jetbrains.kotlin.idea.caches.KotlinShortNamesCache$processMethodsWithName$allProcessed$1.process(KotlinShortNamesCache.kt:209)
	at org.jetbrains.kotlin.idea.caches.KotlinShortNamesCache$processMethodsWithName$allProcessed$1.process(KotlinShortNamesCache.kt:40)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:73)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$2(StubIndexImpl.java:289)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:325)
	at org.jetbrains.kotlin.idea.caches.KotlinShortNamesCache.processMethodsWithName(KotlinShortNamesCache.kt:201)
	at org.jetbrains.kotlin.idea.caches.KotlinShortNamesCache.getMethodsByNameIfNotMoreThan(KotlinShortNamesCache.kt:237)
	at com.intellij.psi.impl.CompositeShortNamesCache.getMethodsByNameIfNotMoreThan(CompositeShortNamesCache.java:145)
	at com.intellij.codeInsight.ExpectedTypesProvider$1.findDeclaredMethods(ExpectedTypesProvider.java:71)
	at com.intellij.codeInsight.ExpectedTypesProvider$MyParentVisitor.findClassesWithDeclaredMethod(ExpectedTypesProvider.java:1282)
	at com.intellij.codeInsight.ExpectedTypesProvider$MyParentVisitor.visitReferenceExpression(ExpectedTypesProvider.java:326)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.accept(PsiReferenceExpressionImpl.java:778)
	at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:153)
	at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:126)
	at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:115)
	at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:111)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticMembersProcessor.getExpectedTypes(StaticMembersProcessor.java:67)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticMembersProcessor.isApplicableFor(StaticMembersProcessor.java:77)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportConstantFix$1.isApplicable(StaticImportConstantFix.java:70)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportConstantFix$1.isApplicable(StaticImportConstantFix.java:65)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticMembersProcessor.registerMember(StaticMembersProcessor.java:154)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticMembersProcessor.getMembersToImport(StaticMembersProcessor.java:56)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportConstantFix.getMembersToImport(StaticImportConstantFix.java:74)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportMemberFix.<init>(StaticImportMemberFix.java:55)
	at com.intellij.codeInsight.daemon.impl.quickfix.StaticImportConstantFix.<init>(StaticImportConstantFix.java:35)
	at com.intellij.codeInsight.daemon.impl.quickfix.DefaultQuickFixProvider.registerFixes(DefaultQuickFixProvider.java:40)
	at com.intellij.codeInsight.daemon.impl.quickfix.DefaultQuickFixProvider.registerFixes(DefaultQuickFixProvider.java:24)
	at com.intellij.codeInsight.quickfix.UnresolvedReferenceQuickFixProvider.registerReferenceFixes(UnresolvedReferenceQuickFixProvider.java:27)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightUtil.checkReference(HighlightUtil.java:3145)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.doVisitReferenceElement(HighlightVisitorImpl.java:1200)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitReferenceExpression(HighlightVisitorImpl.java:1374)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.accept(PsiReferenceExpressionImpl.java:778)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:185)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:336)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:269)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$analyze$1(HighlightVisitorImpl.java:210)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:370)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:209)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
