### ISSUE TITLE
Exception in v5.7

### ISSUE THREAD

**Issue by mikemand** [izhangzhihao/intellij-rainbow-brackets#60]
## Your programming language
PHP

## Expected Behavior
No exceptions.

## Current Behavior
When holding down cmd to navigate to a definition, the IDE locks up for a second and once it comes back, there is an exception with the message: `org/jetbrains/kotlin/psi/psiUtil/PsiUtilsKt` and stack trace:

```
org/jetbrains/kotlin/psi/psiUtil/PsiUtilsKt
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/psi/psiUtil/PsiUtilsKt
	at com.github.izhangzhihao.rainbow.brackets.RainbowInfo.containsOffset(RainbowInfo.kt:38)
	at com.github.izhangzhihao.rainbow.brackets.CtrlHandler$Companion.getRainbowInfo(CtrlHandler.kt:118)
	at com.github.izhangzhihao.rainbow.brackets.CtrlHandler$Companion.findRainbowInfoAt(CtrlHandler.kt:110)
	at com.github.izhangzhihao.rainbow.brackets.CtrlHandler$Companion.access$findRainbowInfoAt(CtrlHandler.kt:97)
	at com.github.izhangzhihao.rainbow.brackets.CtrlHandler.addHighlightAt(CtrlHandler.kt:65)
	at com.github.izhangzhihao.rainbow.brackets.CtrlHandler.onKeyPressed(CtrlHandler.kt:50)
	at com.github.izhangzhihao.rainbow.brackets.EditorEventActionManager$EventListener.keyPressed(EditorEventActionManager.kt:70)
	at java.awt.AWTEventMulticaster.keyPressed(AWTEventMulticaster.java:250)
	at java.awt.Component.processKeyEvent(Component.java:6506)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2833)
	at java.awt.Component.processEvent(Component.java:6325)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:27)
	at java.awt.Component.dispatchEventImpl(Component.java:4774)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.p(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.psi.psiUtil.PsiUtilsKt PluginClassLoader[izhangzhihao.rainbow.brackets, 5.7] com.intellij.ide.plugins.cl.PluginClassLoader@36d96be
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 46 more
```

## Code snippet for reproduce (for bugs)
Please provide code snippet

```php
/** @var Collection $roles */
$roles = $this->roles->all()->load('users')->reject(function (RoleInterface $role) {
    return in_array($role->getRoleSlug(), [
        'admin',
        'client',
    ]);
});
```

## Your Environment

* Plugin version: v5.7
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
PhpStorm 2018.1.3
Build #PS-181.4892.97, built on May 9, 2018
JRE: 1.8.0_152-release-1136-b38 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4
```

**NOTE: If you are reporting a performance issue, please comment your hardware env like this:**

```
iMac (21.5-inch, Mid 2014)
CPU: 1.4 GHz Intel Core i5
Total Number of Cores: 4
Memory: 8 GB 1600 MHz DDR3
Storage: 256GB SATA SSD
Graphics: Intel HD Graphics 5000 1536 MB
```

**Comment by izhangzhihao** [comment]
A simple workaround is try to install the "kotlin plugin" for this moment, we will look into this later.

**Comment by YiiGuxing** [comment]
@mikemand  As a temporary solution, you can disable this option:
![1](https://user-images.githubusercontent.com/10737066/40030772-05fb390a-581f-11e8-9d0f-3df6a7ded70e.png)

**Comment by YiiGuxing** [comment]
@izhangzhihao 发布一个紧急bug修复版本吧，用手动上传发布，这样就不用等官方审核了。

**Comment by izhangzhihao** [comment]
A new release just published [here](https://github.com/izhangzhihao/intellij-rainbow-brackets/releases/tag/5.7.1).

**Comment by mikemand** [comment]
Thank you for the temporary workaround, @YiiGuxing. And thank you for the quick fix, @izhangzhihao.
