### ISSUE TITLE
[Auto Generated Report]java.lang.AssertionError: LinkedHashMap.Entry was not removed. Possibly mutable key: com.intellij.spring.model.SpringModelSearchParameters.BeanClass{myType=PsiType

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#724]
- Plugin Name: Material Theme UI
- Plugin Version: 6.12.1
- OS Name: Windows 10
- OS Version: 10.0
- Java Version: 11.0.9
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- Is Snapshot: false
- App Build: IU-203.5981.155
- StackTrace:

```
java.lang.AssertionError: LinkedHashMap.Entry was not removed. Possibly mutable key: com.intellij.spring.model.SpringModelSearchParameters.BeanClass{myType=PsiType:PostModel, myOptions=7}
	at com.intellij.util.containers.hash.LinkedHashMap.doRemoveEldestEntry(LinkedHashMap.java:138)
	at com.intellij.util.containers.hash.LinkedHashMap.put(LinkedHashMap.java:128)
	at com.intellij.util.containers.SLRUMap.putToProtectedQueue(SLRUMap.java:98)
	at com.intellij.util.containers.SLRUMap.get(SLRUMap.java:89)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$SpringSLRUCache.getCachedValue(SpringCachingProcessor.java:119)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$SpringSLRUCache.get(SpringCachingProcessor.java:105)
	at com.intellij.spring.contexts.model.SpringCachingProcessor.process(SpringCachingProcessor.java:74)
	at com.intellij.spring.contexts.model.LocalXmlModelIndexProcessor.processInheritors(LocalXmlModelIndexProcessor.java:191)
	at com.intellij.spring.contexts.model.LocalXmlModelIndexProcessor.processByClass(LocalXmlModelIndexProcessor.java:165)
	at com.intellij.spring.contexts.model.LocalXmlModelImpl.processLocalBeansByClass(LocalXmlModelImpl.java:373)
	at com.intellij.spring.contexts.model.LocalXmlModelImpl.processLocalBeansByClass(LocalXmlModelImpl.java:367)
	at com.intellij.spring.contexts.model.LocalXmlModelImpl.processByClass(LocalXmlModelImpl.java:352)
	at com.intellij.spring.contexts.model.AbstractProcessableModel.lambda$processByClass$0(AbstractProcessableModel.java:26)
	at com.intellij.spring.contexts.model.visitors.CommonSpringModelVisitorContext.visit(CommonSpringModelVisitorContext.java:30)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:50)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:59)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:51)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:59)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:51)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelatedModels(SpringModelVisitors.java:30)
	at com.intellij.spring.contexts.model.AbstractProcessableModel.processByClass(AbstractProcessableModel.java:26)
	at com.intellij.spring.model.utils.SpringModelSearchers.findBeans(SpringModelSearchers.java:47)
	at com.intellij.spring.web.mvc.services.SpringMvcServiceImpl.lambda$getResolvers$7(SpringMvcServiceImpl.java:148)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at one.util.streamex.AbstractStreamEx.forEach(AbstractStreamEx.java:314)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at one.util.streamex.TailConcatSpliterator.forEachRemaining(TailConcatSpliterator.java:75)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at one.util.streamex.AbstractStreamEx.rawCollect(AbstractStreamEx.java:68)
	at one.util.streamex.AbstractStreamEx.toSet(AbstractStreamEx.java:1251)
	at one.util.streamex.AbstractStreamEx.toImmutableSet(AbstractStreamEx.java:1269)
	at com.intellij.spring.web.mvc.services.SpringMvcServiceImpl.lambda$getViewResolvers$3(SpringMvcServiceImpl.java:98)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:78)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:110)
	at com.intellij.spring.web.mvc.services.SpringMvcServiceImpl.getViewResolvers(SpringMvcServiceImpl.java:96)
	at com.intellij.spring.web.mvc.views.SpringMVCViewReferenceProvider.getReferencesByElement(SpringMVCViewReferenceProvider.java:62)
	at com.intellij.spring.web.mvc.views.SpringMVCViewUastReferenceProvider.getReferencesForInjectionHost(SpringMVCViewUastReferenceProvider.java:98)
	at com.intellij.psi.UastInjectionHostReferenceProvider.getReferencesByElement(UastInjectionHostReferenceProvider.kt:16)
	at com.intellij.psi.UastReferenceProviderAdapter.getReferencesByElement(UastReferenceProviderAdapter.kt:12)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:204)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:167)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:146)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:39)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:153)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:78)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:120)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
	at com.intellij.psi.PsiReferenceServiceImpl.doGetReferences(PsiReferenceServiceImpl.java:35)
	at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:27)
	at com.intellij.psi.PsiReferenceService.getContributedReferences(PsiReferenceService.java:34)
	at com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl.getReferences(PsiLiteralExpressionImpl.java:193)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:45)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:336)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:275)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$analyze$1(HighlightVisitorImpl.java:210)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:370)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:209)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: Material Theme UI
- Plugin Version: 6.13
- OS Name: Windows 10
- OS Version: 10.0
- Java Version: 11.0.9
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- Is Snapshot: false
- App Build: IU-203.5981.155
- StackTrace:

```
java.lang.AssertionError: LinkedHashMap.Entry was not removed. Possibly mutable key: com.intellij.spring.model.SpringModelSearchParameters.BeanClass{myType=PsiType:ClientDataLoader, myOptions=7}
	at com.intellij.util.containers.hash.LinkedHashMap.doRemoveEldestEntry(LinkedHashMap.java:138)
	at com.intellij.util.containers.hash.LinkedHashMap.put(LinkedHashMap.java:128)
	at com.intellij.util.containers.SLRUMap.putToProtectedQueue(SLRUMap.java:98)
	at com.intellij.util.containers.SLRUMap.get(SLRUMap.java:89)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$SpringSLRUCache.getCachedValue(SpringCachingProcessor.java:119)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$SpringSLRUCache.get(SpringCachingProcessor.java:105)
	at com.intellij.spring.contexts.model.SpringCachingProcessor.process(SpringCachingProcessor.java:74)
	at com.intellij.spring.contexts.model.LocalXmlModelIndexProcessor.processInheritors(LocalXmlModelIndexProcessor.java:191)
	at com.intellij.spring.contexts.model.LocalXmlModelIndexProcessor.processByClass(LocalXmlModelIndexProcessor.java:165)
	at com.intellij.spring.contexts.model.LocalXmlModelImpl.processLocalBeansByClass(LocalXmlModelImpl.java:373)
	at com.intellij.spring.contexts.model.LocalXmlModelImpl.processLocalBeansByClass(LocalXmlModelImpl.java:367)
	at com.intellij.spring.contexts.model.LocalXmlModelImpl.processByClass(LocalXmlModelImpl.java:352)
	at com.intellij.spring.contexts.model.AbstractProcessableModel.lambda$processByClass$0(AbstractProcessableModel.java:26)
	at com.intellij.spring.contexts.model.visitors.CommonSpringModelVisitorContext.visit(CommonSpringModelVisitorContext.java:30)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:50)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:59)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:51)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelatedModels(SpringModelVisitors.java:30)
	at com.intellij.spring.contexts.model.AbstractProcessableModel.processByClass(AbstractProcessableModel.java:26)
	at com.intellij.spring.model.utils.SpringModelSearchers.findBeans(SpringModelSearchers.java:47)
	at com.intellij.spring.model.utils.SpringAutowireUtil.autowireByType(SpringAutowireUtil.java:531)
	at com.intellij.spring.model.xml.beans.impl.ResolvedConstructorArgsImpl.resolve(ResolvedConstructorArgsImpl.java:194)
	at com.intellij.spring.model.xml.beans.impl.ResolvedConstructorArgsImpl.<init>(ResolvedConstructorArgsImpl.java:64)
	at com.intellij.spring.model.xml.beans.impl.SpringBeanImpl.lambda$getResolvedConstructorArgs$1(SpringBeanImpl.java:204)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:78)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:110)
	at com.intellij.spring.model.xml.beans.impl.SpringBeanImpl.getResolvedConstructorArgs(SpringBeanImpl.java:204)
	at com.intellij.spring.model.xml.beans.impl.ConstructorArgImpl.getRequiredTypes(ConstructorArgImpl.java:166)
	at com.intellij.spring.model.xml.beans.TypeHolderUtil.lambda$getRequiredTypes$0(TypeHolderUtil.java:42)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:78)
	at com.intellij.spring.model.xml.beans.TypeHolderUtil.getRequiredTypes(TypeHolderUtil.java:41)
	at com.intellij.spring.model.values.PropertyValueConverter.getValueTypes(PropertyValueConverter.java:76)
	at com.intellij.spring.model.values.PropertyValueConverter.getConverters(PropertyValueConverter.java:47)
	at com.intellij.spring.model.values.PropertyValueConverter.getConverter(PropertyValueConverter.java:31)
	at com.intellij.util.xml.WrappingConverter.getDeepestConverter(WrappingConverter.java:73)
	at com.intellij.util.xml.impl.GenericValueReferenceProvider.getReferencesByElement(GenericValueReferenceProvider.java:68)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:204)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:167)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:146)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:39)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:153)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:78)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:120)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
	at com.intellij.psi.impl.source.xml.XmlAttributeValueImpl.getReferences(XmlAttributeValueImpl.java:80)
	at com.intellij.psi.impl.source.xml.XmlAttributeValueImpl.getReferences(XmlAttributeValueImpl.java:90)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:45)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:336)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:275)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:601)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
