### ISSUE TITLE
[auto-generated:1817050667] .
 parent=.

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#82]
- Plugin Name: Rainbow Brackets
- Plugin Version: 5.8.1
- OS Name: Mac OS X
- OS Version: 10.13.4
- Java Version: 1.8.0_152-release
- App Name: AppCode
- App Full Name: AppCode
- Is Snapshot: false
- App Build: OC-182.2757.9
- Last Action: null

```
java.lang.Throwable: .
 parent=.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:285)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.findNotNullChildByType(ASTDelegatePsiElement.java:215)
	at com.jetbrains.swift.psi.impl.expression.SwiftImplicitMemberExpressionImpl.getNameElement(SwiftImplicitMemberExpressionImpl.java:61)
	at com.jetbrains.swift.psi.impl.expression.SwiftImplicitMemberExpressionImpl.createSwiftReference(SwiftImplicitMemberExpressionImpl.java:88)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.getReference(SwiftSymbolsManagerImpl.java:261)
	at com.jetbrains.swift.psi.impl.SwiftReferenceElementBase.getSwiftReference(SwiftReferenceElementBase.java:77)
	at com.jetbrains.swift.psi.impl.SwiftReferenceElementBase.doMultiResolve(SwiftReferenceElementBase.java:117)
	at com.jetbrains.swift.psi.impl.expression.SwiftImplicitMemberExpressionImpl$1.fun(SwiftImplicitMemberExpressionImpl.java:32)
	at com.jetbrains.swift.psi.impl.expression.SwiftImplicitMemberExpressionImpl$1.fun(SwiftImplicitMemberExpressionImpl.java:28)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.a(SwiftSymbolsManagerImpl.java:180)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.a(SwiftSymbolsManagerImpl.java:202)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:96)
	at com.jetbrains.swift.codeinsight.resolve.recursive.DependencyManager.run(DependencyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.b(RecursiveResolveContext.java:90)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:66)
	at com.jetbrains.swift.codeinsight.resolve.recursive.KeyManager.doWithKey(KeyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.cacheOrGet(RecursiveResolveContext.java:65)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.getType(SwiftSymbolsManagerImpl.java:202)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.getType(SwiftSymbolsManagerImpl.java:180)
	at com.jetbrains.swift.psi.impl.expression.SwiftImplicitMemberExpressionImpl.getType(SwiftImplicitMemberExpressionImpl.java:81)
	at com.jetbrains.swift.symbols.impl.SwiftArgumentSymbol.getSwiftType(SwiftArgumentSymbol.java:55)
	at com.jetbrains.swift.psi.impl.types.DelegatingTupleItem.getSwiftType(DelegatingTupleItem.java:35)
	at com.jetbrains.swift.psi.impl.types.sequence.SwiftFunctionCallMapper.checkTypes(SwiftFunctionCallMapper.java:218)
	at com.jetbrains.swift.psi.impl.types.sequence.SwiftFunctionCallMapper.checkTypes(SwiftFunctionCallMapper.java:214)
	at com.jetbrains.swift.psi.impl.types.sequence.SwiftFunctionCallMapper.checkStrong(SwiftFunctionCallMapper.java:188)
	at com.jetbrains.swift.psi.impl.types.sequence.Swift3FunctionCallMapper.checkStrong(Swift3FunctionCallMapper.kt:27)
	at com.jetbrains.swift.psi.impl.types.sequence.SwiftFunctionCallMapper.a(SwiftFunctionCallMapper.java:95)
	at com.jetbrains.swift.psi.impl.types.sequence.SwiftFunctionCallMapper.map(SwiftFunctionCallMapper.java:67)
	at com.jetbrains.swift.psi.impl.types.SwiftFunctionDomainTypeImpl.mapTupleArguments(SwiftFunctionDomainTypeImpl.java:127)
	at com.jetbrains.swift.codeinsight.resolve.recursive.TypeEquation$DefaultImpls.a(TypeEquation.kt:44)
	at com.jetbrains.swift.codeinsight.resolve.recursive.TypeEquation$DefaultImpls.resolve(TypeEquation.kt:32)
	at com.jetbrains.swift.codeinsight.resolve.recursive.ConcreteTypeEquation.resolve(ConcreteTypeEquation.kt:7)
	at com.jetbrains.swift.codeinsight.resolve.recursive.ResolveSession.a(ResolveSession.kt:66)
	at com.jetbrains.swift.codeinsight.resolve.recursive.ResolveSession.resolve(ResolveSession.kt:31)
	at com.jetbrains.swift.codeinsight.resolve.recursive.GenericResolverImpl.resolveEquations(GenericResolverImpl.kt:27)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:44)
	at com.jetbrains.swift.codeinsight.resolve.recursive.StackCacheManager.runOnNewStackFrame(StackCacheManager.java:49)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.tryRecursiveGenericInference(RecursiveResolveContext.java:38)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftRecursiveResolverProcessor.f(SwiftRecursiveResolverProcessor.java:266)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftRecursiveResolverProcessor.a(SwiftRecursiveResolverProcessor.java:167)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftRecursiveResolverProcessor.getResults(SwiftRecursiveResolverProcessor.java:159)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftCallableResolverProcessor.getResults(SwiftCallableResolverProcessor.java:47)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceImpl.resolve(SwiftReferenceImpl.java:338)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceImpl.multiResolve(SwiftReferenceImpl.java:84)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftCallableReferenceBase.multiResolve(SwiftCallableReferenceBase.java:136)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.a(SwiftSymbolsManagerImpl.java:224)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.b(SwiftSymbolsManagerImpl.java:218)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:96)
	at com.jetbrains.swift.codeinsight.resolve.recursive.DependencyManager.run(DependencyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.b(RecursiveResolveContext.java:90)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:66)
	at com.jetbrains.swift.codeinsight.resolve.recursive.KeyManager.doWithKey(KeyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.cacheOrGet(RecursiveResolveContext.java:65)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.multiResolve(SwiftSymbolsManagerImpl.java:218)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceBase.multiResolve(SwiftReferenceBase.java:236)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:147)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:93)
	at com.jetbrains.swift.codeinsight.resolve.recursive.DependencyManager.run(DependencyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.b(RecursiveResolveContext.java:90)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:66)
	at com.jetbrains.swift.codeinsight.resolve.recursive.KeyManager.doWithKey(KeyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.cacheOrGet(RecursiveResolveContext.java:65)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.multiResolve(SwiftSymbolsManagerImpl.java:218)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceBase.multiResolve(SwiftReferenceBase.java:236)
	at com.jetbrains.swift.codeinsight.resolve.SwiftExpectedTypeProvider$MyVisitor.visitReferenceExpression(SwiftExpectedTypeProvider.java:663)
	at com.jetbrains.swift.psi.impl.SwiftReferenceExpressionGenImpl.accept(SwiftReferenceExpressionGenImpl.java:21)
	at com.jetbrains.swift.psi.impl.SwiftReferenceExpressionGenImpl.accept(SwiftReferenceExpressionGenImpl.java:25)
	at com.jetbrains.swift.codeinsight.resolve.SwiftExpectedTypeProvider.getExpectedTypes(SwiftExpectedTypeProvider.java:49)
	at com.jetbrains.swift.codeinsight.resolve.SwiftExpectedTypeProvider.getExpectedTypes(SwiftExpectedTypeProvider.java:38)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftCallableReferenceBase$1.getExpectedTypes(SwiftCallableReferenceBase.java:60)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftDelegatingCallableReferenceInfo.getExpectedTypes(SwiftDelegatingCallableReferenceInfo.kt:13)
	at com.jetbrains.swift.codeinsight.resolve.processor.GenericValueImpl.a(GenericValueImpl.java:95)
	at com.jetbrains.swift.codeinsight.resolve.recursive.AdditionalLazyTypeEquation.getActualType(LazyTypeEquation.kt:24)
	at com.jetbrains.swift.codeinsight.resolve.recursive.TypeEquation$DefaultImpls.applySubstitutor(TypeEquation.kt:59)
	at com.jetbrains.swift.codeinsight.resolve.recursive.AdditionalLazyTypeEquation.applySubstitutor(LazyTypeEquation.kt:19)
	at com.jetbrains.swift.codeinsight.resolve.recursive.ResolveSession.a(ResolveSession.kt:64)
	at com.jetbrains.swift.codeinsight.resolve.recursive.ResolveSession.resolve(ResolveSession.kt:31)
	at com.jetbrains.swift.codeinsight.resolve.recursive.GenericResolverImpl.resolveEquations(GenericResolverImpl.kt:27)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:44)
	at com.jetbrains.swift.codeinsight.resolve.recursive.StackCacheManager.runOnNewStackFrame(StackCacheManager.java:49)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.tryRecursiveGenericInference(RecursiveResolveContext.java:38)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftRecursiveResolverProcessor.f(SwiftRecursiveResolverProcessor.java:266)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftRecursiveResolverProcessor.a(SwiftRecursiveResolverProcessor.java:167)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftRecursiveResolverProcessor.getResults(SwiftRecursiveResolverProcessor.java:159)
	at com.jetbrains.swift.codeinsight.resolve.processor.SwiftCallableResolverProcessor.getResults(SwiftCallableResolverProcessor.java:47)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceImpl.resolve(SwiftReferenceImpl.java:338)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceImpl.multiResolve(SwiftReferenceImpl.java:84)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftCallableReferenceBase.multiResolve(SwiftCallableReferenceBase.java:136)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.a(SwiftSymbolsManagerImpl.java:224)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.b(SwiftSymbolsManagerImpl.java:218)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:96)
	at com.jetbrains.swift.codeinsight.resolve.recursive.DependencyManager.run(DependencyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.b(RecursiveResolveContext.java:90)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.a(RecursiveResolveContext.java:66)
	at com.jetbrains.swift.codeinsight.resolve.recursive.KeyManager.doWithKey(KeyManager.java:23)
	at com.jetbrains.swift.codeinsight.resolve.recursive.RecursiveResolveContext.cacheOrGet(RecursiveResolveContext.java:65)
	at com.jetbrains.swift.codeinsight.resolve.SwiftSymbolsManagerImpl.multiResolve(SwiftSymbolsManagerImpl.java:218)
	at com.jetbrains.swift.codeinsight.resolve.reference.SwiftReferenceBase.multiResolve(SwiftReferenceBase.java:236)
	at com.jetbrains.swift.psi.impl.SwiftReferenceElementBase.doMultiResolve(SwiftReferenceElementBase.java:118)
	at com.jetbrains.swift.psi.impl.SwiftReferenceElementBase.advancedResolve(SwiftReferenceElementBase.java:102)
	at com.jetbrains.swift.codeinsight.highlighting.SwiftColorAnnotator.annotate(SwiftColorAnnotator.java:112)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:366)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:304)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:33)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.RainbowVisitor.analyze(RainbowVisitor.java:50)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.e(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by izhangzhihao** [comment]
See #81
