### ISSUE TITLE
[auto-generated:284237708] superClassSubstitutor requested when derived doesn't extend super:
Super: android.media.SubtitleController.Listener(com.intellij.psi.impl.source.PsiClassImpl; file://C:/Users/ramze/AppData/Local/Android/Sdk/sources/android-27/android/media/SubtitleController.java);
extends: 
implements: 
Derived: android.media.MediaPlayer(com.intellij.psi.impl.source.PsiClassImpl; file://C:/Users/ramze/AppData/Local/Android/Sdk/sources/android-27/android/media/MediaPlayer.java);
extends: PsiType:PlayerBase (com.intellij.psi.impl.source.PsiClassReferenceType; PsiClass:PlayerBase) 
implements: PsiType:Listener (com.intellij.psi.impl.source.PsiClassReferenceType; PsiClass:Listener) PsiType:VolumeAutomation (com.intellij.psi.impl.source.PsiClassReferenceType; PsiClass:VolumeAutomation) 
isInheritor: false false
Super in derived's scope: true
Plain derived's supers contain Super:
Hierarchy:


### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#83]
- Plugin Name: Rainbow Brackets
- Plugin Version: 5.8.1
- OS Name: Windows 10
- OS Version: 10.0
- Java Version: 1.8.0_152-release
- App Name: Studio
- App Full Name: Android Studio
- Is Snapshot: false
- App Build: AI-181.4668.68.32.4802120
- Last Action: null

```
java.lang.Throwable: superClassSubstitutor requested when derived doesn't extend super:
Super: android.media.SubtitleController.Listener(com.intellij.psi.impl.source.PsiClassImpl; file://C:/Users/ramze/AppData/Local/Android/Sdk/sources/android-27/android/media/SubtitleController.java);
extends: 
implements: 
Derived: android.media.MediaPlayer(com.intellij.psi.impl.source.PsiClassImpl; file://C:/Users/ramze/AppData/Local/Android/Sdk/sources/android-27/android/media/MediaPlayer.java);
extends: PsiType:PlayerBase (com.intellij.psi.impl.source.PsiClassReferenceType; PsiClass:PlayerBase) 
implements: PsiType:Listener (com.intellij.psi.impl.source.PsiClassReferenceType; PsiClass:Listener) PsiType:VolumeAutomation (com.intellij.psi.impl.source.PsiClassReferenceType; PsiClass:VolumeAutomation) 
isInheritor: false false
Super in derived's scope: true
Plain derived's supers contain Super:
Hierarchy:

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:131)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:92)
	at com.intellij.psi.impl.JavaClassSupersImpl.reportHierarchyInconsistency(JavaClassSupersImpl.java:211)
	at com.intellij.psi.util.TypeConversionUtil.getSuperClassSubstitutor(TypeConversionUtil.java:1095)
	at com.intellij.psi.util.PsiSuperMethodUtil.collectOverrideEquivalents(PsiSuperMethodUtil.java:124)
	at com.intellij.codeInsight.daemon.impl.analysis.GenericsHighlightUtil.checkUnrelatedDefaultMethods(GenericsHighlightUtil.java:431)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitIdentifier(HighlightVisitorImpl.java:657)
	at com.intellij.psi.impl.source.tree.java.PsiIdentifierImpl.accept(PsiIdentifierImpl.java:39)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:136)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:371)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:333)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:33)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$analyze$2(HighlightVisitorImpl.java:161)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:336)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:160)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:239)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by izhangzhihao** [comment]
I think this error is not because of our side...
