### ISSUE TITLE
[Auto Generated Report]java.lang.IllegalArgumentException: Wrong end

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#843]
- Plugin Name: 
- Plugin Version: 6.13
- OS Name: Windows 10
- OS Version: 10.0
- Java Version: 11.0.8
- App Name: Studio
- App Full Name: Android Studio
- Is Snapshot: false
- App Build: AI-202.7660.26.42.7033425
- StackTrace:

```
java.lang.IllegalArgumentException: Wrong end: 2390; document length=2387; start=676
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:62)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:38)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.<init>(RangeHighlighterImpl.java:72)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighterAndChangeAttributes(MarkupModelImpl.java:154)
	at com.intellij.codeInsight.highlighting.HighlightManagerImpl.addOccurrenceHighlight(HighlightManagerImpl.java:197)
	at com.intellij.codeInsight.highlighting.HighlightManagerImpl.addRangeHighlight(HighlightManagerImpl.java:279)
	at com.intellij.codeInsight.highlighting.HighlightManagerImpl.addRangeHighlight(HighlightManagerImpl.java:247)
	at com.github.izhangzhihao.rainbow.brackets.action.ScopeHighlightingAction.addHighlighter(ScopeHighlightingAction.kt:24)
	at com.github.izhangzhihao.rainbow.brackets.action.AbstractScopeHighlightingAction.actionPerformed(AbstractScopeHighlightingAction.kt:34)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:276)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:905)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:838)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:808)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:505)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: 
- Plugin Version: 6.13
- OS Name: Windows 10
- OS Version: 10.0
- Java Version: 1.8.0_242-release
- App Name: Studio
- App Full Name: Android Studio
- Is Snapshot: false
- App Build: AI-201.8743.12.41.7042882
- StackTrace:

```
java.lang.IllegalArgumentException: Wrong end: 3912; document length=3907; start=855
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:60)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:36)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.<init>(RangeHighlighterImpl.java:68)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighterAndChangeAttributes(MarkupModelImpl.java:114)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighter(MarkupModelImpl.java:165)
	at com.intellij.codeInsight.highlighting.HighlightManagerImpl.addSegmentHighlighter(HighlightManagerImpl.java:99)
	at com.intellij.codeInsight.highlighting.HighlightManagerImpl.addOccurrenceHighlight(HighlightManagerImpl.java:163)
	at com.intellij.codeInsight.highlighting.HighlightManagerImpl.addRangeHighlight(HighlightManagerImpl.java:203)
	at com.github.izhangzhihao.rainbow.brackets.action.ScopeHighlightingAction.addHighlighter(ScopeHighlightingAction.kt:24)
	at com.github.izhangzhihao.rainbow.brackets.action.AbstractScopeHighlightingAction.actionPerformed(AbstractScopeHighlightingAction.kt:34)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:276)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by izhangzhihao** [comment]
I don't know how to reproduce this issue...

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: Material Theme UI
- Plugin Version: 6.17
- OS Name: Windows 10
- OS Version: 10.0
- Java Version: 11.0.10
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- Is Snapshot: false
- App Build: IU-211.6693.111
- StackTrace:

```
java.lang.IllegalArgumentException: Wrong end: 4849; document length=4829; start=3949
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:62)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:38)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.<init>(RangeHighlighterImpl.java:74)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighterAndChangeAttributes(MarkupModelImpl.java:158)
	at com.intellij.codeInsight.highlighting.HighlightManagerImpl.addOccurrenceHighlight(HighlightManagerImpl.java:198)
	at com.intellij.codeInsight.highlighting.HighlightManagerImpl.addRangeHighlight(HighlightManagerImpl.java:281)
	at com.intellij.codeInsight.highlighting.HighlightManagerImpl.addRangeHighlight(HighlightManagerImpl.java:249)
	at com.github.izhangzhihao.rainbow.brackets.action.ScopeHighlightingAction.addHighlighter(ScopeHighlightingAction.kt:24)
	at com.github.izhangzhihao.rainbow.brackets.action.AbstractScopeHighlightingAction.actionPerformed(AbstractScopeHighlightingAction.kt:34)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:277)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:905)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by intellij-rainbow-brackets** [comment]
- Plugin Name: 
- Plugin Version: 6.17
- OS Name: Mac OS X
- OS Version: 11.4
- Java Version: 11.0.11
- App Name: WebStorm
- App Full Name: WebStorm
- Is Snapshot: false
- App Build: WS-211.7442.26
- StackTrace:

```
java.lang.IllegalArgumentException: Wrong end: 4998; document length=4644; start=4219
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:62)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:38)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.<init>(RangeHighlighterImpl.java:74)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighterAndChangeAttributes(MarkupModelImpl.java:158)
	at com.intellij.codeInsight.highlighting.HighlightManagerImpl.addOccurrenceHighlight(HighlightManagerImpl.java:198)
	at com.intellij.codeInsight.highlighting.HighlightManagerImpl.addRangeHighlight(HighlightManagerImpl.java:281)
	at com.intellij.codeInsight.highlighting.HighlightManagerImpl.addRangeHighlight(HighlightManagerImpl.java:249)
	at com.github.izhangzhihao.rainbow.brackets.action.ScopeHighlightingAction.addHighlighter(ScopeHighlightingAction.kt:24)
	at com.github.izhangzhihao.rainbow.brackets.action.AbstractScopeHighlightingAction.actionPerformed(AbstractScopeHighlightingAction.kt:34)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:277)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:905)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
