### ISSUE TITLE
[auto-generated:-1401158982] In file: file://F:/Code/sik-radio/proto_control.h: Nested updates are not allowed for root files.

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [izhangzhihao/intellij-rainbow-brackets#93]
- Plugin Name: Rainbow Brackets
- Plugin Version: 5.8.2
- OS Name: Windows 10
- OS Version: 10.0
- Java Version: 1.8.0_152-release
- App Name: CLion
- App Full Name: CLion
- Is Snapshot: false
- App Build: CL-181.5087.36
- Last Action: RenameElement

```
java.lang.IllegalStateException: Nested updates are not allowed for root files.
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTableUpdater.ensurePendingFilesProcessed(FileSymbolTableUpdater.java:50)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache.ensurePendingFilesProcessed(FileSymbolTablesCache.java:721)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph$Cache.a(OCImportGraph.java:404)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph$Cache.a(OCImportGraph.java:367)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph$Cache.get(OCImportGraph.java:312)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph.findImmediateIncludingFiles(OCImportGraph.java:277)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph.a(OCImportGraph.java:232)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph.findAllRootsThatIncludes(OCImportGraph.java:267)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph.getAllHeaderRoots(OCImportGraph.java:62)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextUtil.a(OCInclusionContextUtil.java:200)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextUtil.getResolveRootAndActiveConfiguration(OCInclusionContextUtil.java:170)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextUtil$1.a(OCInclusionContextUtil.java:61)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextUtil$1.compute(OCInclusionContextUtil.java:49)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextUtil.getActiveConfiguration(OCInclusionContextUtil.java:434)
	at com.jetbrains.cidr.lang.workspace.OCLanguageKindCalculator.calculateLanguageKind(OCLanguageKindCalculator.java:133)
	at com.jetbrains.cidr.lang.psi.impl.OCFileImpl.getKind(OCFileImpl.java:190)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph.buildSymbolAndRootHeaderCache(OCImportGraph.java:89)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTableUpdater.a(FileSymbolTableUpdater.java:147)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTableUpdater.ensurePendingFilesProcessed(FileSymbolTableUpdater.java:108)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache.ensurePendingFilesProcessed(FileSymbolTablesCache.java:721)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph$Cache.a(OCImportGraph.java:404)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph$Cache.a(OCImportGraph.java:367)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph$Cache.get(OCImportGraph.java:312)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph.findImmediateIncludingFiles(OCImportGraph.java:277)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph.a(OCImportGraph.java:232)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph.findAllRootsThatIncludes(OCImportGraph.java:267)
	at com.jetbrains.cidr.lang.preprocessor.OCImportGraph.getAllHeaderRoots(OCImportGraph.java:62)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextUtil.a(OCInclusionContextUtil.java:200)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextUtil.getResolveRootAndActiveConfiguration(OCInclusionContextUtil.java:170)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextUtil.a(OCInclusionContextUtil.java:372)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextUtil.headerContext(OCInclusionContextUtil.java:317)
	at com.jetbrains.cidr.lang.psi.impl.OCFileImpl.getSymbolTable(OCFileImpl.java:270)
	at com.jetbrains.cidr.lang.psi.impl.OCFileImpl.findSymbol(OCFileImpl.java:246)
	at com.jetbrains.cidr.lang.psi.impl.OCIncludeDirectiveImpl$1$1.innerResolve(OCIncludeDirectiveImpl.java:166)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference$MyResolver.resolve(FileReference.java:579)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference$MyResolver.resolve(FileReference.java:573)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:205)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.multiResolve(FileReference.java:122)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.resolve(FileReference.java:348)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.resolve(FileReference.java:46)
	at com.jetbrains.cidr.lang.daemon.OCResolveAnnotator.a(OCResolveAnnotator.java:125)
	at com.jetbrains.cidr.lang.daemon.OCResolveAnnotator.visitImportDirective(OCResolveAnnotator.java:363)
	at com.jetbrains.cidr.lang.psi.impl.OCIncludeDirectiveImpl.accept(OCIncludeDirectiveImpl.java:283)
	at com.jetbrains.cidr.lang.psi.impl.OCElementBase.accept(OCElementBase.java:89)
	at com.jetbrains.cidr.lang.daemon.OCAnnotator.annotate(OCAnnotator.java:87)
	at com.jetbrains.cidr.lang.daemon.OCAnnotator.annotate(OCAnnotator.java:71)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:371)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:303)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:333)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:33)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:239)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by izhangzhihao** [comment]
Seems not because of our side.
